### ISSUE TITLE
Use dhall for BIDS specification and reference implementation

### ISSUE THREAD

**Issue by cfhammill** [bids-standard/bids-specification#101]
Recently a configuration language called dhall has been created to solve many of the problems with configuration files. https://github.com/dhall-lang.

Dhall provides a typed and modular alternative to json/yaml. It additionally provides the ability to include functions in the configuration (e.g. defaults  for a field can be computed from other fields in the configuration). 

I think this language provides a natural way to formalize the BIDS specification. The specification of BIDS *is* a type specification (which fields are optional, what kinds of values are allowed, etc.). This can be capitalized on, once the spec is a type schema there is no need for an independent validator, dhall ensures the types are correct at every I/O step.

Additionally, JSON and dhall are interconvertible (provided a type schema is provided when going from JSON to dhall) so BIDS data-sets using JSON will be forward compatible. 

I recognize that there are substantial risks associated with using relatively new and niche software for large projects. However, types provide safe-guards against many very common classes of bugs that could exist in the specification and validation of BIDS files, which I think justifies the change. Regardless of personal views on the utility of static typing in a general programming context, the advantages in a configuration/specification context should be clear.

In the near term I'm going to work on a subset of the BIDS spec in dhall for comparison and interest sake. Any thoughts, questions, or feedback would be appreciated!

**Comment by chrisfilo** [comment]
Interesting idea. I would suspect that to fully replace the validator with something based on dhall will be challenging because the validator checks file paths and looks into headers of binary imaging files.

Please also note that the validator already uses JSON Schemas that provide type verification.

**Comment by cfhammill** [comment]
Dhall has a typed functional programming language at its core, although the language is total, this means that it in principle it can do the IO required to check headers, although perhaps such things would be painful enough to write that it's worth jumping out to a turing complete language with a rich library ecosystem. I suspect checking the headers of nifti files would be well in scope though.

Interesting re: JSON schemas. Can you point me to where those are written down? that will give me a basis for writing the dhall types. I'll give those a read over as well and see if I'm still convinced of the advantages I list above.

**Comment by chrisfilo** [comment]
https://github.com/bids-standard/bids-validator/tree/master/validators/json/schemas

**Comment by cfhammill** [comment]
Thanks Chris! This is perfect.

**Comment by effigies** [comment]
The existing schema and validation effort is pretty firmly going in the direction it's going. While this could be interesting, there isn't currently the expertise in the community to do this, so it would require a motivated contributor to develop a result at least as far as the current approach, as well as use/generate a form that can be consumed downstream by tools like pybids and BIDS-MATLAB.
