### ISSUE TITLE
Phenotype missing in glossary section

### ISSUE THREAD

**Issue by ghisvail** [bids-standard/bids-specification#1010]
I expected to see a definition for `phenotype` in the glossary section of the spec.

I guess they would be tagged as `associated_data` (like `stimulti`) but I am not certain.

**Comment by tsalo** [comment]
I think `phenotype` is a bit of a special case, since there are rules for how files in that folder should be unorganized, unlike `stimuli` or `code`, but `associated_data` seems like a good place to add it. Would you be willing to open a PR?

**Comment by ghisvail** [comment]
> I think phenotype is a bit of a special case, since there are rules for how files in that folder should be unorganized

Actually, you might have raised a shortcoming in the current taxonomy. My understanding was that `associated_data` implies data stored within are unregulated by the spec, which is not the case for `phenotype` covered by the tabular data section of the spec.

I wonder whether the solution is to introduce a new term to distinguish between unregulated and regulated optional data, something like `additional_data` (regulated)  and `associated_data` (unregulated), or widen the scope for `associated_data` to data which may or may not be regulated.

> Would you be willing to open a PR?

Of course :-)

**Comment by ghisvail** [comment]
Actually, I came to realize that `phenotype` is not that much different to the definition of `datatype`, but applied to modality-agnostic file collections.

Let's imagine `phenotype` but at the subject level, we get:

```
sub-<label>/
    phenotype/
        sub-<label>_acds.json
        sub-<label>_acds.tsv
        sub-<label>_npi.json
        sub-<label>_npi.tsv
```

It really looks like the same constructs used for imaging files at the end of the day, with `phenotype` as the `datatype` and `acds | npi` as the `suffix`.

**Comment by Remi-Gau** [comment]
I think this issue was fixed.

See https://bids-specification.readthedocs.io/en/latest/glossary.html#phenotype-files
