### ISSUE TITLE
broken link to licenses appendix

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-specification#1011]
On https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#dataset_descriptionjson in the License description there is a link to https://bids-specification.readthedocs.io/99-appendices/02-licenses.html which is broken. 

A link that does work is https://bids-specification.readthedocs.io/en/stable/99-appendices/02-licenses.html, but I am not sure how that is supposed to work with the different versions.

**Comment by sappelhoff** [comment]
Thanks for the report! This is related to #974 - we also have some solution proposals over there. :-)
