### ISSUE TITLE
MEG DigitizedHeadPoints definitions

### ISSUE THREAD

**Issue by Moo-Marc** [bids-standard/bids-specification#1022]
For MEG, the DigitizedHeadPoints field exists in 2 different files, with 2 different definitions: 
In _meg.json it's a required boolean, while in _coordsystem.json, it's a relative path to a file.
However, in 1.7.0, both definitions now appear the same.  See [Digitized head points table in this section](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#coordinate-system-json-_coordsystemjson).

I think this is a bug due to how the tables are generated.

**Comment by tsalo** [comment]
I believe you're right. We must have missed the different definitions when we moved them into the schema. I've opened #1023, which hopefully fixes the problem.
