### ISSUE TITLE
Need some MACROS___ for top level files description

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#1038]
https://github.com/bids-standard/bids-specification/pull/1033/files reveals duplication of description for top level files in [src/03-modality-agnostic-files.md](https://github.com/bids-standard/bids-specification/pull/1033/files#diff-d9e3cba862521dd35f361952e6e6a7a4d20c5712af8715bd7d1ae38e057821ddR146) and [src/schema/objects/top_level_files.yaml](https://github.com/bids-standard/bids-specification/pull/1033/files#diff-c956e4a2decf6448a7e573bc50e93a4ea7a1af19f364b1818804a8005871f86bR24) thus begging for some `MACROS___` to just populate the .md with description from the schema.  Attn @tsalo who would know the best -- may be there is already one to be used?

**Comment by tsalo** [comment]
I don't think we have any yet, but I agree that this is a good idea.
