### ISSUE TITLE
Folder vs. Directory

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-specification#1039]
As far as I can tell, it seems that “folder” and “directory” are used pretty interchangeably in the specification — with “directory” occurring slightly more often, but “folder” present in more prominent places:

```
chymera@decohost ~/src/bids-specification $ ag directory -o | wc -l
179
chymera@decohost ~/src/bids-specification $ ag folder -o | wc -l
148
```

In the interest of consistency should we maybe standardize the wording to always be directory?

**Comment by sappelhoff** [comment]
I did a quick search, and it seems like we might lose some precision when we replace all "folder" by "directory" or vice versa:

- https://en.wikipedia.org/wiki/Directory_%28computing%29#Folder_metaphor
- https://stackoverflow.com/questions/5078676/what-is-the-difference-between-a-directory-and-a-folder

That said, I am pretty sure that for almost all cases in our spec, the respective authors did not think about this difference between "folder" and "directory" and indeed just used them interchangeably. I think I am therefore slightly in favor of just using "directory" (at least until we find a good case where we definitely should use "folder").

**Comment by TheChymera** [comment]
@sappelhoff I don't think we would be losing any precision, if anything, the folder notion obscures the underlying structure, which is precisely what we're trying to accurately document.
