### ISSUE TITLE
how to organize longitudinal Sturctral MRI data

### ISSUE THREAD

**Issue by SunnyH666** [bids-standard/bids-specification#1051]
Hi, all

I wonder if I get a longitudinal structral MRI data(and I just have structral MRI data without dwi or fmri data), how should I organized them? treat the second longitudinal structral MRI data as another subject? (I have put my second longitudinal structral MRI into ses-2 folder, but got an error)

please give me some advice!
Many thanks!
Best,
Wenjun

**Comment by effigies** [comment]
Hi, could you share your full file listing and then the validation error you got? It would help any advice be more concrete.

**Comment by SunnyH666** [comment]
thanks for your reply~
I fixed it, something wrong with my file names~~

**Comment by effigies** [comment]
Glad you got it resolved!
