### ISSUE TITLE
Proposal: Update `dataset_description.Authors` requirement level to RECOMMENDED

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#1068]
The validator has been warning on the absence of the authors field for a while, so from the perspective that OPTIONAL, RECOMMENDED, REQUIRED correspond to silence, warnings and errors in validation, it has been RECOMMENDED. I suggest that for consistency we formally mark Authors as RECOMMENDED in the spec.

This will not invalidate any datasets or modify validation behavior in any way.

Thoughts?

**Comment by sappelhoff** [comment]
I agree :heavy_check_mark:

**Comment by Remi-Gau** [comment]
Same
