### ISSUE TITLE
Add rec-<label> entity to DWI files

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#1089]
> I am working with an MR physics group that is using different reconstruction algorithms for DWI data. However, it seems like the optional _rec-label is not present for dwi. Could the _rec-label perhaps be added in this pull request to fix that?

_Originally posted by @dorahermes in https://github.com/bids-standard/bids-specification/issues/105#issuecomment-1106604927_

**Comment by dorahermes** [comment]
Let me know if this pull request #1090  works
