### ISSUE TITLE
Issue with documentation links being lost in translation to readthedocs

### ISSUE THREAD

**Issue by VisLab** [bids-standard/bids-specification#1095]
A number of links in the BIDS specification are not being translated correctly in the readthedocs.

For example, in the License entry in the `dataset_description.json` table in the
[Modality agnostic files](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html) section, the link to Appendix II is:

*https://bids-specification.readthedocs.io/99-appendices/02-licenses.html*

but should be:

*https://bids-specification.readthedocs.io/en/stable/99-appendices/02-licenses.html*

**Comment by sappelhoff** [comment]
I have a working fix in #1093 that is pending review and merging. Please feel free to have a look!
