### ISSUE TITLE
add CONTRIBUTING.md with links/specs of style guide

### ISSUE THREAD

**Issue by edickie** [bids-standard/bids-specification#11]
I realized as I was reading through the raw specification file that I was hesitant to suggest style edits because I didn't know if any decisions had been made about which _flavor_ of markdown we are using, so I didn't know how to suggest changes so things like tables and file paths/directory trees.

I contributing guide with a record of markdown formatting decisions would be useful.

Specifically, the things I wondered about right away were:

- are all the tables still in html because of a formatting decision or can they be converted to markdown tables
- is there a decided formatting structure for directory trees? (should they look like `tree` outputs?) of just bullet-ed/tabbed?

**Comment by chrisfilo** [comment]
We are most likely going to adhere to http://www.cirosantilli.com/markdown-style-guide/. I need to make remark-lint to cooperate first.

**Comment by emdupre** [comment]
Our contributing guide should also include more general information--  particularly on getting started with GitHub, since many contributors may be joining for the first time !

**Comment by KirstieJane** [comment]
+1 to @emdupre's point. Feel free to grab anything from the starter kit that make sense! https://github.com/bids-standard/bids-starter-kit/blob/master/CONTRIBUTING.md

**Comment by chrisfilo** [comment]
This is also a good tutorial: https://egghead.io/lessons/javascript-introduction-to-github

**Comment by KirstieJane** [comment]
Hey folks in the thread - I've been mostly offline for a few weeks - is anyone working on the contributors guide? I can take the lead if that's helpful....I might need a week or so to get it done but happy to be assigned unless anyone else wants to?! (tagging @park-patrick as he did lots of work with me on the `bid-starter-kit` [guidelines](https://github.com/bids-standard/bids-starter-kit/blob/master/CONTRIBUTING.md)??)

**Comment by chrisfilo** [comment]
Thanks for offering to help! We definitely need more documentation for contributors. Happy to "assign" you to this issue, but you will need to accept the invitation to join `bids-standard` org (should be in your email).

**Comment by KirstieJane** [comment]
Done! Thank you - I'd missed that :)

**Comment by chrisfilo** [comment]
Done!

**Comment by Park-Patrick** [comment]
Hi @KirstieJane, sure I'd be open to helping! @chrisfilo could you send me an invitation as well?

**Comment by KirstieJane** [comment]
@park-Patrick - I think we can do the work in a pull request. I only need to be part of the organisation to be “assigned” the issue (and for other reasons - that’s why Chris had sent the invite a week ago!)
