### ISSUE TITLE
[SCHEMA] CHANGES has `required: true` despite it being optional

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-specification#1127]
Most datasets, including most in https://github.com/bids-standard/bids-examples don't have this file.

Incidentally, it might also make sense to imply `required:false` and just not add the key unless it's true.
Let me know and I can edit, test, and submit.

@yarikoptic @effigies

**Comment by effigies** [comment]
Yeah, I think that's a bug. https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html shows CHANGES as OPTIONAL and README as RECOMMENDED.

I think we should change from `required: <true|false>` to `level: <required|recommended|optional>`

**Comment by yarikoptic** [comment]
FWIW, echoing @mih who stopped believing in bool CLI `--options`, some non-bool descriptor here would be better.  not sure about `level` , may be smth like `requirement` or `necessity` or alike would be less ambigous!

**Comment by TheChymera** [comment]
> Yeah, `requirement_level` is probably clearer.

@effigies should I do a PR on this?

**Comment by sappelhoff** [comment]
@TheChymera yes please
