### ISSUE TITLE
URI link broken in BIDS microscopy 

### ISSUE THREAD

**Issue by JuliusWelzel** [bids-standard/bids-specification#1129]
The link to the URI in the BIDS Microscopy metadata field is broken.
It should be resolved if in the specifications-schema-metadata file the link in line 264 is changed to refer to https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#uniform-resource-indicator.

https://github.com/bids-standard/bids-specification/blob/24dbe58010d96c0ce4d4c775230cef94605c6068/src/schema/objects/metadata.yaml#L264

**Comment by sappelhoff** [comment]
Have you tried in the `latest` version of the bids spec? I.e., the unreleased "development" version?

https://bids-specification.readthedocs.io/en/latest/99-appendices/14-glossary.html#bodypartdetailsontology-metadata

I think we fixed this bug in #1056

**Comment by JuliusWelzel** [comment]
Sorry, I missed that one. Works on the dev version.
