### ISSUE TITLE
MOTION BEP: Warning for missing headers description when using .tsv as data format (Motion, generic physio data, etc.)

### ISSUE THREAD

**Issue by sjeung** [bids-standard/bids-specification#1134]
Hi everyone, 

While discussing and testing BEP 029 Motion, which uses .tsv as a file format, we noticed that bids-validator issues warnings for missing header description in motion.json. 

In short, what are your thoughts on allowing .tsv files storing data (not metadata as in channels.tsv) to contain undescribed headers that only serves as channel names? In my opinion describing these channel labels are not really meaningful, as channel labels do not have any designated format and can be assigned by users. (In EEG for example, it does not matter if a channel is named g01 or Pz)

Currently the modality for which this would be most relevant is Motion - in Motion as well as generic physio recording, .tsv columns are used to store channel time series. Normally physio.tsv files would come without headers, but motion had introduced headers in motion.tsv in the following context : 

For example, when data from two accelerometers (acc1, acc2) with 3 channels each (X,Y,Z) would be stacked in one channels.tsv file, columns in "tracksys-acc1_motion.tsv" be named "acc1_X" "acc1_Y", "acc1_Z", and columns in "tracksys-acc2_motion.tsv" as "acc2_X", "acc2_Y", "acc2_Z" (the values in each column is the time series of the corresponding channel).

This makes it easier to match them with channels.tsv column "names" will then have concatenated channels as "acc1_X", "acc1_Y", "acc1_Z", "acc_2_X", "acc2_Y", "acc2_Z".

Last month we decided to move away from this concatenation and instead to have one channles.tsv for each motion.tsv. 
(For example, "tracksys-acc1_channels.tsv", "tracksys-acc2_channels.tsv")
 Still I would like to think about whether it is beneficial to keep headers in for more clarity, although it is redundant as one can identify channels by the order of columns in the corresponding motion.tsv.

Options I can think of : 

1. Remove headers from motion.tsv
This will not require any bids-wide adaptation and will be in harmony with other modalities. 

2. Skip warnings for motion.tsv headers and potentially allow undefined headers in physio.tsv or other data.tsv files to enhance clarity
 
 I would like to hear what you think and I tag here those who have been involved in the discussion  @sappelhoff @JuliusWelzel. Welcome to ping in other modality leads who could find this discussion of interest.

**Comment by sappelhoff** [comment]
I think that option 1 is a good way to go here: Not having headers in `_motion.tsv` files.

It's in line with physio.tsv "timeseries" -- however note the following:

> Please note that, in contrast to other TSV files in BIDS, the TSV files specified for physiological and other continuous recordings do not include a header line. Instead the name of columns are specified in the JSON file.

([source](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/06-physiological-and-other-continuous-recordings.html))

If you want to model `motion.tsv`very closely to `physio.tsv` you need to keep in mind that `motion.json` would require the entries "Columns" (a list of headers that refer to the columns in the tsv file), "SamplingFrequency", and "StartTime". I don't see a particular need for that, however, as you will document "Columns" in your "channels.tsv" files. It all just needs to be made very clear.

**Comment by sjeung** [comment]
Hi Stefan, thanks for the input- we will continue without headers. 

To answer to the remark about physio.tsv, at the moment channels.tsv for each motion data has column "name" and this is practically serving the same purpose as "columns" in physio channels.tsv. "name" column is also used in eeg channels.tsv and it makes sense in that it contains the channel names. "columns" were probably intended to be more generic. I'd be happy to leave this coulmn as is. 

"StartTime" is a recommended field in .json, but the best way to do synchronization is probably to use scans.tsv because this file can be across multiple modalities and does not require prescribing which modality is the "main" modality onto which the onset is anchored. 

sampling_frequency is included, both in channels.tsv and motion.json, same as physio or eeg.

**Comment by JuliusWelzel** [comment]
Both Stefan and Robert supported the idea of headers in the .tsv file. 

Google Doc:
_Stefan Appelhoff
05.11.2020
I don't even know why physio and stim do not include headers ¯\(ツ)/¯. I am +1 for headers here_

I also think it would be convenient. I would actually prefer option 2 and keep headers if the only reason to take them out is a warning in the validator.

**Comment by JuliusWelzel** [comment]
.... and sorry for the late reply, I was on holidays
