### ISSUE TITLE
add 'modality' to glossary

### ISSUE THREAD

**Issue by CPernet** [bids-standard/bids-specification#1141]
I've seen the word 'modality' used in different context, for instance /anat and /func defined as 2 (MRI) modalities. Within BIDS, these are not since under 'Modality specific files', what is listed is different data types based on technology. 

Proposal: a modality corresponds to a technology-driven data type (MRI, MEG, EEG, Behaviour, Eye tracking, etc) and does not separate within modality (e.g. anat vs. func).

**Comment by CPernet** [comment]
ah of course @robertoostenveld was on the case :-) 

Having browsed the different items mentioned above, I do see an issue with name inconsistency I do like your proposal [593](https://github.com/bids-standard/bids-specification/issues/593) with instruments and data types +1

The spec tree would therefore organize along those two names, with data types as top-level folders for data. What happens to the word modality after that?

**Comment by robertoostenveld** [comment]
You may want to have a look at some of my notes that relate to this, see my [BIDS bigger picture](https://docs.google.com/document/d/1cY-iZL8rtgDJ1-YVs1f2h5ugOiuK144zu4ju9UXZEGY/edit?usp=sharing) google doc. It aims to clarify instruments, modalities and suffixes.

**Comment by CPernet** [comment]
I did :-)  and instrument/data type sounds good to me (still not defining what modality would be after that)
