### ISSUE TITLE
SCHEMA_VERSION renaming?

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-specification#1144]
I am thinking that it might be better to disambiguate the naming of this variable from the BIDS version (which is actually the BIDS schema version, now that BIDS is moving to full codification in the schema) by renaming it to `SCHEMA_SYNTAX_VERSION`.

This would make the distinction more obvious and the variable name more self-explanatory.

@yarikoptic I believe you introduced this, what do you think?

**Comment by TheChymera** [comment]
@soichih @erdalkaraca — would this possibly interfere with your workflows?

**Comment by yarikoptic** [comment]
> @yarikoptic I believe you introduced this, what do you think?

it might make sense, although yourself you named BIDS specification version to be "BIDS version" ;) But I *hear you*, I think it might be cleaner with `SCHEMA_SYNTAX_VERSION` although it is not just about "syntax".  So might also be just a matter of documentation that there are 3 versions

- `BIDS_VERSION` -- version of specification
- `SCHEMA_VERSION` -- version of schema for BIDS specification, which could be used for describing multiple BIDS_VERSIONs.
- `LIBRARY_VERSION` -- version of that python library implementing support for various SCHEMA_VERSIONs which would describe even greater range of BIDS_VERSIONs.

**Comment by soichih** [comment]
@TheChymera We just need a mechanism to know when to avoid upgrading our bids-specification that could break our services due to any format changes. It's been a while since I discussed this with @effigies, but basically, we want to auto-update bids-specification the update only consists of the content of the schema - not the structure. If there is a structural change then I want to upgrade to it manually and do thorough testing before jumping to it.

**Comment by TheChymera** [comment]
@soichih Currently we have 2 versioning concepts (though @yarikoptic proposed a third, more on that further down).

* The first is the `BIDSVersion` which I mistakenly called “BIDS Schema Version” above. This tracks the content, in a representation-agnostic way. Technically every single line in the schema could change without incrementing the BIDS Version, as long as its high-level human-read interpretation would remain the same
* The second is what is currently called `SCHEMA_VERSION` which pertains to the representation (which I will refer to as Schema Syntax Version below). This would have to change with significant change to the schema structure.

The problems we have are:

0. The current `SCHEMA_VERSION` name is simply too easily confused with BIDS Version, particularly when one is handling the *BIDS schema*.
1. Does the Schema Syntax Version *have* to change at all if the BIDS Version changes (i.e. new content is added, but the logic, at least with respect to parsing, stays the same)?
2. How do we account for parsing (i.e. rendering and validation) logic updates which do not change the actual schema structure, but simply the quality of our reference logic?

The proposals which I would make would be:

0. Change the name to make it more descriptive, `SCHEMA_SYNTAX_VERSION` was my first proposal, though in view of the following `SCHEMA_LOGIC_VERSION` might be equally good or better. @soichih your feedback would be relevant for this point in particular --- as whether or not a renaming would cause significant issues for you might impact our choice or at least the timing of the change (though since we're pre-release perhaps this is the best time for any potentially painful changes).
1. For the time being, the Schema Syntax Version simply *has* to be incremented in some fashion as the BIDS Version changes. This is because we do not yet leverage (though we are working on) a usable package tracking multiple schema versions. Downstream packages will, for a while still, use the `bidsschematools` package, and when a new BIDS Version is released we should follow it up with a `bidsschematools` release which necessarily needs to have some sort of increment to distinguish it fro the prior one.
2. As we have established in (1) that the Schema Syntax Version may be incremented by ancillary modifications, the same increment can account for changes to rendering and validation. The versioning would be `MAJOR.minor.patch` where only `MAJOR` and `minor` track schema compatibility changes, and `patch` tracks increments in logic or content. For @soichih 's specific use case, if I understand this correctly, this means that `MAJOR.minor` changes would require manual upgrade, whereas `patch` can be updated automatically.

I think this is simple and concise, and in particular would save us the trouble of coming up with and tracking the relationships of yet another separate version model for the built-in schema parsing code. It would also encourage continued co-develpment of schema and logic, so that there is no divergence, no need to coordinate PRs across repositories, and would present any schema syntax updates with the immediate reality constraint as to how feasible it is to actually parse them.

For overview purposes I have put together a table:

|     BIDS_VERSION              |   release                       |  SCHEMA_LOGIC_VERSION  |        release                                 |
| ------------------------------------ | ------------------------------ | ------------------------------------------- | ------------------------------------------ |
| `1.7.0-376-g513fabc`         |        -                             |  `0.3.0`                                         |       initial release                         |
| `1.7.0-427-?`                     |        -                             |  `0.3.1`                                         | validator parsing improvements |
| `1.7.0-597-?`                     |                                      |  `0.3.2`                                         | `render.py` fixes                         |
| `1.7.0-598-?`                     |                                      |  `0.4.0`                                         | Compatibility-breaking schema reorganization |
| `1.8.0`                     |     Covering a lot of cool new modalities     |  `0.4.1`                                         | Releasing bidsschematools complementing the BIDS release                         |
| `1.8.0-123-?`                                |          |  `0.4.2`                                         | Error code tracking in and parsing from in schema                               |
| `1.8.0-163-?`                                |          |  `0.4.3`                                         | Error code support in validator                               |

**Comment by TheChymera** [comment]
After discussing this live with @yarikoptic  we agreed that `SCHEMA_LOGIC_VERSION` incrementation beyond changing the syntax (breaking) and codifying additional content documented in the standard outside the schema (non-breaking) is equivalent to a change in `BIDS_VERSION`, so `SCHEMA_SYNTAX_VERSION` patch incrementation with `BIDS_VERSION` releases makes sense.

There is still disagreement on whether or not the `SCHEMA_LOGIC_VERSION` patch number should also be incremented with parsing changes.

Yaro's argument *against* this is that parsing API changes which can reasonably break downstream compatibility would be relegated to the patch number, and downstream users and package maintainers may be easily confused.

My argument *for* this is that the only purpose of the schemacode is to provide reference parsing for the schema, and improvements or changes therein are indeed only patches with respect to the actual logic codified by the schema.

Overall we agreed that for the first release at least, and possibly for a while longer, there is no need for the released package versioning to diverge from `SCHEMA_VERSION`, the name of which I would still like to change to `SCHEMA_LOGIC_VERSION` or `SCHEMA_SYNTAX_VERSION` (which we didn't get to discussing).

**Comment by yarikoptic** [comment]
I think we overall converged here and do have `BIDS_VERSION` and `SCHEMA_VERSION` and this could just be closed (instead of labeled with `bikeshed` ;))
