### ISSUE TITLE
tsv metadata in json files

### ISSUE THREAD

**Issue by wiheto** [bids-standard/bids-specification#115]
So I am working on making my temporal network package teneto to comply with the RC1 BIDS derivatives. Among other things it creates connectivity matrices and time-varying connectivity matrices (I'm going to suggest the suffices "_conn" and "_tconn" when we can make suggestion again). 

I am thinking what is the best way to store these as to make it BIDS compatible and having a slight problem regarding tsv metadata. So the tsv files will look something like this: 

``` 
i    j    value    [time] 
0    1    0.5      0
0    1    0.55     1
...
```

or (more likely)

``` 
i    j    value_at_t    value_at_t2 
0    1    0.5           0.55
0    2    0.4           0.41
...
```

_However_ the problem I am running into is regarding the metadata for the tsv files. 

At the moment the json file for tsv files are defined in the BIDS specification: 

> Tabular files MAY be optionally accompanied by a simple data dictionary in a json format (see below). The data dictionaries MUST have the same name as their corresponding tabular files but with .json extensions. Each entry in the data dictionary has a name corresponding to a column name

So at the moment, from what I can tell, there is no way to put in metadata for an entire tsv file in the json (unless I have missed where this is specified). The metadata must be for each column. This is sub-optimal for me use case. If I want the json sidecar to include metadata about how the connectivity matrix were defined (e.g. if Spearman or Pearson correlations were used to make the connectivity matrix, if it is symmetric or directed connectivity matrix, if it reflects functional or structural data, any additional transforms performed after the correlations were made), there is not necessarily a good column to put this information in as it reflects the entire file.  

A couple of suggestions to solve this: 

1. Allow a non-column entry in the json (e.g. "\_\_global\_\_") for json sidecars that accompany tsv files. If this solution, the BIDS specification will have to be modified to allow this.
2. This type of data should not be saved as a tsv. Connectivity data should only be specified in cifti formats (I don't think this is the best solution personally, but I can see why some would suggest it).  
3. Place the global metadata in the columns most relevant for that property. E.g. in the voxel/node index columns i and j the metadata could include if the connectivity matrix is directed or not and the. This would not require any change to BIDS but, for usability, cramming metadata in slightly unexpected places seems suboptimal. 

My vote is option 1 as that would also solve any similar problem that arises in the future without having to shoehorn global metadata into column data.

**Comment by chrisfilo** [comment]
Thanks for bringing this up.

Connectivity matrices are very important derivatives and @eduff and @pauldmccarthy are working on a spec describing how to store them. See https://docs.google.com/document/d/1ugBdUF6dhElXdj3u9vw0iWjE6f_Bibsro3ah7sRV0GA/edit for details.

As for a global field - this has been proposed a while ago in the mailing list, but somehow did not make it to the spec. I opened a PR with such change: https://github.com/bids-standard/bids-specification/pull/117

**Comment by wiheto** [comment]
I had totally missed the connectivity spec! I will lookover that.  

That clears up the global problem I was having at least. Thanks! I'll close this now since it seems a duplicate.
