### ISSUE TITLE
Bids for anatomical fetal MRI raw data

### ISSUE THREAD

**Issue by alexpron** [bids-standard/bids-specification#1150]
Dear all, 

Do you have any information about BIDS standard for raw fetal MRI data ?

### Fetal MRI data description
 Fetal MRI data are essentially anatomical MRI T2 data composed of several sequences (e.g.  HASTE, or TrueFisp) acquired according to several orientations (e.g. axial, coronal, sagittal, transverse). Usually there are three different orientations and each orientation can be repeated several times (e.g. 1 coronal acquisition and 2 sagittal acquisitions). Also different in-line (console) processing can be applied (e.g, motion correction, distorsion correction)
 
Do you think such kind of data could be represented using the usual MRI bids keywords (e.g. run, desc) ?

Thank you in advance,
@gauzias @davidmeunier79 @SylvainTakerkart

**Comment by sappelhoff** [comment]
Hey @alexpron such usage questions are often better placed here: https://neurostars.org/tag/bids (note the "bids" tag), but maybe someone here will answer - so I'll leave the issue open for a time.

**Comment by alexpron** [comment]
Thanks for your answer @sappelhoff :) I ll also ask the question on neurostars :)

**Comment by alexpron** [comment]
Here is the neurostars link https://neurostars.org/t/bids-support-for-fetal-mri-scans/23135 if others are interested.
