### ISSUE TITLE
Add bidsschematools API documentation to website

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#1154]
It looks like there are [several mkdocs plugins](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#api-documentation-building) that can build API documentation. Does anyone have a preference?

**Comment by effigies** [comment]
On balance, I'd probably prefer not to have it directly on RTD. What if we set it up as a standard sphinx page and push to https://bids-standard.github.io/bidsschematools/?

**Comment by tsalo** [comment]
I figured we'd bury it in the appendix, but I'm happy with a separate site as well, as long as we link to it in the schema documentation.

**Comment by effigies** [comment]
Should we be using https://github.com/bids-standard/bids-schema? I know that @TheChymera did not want to call the Python package `bids-schema` on the grounds that that should be a data package, but that repository does have a `tools/` subdirectory that the package could ultimately wind up in. In which case we would maybe push to https://bids-standard.github.io/bids-schema/api/?

**Comment by yarikoptic** [comment]
> Ideally that should contain 0% Python code and therefore have no API @yarikoptic

yes/most-likely ;)  At least ATM while both schema content, its `SCHEMA_VERSION` and `bidsschematools` are still in very active development, IMHO it is best to keep them close by in this repo, and use that `bids-schema` only for export of various versions of BIDS (as expressed in schema).  But later, who knows -- we might move `bidsschematools` into a separate repo. I do not see indeed a reason to "pair" archives of schema releases with the code in one repo really.

**Comment by effigies** [comment]
@bendhouseart Got things running over at https://bidsschematools.readthedocs.io/.
