### ISSUE TITLE
Error in BIDS v1.7.0 metadata.yml

### ISSUE THREAD

**Issue by tomhampshire** [bids-standard/bids-specification#1156]
There is an error in the BIDS metadata.yml for version 1.7.0. This line and the line below it need to be de-indented by 2 spaces:

https://github.com/bids-standard/bids-specification/blob/a93d4f2a27b2b79ba569a1d02f1e7f560af3525f/src/schema/objects/metadata.yaml#L416

In `ChunkTransformationMatrixAxis`, the `minItems` and `maxItems` are applied to the strings inside the array. They should be applied to the array of strings, as `minItems` and `maxItems` are invalid when applied to strings.

**Comment by effigies** [comment]
I agree, and I think they should be moved up above `items:` for consistency with other entries. Would you care to make a quick PR?

**Comment by tomhampshire** [comment]
Sure, I'll have a look today.
