### ISSUE TITLE
No entities in glossary

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#1187]
None of the entities ans their definitions are listed in our glossary.

https://bids-specification.readthedocs.io/en/latest/99-appendices/14-glossary.html

In a way this makes sense because they are listed in the entities page. 

https://bids-specification.readthedocs.io/en/latest/99-appendices/09-entities.html

But I would have expected them to be listed in the glossary too.

@tsalo

What would make more sense?
1. Adding entities in the gloassary (not a problem to have duplications because either page is auto generated)
2. Have a note at the top of the glossary saying where the entities definitions can be found.

I have a personal preference for 1 as the note in 2 can be easily missed.

**Comment by tsalo** [comment]
They appear to be in there to me. [Here's run](https://bids-specification.readthedocs.io/en/latest/99-appendices/14-glossary.html#run-entities), for example.

**Comment by Remi-Gau** [comment]
Ok never mind.
Must have messed up my ctrl f.
