### ISSUE TITLE
Add legend below filename templates

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#1198]
Small suggestion to add a legend in the macro that generate the filename templates.

May help new comers.

It would add:

**Legend**

- entities between square brackets (for example `[_ses-<label>]`) are OPTIONAL
- for a definition of `label` and `index`, please refer to the relevant section in the [common principles](https://bids-specification.readthedocs.io/en/latest/02-common-principles.html#definitions)

**Comment by tsalo** [comment]
I think you could link to the label and index format glossary entries instead of the common principles. Also, maybe a link to the entities appendix could be included in the legend.
