### ISSUE TITLE
Reorganize appendices

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#1204]
Here is the current order:

1. [Contributors](https://bids-specification.readthedocs.io/en/latest/99-appendices/01-contributors.html)
2. [Licenses](https://bids-specification.readthedocs.io/en/latest/99-appendices/02-licenses.html)
3. [Hierarchical Event Descriptors](https://bids-specification.readthedocs.io/en/latest/99-appendices/03-hed.html)
4. [Entity table](https://bids-specification.readthedocs.io/en/latest/99-appendices/04-entity-table.html)
5. [Units](https://bids-specification.readthedocs.io/en/latest/99-appendices/05-units.html)
6. [MEG file formats](https://bids-specification.readthedocs.io/en/latest/99-appendices/06-meg-file-formats.html)
7. [MEG systems](https://bids-specification.readthedocs.io/en/latest/99-appendices/07-meg-systems.html)
8. [Coordinate systems](https://bids-specification.readthedocs.io/en/latest/99-appendices/08-coordinate-systems.html)
9. [Entities](https://bids-specification.readthedocs.io/en/latest/99-appendices/09-entities.html)
10. [File collections](https://bids-specification.readthedocs.io/en/latest/99-appendices/10-file-collections.html)
11. [Quantitative MRI](https://bids-specification.readthedocs.io/en/latest/99-appendices/11-qmri.html)
12. [Arterial Spin Labeling](https://bids-specification.readthedocs.io/en/latest/99-appendices/12-arterial-spin-labeling.html)
13. [Cross modality correspondence](https://bids-specification.readthedocs.io/en/latest/99-appendices/13-cross-modality-correspondence.html)
14. [Glossary](https://bids-specification.readthedocs.io/en/latest/99-appendices/14-glossary.html)

I think we should reorganize it so that it moves from more general topics to more specific. For example, the glossary should be close to the top, along with general specification principles like entity descriptions and units.

1. [Contributors](https://bids-specification.readthedocs.io/en/latest/99-appendices/01-contributors.html)
2. [Licenses](https://bids-specification.readthedocs.io/en/latest/99-appendices/02-licenses.html) 
14. [Glossary](https://bids-specification.readthedocs.io/en/latest/99-appendices/14-glossary.html)
5. [Entity table](https://bids-specification.readthedocs.io/en/latest/99-appendices/04-entity-table.html)
9. [Entities](https://bids-specification.readthedocs.io/en/latest/99-appendices/09-entities.html)
6. [Units](https://bids-specification.readthedocs.io/en/latest/99-appendices/05-units.html)
10. [File collections](https://bids-specification.readthedocs.io/en/latest/99-appendices/10-file-collections.html)
4. [Hierarchical Event Descriptors](https://bids-specification.readthedocs.io/en/latest/99-appendices/03-hed.html)
7. [MEG file formats](https://bids-specification.readthedocs.io/en/latest/99-appendices/06-meg-file-formats.html)
8. [MEG systems](https://bids-specification.readthedocs.io/en/latest/99-appendices/07-meg-systems.html)
9. [Coordinate systems](https://bids-specification.readthedocs.io/en/latest/99-appendices/08-coordinate-systems.html)
11. [Quantitative MRI](https://bids-specification.readthedocs.io/en/latest/99-appendices/11-qmri.html)
12. [Arterial Spin Labeling](https://bids-specification.readthedocs.io/en/latest/99-appendices/12-arterial-spin-labeling.html)
13. [Cross modality correspondence](https://bids-specification.readthedocs.io/en/latest/99-appendices/13-cross-modality-correspondence.html)

**Comment by sappelhoff** [comment]
I generally agree, but would it be worth breaking a lot of links?

**Comment by tsalo** [comment]
Maybe we could forward the current URLs to the new ones automatically? I'm not sure how to do that in mkdocs, but if it's possible then that would solve the problem.

**Comment by tsalo** [comment]
It looks like there's a [`mkdocs-redirects`](https://github.com/mkdocs/mkdocs-redirects) plugin that we could use.

**Comment by effigies** [comment]
Do we want to drop the `NN-` prefixes? The order is determined by `mkdocs.yml`, not the sort order of the source files.

**Comment by tsalo** [comment]
Should the glossary be part of the main specification?

**Comment by Remi-Gau** [comment]
> Should the glossary be part of the main specification?

I would say yes but maybe you have some alternative in mind.

**Comment by tsalo** [comment]
I was just thinking that the glossary should be more easily accessible (i.e., a chapter in the main specification instead of an appendix), but I don't know if others feel the same way. As we start to link more terms in the main text to glossary items, it seems like the glossary should become more of a central part of the spec.

**Comment by Remi-Gau** [comment]
hahaha. I had understood the opposite of what you implied: that you wanted to take it completely out of the spec and make it standalone as if it was not related to the spec. I am tired...

But yeah I would not mind making it more central.

**Comment by sappelhoff** [comment]
> As we start to link more terms in the main text to glossary items, it seems like the glossary should become more of a central part of the spec.

sound like a good idea to me!
