### ISSUE TITLE
Removing pandas dependency from bidsschematools

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-specification#1214]
Currently we still need pandas (which pulls in numpy, matplotlib, etc), albeit pending https://github.com/bids-standard/bids-specification/pull/1211 this is only an optional dependency and only used for `bidsschematools.render`.

I wonder whether we couldn't get rid of it alltogether. @effigies reccomended https://pypi.org/project/raccoon/ as a possible replacement, though we might in the end not need that either. I'll need to have a closer look at the code, as it stands we seem to rely on dataframes in a number of functions (including in `bidsschematools.utils`, but only imported for rendering).

@yarikoptic  @tsalo

**Comment by sappelhoff** [comment]
> reccomended https://pypi.org/project/raccoon/ as a possible replacement, though we might in the end not need that either. 

I'd much rather have pandas as a dependency than to add something that may be more lightweight but that few people know

+1 on making pandas an optional dependency if rendering is needed.

**Comment by TheChymera** [comment]
deprecated by https://github.com/bids-standard/bids-specification/issues/1258
