### ISSUE TITLE
RTD does not render specific versions or 'draft'

### ISSUE THREAD

**Issue by chrisfilo** [bids-standard/bids-specification#122]
Neither https://bids-specification.readthedocs.io/en/draft/ nor https://bids-specification.readthedocs.io/en/v.1.1.2 resolves correctly.

**Comment by choldgraf** [comment]
lemme look into it

**Comment by choldgraf** [comment]
OK figured it out - I triggered a manual build by:

1. going here: https://readthedocs.org/projects/bids-specification/builds/
2. Making sure that "latest" was active on the drop-down to the right.
3. Clicking "Build Version" (see img below)

   ![image](https://user-images.githubusercontent.com/1839645/50983682-ce573000-14b4-11e9-9c0a-ba2d55d982a1.png)
   
   This caused RTD to hit the github API and then it found the tagged release. I don't *think* this is necessary each time (maybe only if we create a new release?)

4. Then I went to `Admin -> Versions`, found the tagged version under "Choose active versions" and checked the box next to "Active" for that version.

   ![image](https://user-images.githubusercontent.com/1839645/50983776-11b19e80-14b5-11e9-93d5-41ea5d8369ed.png)

One other note - the latest version lives at `/latest/` not `/draft/`.

The links are here:
https://bids-specification.readthedocs.io/en/v.1.1.2/
https://bids-specification.readthedocs.io/en/latest/

**Comment by chrisfilo** [comment]
Perfect! Thank you!

**Comment by chrisfilo** [comment]
Actually `latest` corresponds to the content of `master` branch and `stable` is the latest tag - see https://docs.readthedocs.io/en/latest/versions.html.

Because our tags had non-standard format the stable RTD page did not render. I fixed the tag and stable is working now: https://bids-specification.readthedocs.io/en/stable/
