### ISSUE TITLE
Overlap in derivatives for tedana, raw for BEP001

### ISSUE THREAD

**Issue by emdupre** [bids-standard/bids-specification#127]
We (@tsalo and I) were looking into creating BIDS derivatives for the `tedana` package. We've mostly succeeded in [mapping our outputs on to existing BIDS derivatives](https://github.com/ME-ICA/tedana/pull/152), but there are two file types we're still unsure about.

One of these is a T2* map. Looking through the [BEP001 draft](https://docs.google.com/document/d/1QwfHyBzOyFWOLO4u_kkojLpUhW0-4_M7Ubafu9Gf4Gg/edit#heading=h.edzhdehfsb1s), it seems that there's already a defined `T2Starmap` suffix. We were wondering if it would make sense to use the same suffix, here ? Would it be as simple as setting the `Estimation Method` field as [Posse et al., 1999](https://github.com/poldracklab/fmriprep/blob/c92bf833fecf645a2fbf3943486c665a9ebc54f7/fmriprep/data/boilerplate.bib#L296) ?

The other data type is [what we call an `S0` map](https://tedana.readthedocs.io/en/latest/approach.html#monoexponential-decay-model-fit), which doesn't seem to have a correspondence to anything yet defined in BEP001. Is there any correspondence that I'm not seeing, or would this make sense as its own suffix ?

Pinging in some BEP001 folks who might have comments: @KirstieJane @Gilles86 @agahkarakuzu @handwerkerd

**Comment by Gilles86** [comment]
Hey Elizabeth,

This package look very cool!

Note that the latest version of the BEP001 text can be found [on github](https://github.com/bids-standard/bep001/blob/maintext/main.md).

Although I have the maps you describe in my own data and use them in my preprocessing, they are not described as a specific use case in BEP0001 right now. They are somewhat similar to PD maps, but they still contain B0 and B1 effects and are not really quantitative. You could maybe call them PDw, but was I actually do in my data is, indeed, to use the suffix _S0map.

I would suggest to add this use case to the standard. @emdupre, would you be interested in drafting something up in a pull request? @KirstieJane, @handwerkerd, any thoughts?

**Comment by KirstieJane** [comment]
Heya! Sorry I missed this thread. One of the conversations that isn't well documented in BEP001 at the moment is the fact that quite a few of these suffices are going to end up in derivatives (still under discussion).

So, I think adding a new suffix is the right decision, and `_S0map` sounds good to me!

**Comment by tsalo** [comment]
@emdupre we can close this, right?

**Comment by tsalo** [comment]
Closed with @emdupre's permission.
