### ISSUE TITLE
What directories can be at the top level of a BIDS Dataset?

### ISSUE THREAD

**Issue by VisLab** [bids-standard/bids-specification#1284]
Is there some place in the BIDS specification that states what directories under the data set root are valid?

I know that the following are okay:  `derivatives`, `stimuli`, `code`, `sourcedata`.... but I couldn't find anywhere in the spec where it clearly stated that.   Could someone point me there if I missed it?

I also know that putting random directories under the data set root doesn't validate.  Is there a list somewhere?

**Comment by Remi-Gau** [comment]
I believe this is the yml that defines those: https://github.com/bids-standard/bids-specification/blob/master/src/schema/objects/associated_data.yaml

**Comment by VisLab** [comment]
It's nice to know that there aren't any other directories that I didn't know about, 
but I was hoping that this information could be placed somewhere in the written specification.  

It is really hard for a new user to get a picture of what the top-level structure of a BIDS data set is.

This information seems to be missing from the [Directory structure](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#directory-structure) section of Common principles.

**Comment by Remi-Gau** [comment]
I agree that this should help set the big picture and have a single place in the specification where this is mentioned.

I can try to see how to generate this from the schema with a macro.
