### ISSUE TITLE
renaming CTF files

### ISSUE THREAD

**Issue by jasmainak** [bids-standard/bids-specification#130]
The specification [says the following](https://bids-specification.readthedocs.io/en/stable/99-appendices/06-meg-file-formats.html#ctf):

> The renaming of CTF datasets SHOULD be done using the CTF newDs command-line application.

is there something special about what the newDs tool does which cannot be done by other software? If not, I suggest tweaking the language here a bit:

> The renaming of CTF datasets SHOULD be done with a specialized software (e.g., the CTF newDs command-line application or MNE-BIDS).

cc @sappelhoff

**Comment by monkeyman192** [comment]
If you end up editing this section, may I suggest changing

> The files contained within a .ds directory are named such that they match the parent directory, but conserve the original file extension

to

> The files contained within a .ds directory are named such that they match the parent directory, but preserve the original file extension

It's only a minor change but I feel the word `conserve` isn't really the right one and `preserve` is.
