### ISSUE TITLE
[BUG] broken link to Appendix VII: MEG systems

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-specification#1308]
on page https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#sidecar-json-_megjson there is a link to Appendix VII: MEG systems (twice). 

It points to https://bids-specification.readthedocs.io/99-appendices/07-meg-systems.html which gives a 404, but should point to https://bids-specification.readthedocs.io/en/stable/99-appendices/07-meg-systems.html instead.

**Comment by sappelhoff** [comment]
Thanks Robert, this bug is fixed in the development version that will be shipped soon!
