### ISSUE TITLE
clean wiki

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#1316]
- [x] move election data and code from google drive into their own repository 
- [x] mention them on the bids website
- [x] remove those sections from the [spec wiki](https://github.com/bids-standard/bids-specification/wiki/BIDS-Steering-Group-election-data)

**Comment by sappelhoff** [comment]
I deprecated the WIKI page. We can safely fully remove it in some months or a year from now, I think.

**Comment by Remi-Gau** [comment]
awesome!!

thanks @sappelhoff
