### ISSUE TITLE
Add new derivative file extensions

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#1317]
### Your idea

In https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#file-formation-specification we define NIfTI, TSV and JSON as generally valid extensions.

For derivatives, I think it makes sense to introduce CIFTI-2 and GIFTI files, along with their extensions (e.g., `.dtseries.nii`, `.surf.gii`) to establish these as acceptable file types. We could use a limited subset, if there are some that are never seen in practice and we don't want to endorse without a use-case, or we could just say "If it follows these specs, then it must be fine".

Thoughts? Any other file types to consider?

**Comment by sappelhoff** [comment]
> or we could just say "If it follows these specs, then it must be fine".

that seems easier on our part: Adopting a standard might also be clearer than taking only a part from it.

How about CIFTI-1? Or if a CIFTI-3 comes about, or a GIFTI-2? Would we support those, or be strict about the versions (?) that we support?

Can these file formats reasonably be used for data from modalities other than MRI?

**Comment by effigies** [comment]
> How about CIFTI-1? Or if a CIFTI-3 comes about, or a GIFTI-2? Would we support those, or be strict about the versions (?) that we support?

CIFTI-1 is dead and people shouldn't use it. If CIFTI-3 or GIFTI-2 comes out, we would need to assess them.

> Can these file formats reasonably be used for data from modalities other than MRI?

Yes, any data resampled to the cortical surface could be put in these formats, including EEG and MEG.
