### ISSUE TITLE
Unclear channel type "TRIG" --> analog versus digital

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#1318]
for MEG, EEG, iEEG, and fNIRS we have the [`TriggerChannelCount` metadata](https://bids-specification.readthedocs.io/en/latest/glossary.html#objects.metadata.TriggerChannelCount), which says:

> Number of channels for digital (TTL bit level) triggers.

I would have thought that the corresponding **channel type** is `TRIG`, which is unfortunately only described as:

> System Triggers

this description is the same throughout the spec (MEG, EEG, iEEG, fNIRS), but I think it's not enough. Especially given that the examples where `TRIG` is used look as follows:

```Text
name type units description sampling_frequency low_cutoff high_cutoff notch software_filters status
UDIO001 TRIG V analogue trigger 1200 0.1 300 0 n/a good
```

:point_up: here (from the [MEG section](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#channels-description-_channelstsv)), the `TRIG` channel is analog, which doesn't fit with the `TriggerChannelCount` metadata, that says these channels should be digital.

```Text
name  type  units low_cutoff  high_cutoff status  status_description
TR1   TRIG  n/a   n/a         n/a         good    n/a
```

:point_up: whereas here (from the [iEEG section](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/04-intracranial-electroencephalography.html#channels-description-_channelstsv)), the `TRIG` channel has no units, i.e., is probably a digital channel of "TTL-level" integers (0-255, typically).

---

I suggest to:

1. make the `TriggerChannelCount` metadata also allow analog trigger channels (Volt channels that can be easily converted to digital "TTL bit level" channels), and to connect the metdata to the `TRIG` channel type
2. extend the description of the `TRIG` channel type from "System triggers" to something that encompasses other commonly used names for such data. E.g., "TTL markers", "event markers", ...

WDYT?

**Comment by sappelhoff** [comment]
cc @bids-standard/raw-electrophys-ieeg

**Comment by robertoostenveld** [comment]
In general I agree, but I would refrain from using the work "markers" and definitely not go in the direction of annotations. File formats (i.e., acquisition systems) that I know that use those represent that information differently than what we have in mind here, which is a "continuously sampled representation of analog and/or digital values that is used to synchronize with external devices". 

If you ask me, a BrainVision vmrk file does not contain a trigger channel. An EDF+ annotation channel is not a trigger channel.

But analog TTL (usually between 0 and 5V, although nowadays sometimes only up to 3.3V) and digital (integers, where each bit corresponds with an analog TTL input) are both part of `TRIG` in my perspective.
