### ISSUE TITLE
setup precommit to play nice with bidsschema CI

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#1321]
Find a pre-commit config that is compatible with the linting configuration used for the bidsschema tools and does not break anything in CI.

FYI: I am working on my main branch to be able to show the output of pre-commit CI:
for example: https://results.pre-commit.ci/run/github/150988005/1661942215.jTaSkg0fQD2c-OyJfvjqGw

issue corresponding to #1267 that was closed prematurely

**Comment by effigies** [comment]
@Remi-Gau FWIW I spent time I shouldn't have: https://github.com/effigies/bids-specification/compare/schema/lazy_loading...ci/precommit (I was working on the schema/lazy_loading branch and didn't rebase)

Not sure if this is helpful.

**Comment by Remi-Gau** [comment]
Cool thanks

will have a look but if this only touches the precommit config and not the schema tools linting CI I am not holding my breath
