### ISSUE TITLE
[BUG] Different conventions used for TotalReadoutTime

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-specification#1351]
### Describe your problem in detail.

In [MRI section](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html) `TotalReadoutTime` is defined using FSL convention: `EffectiveEchoSpacing * (ReconMatrixPE - 1)`,
this is confirmed in [Glossary](https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.TotalReadoutTime).

In [qMRI appendix](https://bids-specification.readthedocs.io/en/stable/appendices/qmri.html#tb1epi-specific-notes) is defined using SPM convention: `EffectiveEchoSpacing * PEReconMatrix`.

### Describe what you expected.

Can you please uniformise the definitions? 

No need to tell the usage of different conventions depending on context is confusing and error prone.

### BIDS specification section

https://bids-specification.readthedocs.io/en/stable/glossary.html#objects.metadata.TotalReadoutTime
https://bids-specification.readthedocs.io/en/stable/appendices/qmri.html#tb1epi-specific-notes

**Comment by Remi-Gau** [comment]
@agahkarakuzu we may need your help on this.

**Comment by sappelhoff** [comment]
Also tagging @Gilles86

**Comment by Gilles86** [comment]
Sure. Let's align the two to the one in the MRI section? How do we best go about that?

**Comment by effigies** [comment]
@nbeliy @Gilles86 Would you mind having a look at #1912?

**Comment by nbeliy** [comment]
Looks good for me
