### ISSUE TITLE
Check mkdocs-material beta release

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#1365]
mkdocs-material has announced a beta of a breaking release: [9.0.0b1](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.0b1)

We should verify that it doesn't break anything, as eventually rendering will be based on this. I've tested with:

```console
$ pip install --upgrade --pre -r requirements
$ mkdocs serve
```

There are no failures. I've also looked through their changelog (in the release) and nothing seems obviously applicable to us, but it would be good to get more eyes on this.

**Comment by sappelhoff** [comment]
I double checked, serving works without issues on my machine as well and the "removed" section in their changelog seems irrelevant to us.
