### ISSUE TITLE
"orientation_component" in BIDS-NIRS conflicts with "component" in motion BEP

### ISSUE THREAD

**Issue by sjeung** [bids-standard/bids-specification#1393]
Hello everyone! And especially those who are involved in Motion/NIRS  (@JuliusWelzel @helenacockx  @rob-luke @sappelhoff)- 

Since the community review phase for BIDS-NIRS, I have been aware that some motion channels (especially IMU output) are defined in BIDS-NIRS.  Although it has been brought to our attention that there were some differences in channel names (for example ACC vs ACCEL) and we were able to resolve it, only now I noticed that there is column ["orientation_component"](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/11-near-infrared-spectroscopy.html#:~:text=orientation_component) defined for channels.tsv in BIDS-NIRS.    
 
BIDS-NIRS : **orientation_component** is optional, but required **if type is ACCEL, GYRO or MAGN** and **must be one of: "x", "y", "z"**.  

Unfortunately, this clashes and overlaps with ["component"](https://github.com/JuliusWelzel/bids-specification/blob/bep-029/src/modality-specific-files/motion.md#:~:text=Description-,component,-REQUIRED) column that is defined in the current motion BEP. 

BIDS-MOTION : **component** is required for motion data and **must be one of: "x" ,"y", "z", "quat_x", "quat_y", "quat_z", "quat_w", "n/a"**.  

Per current BIDS-NIRS and motion BEP specs the channels.tsv file would look something like this (omitted irrelevant columns):

| label                 | type           | component           | orientation_component  |
| ----------------:|-------------:| -------------------:|----------------------------:|
| hand_accel_x    | ACCEL     |   x |  x |
| hand_accel_y    | ACCEL     |  y  |  y |
| hand_accel_z    | ACCEL     |  z  |  z |
| hand_gyro_x    | GYRO    |  x  |  x |
| hand_gyro_y    | GYRO    |  y |  y |
| hand_gyro_z    | GYRO    |  z  |  z |
| latency    | LATENCY    |  n/a  | n/a |

 
Overall I believe that renaming **orientation_component** column to **component** will be more handy. 
- channel types in NIRS that require specification of x,y,z components does not only include GYRO but also ACCEL and MAGN, which are non-orientation channel types
- BIDS-motion which also includes the three types need a similar column for POS and VEL channels, which are again non-orientation channels. It would be redundant if we have a separate column named **component** or **position_component** on top of **orientation_component**

Was there any reason that it's not been named "component" (e.g., clash with another concept in BIDS?)?
And what are your thoughts on changing "orientation_component" to "component" and having a shared definition with BIDS-motion? To do this we would simply take the "component" column definition from BIDS-motion and specify for which channel types this column is required as it is in current BIDS-NIRS.

Would be great if we can resolve this before we go into community review phase starting next week.
Thanks and looking forward to your feedback!

**Comment by sappelhoff** [comment]
> Overall I believe that renaming orientation_component column to component will be more handy.

given that NIRS has already been released with BIDS v1.8.0, the only way to "properly" do this renaming in a backward compatible manner would be to [deprecate](https://bids-specification.readthedocs.io/en/latest/glossary.html#deprecated-common_principles) `orientation_component` in NIRS, and RECOMMEND curators to use `component` instead.

> Was there any reason that it's not been named "component" (e.g., clash with another concept in BIDS?)?

to my knowledge there was no public discussion on this.

---

Can you state in all brevity what concrete steps would the MOTION BEP be required to do in case we **don't** deprecate the `orientation_component` column in NIRS? (And if there are alternative ways, please state them separately)

**Comment by sjeung** [comment]
The options depend a bit on whether channels.tsv column definitions are shared across modalities. 
If NIRS definition (orientation_component is optional, but **required if type is ACCEL, GYRO or MAGN** and must be one of: "x", "y", "z") can be ignored in a *_channels.tsv file accopanying motion data, keeping things as they are in NIRS and motion spec will result in option a-1) below. 

On the other hand if users defining ACCEL, GYRO, MAGN as motion data should also comply to NIRS definition, I can think of situations like  a-2), b) or c). 

a) Keep NIRS orientation_component and motion component definitions as they are now 

a-1) People who share ACCEL, GYRO, MAGN channels as motion don't have to add **orientation_component** column. 
Then *_channels.tsv shared with NIRS will have column **orientation_component**, and *_channels.tsv shared with motion will have column **component** if there is any ACCEL, GYRO, MAGN channels.
- PRO at least within motion modality it is in harmony with non-orientation or non-IMU data
- CON is that the same channel types are defined twice within BIDS and used in slightly different manners.   
  <br>
  
a-2) People who share ACCEL, GYRO, MAGN channels as motion should add **orientation_component** column.
Then *_channels.tsv shared with motion will have both **component** and **orientation_component** if there is any ACCEL, GYRO, MAGN channels.
- PRO same as a-1)
- CON redundant and potentially confusing for the same reason as in a-1)  
  <br>
  
b) Rename motion **component** to **orientation_component** to have a common definition with NIRS
**orientation_component** should then include more channel types such as POS, VEL ...etc, and allow "quat_x", "quat_y" ... keywords.  
- PRO all information on axial component of spatial quantity is coherently saved in one column
- CON naming is misleading because there are more channel types in addition to ACCEL that are not orientation-related  
  <br>
  

c) Rename motion **component** to **position_component** (?) or some other concept that can complement **orientation_component** that is defined for all non-IMU channels.
Then "orientation_component" column can add more orientation channel types such as "ORNT" and "ANGACC"
- PRO relatively precise definition possible 
- CON although every motion channel will use either orientation_ or position component and never both, information is spread onto two columns, and the ACCEL channel becomes an oddball, because it is the time derivative of position (not orientation) but is defined in orientation_component column

**Comment by sappelhoff** [comment]
Thanks a lot! Just to be clear, regarding c)

> the ACCEL channel becomes an oddball, because it is the time derivative of position (not orientation) but is defined in orientation_component column

that is already "a problem" in current NIRS, right?

**Comment by helenacockx** [comment]
This is a bit unfortunate indeed...
I see that in the [restricted keyword list for_channels.tsv of fNIRS-BIDS](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/11-near-infrared-spectroscopy.html#restricted-keyword-list-for-the-channel-types) it is correctly stated as _component_:

> Accelerometer channel, one channel for each orientation. An extra column component for the axis of the orientation MUST be added to the *_channels.tsv file (x, y or z).

But that it is wrongly written in the other table. 

I assume that this is just a mistake of fNIRS-BIDS and cannot come up with another reason why it was named differently.

The best option in my eyes is indeed to depreciate _orientation_component_ and replace it by _component_. I don't think that the implications will be big as fNIRS-BIDS is only released recently and not many fNIRS researchers record IMU data during their experiments. However, the 'BIDS policy makers' should also agree with this.

**Comment by sappelhoff** [comment]
Mh. If `component` is even in the spec for NIRS, then one could argue that `orientation_component` could be changed to `component` as a bugfix, without deprecation. What are your thoughts on this?

cc @rob-luke @lpollonini

**Comment by Remi-Gau** [comment]
Just tried to wrap my head around this and indeed the bug fix route seems sensible to me.

Also preferred as it is one of the options that will minimize duplication of definitions in the bids lexicon.

**Comment by rob-luke** [comment]
> Mh. If component is even in the spec for NIRS, then one could argue that orientation_component could be changed to component as a bugfix, without deprecation. What are your thoughts on this?

This seems reasonable to me.

I do not recall any specific reason why we used the term `orientation_component` and would be pleased to be led by the motion experts here (and that's why we got them to review the NIRS BEP too, thanks!).

**Comment by sjeung** [comment]
> > Mh. If component is even in the spec for NIRS, then one could argue that orientation_component could be changed to component as a bugfix, without deprecation. What are your thoughts on this?
> 
> This seems reasonable to me.
> 
> I do not recall any specific reason why we used the term `orientation_component` and would be pleased to be led by the motion experts here (and that's why we got them to review the NIRS BEP too, thanks!).

Thanks everyone for sharing your insights, @rob-luke I agree that it was unfortunate that we didn't get to identify this issue during NIRS review. But I am glad to see that the opinions are converging now. BIDS-Motion would then proceed with column name "component" and this will cover the IMU channels defined in NIRS. 

I propose the following, where NIRS replace `orientation_component` with `component`, then both MOTION and NIRS polish wording for column definition for `component` and description for motion channel types. (in BIDS MOTION descriptions of motion channel types are somewhat minimal and I think it's good to elaborate on it like it's done in NIRS)

If we reach a consensus here I would like to then draft a PR for BIDS-NIRS too, as a fix, in addition to updating Motion BIDS spec. Does this sound like a good workflow @sappelhoff @JuliusWelzel @rob-luke?

The only point I am not sure about is that the column order definition as in NIRS component column is optional and can appear anywhere where in Motion it is the second column and is required - in my opinion it is fine to let these aspects differ between modalities.


1. NIRS
- Rename column 'orientation_component' to 'component' 
- Wording change in [column](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/11-near-infrared-spectroscopy.html#restricted-keyword-list-for-the-channel-types:~:text=orientation_component) and [type keywords](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/11-near-infrared-spectroscopy.html#restricted-keyword-list-for-the-channel-types:~:text=mua%20in%20SNIRF.-,ACCEL,-Accelerometer%20channel%2C%20one) definitions (to be shared between Motion & NIRS as well as other modalities using mocap)

    Description of the orientation of the channel. This column may appear anywhere in the file. Must be one of: "x", "y", "z".
    -> Description of the spatial axis or component associated with the channel. This column may appear anywhere in the file. Must be one of: "x", "y", "z","quat_x", "quat_y", "quat_z", "quat_w", "n/a".

    Accelerometer channel, one channel for each orientation. An extra column component for the axis of the orientation MUST be added to the *_channels.tsv file (x, y or z).
    -> Accelerometer channel, one channel for each spatial axis. An extra column component for the axis of the orientation MUST be added to the *_channels.tsv file (x, y or z).

2. MOTION
- Wording change in [column](https://bids-specification--981.org.readthedocs.build/en/981/modality-specific-files/motion.html#:~:text=%22VEL%22.-,component,string,-Component%20of%20the) and [type keywords](https://bids-specification--981.org.readthedocs.build/en/981/modality-specific-files/motion.html#:~:text=Description-,ACCEL,Acceleration,-ANGACC) definitions (to be shared between Motion & NIRS as well as other modalities using mocap)

    Component of the representational system described in *_motion.json that the channel contains. This column must appear second in the file. Must be one of: "x", "y", "z", "quat_x", "quat_y", "quat_z", "quat_w", "n/a".
    -> Description of the spatial axis or component associated with the channel. This column must appear second in the file. Must be one of: "x", "y", "z","quat_x", "quat_y", "quat_z", "quat_w", "n/a".

    Acceleration
    -> Accelerometer channel, one channel for each spatial axis. An extra column component for the axis of the orientation MUST be added to the *_channels.tsv file (x, y or z).

**Comment by sappelhoff** [comment]
> I would like to then draft a PR for BIDS-NIRS too, as a fix, in addition to updating Motion BIDS spec

Just to be clear: BIDS-NIRS is just BIDS now, given that the BEP has been merged and released :-)

But I agree with your plan to prepare a separate PR to "fix" the NIRS "component" and pave the way for the MOTION BEP to be easily integrated. We will then review and merge that PR, and once it's merged into `master`, we will pull `master` into your MOTION branch, from which the community review will soon happen.

> The only point I am not sure about is that the column order definition as in NIRS component column is optional and can appear anywhere where in Motion it is the second column and is required - in my opinion it is fine to let these aspects differ between modalities.

Fine by me as well.

**Comment by robertoostenveld** [comment]
Sorry for being a bit late to the discussion; the arguments above are well considered and I also find that renaming `orientation_component` to `component`  is the preferred solution. It is regretfully not the first time that, shortly after a new modality being released, we have to make a small fix like this (see for example 1.1.1 in the [changelog](https://bids-specification.readthedocs.io/en/v1.8.0/CHANGES.html)). Following this fix for NIRS this could be version 1.8.1, or it can be combined with the motion BEP into 1.9.0.

**Comment by lpollonini** [comment]
Sorry for being late too. Thumbs up from me on the renaming solution, and sorry for letting this inconsistency slip though in the first place.
