### ISSUE TITLE
[BUG] Genetics metadata field is OPTIONAL in specification, but REQUIRED in validator

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#1395]
### Describe your problem in detail.

When there are genetic data in the dataset (i.e., a `genetic_info.json` file exists), the validator raises an error if a `Genetics` field is not present in the `dataset_description.json`. However, in the specification, this field is optional, even when genetic data are present.

This stems from https://github.com/bids-standard/bids-specification/pull/1353/files#r1020317330.

### Describe what you expected.

I think we should make the specification reflect what the validator has been doing (potentially for years). We should make the `Genetics` field required if genetic data are present in the dataset.

### BIDS specification section

https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/08-genetic-descriptor.html#dataset-description

**Comment by effigies** [comment]
Or we could decide to relax the validator to match the spec. But the point is that datasets that did not conform to this would not have validated, so it would not break things to go from OPTIONAL to REQUIRED.

**Comment by tsalo** [comment]
That's definitely a possibility too. Personally, I would prefer to make the field required.

**Comment by sappelhoff** [comment]
for reference, this is the check: https://github.com/bids-standard/bids-validator/blob/47d2912e91d1c78ac93470d5e76a0752ecfbce64/bids-validator/validators/bids/checkDatasetDescription.js#L23-L35

Seems like:

- if `genetic_info.json` is present in the dataset, 
- then a `Genetics` object must be present in `dataset_description.json`,
- and that object must contain a `Dataset` key-value pair
