### ISSUE TITLE
SCHEMA: Issues to implement

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#1402]
The following BIDS Validator issues should be implementable without further changes to the schema:

* [x] TOO_FEW_AUTHORS (`length(json.Authors) > 1`, select dataset_description.json)
* [x] SLICETIMING_VALUES_GREATOR_THAN_REPETITION_TIME
* [x] EFFECTIVEECHOSPACING_TOO_LARGE
* [x] ECHOTIME1_2_DIFFERENCE_UNREASONABLE (phasediff only; implementing for phase1/phase2 would be a bonus)
* [x] SLICETIMING_ELEMENTS
* [x] REPETITIONTIME_PREPARATION_NOT_CONSISTENT
* [x] VOLUME_TIMING_AND_REPETITION_TIME_MUTUALLY_EXCLUSIVE (needs issue annotation, possibly reimplement in checks)
* [x] NIFTI_DIMENSION
* [x] NIFTI_UNIT
* [x] NIFTI_PIXDIM
* [x] BOLD_NOT_4D
* [x] SFORM_AND_QFORM_IN_IMAGE_HEADER_ARE_ZERO
* [x] ~~NIFTI_PIXDIM4~~ Implementation detail of old Nifti parser; covered by BOLD_NOT_4D and REPETITION_TIME_MISMATCH
* [x] MAGNITUDE_FILE_WITH_TOO_MANY_DIMENSIONS
* [x] T1W_FILE_WITH_TOO_MANY_DIMENSIONS
* [x] REPETITION_TIME_GREATER_THAN
* [x] ECHO_TIME_GREATER_THAN
* [x] ECHO_TIME_DIFFERENCE_GREATER_THAN
* [x] TOTAL_READOUT_TIME_GREATER_THAN
* [x] REPETITION_TIME_MISMATCH
* [x] EFFECTIVEECHOSPACING_LARGER_THAN_TOTALREADOUTTIME
* [x] POST_LABELING_DELAY_GREATER
* [x] BOLUS_CUT_OFF_DELAY_TIME_GREATER
* [x] LABELING_DURATION_GREATER
* [x] ECHO_TIME_ELEMENTS
* [x] "Participants age 89 or higher" (yes, this really is the code; change it to something consistent)
* [x] MISSING_TSV_COLUMN_IEEG_CHANNELS - Update `rules.tabular_data.ieeg.iEEGChannels.initial_columns`
* [x] MISSING_TSV_COLUMN_IEEG_ELECTRODES - Update `rules.tabular_data.ieeg.iEEGElectroes.initial_columns`
* [x] STIMULUS_FILE_MISSING - `checks: [exists(columns.stim_file, "stimuli") == length(columns.stim_file)]`

The following issues can be implemented at present by using the selector `path == '/dataset_description.json'` to ensure that they're only run once (a different approach may be justified later):

* [x] SAMPLES_TSV_MISSING
* [x] SUBJECT_FOLDERS
* [x] PARTICIPANT_ID_MISMATCH
* [x] PHENOTYPE_SUBJECTS_MISSING

**Comment by Remi-Gau** [comment]
closing as all of those seems to have been done
reopen if necessary
