### ISSUE TITLE
[BUG] ambiguity in filename template in anat

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#1418]
### Describe your problem in detail.

See below.

The 2 last lines seem redundant because the part entity is already optional in the 2 first filename patterns.

```text
sub-<label>/
    [ses-<label>/]
        anat/
            sub-<label>[_ses-<label>][_task-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>][_part-<mag|phase|real|imag>]_<suffix>.json
            sub-<label>[_ses-<label>][_task-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>][_part-<mag|phase|real|imag>]_<suffix>.nii[.gz]
            sub-<label>[_ses-<label>][_task-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>]_<suffix>.json
            sub-<label>[_ses-<label>][_task-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>]_<suffix>.nii[.gz]
````

This seems to be due to fact that parametric anat files do not support the part entities where as non-param anat files do.

https://github.com/bids-standard/bids-specification/blob/master/src/schema/rules/files/raw/anat.yaml#L32

Both filename patterns get rendered but given that param and non-param have >6 suffixes it becomes impossible from the filename template alone to know which suffix supports the part entity.

### Describe what you expected.

Maybe only this? 

```text
sub-<label>/
    [ses-<label>/]
        anat/
            sub-<label>[_ses-<label>][_task-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>][_part-<mag|phase|real|imag>]_<suffix>.json
            sub-<label>[_ses-<label>][_task-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>][_part-<mag|phase|real|imag>]_<suffix>.nii[.gz]
```

Or better have `_<suffix>` be more specific to say which filename patterns goes with what suffix.

In any case given that we have a table in the `anat` section of all the non-parametric suffixes, we probably should have one with all the parametric ones.

### BIDS specification section

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/magnetic-resonance-imaging-data.html#anatomy-imaging-data

**Comment by tsalo** [comment]
I think splitting up the filename template into separate ones for the non-parametric and parametric sections would be a good solution.

**Comment by Remi-Gau** [comment]
You mean calling the macro twice each with a table of suffixes below?

**Comment by tsalo** [comment]
I think so. We could have one section for non-parametric structural data, with the associated table of suffixes and filename pattern macro calls, and then a new subsection about parametric structural data.
