### ISSUE TITLE
Fix glossary references and add line breaks to specific paragraph

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#1423]
See: https://github.com/bids-standard/bids-specification/blob/45491588426329e5af3159c40b14d047cbcd0329/src/common-principles.md?plain=1#L188

```
[`ses-`](https://bids-specification.readthedocs.io/en/stable/glossary.html#session-entities)
```

☝️ we should change how the glossary is linked here.

**Comment by Remi-Gau** [comment]
Adressed by #1411, no?

**Comment by sappelhoff** [comment]
ah yes -- thank you!
