### ISSUE TITLE
Formalize how channel types are shared between modalities that use `channels.tsv` files.

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#1436]
came up during the BEP029 (motion) community review:

- https://github.com/bids-standard/bids-specification/pull/981#issuecomment-1453616882

also related to:

- https://github.com/bids-standard/bids-specification/issues/1126
- https://github.com/bids-standard/bids-specification/issues/904

Some BIDS modalities allow for `channels.tsv` metadata:

- EEG
- MEG
- iEEG
- NIRS

`channels.tsv` files MUST have a `type` column that contains (upper case) strings from a defined vocabulary as specified in the modality specific sections. This column MUST be the second column in `channels.tsv` files.

In the schema, the valid values for `type` are specified separately for EEG, MEG, iEEG, and NIRS, see:

https://github.com/bids-standard/bids-specification/blob/741d4ef65610dd4f8fb6cc2ae4943edc4756ffd4/src/schema/objects/columns.yaml#L601

https://github.com/bids-standard/bids-specification/blob/741d4ef65610dd4f8fb6cc2ae4943edc4756ffd4/src/schema/objects/columns.yaml#L626

https://github.com/bids-standard/bids-specification/blob/741d4ef65610dd4f8fb6cc2ae4943edc4756ffd4/src/schema/objects/columns.yaml#L662

https://github.com/bids-standard/bids-specification/blob/741d4ef65610dd4f8fb6cc2ae4943edc4756ffd4/src/schema/objects/columns.yaml#L690

Even though in the spec, it says:

For EEG (types are shared with MEG and iEEG):

https://github.com/bids-standard/bids-specification/blob/741d4ef65610dd4f8fb6cc2ae4943edc4756ffd4/src/modality-specific-files/electroencephalography.md?plain=1#L217-L219

For MEG (no mention of sharing):

https://github.com/bids-standard/bids-specification/blob/741d4ef65610dd4f8fb6cc2ae4943edc4756ffd4/src/modality-specific-files/magnetoencephalography.md?plain=1#L229-L230

For iEEG (types are shared with MEG and EEG):

https://github.com/bids-standard/bids-specification/blob/741d4ef65610dd4f8fb6cc2ae4943edc4756ffd4/src/modality-specific-files/intracranial-electroencephalography.md?plain=1#L233-L235

For NIRS (types are shared with EEG, MEG, and iEEG -- see last sentence):

https://github.com/bids-standard/bids-specification/blob/741d4ef65610dd4f8fb6cc2ae4943edc4756ffd4/src/modality-specific-files/near-infrared-spectroscopy.md?plain=1#L197-L207

---

We should:

1. clarify/formalize how channel types may be shared between modalities
2. think about how to make this clearer in the schema and the associated rendering of channel type tables in the modality sections

I propose that channel types should be shared between all BIDS modalities.

**Comment by JuliusWelzel** [comment]
Would it make sense to specify for each modality if the keywords in `type` are modality-specific or can be shared? Some channel types might require modality-specific metadata to be shared -> `type` ACCEL in MOTION must also have `component` in the `channels.tsv` specified, `type` LATENCY is independent of any other modality-specific `channels.tsv` column.

I also noted that the glossary for channel types does not specify which modality it refers to (https://bids-specification.readthedocs.io/en/stable/glossary.html#type-sense-1-columns). Currently rendered as `type sense 1`, `type sense 2`, ... .

**Comment by sjeung** [comment]
I do like having channel definitions shared across modalities whenever possible. 
However I also see the need for distinguishing between types that are more central to the modality and more peripheral. 
For instance we should make it explicit that (not all but at least one of) MEG channel types MUST be included if they put the data in MEG folder whereas EEG channels may be included when it happens to have been recorded by the same device. 

For instance, 
(need to still think about the naming) 
eeg core : EEG, EOG ... 
eeg additional : eyegaze, audio ...  

Then the website can only render the core channel types. 
Additional types that are particularly relevant described in text.

And prescribe people with "recommended" modality per channel type?
For instance definition for POS channel type has motion as "recommended" modality, whereas latency can be marked as modality agnostic. 

I acknowledge that this does not have to be a hard set thing because depending on the data set one modality is more important than another, but ideally people should be encouraged to separate between different data modalities and this can be made explicit by recommending a modality per type.

**Comment by sappelhoff** [comment]
In the biweekly maintainers meeting yesterday we discussed a plan that I think goes well together with your suggestions, Julius and Sein. Thanks!

The current plan is to:

1. Go through each channel type and check the definition, and formalize/disambiguate it where needed. Re: Julius [comment](https://github.com/bids-standard/bids-specification/issues/1436#issuecomment-1461571506), it's our goal that each channel type has **one** definition, as opposed to a different usage depending on BIDS modality. From a brief glance at the spec, I think that should currently still be possible without any breakage of backwards compatibility
2. Adjust how channel types are handled in the schema -- in particular we'll see whether something like "Home modalities" for channel types would be feasible (e.g., axial gradiometer have the home modality MEG); "other" channels would be classified under a "common type" home modality (or similar)
3. In each *rendered* BIDS spec modality section we will then list the channel types that belong to that home modality, together with a note that any other types are valid as well, and with a link to a new appendix page that will list **all** channel types in a single table

I'll take care of step 1 soon (next week, probably), and Chris will see whether he can carve out some time to do steps 2 and 3 (with help from the rest of us where needed)


cc @rwblair @effigies @ericearl @bendhouseart -- let me know if I missed something.

**Comment by JuliusWelzel** [comment]
Sounds like a very good solution you came up with! I can draft a table for MOTION-BIDS which channels are "home" in motion and which are not. Would that help?

**Comment by JuliusWelzel** [comment]
One uncertainty on my part when creating a BEP, which I am now realizing, is according to which criteria do I include which existing channel types in my schema objects? What is the rationale for including `Audio` as a channel `type` in EEG, iEEG, MEG and NIRS?

**Comment by JuliusWelzel** [comment]
How is channel type [`SYSCLOCK`](https://github.com/JuliusWelzel/bids-specification/blob/fdfd89c6f7d48e65e0a32f946053de81ab4a4270/src/modality-specific-files/electroencephalography.md?plain=1#L236) different from [`LATENCY`](https://github.com/JuliusWelzel/bids-specification/blob/fdfd89c6f7d48e65e0a32f946053de81ab4a4270/src/modality-specific-files/motion.md?plain=1#L170)? If there is no difference, it might make sense to use only one going forward.

**Comment by sappelhoff** [comment]
> How is channel type [SYSCLOCK](https://github.com/JuliusWelzel/bids-specification/blob/fdfd89c6f7d48e65e0a32f946053de81ab4a4270/src/modality-specific-files/electroencephalography.md?plain=1#L236) different from [LATENCY](https://github.com/JuliusWelzel/bids-specification/blob/fdfd89c6f7d48e65e0a32f946053de81ab4a4270/src/modality-specific-files/motion.md?plain=1#L170)? If there is no difference, it might make sense to use only one going forward.

The `SYSCLOCK` channel type was introduced with the MEG BEP at some point. I have not seen it being used in any BIDS dataset though. Do you remember the reasoning around it, or can provide some context @robertoostenveld @jasmainak @guiomar @teonbrooks ? For which kind of data is this channel type supposed to be used? The definition currently just says:

> System time showing elapsed time since trial started

I find the definition of the `LATENCY` channel type much more clear:

> Latency of samples in seconds from recording onset. MUST be in form of `ss[.000000]` , where [.000000] is an optional subsecond resolution 

Although I would specify what is meant by "recording onset" --> perhaps the onset that is noted down in the `acq_time` column in the `scans.tsv` file?

Furthermore, the `ss` in `ss[.000000]` suggests that there will never be more than 99 seconds, or do I misunderstand this notation?

For reference, here are some similar metadata and their definitions:

[`acq_time`](https://bids-specification.readthedocs.io/en/latest/glossary.html#objects.columns.acq_time__scans) definition (from [scans file](https://bids-specification.readthedocs.io/en/latest/modality-agnostic-files.html#scans-file)):

> Acquisition time refers to when the first data point in each run was acquired. Furthermore, if this header is provided, the acquisition times of all files from the same recording MUST be identical. Datetime format and their anonymization are described in [Units](https://bids-specification.readthedocs.io/en/latest/common-principles.html#units).

[`StartTime`](https://bids-specification.readthedocs.io/en/latest/glossary.html#objects.metadata.StartTime) definition (from physio data):

> Start time in seconds in relation to the start of acquisition of the first data sample in the corresponding neural dataset (negative values are allowed). 

---

In general I agree that we should not introduce a new channel type (`LATENCY`) if an earlier channel type (`SYSCLOCK`) already covers it. Having that said, the `SYSCLOCK` type is not very clearly defined currently, so let's figure that out first.

**Comment by sappelhoff** [comment]
> I noticed the channel of type MAGN in MOTION-BIDS is similar to [MEGMAG](https://github.com/bids-standard/bids-specification/blob/03a569d627529bd858ec3bf00b5c732938bf05e2/src/schema/objects/columns.yaml#LL634C7-L634C13). It seems odd to abbreviate a channel of the same concept (both Magenometers) slightly different (*MAG and MAGN).

I agree it is kind of unfortunate to have this channel type in two versions -- if they do carry the same data.

The definition for MEGMAG currently reads:

> MEG magnetometer

Whereas for MAGN, it reads:

> Magnetic field strength, one channel for each spatial axis. Column `component` for the axis MUST be added to the `*_channels.tsv` file (x, y or z)

Potential solutions: 

1. live with the fact that we'll have `MEGMAG` for just MEG, and use `MAGN` for all other magnetometers
1. add to the definition of `MEGMAG`, saying that if used under anything **but** MEG, it must have an associated `component` metadata entry in `channels.tsv`, and then use `MEGMAG` also for motion 

I dislike the second suggestion because the type would have "MEG" in its name even when used outside of MEG, and because we already agreed (among maintainers) that it's probably not a smart idea to have channel types of the same name take on different meanings depending on the modality they are being used in.

I dislike the first suggestion because we are essentially duplicating a channel type. But I believe that for backward compatibility reasons, this is the road I'd take.

Any other suggestions?

---

(btw @JuliusWelzel and @sjeung, shouldn't the `(x, y, z)` in the description rather refer to the possible values for the `component` column, which are x, y, z, quat_x, quat_y, quat_z, quat_w, and n/a?)

**Comment by sappelhoff** [comment]
Lastly @JuliusWelzel, I think you misunderstood the intention of which modalities channel types are shared with --> the idea is that all channel types can be used in any modality (what you have as "ALL" in your table) ... but that each channel type has a "home modality" (e.g., for `MAGN` it could be motion, for `EEG` it'd be eeg), and when there is an unclear home modality, the home modality would be "common" (e.g., for `MISC` or `SYSCLOCK`).

**Comment by jasmainak** [comment]
I don't have any recollection of SYSCLOCK ... maybe @robertoostenveld could help :) Furthermore, it seems that none of the openneuro datasets [is using it](https://openneuro.org/search?query=%7B%22keywords%22%3A%5B%22sysclock%22%5D%7D)

**Comment by sjeung** [comment]
Thanks @JuliusWelzel for the table! 

Regarding the comment from @sappelhoff about `latency` channel, yes, the onset is intended to be the acq_time of scans.tsv and the text could be updated to make that clear. 
That would also imply that the first sample should always have latency of 0, considering acq_time = when the first data point in each run was acquired.
 
ss[.000000] was not intended to imply integer digit limit. But I see how it is misleading. 
Should we update the notation to s[.000000] and add that s refers to an integer of arbitrary number of digits?


Regarding the `MEGMAG` type I also favor the first suggestion because the use cases are quite different requiring different metadata. 

And the (x,y,z) could simply be omitted or replaced with text description like "... to describe the mapping to the spatial axes"

**Comment by JuliusWelzel** [comment]
> Regarding the comment from @sappelhoff about `latency` channel, yes, the onset is intended to be the `acq_time` of `scans.tsv` and the text could be updated to make that clear. That would also imply that the first sample should always have latency of 0, considering `acq_time` = when the first data point in each run was acquired.

Good point, I will update the text accordingly.

> ss[.000000] was not intended to imply integer digit limit. But I see how it is misleading. Should we update the notation to s[.000000] and add that s refers to an integer of arbitrary number of digits?

I think it would be more feasible to `hh:mm:ss[.000000]` as indicated here for time stamps (https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#units). This would make it more human readable if you have big latencies (e.g. 10000 secs). 

> Regarding the `MEGMAG` type I also favor the first suggestion because the use cases are quite different requiring different metadata.

+1 for Stefan first proposed solution.

> And the (x,y,z) could simply be omitted or replaced with text description like "... to describe the mapping to the spatial axes"
 
I like that!

**Comment by sjeung** [comment]
When it comes to latency channel values, I would stick to the numeric format for keeping the content of .tsv uniform because I remember running into some problems (both reading and writing) when I mix non-numeric datetime and numerics as entries for .tsv

**Comment by JuliusWelzel** [comment]
> When it comes to latency channel values, I would stick to the numeric format for keeping the content of .tsv uniform because I remember running into some problems (both reading and writing) when I mix non-numeric datetime and numerics as entries for .tsv

That is a good argument. 

> Furthermore, the ss in ss[.000000] suggests that there will never be more than 99 seconds, or do I misunderstand this notation?

What would be best to address Stefan's comment?  
[`acq_time`](https://bids-specification.readthedocs.io/en/latest/glossary.html#objects.columns.acq_time__scans) has to be in datetime and [`StartTime`](https://bids-specification.readthedocs.io/en/latest/glossary.html#objects.metadata.StartTime) does not specifically say it can be subsecond precision, which would be important to indicate.

**Comment by helenacockx** [comment]
I noticed that we might have a redundancy in the proposed keywords for motion channel types currently. There is a channel name `GYRO` and `ANGVEL`, while gyroscopes, in fact, measure angular velocity. I think we should choose one of both here. 
`ANGVEL` seems most logical given that the other channel types also describe what the motion trackers measure, rather than what they technically are (e.g., `POS`). However, `GYRO` was already implemented in the fINRS-BIDS...

**Comment by helenacockx** [comment]
One other remark: we have `ACCEL`, but `ANGACC`. Wouldn't it make sense to make this consistent too, so `ANGACCEL`?

**Comment by JuliusWelzel** [comment]
> I noticed that we might have a redundancy in the proposed keywords for motion channel types currently. There is a channel name GYRO and ANGVEL, while gyroscopes, in fact, measure angular velocity. I think we should choose one of both here.

Thanks for spotting this! We had the exact discussion a while back and agreed on GYRO over ANGVEL see [here](https://groups.google.com/g/bids-discussion/c/JH9t06EA7UQ/m/V5Z0z2xVBgAJ). I fixed it in 8cad179ec2c2e3cbcf407a9ec201c93ee6d2561b.

**Comment by JuliusWelzel** [comment]
> One other remark: we have `ACCEL`, but `ANGACC`. Wouldn't it make sense to make this consistent too, so `ANGACCEL`?

We also discussed this on GH, but unfortunately I don't recall or find the reasoning. Maybe @sjeung can remember?

**Comment by sappelhoff** [comment]
> One other remark: we have ACCEL, but ANGACC. Wouldn't it make sense to make this consistent too, so ANGACCEL?

@helenacockx is this just a suggestion for renaming `ANGACC` to  `ANGACCEL`? If yes, then I'd be in favor of this.

**Comment by robertoostenveld** [comment]
Yes, that is what it is. I am also in favor.

**Comment by sappelhoff** [comment]
I have taken the liberty to push these changes to @JuliusWelzel's PR:

- https://github.com/bids-standard/bids-specification/pull/1478

@sjeung @JuliusWelzel please confirm that this is fine, then we can merge it and adjust the examples. I'll also have a look at the BIDS validator when the PR is merged.

**Comment by JuliusWelzel** [comment]
Look good to me, thanks!

**Comment by sjeung** [comment]
> I have taken the liberty to push these changes to @JuliusWelzel's PR:
> 
> * [[FIX] motion channel types: remove ANGVEL, rename ANGACC -> ANGACCEL #1478](https://github.com/bids-standard/bids-specification/pull/1478)
> 
> @sjeung @JuliusWelzel please confirm that this is fine, then we can merge it and adjust the examples. I'll also have a look at the BIDS validator when the PR is merged.

Too me, too. I don't recall any particular reason to prefer ANGACC to ANGACCEL, except for the length. I am fine with renaming and will adjust example data sets accordingly. 

Thanks for the feedback Helena & for update Stefan!

**Comment by JuliusWelzel** [comment]
@sappelhoff 
Just checking the Issues I was involved in for the 1.9 release. :)

I think this issue can be closed as it seems to be addressed [here](https://github.com/bids-standard/bids-specification/blob/8dc522157743c636bcf752d90e07d70ba41c5f19/src/schema/objects/columns.yaml#L618). For future BEPs, all available channels type can be found in this schema object, correct? If a new channel type is introduced, it will be added here as well.

**Comment by sappelhoff** [comment]
indeed @JuliusWelzel, thank you. I am closing this in favor of:

- https://github.com/bids-standard/bids-specification/issues/1529

however, #1529 will be taken off the 1.9 release as it's mostly visuals that can also be added *after* a release.
