### ISSUE TITLE
"fromrecorded"

### ISSUE THREAD

**Issue by arokem** [bids-standard/bids-specification#1452]
Is this a typo? Or is "fromrecorded" a technical term?

https://github.com/bids-standard/bids-specification/blame/8bc376ed4fb700fec3c266ef5b72c8c311a8f131/src/schema/objects/suffixes.yaml#L676

**Comment by arokem** [comment]
Potentially addressed in 104abd53

**Comment by tsalo** [comment]
I also fixed it in #1451, so it should be fixed via one PR or another soon.

**Comment by arokem** [comment]
My money is on #1451 😄

**Comment by effigies** [comment]
I took the fix showing up in two PRs as two votes and just cherry-picked it in. You're both authors on the commit.
