### ISSUE TITLE
HTML files and images in BIDS

### ISSUE THREAD

**Issue by ericearl** [bids-standard/bids-specification#148]
Hello BIDS folks!

Our lab has BIDS derivatives files which are basically static quality control HTML websites generated per sub-SUBJECT_ses-SESSION as part of a bigger pipeline (with many stages/sub-components).  These static HTML pages have an interactive Brainsprite of T1 and T2 with white matter and pial surface overlays as well as every task-*_bold registration and movement plots for each task.  We call this HTML QC site the “Executive Summary”.  I did not see anything in the BIDS derivatives BEP covering the idea of multi-type (anat & func) HTML derivatives like this:

- …/ABCD/derivatives/dcan_abcd_pipeline/sub-SUBJECT/ses-SESSION/
    - sub-SUBJECT_ses-SESSION_executivesummary.html
    - img/
        - [png & gif files]
 
What should we name and place these as in the derivatives/dcan_abcd_pipeline/?

**Comment by dasturge** [comment]
The common derivatives specification does allow for an html file, however it does not comment on how to handle image files.

For now, our group has elected to use an "img" folder as is standard in basic html, with no particular restriction on the contents as of yet, as they are meant to be viewed in the webpage, and they contain overlays of multiple derivative images so it's not obvious how one would name them.

**Comment by effigies** [comment]
Hi @ericearl, sorry I missed this. Yes, HTML reports are not well specified in derivatives. The current philosophy is that the derivatives should focus largely on the data files needed for further analysis, and report naming conventions can be somewhat idiosyncratic without damaging a derivatives dataset's reusability.

fMRIPrep's current reporting strategy looks like the following:

```
fmriprep/
    sub-01/
        anat/
        figures/
            ...
        func/
    ...
    sub-01.html
    ...
```

So they're mixed right in. In FitLins, I'm following an approach more similar to yours, with the run-level HTML reports falling in the `func/` output directory, and the group-level HTML reports at the root. (This is likely to change as my directories are getting full...)

I'm not sure either of these is the best way, and if there's a move to standardize reporting in the future, we can revisit. Maybe for now this issue can stand as an advisory doc where approaches are enumerated and pros and cons can be listed. If it gets unwieldy, we can turn it into a real doc.
