### ISSUE TITLE
Clarify that a `rawdata` directory is not a prescription

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#1519]
https://github.com/bids-standard/bids-specification/blob/40f4fbb0649a8dab65f4327df342251ad841bfb8/src/common-principles.md?plain=1#L289-L291

although this sentence might make it seem as if it were. (re: discussion at sprint)

**Comment by effigies** [comment]
I suppose we could just add

> (Note that `rawdata` here is an arbitrarily-chosen name. BIDS specifies the contents of a dataset, not the names of directories containing datasets.)
