### ISSUE TITLE
Unknown Contrast Agent in BIDS

### ISSUE THREAD

**Issue by RaphaelMaser** [bids-standard/bids-specification#1542]
Hello,
We (@adhusch, @MeryemABBAD) are trying to convert several datasets from DICOM to the BIDS format. There are some datasets which use a contrast agent but it's not clear which one was used.
There is the ContrastBolusIngredient field in the meta-data but the documentation states that "Allowed values: IODINE, GADOLINIUM, CARBON DIOXIDE, BARIUM, XENON". Secondly there is the ceagend entity but the documentation states that it represents the ContrastBolusIngredient field. We assume that by using "ce: True" and "ContrastBolusIngredient: UNKNOWN" the dataset would not comply with BIDS anymore. How does BIDS handle these cases?
Thanks!

**Comment by Remi-Gau** [comment]
> How does BIDS handle these cases?

I don't think we have to face the issue yet. So this is a first one.

I tested on one of the bids example with some dummy values (see below) and it seems that the validator does not catch those issues... Yet.

Once the validator starts on the schema, those may get flagged as errors

```
ds001/sub-01
├── anat
│   ├── sub-01_ce-foo_T1w.json
│   ├── sub-01_ce-foo_T1w.nii.gz
│   └── sub-01_inplaneT2.nii.gz
```

```bash
$ cat ds001/sub-01/anat/sub-01_ce-foo_T1w.json 

{"ContrastBolusIngredient": "foo"}
```

**Comment by RaphaelMaser** [comment]
Thanks for you answer!
So, if I understand you correctly then this would not be a future-proof way of indicating the contrast agent. Is there a better way to include the information about the contrast agent without (potentially) loosing bids validity in the future?

**Comment by Remi-Gau** [comment]
Maybe adding an "unknown" case in the specification would make sense here. I definitely would not be opposed to it.

@effigies what do you think?

**Comment by effigies** [comment]
Seems like there's a legitimate use case, so we should support it. Also seems like there should be a `none` value, to distinguish scans with/without in studies that have both.

**Comment by RaphaelMaser** [comment]
Thanks for your help, including these options in the specification would be great!

**Comment by Remi-Gau** [comment]
This is what the new metadata definition would look like:

https://bids-specification--1547.org.readthedocs.build/en/1547/glossary.html#contrastbolusingredient-metadata

**Comment by CPernet** [comment]
those agents are constrained by the DICOM standard (same as PET)

**Comment by CPernet** [comment]
given the list: changes are  
- barium --> Barium Sulfate
- iodine -- well there are many variations just iodine does not look correct
- xenon does not look supported ? where is this coming from 
- none -- fine
- UNKNOWN -> contrast agent (there is such a general term in the list)

as a practical matter, I suggest to make a list (json to yml) with explicit reference to DICOM and validated checking values in there
