### ISSUE TITLE
Mistake in the PDw suffix description

### ISSUE THREAD

**Issue by jeremie-fouquet** [bids-standard/bids-specification#1572]
I stumbled on what appears to be a mistake in the [PDw suffix description](https://github.com/bids-standard/bids-specification/blob/ada2c5d445f1c0eab306e7a0d691e1889f1ffe4c/src/schema/objects/suffixes.yaml#L237). It says:

> In spin-echo sequences this contrast is achieved at short repetition and long echo times.

However, the opposite is true, i.e., [in spin-echo sequences, this contrast is achieved at long repetition and short echo times, just like in gradient echo sequences](https://mriquestions.com/image-contrast-trte.html). This description section should be changed to something like: "In both spin-echo and gradient-echo sequences, this contrast is achieved at long repetition and short echo times, and at small flip angles in gradient-echo."

**Comment by effigies** [comment]
Looks correct. Care to submit your fix?
