### ISSUE TITLE
Add CHUNCK entity for (spinal) MRI 

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#1574]
### Your idea

- mentioned at the BIDS townhall 2023
- briefly discussed with @jcohenadad at OHBM2023

@jcohenadad if you want support for this, I think this could be added to BIDS mri anat without too much struggle (famous last words).

But it'd be best if this came along with an example dataset that we can link to in the bids example repo.

**Comment by sappelhoff** [comment]
is this related to:

- https://github.com/bids-standard/bids-specification/issues/1382
- https://github.com/bids-standard/bids-specification/issues/935

?
