### ISSUE TITLE
SliceTiming for 3D acquisitions

### ISSUE THREAD

**Issue by neurolabusc** [bids-standard/bids-specification#1585]
I suggest that the [SliceTiming](https://bids-specification.readthedocs.io/en/stable/glossary.html#slicetiming-metadata) and [Timing Parameters](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#timing-parameters_1) sections of the specification be extended to note that `SliceTiming` is not required or allowed when [MRAcquisitionType](https://bids-specification.readthedocs.io/en/stable/glossary.html#mracquisitiontype-metadata) is `3D` as I describe [here](https://neurostars.org/t/3d-func-bold-bids-sidecar/26509).

**Comment by tsalo** [comment]
I agree. This is already successfully handled for ASL data, so it should be straightforward to apply for general MRI data.
