### ISSUE TITLE
Location of raw data: rawdata subfolder?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [bids-standard/bids-specification#159]
_BIDS_ is centred around **raw data**. This probably used to make sense but nowadays I see more and more users working with **derived data** - perhaps thanks to _BIDS_ and other efforts to standardize raw data and code. Many users in my lab disagree with hiding derived data in `derivatives` and storing **raw data** directly under the root folder of the project.

In addition to the imbalance between the different categories of data (_source_, _raw_ and _derived_) important files such as `README` or `participants.tsv` are lost alongside `sub-<label>` subfolders. In projects with thousands of subjects stored on an NFS share a mere `ls` in the root folder may require many seconds.

Would you consider an **option** to store raw data in a `rawdata` subfolder instead of the root folder?

**Comment by satra** [comment]
@DimitriPapadopoulos - as far as the spec is concerned, derivatives does not even have to be under the bids dataset.

in most of our use cases derived data is in a separate filesystem relative to raw data. we took that decision, because raw data is somewhat essential and needs to be backed up (actually mostly the source data - since we can derive bids dataset from it). there are also other efficiency uses in access to files from a cluster.

i also know of at least one center that puts the raw data set under derivatives using a source data folder.

**Comment by DimitriPapadopoulos** [comment]
@satra Still, `derivatives` _may_ contain derived data, even if is_not required_ to store derived data in `derivatives`. If we do choose to publish a dataset with derived data as a single BIDS dataset, derived data in `derivatives` are hidden by the cluttered root folder.

Thank you for the suggestion to store raw data under `derivatives/rawdata` (or really `derivatives/sourcedata`?) which may help in some use cases.

By the way, in many of our cases we store source data (DICOM files) in a different file system as well. They are not visible on the same file system because they may be seen as more sensitive (more difficult to anonymize/pseudonymize than NIfTI because of the undocumented private tags).

**Comment by nicholst** [comment]
@DimitriPapadopoulos - You may want to enter this suggestion into the BIDS
2.0 Suggestion document -
https://docs.google.com/document/d/1LEgsMiisGDe1Gv-hBp1EcLmoz7AlKj6VYULUgDD3Zdw/edit#

This is a place we collect suggestions that represent major breaks in
backwards compatibility.

**Comment by DimitriPapadopoulos** [comment]
@nicholst Done. Hope I have done things correctly.

> ### Alternative location for raw data
> Raw data are currently stored under the root folder of the dataset.
> * The root folder gets cluttered by `sub-<label>` subfolders and hides important files such as `README` and derived data in `derivatives`.
> * This also creates an imbalance with source data that are stored in `sourcedata` and derived data in `derivatives`.
> 
> Perhaps raw data could be stored in an (optional?) `rawdata` subfolder.

**Comment by satra** [comment]
> Still, `derivatives` _may_ contain derived data, even if is _not required_ to store derived data in `derivatives`. If we do choose to publish a dataset with derived data as a single BIDS dataset, derived data in `derivatives` are hidden by the cluttered root folder.

@DimitriPapadopoulos - in fact i suggested this for someone converting dicoms to bids on a neurostars discussion, and i completely agree that in many cases the raw dataset can get cluttered.

**Comment by chrisfilo** [comment]
This has been discussed at a few venues before. Perhaps we should add the following to the spec.

If you wish to separate raw data, source data and derivatives a following folder structure can be adopted:

```
ds00999/
  sourcedata/
  rawdata/
    dataset_description.json
    participants.tsv
    sub-01/
    sub-02/
  derivatives/
```

In this scheme neither `ds00999`, `sourcedata`, nor `derivatives` is a BIDS dataset. Only `rawdata` is a BIDS dataset.

The above scheme is perfectly legal with the current spec - without the need to introduce additional changes.

**Comment by DimitriPapadopoulos** [comment]
Ah, I hadn't thought of that. Excellent workaround!

On the other hand we lose the benefit of having derived data in a BIDS dataset. Somehow this confirms that BIDS is centred on raw data. Perhaps standardizing derived data and keeping derived data in BIDS datasets is not a reasonable goal in the short term?

**Comment by chrisfilo** [comment]
Standardizing derived data is underway (see #109), and it will support nested as well as standalone derived datasets.

**Comment by DimitriPapadopoulos** [comment]
If standardizing derived data is underway, then it makes sense to have raw and derived data in the same BIDS dataset, in which case I think my comments still apply and need to be considered:
* **cluttered root folder:** If you have thousands of subjects a mere `ls` on an NFS share may require lots of seconds. Important files such as `README` or `participants.tsv` are lost in a sea of `sub-<label>` files.
* **imbalance between raw data and derived data:** Nowadays derived data are getting more important than raw data but they remain hidden under the cluttered root folder.

It remains possible to maintain raw and derived data in different as you suggest, but then wouldn't the file hierarchy for derived data be too deep?
```
global_dataset_directory/    # not a BIDS dataset
    rawdata/                 # separate BIDS dataset for raw data
    derivatives/             # separate BIDS dataset for derived data
        derivatives/         # this directory is too deep!
```

**Comment by chrisfilo** [comment]
The example is unusual but would be supported under #109. We digress though - this discussion is better had in the #109 thread.

In the short term it's probably best to add the example from https://github.com/bids-standard/bids-specification/issues/159#issuecomment-465685643 to the current spec.

**Comment by DimitriPapadopoulos** [comment]
I will have a look at #109, thank you for pointing to it.
