### ISSUE TITLE
CONTRIBUTING.md vs. BIDS Contributor Guide

### ISSUE THREAD

**Issue by nicholst** [bids-standard/bids-specification#160]
The [Extending the BIDS specification](https://bids-specification.readthedocs.io/en/latest/06-extensions.html) section of BIDS v1.1.2-dev currently only points to the G-doc based [BIDS Contributor guide](https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/edit?usp%3Dsharing&sa=D&ust=1537468908724000) and doesn't mention [`CONTRIBUTING.md`](https://github.com/bids-standard/bids-specification/blob/master/CONTRIBUTING.md).

Conversely,  [`CONTRIBUTING.md`](https://github.com/bids-standard/bids-specification/blob/master/CONTRIBUTING.md) doesn't mention the [BIDS Contributor guide](https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/edit?usp%3Dsharing&sa=D&ust=1537468908724000).

I was just about to lodge a tiny PR to change the standard to point solely to `CONTRIBUTING.md` but I now see that the BIDS Contributor guide has a lot that isn't in `CONTRIBUTING.md`, in particular on creating drafts of extensions in Google docs.

Should we (a) merge the content of the [BIDS Contributor guide](https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/edit?usp%3Dsharing&sa=D&ust=1537468908724000) guide into [`CONTRIBUTING.md`](https://github.com/bids-standard/bids-specification/blob/master/CONTRIBUTING.md)?  Or just (b) edit the [Extending the BIDS specification](https://bids-specification.readthedocs.io/en/latest/06-extensions.html) to additionally point to [`CONTRIBUTING.md`](https://github.com/bids-standard/bids-specification/blob/master/CONTRIBUTING.md)?

**Comment by emdupre** [comment]
Personally, I read CONTRIBUTING as geared towards the process of making a contribution (i.e., how to open PRs). The BIDS Contributor guide, meanwhile, seems more oriented towards the decision to create a new BEP and some guidelines for that process. 

Since it seems that there's a distinction in the goals of these two documents, I'd probably keep them as two separate files but have them point to one another !

**Comment by sappelhoff** [comment]
I agree with @emdupre - however I think that it'd be smart to link from one guide to the other and vice versa, with a brief sentence on describing the goals of each of the guides.

Would you be fine with that solution @nicholst?

**Comment by emdupre** [comment]
One other idea -- maybe we could rename the BIDS Contributor Guide to something less likely to create confusion with CONTRIBUTING.md. What about BEP Lead Guidelines or something similar ?

**Comment by nicholst** [comment]
Yes @emdupre I think changing the name of the non-CONTRIBUTING.md file is a great idea.

So we have `CONTRIBUTING.md` as a traditional "how do I contribute PRs to this github-based standard?", vs. an external "BIDS Extension Proposals: A guide" type document.  This would be great.

**Comment by effigies** [comment]
:+1:

**Comment by sappelhoff** [comment]
done: https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/

thanks everybody!
