### ISSUE TITLE
[BUG] Broken link to BEP guidelines

### ISSUE THREAD

**Issue by cmaumet** [bids-standard/bids-specification#1621]
### Describe your problem in detail.

Hi everyone!

Looking in the BIDS-specification at https://bids-specification.readthedocs.io/en/stable/07-extensions.html: 
 - the link onto "BEP guidelines Google Doc" leads to https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/ 
 - this link brings us to a Google doc that turns mentions "The content of this document has been moved to this page: https://bids.neuroimaging.io/bep_guide.html"
 - the link is 404 file not found.

### Describe what you expected.

A link to the BEP contributor guidelines. Any help is very welcome!

### BIDS specification section

https://bids-specification.readthedocs.io/en/latest/...

**Comment by Remi-Gau** [comment]
a horde of dead links 🧟 🧟‍♀️ 🧟‍♂️ 

here are the correct ones:
repo: https://github.com/bids-standard/bids-extensions
doc: https://bids-extensions.readthedocs.io/en/latest/

**Comment by Remi-Gau** [comment]
AFAICT this is already fixed on latest:

- stable: https://bids-specification.readthedocs.io/en/stable/07-extensions.html
- latest: https://bids-specification.readthedocs.io/en/latest/07-extensions.html

you can switch spec version directly via the URL or 
by selecting from a menu at the bottom right:

![image](https://github.com/bids-standard/bids-specification/assets/6961185/a8f86d32-524e-48be-8ee5-cdbfd447b6c0)

**Comment by Remi-Gau** [comment]
Maybe we don't do enough bug-fix release between minor release, so I usually have "latest" as my default bookmark.

**Comment by cmaumet** [comment]
Thanks for the pro-tip ;)
