### ISSUE TITLE
electrical stimulation during MEG/EEG recordings

### ISSUE THREAD

**Issue by MatthiasSure** [bids-standard/bids-specification#1635]
Hello everyone, I work with MEG data with simultaneous deep brain stimulation. However, there is no field for MEG data to store information for electrical stimulation in a standardized way. Since there is a field for this in iEEG data, I would suggest enabling this field also for MEG and EEG data?
Would this be feasible?
Greetings,
Matthias

**Comment by effigies** [comment]
cc @bids-standard/raw-electrophys

**Comment by sappelhoff** [comment]
I don't see why this wouldn't be feasible. +1 to permit it

**Comment by robertoostenveld** [comment]
+1

**Comment by effigies** [comment]
Is this as simple as copying:

https://github.com/bids-standard/bids-specification/blob/0dcb141fccec5bbd92e482a071fefba0d0bbfdb1/src/modality-specific-files/intracranial-electroencephalography.md?plain=1#L511-L533

Into EEG and MEG, but with a couple words fixed up here and there? Or is there more to add/modify?

**Comment by sappelhoff** [comment]
Reading this alerts me to the fact that while for iEEG, the source of electrical stimulation is specified (via the iEEG electrodes), this is not apparent for your usecase @MatthiasSure -- how are you doing it? how are you planning to document it within BIDS?

is adding an explicit description of the `electrical_stimulation_<label>` column to MEG and EEG what you had in mind with your request here?

**Comment by MatthiasSure** [comment]
I did not realize that electrical_stimulation_<label> was linked to the iEEG channels. I assumed that you can write all contents in electrical_stimulation_<label without restrictions. My plan would have been to specify under electrical_stimulation_<label> for each implanted electrode the fields IPG, electrode type, stimulation contact, stimulation frequency, stimulation amplitude, stimulation pulse width, and stimulation type(cyclic or continuous). These are all values that are useful in reconstructions, artifact cleanups, and specific analyses (e.g., focus on the time between stimulation pulses). Since these are values that can change between runs, I didn't find the participants.tsv useful and thought that the electrical_stimulation_<label> could be used to specify the values in at least some order.

**Comment by robertoostenveld** [comment]
It needs to be specified how the intracranial electrical stimulation is done. Do you have, next to the `bidsroot/sub-01/meg` folder in the raw dataset, also an `bidsroot/sub-01/ieeg` with the specification of electrodes and channels?

**Comment by dorahermes** [comment]
These two scenarios for electrical stimulation in iEEG are currently described:

1) The electrical stimulation has an event-like structure with onsets. In this case, in the _ieeg.json, the "ElectricalStimulation" field is true and the  "ElectricalStimulationParameters" may contain parameters. In addition, the _events.tsv file may describe the onsets and electrodes that were stimulated as @effigies indicated above. For examples op OpenNeuro, see: https://openneuro.org/datasets/ds004696/versions/1.0.0 and https://openneuro.org/datasets/ds004080/versions/1.2.4

2) The electrical stimulation is continuous. In this case, in the _ieeg.json, the "ElectricalStimulation" field is true and the  "ElectricalStimulationParameters" should have a text description of the parameters. 

Not sure what the case is for you deep brain stimulation data?

**Comment by MatthiasSure** [comment]
Hi,

@robertoostenveld So far, I have not had a complete BIDS compliant dataset, as I was first trying to figure out how to properly incorporate the DBS information. In my dataset, no information about the stimulation parameters goes into the acquisition software of the MEG because it is a chronically implanted deep brain stimulation system in Parkinson's patients. Using a tablet, I can connect to the implanted pulse generator and read and change the stimulation parameters (e.g., stimulation contact). This is, therefore, information that has to be entered by hand or read out from a PDF document.

@dorahermes Usually, it is a continuous stimulation. Meanwhile, we can also set a cyclic stimulation via the IPG (e.g. stimulation every 5 seconds on or off).

I hope I have answered the questions.

**Comment by dorahermes** [comment]
@MatthiasSure that helps a lot. Since the stimulation is continuous, and not an event-structure, you would currently have option 2) in the ieeg case:
In the `_ieeg.json` file the `ElectricalStimulation` field is true and `ElectricalStimulationParameters` can describe the parameters in freeform text. (As there are no standards yet to describe electrical stimulation parameters, this text is currently freeform).

This would translate to MEG if the `_meg.json` file has optional fields for `ElectricalStimulation` and `ElectricalStimulationParameters`.

**Comment by sappelhoff** [comment]
@dorahermes' suggestion could be easily implemented both in the BIDS schema (copying the following over to MEG and EEG):

https://github.com/bids-standard/bids-specification/blob/8d9c8df35ee175f0b31f1820de3aef08d07c6422/src/schema/rules/sidecars/ieeg.yaml#L89-L96

and in the legacy validator (copying the following over to MEG and EEG): 

https://github.com/bids-standard/bids-validator/blob/78fbf69878d638ae515e85dd8577a58ab0fb67cc/bids-validator/validators/json/schemas/ieeg.json#L81-L82

... And perhaps the DBS probe itself could be specified as if it were an iEEG electrode? If it's necessary to specify this beyong what could be put into the free form `ElectricalStimulationParameters` field and the `README` of the dataset.

**Comment by MatthiasSure** [comment]
I think that both options, either describing the DBS electrodes as iEEG electrodes or as free text in ElectricalStimulationParameters, should be sufficient until measurements with DBS are further standardized.

**Comment by dorahermes** [comment]
Nice! Note - in the iEEG extension, DBS electrodes are a type of electrode. There were many DBS scientists involved in the iEEG extension and BIDS-iEEG was intended to cover DBS, but would be good to understand if there are any specific issues.

**Comment by MatthiasSure** [comment]
I think one issue is that stimulation settings are highly variable (bipolar vs monopolar stimulation, is one or more contacts used for stimulation, etc). Then for further analysis, such as the Volume of Tissue activated, the exact location of the electrodes would also be interesting. This would be all information that would probably have to be added as free text according to the current possibilities.

**Comment by sappelhoff** [comment]
@MatthiasSure maybe BEP037 is of interest to you:  https://bids.neuroimaging.io/bep037
