### ISSUE TITLE
Allow modification of the changelog post merge

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/bids-specification#164]
The changelog is currently generated automatically without a possibility to manually modify an incorrect PR title post-merge. This would be useful to correct typos and improve the clarity of the changelog.

**Comment by franklin-feingold** [comment]
The changelog generator implemented will process PR updates (i.e. modifying the PR title) and be updated in the next merged PR. The generation happens at the next merged PR because that is the action that triggers a changelog build and deploy.

**Comment by chrisfilo** [comment]
Ok so if I understand you correctly you are saying that we can go to github web interface and changed names of historical PRs that have already been merged. Upon next merge of a new PR those changes will be picked up by the changelog generator and the changelog will be updated.

This sort of works, but it does require a new PR (non release one) to be merged to triger regeneration of the changelog. I was envisaging tweaking the changelog as part of the release process. @effigies what do you think?

**Comment by effigies** [comment]
On the whole, I'd prefer that there was an opportunity to manually set a ground truth, instead of manipulating the algorithm's inputs. But this does sound like a relatively easy first pass adjustment.

**Comment by franklin-feingold** [comment]
Correct and the reason it is on merged PR's is that we do not want the changelog to be generated on commits because then it will get into a circle due to the changelog being pushed automatically into the repo. I think in line with your thinking - as part of the release PR there will also be an updated changelog as well?

If I'm interpreting what you are describing - in the PR review process we would have a set of controlled vocabulary that the label can be and before the PR is merged confirm that the label is there and part of the vocabulary?

**Comment by effigies** [comment]
Just to link in discussion in https://github.com/bids-standard/bids-specification/pull/232#issuecomment-493122650:

> I think there should be two changelogs: the repository changelog and the specification changelog. When somebody's reading the spec, what they care about is what new features are there in the specification, and absolutely not what changes were made to the build system.
> 
> IMO, the specification changelog should ONLY include `[FIX]` and `[ENH]` changes, and should strip out the tags. I also think we should be able to go in and retroactively fix the changelog to be more human friendly without our changes getting destroyed every time a PR gets merged.

**Comment by franklin-feingold** [comment]
My concern regarding two changelogs is the maintenance and piping for each to stay up to date. I can envision using the pieces we have of the current changelog generator to create both of these logs, then having a pruning call to clean it up and keep what each needs.

> I also think we should be able to go in and retroactively fix the changelog to be more human friendly without our changes getting destroyed every time a PR gets merged.

This is possible within our current solution. It would be "freezing" old changes (i.e. when a new release has deployed the changelog generator will only look to capture the most recent changes and ignoring everything older than that (I believe this is based off tagging)
