### ISSUE TITLE
[BUG] /phenotype is not listed as an allowed top-level directory

### ISSUE THREAD

**Issue by VisLab** [bids-standard/bids-specification#1642]
### Describe your problem in detail.

In [**Modality agnostic files**](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#phenotypic-and-assessment-data) the specification says:

> Each of the measurement files MUST be kept in a `/phenotype` directory placed at the root of the BIDS dataset and MUST end with the .tsv extension.

but `phenotype` is not listed as one of the allowed top-level directories in [https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#filesystem-structure](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#filesystem-structure)

**Comment by Remi-Gau** [comment]
I confirm that this indeed also the case in the latest version: https://bids-specification.readthedocs.io/en/latest/common-principles.html#filesystem-structure
