### ISSUE TITLE
Add support for HiP-CT

### ISSUE THREAD

**Issue by balbasty** [bids-standard/bids-specification#1646]
Dear BIDS community

[Hierarchical Phase-Contrast Tomography (HiP-CT)](https://mecheng.ucl.ac.uk/hip-ct/) is an _ex vivo_ X-ray technique that leverages high-energy X-ray sources -- specifically, the ESRF's [Extremely Brilliant Source (EBS)](https://www.esrf.fr/home/UsersAndScience/Accelerators/ebs---extremely-brilliant-source.html).  HiP-CT is non-destructive, reaches resolutions of 1 to 10 um, and allows specific ROIs to be imaged within the sample without physical sectioning. Although the modality is obviously not widely available, the UCL group has a relatively streamlined acquisition process and we will be collecting data on multiple brains in the coming years.

We would like to add support for HiP-CT in BIDS, and we think it most naturally fits as a new [modality suffix](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/10-microscopy.html#modality-suffixes) within the microscopy extension. This makes sense because micro-CT is already supported as a microscopy suffix. Also, the microscopy extension already includes tags that are required by HiP-CT data (for example, the existence of multiple images of the same samples, potentially with different resolutions and different field-of-views, labeled as `chunk-`). We are therefore proposing to add the `hipCT` suffix to the microscopy extension.

We have uploaded an exampled dataset that follows the proposed convention to DANDI:
https://dandiarchive.org/dandiset/000026/draft/files?location=sub-I58%2Fses-Hip-CT%2Fmicr&page=1
We also provide three neuroglancer links that allow each volume to be visualized online, directly streaming the dandi data:
- [sub-I58_sample-01_chunk-01_hipCT.ome.zarr](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22z%22:%5B0.00001513%2C%22m%22%5D%2C%22y%22:%5B0.00001513%2C%22m%22%5D%2C%22x%22:%5B0.00001513%2C%22m%22%5D%7D%2C%22position%22:%5B3527.632568359375%2C3794.590087890625%2C5184%5D%2C%22crossSectionScale%22:31.390256894755275%2C%22projectionScale%22:16384%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/5c37c233-222f-4e60-96e7-a7536e08ef61%22%2C%22tab%22:%22rendering%22%2C%22shaderControls%22:%7B%22normalized%22:%7B%22range%22:%5B22104%2C25953%5D%7D%7D%2C%22name%22:%225c37c233-222f-4e60-96e7-a7536e08ef61%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%225c37c233-222f-4e60-96e7-a7536e08ef61%22%7D%2C%22layout%22:%224panel%22%7D) : left hemisphere @ 15.13 um
- [sub-I58_sample-01_chunk-02_hipCT.ome.zarr](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22z%22:%5B0.00000621%2C%22m%22%5D%2C%22y%22:%5B0.00000621%2C%22m%22%5D%2C%22x%22:%5B0.00000621%2C%22m%22%5D%7D%2C%22position%22:%5B5451.6162109375%2C5732.28466796875%2C4546.75244140625%5D%2C%22crossSectionScale%22:49.156053362683316%2C%22projectionScale%22:16384%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/a2861b6d-074a-46cc-a221-b6e9a75dc6be/%22%2C%22tab%22:%22rendering%22%2C%22shaderControls%22:%7B%22normalized%22:%7B%22range%22:%5B13177%2C21152%5D%7D%7D%2C%22name%22:%22a2861b6d-074a-46cc-a221-b6e9a75dc6be%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22a2861b6d-074a-46cc-a221-b6e9a75dc6be%22%7D%2C%22layout%22:%224panel%22%7D) : Broca's area @ 6.21 um
- [sub-I58_sample-01_chunk-03_hipCT.ome.zarr](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22z%22:%5B0.00000621%2C%22m%22%5D%2C%22y%22:%5B0.00000621%2C%22m%22%5D%2C%22x%22:%5B0.00000621%2C%22m%22%5D%7D%2C%22position%22:%5B2329.662353515625%2C4528%2C4731.287109375%5D%2C%22crossSectionScale%22:39.25190586030442%2C%22projectionScale%22:16384%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22zarr://https://dandiarchive.s3.amazonaws.com/zarr/1904d2d9-ed31-4cf5-b723-eedff28d2c7c/%22%2C%22tab%22:%22rendering%22%2C%22shaderControls%22:%7B%22normalized%22:%7B%22range%22:%5B6517%2C13261%5D%7D%7D%2C%22name%22:%22a2861b6d-074a-46cc-a221-b6e9a75dc6be%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22a2861b6d-074a-46cc-a221-b6e9a75dc6be%22%7D%2C%22layout%22:%224panel%22%7D) : Brainstem @ 6.21 um

Let me also include a typical metadata file provided by the UCL group:
```
############# DOI ###################

Title		= "U.N."
Abstract	= "U.N."
Users		= "U.N."


############ proposal ###############

proposalTitle   ="U.N."
proposalNumber  ="md190"
proposers       ="U.N."
experimentType  ="U.N."
technique       ="U.N."
beamlineName    ="BM18"
instrumentName  ="U.N."


############ patient ################

PatientInstitue ="U.N."
PatientNumber   ="I58-LH"
PatientAge      ="U.N. years"
PatientSex      ="U.N."
PatientWeight   ="U.N. kg"
PatientSize     ="U.N. cm"
PatientMedInfo  ="U.N."


########### sample ################

SampleName  ="I58-LH_brain"
SampleInfo  ="complete heart from the body donor program of the Laboratoire d'Anatomie des Alpes Francaise (LADAF)"
SamplePrep  ="formalin fixed, progressive transfer to ethanol 70%. Vacuum degassing at each transfer to new ethanol bath, mounted with agar crushed gel at 70% ethanol"

########### scan parameters ###########

StartTime       ="20/01/2023"
SRCurrent       ="200mA mA"
IDName          ="BM18"
ScanRadix       ="HA-2300_15.13um_I58-LH_brain_C"
XStep           ="U.N."
XStages         ="U.N."
YStep           ="U.N."
YStages         ="U.N."
ZStep           ="5"
ZStages         ="32"
Projections     ="15000"
RefN            ="U.N."
DarkN           ="U.N."
RefOn           ="U.N."
ScanningMode    ="U.N."
ExposureTime    ="0.014 s"
AccExposureTime ="0.07 s"
AccFramesCount  ="5"
PixelSize       ="15.13 um"
PropDistance    ="15000 mm"
Filters         ="Sapphire 10mm SiO2 15mm"
Det_Avg_Energy  ="90 keV"
ScanGeometry    ="half-acquisition"
ScanRange       ="360 deg"
SensorName      ="IRIS15"
SensorMode      ="U.N."
SensorPixelSize ="4.25 um"
Magnification   ="0.3"
XPixelNum       ="5046"
YPixelNum       ="400"
OpticsType      ="Dzoom"
Scintillator    ="LuAG 2000 reflective"
SurfDoseRate    ="26.9 Gy/s"
ScanTime        ="20"
SeriesTime      ="10.7"


######### processing ############

RefApproach     ="U.N."
VolumeX         ="9413"
VolumeY         ="9413"
VolumeZ         ="10656"
32to16BitsMin   ="-0.17"
32to16BitsMax   ="0.31"
Jp2ComprRatio   ="10"
```

And the corresponding BIDS json file
```
{
	"IntendedFor":"sub-I58_sample-01_chunk-01_hipCT.ome.json",
	"Manufacturer":"ESRF",
	"StationName": "BM18",
	"InstitutionName":"European Synchrotron Radiation Facility",
	"InstitutionAddress":"71 Av. des Martyrs, 38000 Grenoble, France",
	"PixelSize":"[15.13, 15.13, 15.13]",
	"PixelSizeUnits":"um",
	"OtherAcquisitionParameters": "{\"StartTime\": \"20/01/2023\", \"SRCurrent\": \"200mA mA\", \"IDName\": \"BM18\", \"ScanRadix\": \"HA-2300_15.13um_I58-LH_brain_C\", \"ZStep\": \"5\", \"ZStages\": \"32\", \"Projections\": \"15000\", \"ExposureTime\": \"0.014 s\", \"AccExposureTime\": \"0.07 s\", \"AccFramesCount\": \"5\", \"PixelSize\": \"15.13 um\", \"PropDistance\": \"15000 mm\", \"Filters\": \"Sapphire 10mm SiO2 15mm\", \"Det_Avg_Energy\": \"90 keV\", \"ScanGeometry\": \"half-acquisition\", \"ScanRange\": \"360 deg\", \"SensorName\": \"IRIS15\", \"SensorPixelSize\": \"4.25 um\", \"Magnification\": \"0.3\", \"XPixelNum\": \"5046\", \"YPixelNum\": \"400\", \"OpticsType\": \"Dzoom\", \"Scintillator\": \"LuAG 2000 reflective\", \"SurfDoseRate\": \"26.9 Gy/s\", \"ScanTime\": \"20\", \"SeriesTime\": \"10.7\"}",
	"BodyPart":"Brain",
	"BodyPartDetails":"Left Hemisphere",
	"SampleEnviornment":"ex vivo",
	"SampleEmbedding":"agar crushed gel at 70% ethanol",
	"SampleFixation":"formalin",
	"SampleExtractionInstitution":"Massachusetts General Hospital"
}
```

Currently, the HiP-CT acquisition parameters are stored in the `"OtherAcquisitionParameters"` field, as a serialized JSON dictionary. But it may be better to move some of these HiP-CT-specific tags into the BIDS spec, and we would welcome any feedback from users of the other microscopy modalities.

@satra @Kevancic @dstansby 

Thanks
Yael

**Comment by Remi-Gau** [comment]
out of curiosity would it not be an issue if we one day wanted to integrate CT in BIDS:
see https://bids.neuroimaging.io/bep024 ?

**Comment by balbasty** [comment]
This is a good question.

I am a bit wary of having HiP-CT as a special case of CT for several reasons:

- It is a phase-based contrast -- not the typical absorption-based contrast used in CT
- It can only be acquired on ex vivo tissue, which makes it closer to a microscopy technique than an in vivo modality
- Its very high resolution and ginormous size means that we must use the zarr format, which is only accepted in the standard under `micr/`, as far as I understand

That said, I am neither a CT nor a HiP-CT expert, let me try to get someone who knows what they are talking about to chime in.

**Comment by ucbpclw** [comment]
Hi all, thought I'd jump in here to add some extra info regarding HiP-CT. @balbasty is correct for all the above. I think to summarise and add some of my own  reasons to separate HiP-CT from CT: 
1) HiP-CT is ex vivo only 
2) It replies of propagation based phase-contrast 
3) It has a hierarchical resolution format, i.e. the whole organ is imaged at an overview resolution and then specific areas can be imaged at higher resolution creating multi-scale datasets of single organ
4) As mentioed datasets are large, some of our largest aquired brain data sets are now at 14TB for one sample.
5) HiP-CT is a synchrotron technique, meaning that the meta-data fields for both acquisition and also reconstruction will be quite different and varied compared with a clinical or even a lab based CT system. 


Also there is more detail on the technique in this [paper](https://www.nature.com/articles/s41592-021-01317-x) , and you can see some video that give a clearer idea of the technique[ here](https://www.youtube.com/@hip-ct8263).

**Comment by Remi-Gau** [comment]
OK it feels pretty clear from what you are saying that this is quite different from clinical CT.

From what I understand it looks like adding a microscopy suffix is needed to start supporting this.

> Currently, the HiP-CT acquisition parameters are stored in the `"OtherAcquisitionParameters"` field, as a serialized JSON dictionary.

In many cases BIDS lets you add extra metadata, so no need to to have it serialized however better in this case to start listing the metadata that will be REQUIRED for downstream analysis and add those to the bids spec

**Comment by satra** [comment]
@balbasty - do you want to start a PR to the spec for this?

**Comment by Remi-Gau** [comment]
I would not mind also seeing an example added to the bids example repo: https://github.com/bids-standard/bids-examples#contributing

**Comment by satra** [comment]
> looks like adding a microscopy suffix

you mean under the `micr` prefix. the suffix is just `hipCT` as proposed right?

> seeing an example added to the bids example 

perhaps a downscaled version for the moment could work. may be just at the coarsest levels. one of the the images that @balbasty linked to has 1 million objects :)

**Comment by balbasty** [comment]
Sure I can draft a PR.

The one thing I am not sure yet is which metadata should be added (if any). @ucbpclw do you think any of the metadata should be REQUIRED or RECOMMENDED to store in the sidecar json file?

And don't worry I won't push terabytes of data to the example repo! Something like the 1mm resolution level would make sense I'd say.

**Comment by effigies** [comment]
I don't think we inspect the contents of zarr directories. You could drop everything but any metadata files inside that may need to be inspected to ensure consistency between OME and BIDS.

**Comment by ucbpclw** [comment]
Do you mean which of metadata fields we sent in our example file are essential?

C

________________________________

**Comment by Remi-Gau** [comment]
to illustrate what @effigies said, here are the content of the microscopy examples:

**Comment by balbasty** [comment]
@ucbpclw 

> Do you mean which of metadata fields we sent in our example file are essential?

Yes, exactly

**Comment by balbasty** [comment]
Hi

I am reopening this thread. After further discussions with "synchrotron-CT" experts (@chourroutm, @dstansby, @ucbpclw), it appeared that hipCT might not be the most adequate suffix. The "H" means hierarchical and really relates to the acqusition of multiple images in the same sample. Each individual image is a (very fancy) phase-contrast CT.

They have suggested "PC" for phase-contrast, although in the current spec, "PC" relates to optical phase-contrast, not xray phase-contrast. 

It might be good to fix this suffix before the next releast of the spec.

@satra @yendiki @effigies @yarikoptic

**Comment by effigies** [comment]
XPC - X-ray Phase Contrast?

**Comment by ayendiki** [comment]
Adding the X does make it sound cooler.

________________________________

**Comment by dstansby** [comment]
Agree that it's worth dropping the "Hi" of "HiP-CT" - as mentioned above stands for Hierarchical which is about how mutiple datasets/scans relate to each other (basically some are higher resolution VOIs of others).

XPC sounds good. Does the suffix need to indicate it's CT data though? I note there's already a microCT suffix in the spec. So how about something like xPCCT? Or just PCCT for phase contrast computed tomography?

**Comment by effigies** [comment]
> XPC sounds good. Does the suffix need to indicate it's CT data though?

The only hard and fast rule is that it needs to be alphanumeric. Otherwise, if the affected community agrees that it's precise enough, and people outside the community don't see it conflicting with something familiar to them, then it's all good.

> I note there's already a microCT suffix in the spec. So how about something like xPCCT? Or just PCCT for phase contrast computed tomography?

I don't love xPCCT, but XPC and PCCT seem equally fine to me. But I don't work with these data, so I'm happy to leave it to those who do.

**Comment by dstansby** [comment]
If there's no particular standard/rules for what has to be in the suffix, apart from understandable by the community, then maybe it's worth keeping this as hipCT?

**Comment by chourroutm** [comment]
@dstansby I'd rather go for a broader name, as we're the only group/consortium doing HiP-CT (at the moment) but the community using the same underlying technique --- without the hierarchical component, which indeed rather corresponds to a dataset rather than a sole volume --- is already quite developed .

The different names I am aware of are:

- X-ray phase-contrast tomography / XPCT, [doi:10.1016/j.neuroimage.2018.09.044](https://doi.org/10.1016/j.neuroimage.2018.09.044)
- X-ray phase-contrast computed tomography / XPCCT, [doi:10.1088/1361-6560/acd48d](https://doi.org/10.1088/1361-6560/acd48d)
- X-ray phase microtomography, [doi:10.1038/srep00826](https://doi.org/10.1038/srep00826)
- Synchrotron X-ray computed tomography / SXCT, [doi:10.1038/s41598-022-21741-z](https://doi.org/10.1038/s41598-022-21741-z)
- Phase-contrast X-ray imaging / PCXI, [doi:10.1038/s41598-018-29841-5](https://doi.org/10.1038/s41598-018-29841-5)
- X-ray phase-contrast imaging / XPCI, [doi:10.3390/app12199539](https://doi.org/10.3390/app12199539)
- Phase-contrast X-ray synchrotron microtomography / PCXSμT, [doi:10.1371/journal.pone.0229140](https://doi.org/10.1371/journal.pone.0229140)
- X-ray tomographic imaging / XTI, [doi:10.1007/s00418-020-01868-8](https://doi.org/10.1007/s00418-020-01868-8)

As there is no real consensus of the naming within the community, we will not please everyone, of course. It seems to me that XPC might be sufficient as a suffix to the `microscopy` keyword. Otherwise, to convey the 3D, maybe XPCT is the one to go.

**Comment by chourroutm** [comment]
What's the opinion of the others? @ucbpclw @balbasty @satra
My former collaborators were also interested in such an addition, I can include them in the decision-making.

Then, what is the course of events? Should I draft a PR with one of the two suffices?

I suppose we can prepare in the following months (once the validator recognizes the suffix) a truncated version of the open brain dataset from the Human Organ Atlas: https://human-organ-atlas.esrf.eu/datasets/572252538

**Comment by balbasty** [comment]
@chourroutm  I vote XPCT, but yes it'd be great to have a validation from other groups, so that it lives up to the test of time :)

Once it's ok'd, you (or I) should revert the changes from PR #1686 and replace all occurences of hipCT by XPCT.

**Comment by effigies** [comment]
It would be good to get an example in https://github.com/bids-standard/bids-examples as well, so that we can update and test the validator. See the [contributing guide](https://bids-standard.github.io/bids-examples/CONTRIBUTING.html).

**Comment by ucbpclw** [comment]
I would vote XPCT as well, it is the wording we are generally using when writing grants as it captures all the essential components of the technique and is specific enough to differentiate it from other X-ray or tomography examples.

**Comment by chourroutm** [comment]
@gobej and @embrun do you want to weigh in?

**Comment by chourroutm** [comment]
@effigies I've tailored an example dataset in [chourroutm/bids-xpct-example/tree/master/micr_XPCTzarr](https://github.com/chourroutm/bids-xpct-example/tree/master/micr_XPCTzarr) that we'll amend before I draft a PR to [bids-standard/bids-examples](https://github.com/bids-standard/bids-examples).

@ucbpclw @dstansby and eventually @balbasty can I have your inputs on [the dataset](https://github.com/chourroutm/bids-xpct-example/tree/master/micr_XPCTzarr)? This is the file structure of the example dataset:

```
micr_XPCTzarr
|   dataset_description.json
|   participants.json
|   participants.tsv
|   README.md
|   samples.json
|   samples.tsv
|   
+---code
|       data_retrieval.py
|       data_retrieval_reqs.txt
|       metadata_formatter.py
|       metadata_formatter_reqs.txt
|       truncate_data.sh
|       
\---sub-LADAF-2020-31
    |   sub-LADAF-2020-31_sessions.json
    |   sub-LADAF-2020-31_sessions.tsv
    |   
    \---ses-01
        \---micr
            |   sub-LADAF-2020-31_ses-01_sample-brain_photo.jpg
            |   sub-LADAF-2020-31_ses-01_sample-brain_photo.json
            |   sub-LADAF-2020-31_ses-01_sample-brain_XPCT.json
            |   
            \---sub-LADAF-2020-31_ses-01_sample-brain_XPCT.ome.zarr
                |   .zattrs
                |   .zgroup
                |   
                +---0
                |   |   .zarray
                |   [...]
                [...]
                |
                +---4
                    |        
                    [...]
                    |           
                    \---9
                        +---0
                        |       0
                        |       1
                        |       2
                        |       
                        +---1
                        |       0
                        |       1
                        |       2
                        |       
                        \---2
                                0
                                1
                                2
```

**Comment by dstansby** [comment]
Layout looks good to me (FWIW I sucessfully adapted a HiP-CT dataset to BIDS to upload to LINC), but I think that's beyond the scope of this issue (which is just about the prefix)?

**Comment by effigies** [comment]
#1822 changing hipCT to XPCT has been open a week with no objections. I would ask someone else to leave an approving review and encourage anybody who would object to do so as soon as possible.

**Comment by fabienchauveau** [comment]
I am also in favour of "XPCT".

**Comment by effigies** [comment]
XPCT adopted in #1822.
