### ISSUE TITLE
update doc on communication platforms linked in release protocol

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#1654]
https://github.com/bids-standard/bids-specification/blob/51a40fba7fa5b2a41c62802dd2329fe617f8ae04/Release_Protocol.md?plain=1#L263

links to: https://docs.google.com/spreadsheets/d/16SAGK3zG93WM2EWuoZDcRIC7ygPc5b7PDNGpFyC3obA/edit#gid=0

This list should be updated:

- twitter is now X
- we now have mastodon and [bluesky](https://bsky.app/profile/bidsstandard.bsky.social)
- ...

**Comment by Remi-Gau** [comment]
Question: should this list live in a google file or in markdown on a repo?

**Comment by sappelhoff** [comment]
IMHO we should move this away from the Google Sheet to a repo. These communication channels change only rarely and edits could/should be made transparently via PRs.

**Comment by sappelhoff** [comment]
Actually, I think this is relevant to what @christinerogers has also mentioned several times now --> we should have a page somewhere that clearly documents all our communication channels and their uses.

Then we should refer from all other places to that page ... instead of having a sentence like "it will be shared via twitter", it should be "it will be shared via our communication channels, see link"

Also related to this: 

- https://github.com/bids-standard/bids-website/issues/349

**Comment by Remi-Gau** [comment]
OK let's ungooglify this then: this belongs better in the bids-website repo?
