### ISSUE TITLE
Questions about appendix VIII: Preferred Names of Coordinate Systems

### ISSUE THREAD

**Issue by ftadel** [bids-standard/bids-specification#169]
Related with Appendix VIII: https://github.com/bids-standard/bids-specification/blob/master/src/99-appendices/08-coordinate-systems.md

1) What is the recommended space label to refer to the head coordinates (in subject space, not normalized) coming from the voxel-to-world transformation sform coming from a .nii file immediately after converting from DICOM?
"head", "world", "ras", "orig", "subject"?

2) Is it OK to specify only MNI152, or should we always specify the full template name? (eg. MNI152NLin6)
If the latter: does anybody know what to indicate when using an affine SPM12 registration ([spm_maff8](https://github.com/neurodebian/spm12/blob/master/spm_maff8.m))?

**Comment by chrisfilo** [comment]
Hi @ftadel,

We use https://neurostars.org/tags/bids for answering questions - it makes them easier to find. When reposting the question it would be good to provide more context in terms of what data type/file you are interested in and what JSON of filename keyword you are trying to fill.

PS I am assuming the question is about the released version of BIDS not [the derivatives proposal](https://github.com/bids-standard/bids-specification/pull/109) - if I am mistaken posting it there would be a better place.

**Comment by ftadel** [comment]
This was actually to point at missing information in the Appendix VIII, but OK, I reposted it there:
https://neurostars.org/t/questions-about-appendix-viii-preferred-names-of-coordinate-systems/3758

Thanks

**Comment by chrisfilo** [comment]
Thanks. It is likely that the interactions on neurostars will lead to a conclusion that the spec needs improvement. It's just that there are more people monitoring neurostars as a support channel to help you.

**Comment by chrisfilo** [comment]
https://neurostars.org/t/questions-about-appendix-viii-preferred-names-of-coordinate-systems/3758
