### ISSUE TITLE
Event onset times can be out of order

### ISSUE THREAD

**Issue by VisLab** [bids-standard/bids-specification#1691]
Some datasets on OpenNeuro do not have their events ordered in ascending order by the `onset` time. I couldn't find anything in the spec about this.... but I think downstream analysts have a reasonable expectation that event times should be non-decreasing and will be in for a nasty surprise (if they notice it) when using these datasets.

Should there be a requirement that time series times be non-decreasing?

**Comment by Remi-Gau** [comment]
I have come across datasets like this and written experiment scripts that came close to generate things like this too.

As a BIDS dataset user, I have learned that my scripts / workflow should sort events before using them.

Making this kind of thing explicit would be a good thing.

I would not personally make it a requirement, but it could be recommended.

**Comment by sappelhoff** [comment]
> Making this kind of thing explicit would be a good thing.
> I would not personally make it a requirement, but it could be recommended.

I am +1 for this
