### ISSUE TITLE
Specify which electrodes were excluded before preprocessing

### ISSUE THREAD

**Issue by nickilanger** [bids-standard/bids-specification#170]
Hi All, 

I think we should should specify, which electrodes were excluded before preprocessing. For example, many researchers, who use the EGI system remove the outer ring of the electrodes from further analysis. Maybe this belongs to the derivatives description.

**Comment by sappelhoff** [comment]
hi @nickilanger,

it depends a bit on what you mean by "removing electrodes before preprocessing". Do you mean:

1. there is raw data
2. a researcher discards parts of the data (some electrodes)
3. the researcher then shares this data as a raw dataset without documenting what happened in step 2. 

?

If I misrepresent your point, please correct me.

Convenience link to [derivatives](https://docs.google.com/document/d/1PmcVs7vg7Th-cGC-UrX8rAhKUHIzOI-uIOh69_mvdlw/edit?ts=5c811e55)

**Comment by nickilanger** [comment]
Hi Stefan, 

Yes, I think you interpreted it correctly. There is raw data (e.g. 128 electrodes). A researchers dicards parts of the data (some electrodes). 

But, then there are two perspectives on it: Sharing modified raw data (as you suggested):

> the researcher then shares this data as a raw dataset without documenting what happened in step 2.

Then I think it has to be included in the BIDS manuscript describing the raw data. 

However, one you also take the perspective that discarding some electrodes is a first preprocessing step. So, it probably should belong to the BEP 21 manuscript.

Let me know, what you think. 

Best, 

Nicolas


Nicolas Langer
Assistant Professor of Methods of Plasticity Research
University of Zurich
Andreasstrasse 15 (Office AND.4.58)
8050, Zurich, Switzerland
n.langer@psychologie.uzh.ch
phone: (+41) 44 635 34 14
http://www.psychology.uzh.ch/en/areas/nec/plafor.html

**Comment by sappelhoff** [comment]
I agree with you. To have a solution for now, I suggest the following:

Using the current BIDS spec, the full data should be shared as **raw** BIDS dataset. If some electrodes were removed due to a "common workflow" or similar, this would have to be documented, e.g., in the README. But preferably, no data is dropped.

However as you mention, removing electrodes could also be framed as a preprocessing step. We are not far enough in BEP021 to have a way of specifying this yet. I think it'd be great if you could open up a conversation on this in the BEP021 derivatives section.

Thanks,

Stefan

**Comment by nickilanger** [comment]
Hi Stefan, 

I think i did already. But I double check again. If not, I will open up a conversation on this topic. 

Best, 

Nicolas

Nicolas Langer
Assistant Professor of Methods of Plasticity Research
University of Zurich
Andreasstrasse 15 (Office AND.4.58)
8050, Zurich, Switzerland
n.langer@psychologie.uzh.ch
phone: (+41) 44 635 34 14
http://www.psychology.uzh.ch/en/areas/nec/plafor.html

**Comment by dorahermes** [comment]
+1 to having a discussion about this as this also applies to iEEG @choldgraf 
we can have implanted electrodes that are not recorded (due to various reasons)
