### ISSUE TITLE
[BUG] timeseries files support task entity for ASL and DWI 

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#1701]
### Describe your problem in detail.

physio / stim files support task entity for ASL and DWI when the data files for ASL and DWI do not.

mentioned in https://neurostars.org/t/bids-validator-asl-filename-error/28116

### Describe what you expected.

no file under ASL and DWI should support the task entity

original support for physio / stim was introduced in #894 

see here: https://github.com/bids-standard/bids-specification/pull/894/files#r1486489726

but the current schema for those files for MRI is based on a file pattern that includes task:

https://github.com/bids-standard/bids-specification/blob/365f3219aec261654220c4bb88e02498b5b39ad8/src/schema/rules/files/raw/task.yaml#L75

### BIDS specification section

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/magnetic-resonance-imaging-data.html#arterial-spin-labeling-perfusion-data

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/magnetic-resonance-imaging-data.html#diffusion-imaging-data

**Comment by tsalo** [comment]
@Remi-Gau actually, I don't know much about `stim` files. Should `stim` files even be allowed for files without a task entity? Aren't they like a continuous version of events files?

**Comment by Remi-Gau** [comment]
> @Remi-Gau actually, I don't know much about `stim` files. Should `stim` files even be allowed for files without a task entity? Aren't they like a continuous version of events files?

yeah I asked myself that but given that this was introduced in #894, I wanted to just highlight this "regression" but it sort of makes me wonder what I was thinking when I wrote #894
