### ISSUE TITLE
[DWI] Allow bval and bvec for PEPOLAR fieldmaps

### ISSUE THREAD

**Issue by mattcieslak** [bids-standard/bids-specification#1724]
### Your idea

Siemens scanners typically don't let you acquire just a b=0 image and will produce some b>0 images as well. For PEPOLAR epi fieldmaps this means that there is a relevant bval and bvec that are useful for determining which volumes should be used for distortion correction. 

Since there is some activity on DWI in #1723, I was hoping to get some input on this idea too. 

In our group, we keep the epi bval and bvec files so they can be used during processing, but list them in .bidsignore so the data is still bids compatible. This is not a great workaround.

Pinging @cookpa @pierre-nedelec @tsalo

**Comment by effigies** [comment]
So this would permit `_epi.{bval,bvec}` files? That seems fine to me.

**Comment by cookpa** [comment]
For an example of this, the UK biobank protocol acquires b=0 scan with reversed phase encoding. To maximize similarity to the main dMRI sequence, it has a maximum b-value of 2000. 

https://www.fmrib.ox.ac.uk/ukbiobank/protocol/V4_23092014.pdf

Allowing bvec / bval would help apps choose the b=0 volumes for SDC purposes

**Comment by mattcieslak** [comment]
[Most recent encounter with this issue](https://neurostars.org/t/qsiprep-is-it-possible-to-manually-specify-topup-images/28823). If I open a PR for this do you think it would get approved?

**Comment by arokem** [comment]
> If I open a PR for this do you think it would get approved?

I think that [this comment](https://github.com/bids-standard/bids-specification/issues/1724#issuecomment-1986047794) suggests that it would.

**Comment by effigies** [comment]
Yeah, there are no objections and a clear use case, and nothing really new needs to be introduced. Those are the kind of decisions that we're good at.
