### ISSUE TITLE
Suggestion: add some admonition text warning that sharing under sourcedata/ should be done carefully

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#1744]
we want to include here some language that the specification is completely naive about whether those data can be shared. Along these lines, it would be a good place to mention that source files requiring anonymization can be stored here and still be considered "source data" (although there's been one processing step in between).

The point is, many students and young researchers may be unaware of the circumstances under which the data may or may not shared and not adding some sort of warning or language here to say: hey, discuss with your PI or your university or whoever this needs be discussed before dropping anything and using this as a means of releasing data public.

_Originally posted by @oesteban in https://github.com/bids-standard/bids-specification/pull/1737#discussion_r1534513241_

**Comment by oesteban** [comment]
I've changed the title because it may be the case that data cannot be shared without anonymization and yet you want to share them after anonymization.

It's more about warning that sharing data under sourcedata/ must be done extra-carefully before any damage is done.

**Comment by Remi-Gau** [comment]
Thanks and my bad for the lack of clarity.

**Comment by PeerHerholz** [comment]
Thanks for this folks! 

That's something we discussed a lot in [BIDSonym](https://github.com/PeerHerholz/BIDSonym) where we copy the OG, ie non-pseudonymized/anonymized data from the `BIDS` root into `/sourcedata/`, apply deidentification there and save the respectively pseudonymize/anonymize in `BIDS` root. 
This might be another use case to bring up/discuss as there's not only "classic" `sourcedata`, ie `dicoms` or so, but also `BIDS` dataset(s) before pseudonymization/anonymization. I'm of course happy to adapt things given the outcomes of this discussion/new guidelines proposed here.

Thanks again.
