### ISSUE TITLE
Add MACRO for every TSV add HTML tooltip with a warning if spaces were used

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#1756]
### Your idea

Inspired by
- https://github.com/bids-standard/bids-specification/pull/1749/files#r1545494653

The idea is that the warning in common principles would not be seen by majority of people who just end up at examples with TSVs which use spaces to improve indentation... Could be some kind of an alert sign with some modal window showing warning if pressed.

**Comment by Remi-Gau** [comment]
- See also #644
