### ISSUE TITLE
MACRO to "Render" TSV examples as a TABLE but tab-separated if copy/pasted

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#1757]
### Your idea

Pretty much an alternative to
- https://github.com/bids-standard/bids-specification/issues/1756

Here is an example which we came up with chatgpt: http://www.oneukrainian.com/tmp/tabs-demo.html . Try to copy/paste ;)

CSS styling could be adjusted so it is all tight and no borders etc, so just looks like a table of text.  The point is to address the shortcoming that now we need to indent TSV examples with spaces for "nice looking" rendering.

Concern originated
- https://github.com/bids-standard/bids-specification/pull/1749/files#r1545494653

Edit 1:
here is a better styled example: http://www.oneukrainian.com/tmp/tabs-demo2.html  . The "tricky" behavior I see. Whenever I just select on my linux laptop, which automagically copies to clipboard, I have desired part as tsv. When I click "ctrl-c" as to copy into clipboard explicitly - I seem to get the full table.  Could be treated as a feature ;)

Not sure yet what should be done for PDF -- probably just a note added ;-)

**Comment by Remi-Gau** [comment]
- See also #644
