### ISSUE TITLE
schema: should associations/bval/target have a suffix?

### ISSUE THREAD

**Issue by bendichter** [bids-standard/bids-specification#1779]
I am currently working on a metaschema and have a question about the expected form of the `associations.yaml` file.

https://github.com/bids-standard/bids-specification/blob/943c20e619567855ccee2896b65c1001f338010c/src/schema/meta/associations.yaml#L60-L74

In this `associations.yaml` schema file, all the other entries have a target/suffix field except `bval` and `bvec`. Is this field allowed to be missing? It's not a problem either way I just want to make sure this isn't a mistake.

**Comment by effigies** [comment]
It's not a mistake. These are overrides from the current file's path components.
