### ISSUE TITLE
anonymization → deidentififcation (or pseudonymization)

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [bids-standard/bids-specification#1782]
Following https://github.com/bids-standard/bids-specification/pull/1769#discussion_r1565742030, I would recommend changing `anonymization` to `deidentififcation`, as `anonymization` has a very specific meaning under the GDPR and probably ~~[ISO/IEC 29100:2011](https://www.iso.org/fr/standard/45123.html) →~~ [ISO/IEC 29100:2024](https://www.iso.org/fr/standard/85938.html) / [ISO/IEC 27559:20](https://www.iso.org/standard/71677.html) (but I don't have the ISO standards to make sure):
> PROCESS BY WHICH PERSONALLY IDENTIFIABLE INFORMATION (PII) IS IRREVERSIBLY ALTERED IN SUCH A WAY THAT A PII PRINCIPAL CAN NO LONGER BE IDENTIFIED DIRECTLY OR INDIRECTLY, EITHER BY THE PII CONTROLLER ALONE OR IN COLLABORATION WITH ANY OTHER PARTY

Current occurrences:
https://github.com/search?q=repo%3Abids-standard%2Fbids-specification%20anonymization&type=code

**Comment by Remi-Gau** [comment]
I would not be opposed to add this change to #1769

**Comment by DimitriPapadopoulos** [comment]
Hiow can I help, and what the occurrences not directly related to https://github.com/bids-standard/bids-specification/pull/1769??

https://github.com/search?q=repo%3Abids-standard%2Fbids-specification%20anonymization&type=code
