### ISSUE TITLE
Forcing .gz compression on physio files not optimal

### ISSUE THREAD

**Issue by arnodelorme** [bids-standard/bids-specification#1788]
I was reviewing the format specifications for physio files. Forcing ".gz" compression of the .tsv file makes little sense to me. Some physio files (eye-tracking files, for example) have low channels and low sampling frequency, so raw .tsv files should be allowed because they are usually not that big anyway. Also, ".gz" compression is problematic. This is not a standard compression scheme on Windows. BIDS is supposed to be easy to use. The ".gz" compression may force some users (including naive users who only want to open the file in Excel) to install specific software. Preparing a physio file on Windows will be nearly impossible for naive users who do not master the DOS command line or install Cygwin or another similar tool. Forcing people to use a Unix compression scheme on Windows decreases adoption. Let's allow standard .tsv in addition to compressed .tsv files for increased ease of use. @robertoostenveld @CPernet

**Comment by effigies** [comment]
Is this specific to eye-tracking? Because there's a BEP working on that: https://github.com/bids-standard/bids-specification/pull/1128

**Comment by arnodelorme** [comment]
It is in the current BIDS standard https://github.com/bids-standard/bids-specification/blob/master/src/modality-specific-files/physiological-recordings.md

**Comment by Remi-Gau** [comment]
@arnodelorme 
- Would you be OK closing this issue and moving this comment to this one: https://github.com/bids-standard/bids-specification/issues/472 where the same topic disccussed?

@effigies 
I think that the eyetracking BEP is high-lighting how this could be an issue but to me it looks like that compression issue is partly orthogonal to the eyetracking content.

**Comment by arnodelorme** [comment]
OK

**Comment by Remi-Gau** [comment]
thanks :wink: 🙏🏾
