### ISSUE TITLE
possibly use mdBook to render md files online

### ISSUE THREAD

**Issue by teonbrooks** [bids-standard/bids-specification#18]
one possibility for the specification now that it is in md is to use [mdBook](https://github.com/rust-lang-nursery/mdBook). it's a project from the Rust team and it renders [book-like](https://rust-lang-nursery.github.io/mdBook/) html site.

**Comment by chrisfilo** [comment]
One cool feature is that we could include source files such as JSON examples and validate them in CI: https://rust-lang-nursery.github.io/mdBook/format/mdbook.html#including-files

**Comment by franklin-feingold** [comment]
It may help to split up the specification and the mdbook appears to be a nice appealing way to complete this. I like the way it looks and this can help ease new users into reading it. Including source files is a nice feature. The storage doesn't appear too complex to interpret and follow. 
A concern is that splitting it up may make it more difficult to locate items across different sections. We would lose quickly just finding across the entire document. We can also consider keeping the entire specification md file so not to lose the quick finding functionality for those that want the entire specification.

**Comment by chrisfilo** [comment]
I had another look at mdbook and there are two features I was missing:
- ability to export a PDF version (a feature requested by @dorahermes)
- ability to provide multiple versions of the rendered specification

I found an interesting potential alternative - https://www.mkdocs.org/. 
- It solves the above issues via plugins (https://github.com/jimporter/mike and https://github.com/shauser/mkdocs-pdf-export-plugin).
- It's written in Python (so it would be easier to fix things if we want to)
- It has an export plugin for combining all content into a single page (like @franklin-feingold suggested)
- It has a built-in search function
- Has a beautiful material design theme https://squidfunk.github.io/mkdocs-material/

What do people think?

**Comment by teonbrooks** [comment]
>     * ability to export a PDF version (a feature requested by @dorahermes)

did some searching and there is an export ability using this [repo](https://github.com/killercup/trpl-ebook). it adds more to the build, which might be less ideal.

**Comment by choldgraf** [comment]
Note that I think the choice of build system should be independent of the "split into multiple md files" stuff...so we shouldn't entangle the two if we think it'll be a bit of extra time to find the right build/hosting setup

**Comment by chrisfilo** [comment]
Playing with mkdocs right now - looks stunning so far
![image](https://user-images.githubusercontent.com/238759/46391939-37e4c880-c694-11e8-96b1-c6ee2bdb6803.png)

**Comment by choldgraf** [comment]
I know that @yuvipanda has used mkdocs before and I think really liked it

**Comment by chrisfilo** [comment]
@choldgraf indeed - splitting is a separate issue https://github.com/bids-standard/bids-specification/issues/4

**Comment by yuvipanda** [comment]
@choldgraf I found mkdocs quite lacking in many ways. Using mkdocs was what finally fully converted me to rST and Sphinx :)

**Comment by KirstieJane** [comment]
Just on the export as a PDF question - if you click the little print button at the top of the rendered page (that @teonbrooks created in #22 hosted at https://teonbrooks.github.io/bids-specification you can get a pretty nice PDF of the whole site. What are the additional requirements? To do it programatically?

[bids-standard-print.pdf](https://github.com/bids-standard/bids-specification/files/2441203/bids-standard-print.pdf)

**Comment by KirstieJane** [comment]
You could just print the page from the browser if you wanted a subsection. What's the usecase that you can imagine for the PDF @dorahermes? To physically print out, or to email around? The broken links are a problem for the email but not for printing for example.

[bids-standard-definitions-only.pdf](https://github.com/bids-standard/bids-specification/files/2441240/bids-standard-definitions-only.pdf)

**Comment by dorahermes** [comment]
Use cases for having a PDF of the spec: 
1) Being able to have a certain version of 'The Spec'. Say you have a project and are putting data in BIDS Version X, I can imagine that a lab would want to have a PDF of this BIDS version alongside instructions of how to put data in BIDS. 
2) I personally like having a PDF when I travel a lot and the internet is crappy.

**Comment by KirstieJane** [comment]
Coolio - I think for the first option it's important to have a nice PDF that includes the links etc. I think this would only have to be made once for each release so maybe it doesn't have to be done really automatically.

For crappy internet the pdfs with the broken links would probably be fine.

Totally ok by me for the search for a nice way of doing everything to continue, I guess this is just a light +1 for the simplicity of mdBook 😸

**Comment by dorahermes** [comment]
and one more example,
3. Some people might need to be able to generate a paper-trail for data-management plans.

+1 for a nice PDF with links only generated once per release

**Comment by teonbrooks** [comment]
@satra brought up another great suggestion for a rendering engine, sphinx: https://github.com/bids-standard/bids-specification/pull/28#issuecomment-426812108

it seems that there are three options at the moment
- mdBook
- mkDocs
- sphinx

**Comment by chrisfilo** [comment]
I created some prototypes:
- mdbook version https://github.com/bids-standard/bids-specification/pull/37
- mkdocs version https://github.com/bids-standard/bids-specification/pull/36

Let me know what do you think

**Comment by nicholst** [comment]
I'd like to throw one consideration into the formatting discussions:  HTML print-to-PDF by the browser is a highly browser-dependent operation.  E.g. I've even seen different PDFs produced from the same website on the same OS but slightly different versions of a Chrome browser.

My $0.02 is that a highly professionally rendered PDF is a priority for the spec.  If the plan is that each user/reader is to create a PDF by a browser Print-to-PDF action, we need to verify that good looking PDF is found with different browsers (presumably at least Firefox, Chrome, DefaultOSbrowser).

Thus, if one of the tools we're evaluating has the capability of rendering to PDF directly (in a browser-independent fashion), this is a big plus.

See, e.g. first page on Mac OS on, Chrome, Safari, Firefox, illustrated here, respectively:

<img width="309" alt="bids-chrome" src="https://user-images.githubusercontent.com/5155907/46571363-9e573880-c96b-11e8-9b3e-6074844f77e7.png"> <img width="309" alt="bids-safari" src="https://user-images.githubusercontent.com/5155907/46571364-a1eabf80-c96b-11e8-8fac-5dcf59259b48.png"> <img width="310" alt="bids-firefox" src="https://user-images.githubusercontent.com/5155907/46571366-a57e4680-c96b-11e8-8795-5a326367ed3c.png">

Full PDFs here:  [Chrome](https://www.dropbox.com/s/xkmwo8v22iue0wj/BIDS-PrintTest-MacOS-Chrome.pdf?dl=0) |  [Safari](https://www.dropbox.com/s/syng8034zowgb1w/BIDS-PrintTest-MacOS-Safari.pdf?dl=0) |  [Firefox](https://www.dropbox.com/s/hkzded9ybc0pvbv/BIDS-PrintTest-MacOS-Firefox.pdf?dl=0)

**Comment by chrisfilo** [comment]
@nicholst delivering professionally looking PDF will be hard. Best approach is using pandoc, (see example output https://11-151034407-gh.circle-artifacts.com/0/home/circleci/project/site/specification.pdf) but there still issues with tables and header hierarchy.

I was hoping that most people will be interested in HTML outputs.

**Comment by choldgraf** [comment]
2 cents about the PDF printing: I think this should be community-driven question. How do we know that a large % of users want to print the specification out as a PDF for reference? Perhaps a user survey of some kind can help give us a path forward.

**Comment by nicholst** [comment]
I may have muddled things. IMHO, a polished PDF adds credibility/stature to the effort, but if the consensus is that HTML is sufficient, that’s fine.  I think my point is that *if* we’re considering PDF it should be good & consistent; otw, we say this is a HTML spec and leave it at that. 

As a random idea: I just looked at some PDF from Read The Docs and it looked very nice. Is that system in the running here?

**Comment by choldgraf** [comment]
we had discussed using `readthedocs` and hosting with sphinx. I believe it actually works with `mkdocs` https://mkdocs.readthedocs.io/en/stable/ so maybe that's a good approach!

**Comment by chrisfilo** [comment]
Would someone be willing to explore the readthedocs route (especially the PDF generation feature)?

**Comment by choldgraf** [comment]
if you give me admin privileges on the repo and merge the mkdocs PR (so that the mkdocs files are in `docs/`, then I can try to set up RTD.

**Comment by chrisfilo** [comment]
Would you mind doing this on your fork? I don't want to commit to mkdocs solution yet.

**Comment by nicholst** [comment]
@choldgraf: Oddly that link https://mkdocs.readthedocs.io/en/stable/ lacks the PDF rendering I had seen.

I was looking at this site: https://packaging.python.org/ which has a floating pop-up menu in the lower right that gives a PDF download option.  In contrast, say, https://mriqc.readthedocs.io/en/stable/index.html has a similar pop-up (on the lower left) but offers now PDF download.

**Comment by choldgraf** [comment]
hmmm - usually it shows up in the little "latest" menu in the bottom right (e.g. it's there on this page https://repo2docker.readthedocs.io/en/latest). Maybe RTD doesn't build PDF with mkdocs?

**Comment by choldgraf** [comment]
@chrisfilo isn't there already a PR open that gets this repo built on mkdocs? All we'd need to do is set up readthedocs with whatever repo that is. What is the question you'd like answered with respect to readthedocs? Just whether you can download as PDF using mkdocs?

**Comment by choldgraf** [comment]
ok - if I have a moment than I'll give it a shot

**Comment by chrisfilo** [comment]
Thanks!

**Comment by choldgraf** [comment]
So an update here: it looks like mkdocs is pretty easy to set up on readthedocs, but it does not support anything like PDF/EPUB generation of the document.

What do folks think about this?

**Comment by teonbrooks** [comment]
@choldgraf, do you know how repo2docker generates its pdf and epub? that would be a nice to have if it's easily implementable.

**Comment by choldgraf** [comment]
We're using sphinx there, which uses `rst` under the hood. Sphinx works with markdown as well through Recommonmark, but I think some features (like markdown tables) don't work :-/

**Comment by chrisfilo** [comment]
Even though I like the option of having PDF (if it comes 'for free'), but it seems this is not easy. I believe we get the "prestige" effect from multiple papers related to BIDS that are published and in the works. I'm not sure we need to do a formal survey, but happy to be convinced otherwise.

Personally, I would just pick one of the HTML only solutions, for now, deploy it, but be open for future contributions enabling quality PDF output.

**Comment by teonbrooks** [comment]
+1. This would be in the same vein as W3C. 

for archival purposes, I think as long as we can have pointers to the previous versions, we should be set. we can just have links to all the pdf versions before markdown, and then we will just have versioned html build views of post markdown.

**Comment by dorahermes** [comment]
+1 on being pragmatic
and +1 on Teon's suggestion on having a previous version archived

**Comment by choldgraf** [comment]
A note re: readthedocs, it will also archive old versions of the specification relatively seamlessly, so if we want to use mkdocs (#42) then that would come "for free" even if PDF generation does not

**Comment by chrisfilo** [comment]
Does this work with `mkdocs` integration? I could not see the menu with versions usually present in sphinx/rst readthedocs documents.

It's also not so hard to configure circle to deploy each version to a new subfolder (`1.1.1/index.html`, `1.2.0/index.html`). Archival versions of source documents (Markdown) will, of course, be available on github as well.

**Comment by choldgraf** [comment]
I believe that versioning should work fine with mkdocs...if the community is +1 on using mkdocs then I can try to confirm this in my RTD PR

**Comment by chrisfilo** [comment]
If versioning via RTD doesn't work we can always use https://pypi.org/project/mike/ and push directly to gh-pages.

I don't have a strong preference - I like material design of `mkdocs`, but I dislike the necessity of having an extra index.md file and lack of single page print option.

**Comment by choldgraf** [comment]
@chrisfilo this makes think of a question: does the bids-specification community have an official governance process? E.g., what's the process by which we would decide to use one build system over another?

**Comment by chrisfilo** [comment]
We listen to each other, strive for consensus, use voting to resolve
conflicts.

However, there is no formal governance structure. It's a complex topic that
we will address in due time. If you have concrete ideas for a governance
structure I would love to hear them (for the sake of clarity in a separate
issue).

**Comment by choldgraf** [comment]
Sounds good - longer governance conversations I agree are a separate issue.

For this issue, my 2 cents is that we should:

* just use mkdocs for now
* use readthedocs for hosting and versioning
    * If RTD *won't* work for versioning, auto-deploy it to folders per @chrisfilo's suggestion
* keep considering another markdown-based SSG like mdbook for a future decision
* choose a URL that is not RTD-specific (maybe?)

My reasoning:
The mkdocs PR is already ready to go more or less, and I don't think we should let "picking the right tool" get in the way of "picking any tool at all". With mkdocs we aren't committing ourselves to any kind of complex dependency that'll make it hard to switch to something later if a better option surfaces (beyond potentially the reliance on RTD for versioning...on that point, we should probably get a URL that isn't dependent on readthedocs so that we could switch if need be). I am still intrigued by @teonbrooks 's idea of mdbook, but I think we could keep exploring that idea on an ongoing basis and revisit this conversation later if it seems like it's the best choice.

Thoughts?

**Comment by chrisfilo** [comment]
Ok lets do this and see how it works. I'll give you the appropriate permissions to the repo.

**Comment by chrisfilo** [comment]
nice, but I think you made a typo `bids-specificaion` -> `bids-specification`

**Comment by choldgraf** [comment]
oops, try again

**Comment by choldgraf** [comment]
btw - anybody that wants to be an admin on RTD needs to make a RTD account. Lemme know when you do this and I'll add you!
