### ISSUE TITLE
update qMRI to align with the new definition of derivatives

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#1812]
1. qmri appendix defines quantitative maps as derivatives regardless of how they were generated

   https://bids-specification.readthedocs.io/en/latest/appendices/qmri.html#quantitative-maps-are-derivatives

   > Regardless of how they are obtained (pre- or post-generated), qMRI maps are stored in the derivatives directory.

   One exception to this in the qMRI page is the recommendation to store scanner-generated UNIT1 files along with the raw data.

2. The schema files rules for quantitative maps under the rules for raw datasets.

   https://github.com/bids-standard/bids-specification/blob/0950f6df9e9c6d598fcc50e269f350066d78b7a0/src/schema/rules/files/raw/anat.yaml#L34

3. The legacy valiator (version 1.14.5) is completely fine with having those quantitative maps in a raw dataset (tested on several of the bids examples).

---

- **1** contradicts the operational definition of derivatives datasets that was agreed on in Copenhagen last year.

  https://bids-specification.readthedocs.io/en/latest/derivatives/introduction.html#bids-derivatives

  > Raw data are data that have been curated into BIDS from a non-BIDS source. If a dataset is derived from at least one other valid BIDS dataset, then it is a derivative dataset.

- **1** contradicts the behavior of the legacy validator (**3"") and, **1** and **2** tends to contradict each other as the schema seems to imply that quantitative maps are legit raw data (I would expect that the deno validator would behave the same as the legacy one given the schema).

**Comment by Remi-Gau** [comment]
> [!NOTE]
> the location of this definition of derivatives should probably be moved to common principles (maybe in the definition section)

**Comment by Remi-Gau** [comment]
## Suggestion

Adapt the qmri appendix to align with the definition of derivatives. 

As far as I can tell this would not break backward compatibility as it only expands things that can go in raw dataset and also because it seems that any invalid dataset under the current reading of the BIDS spec for qMRI would not have been detected by the validator.

**Comment by Remi-Gau** [comment]
@agahkarakuzu 

pinging you, so you are not surprised if you get a PR to review.

**Comment by agahkarakuzu** [comment]
@Remi-Gau, thank you so much for looking into this, and sorry for being late to the party!

> qMRI maps are stored differently depending on the process that generated them. Pre-generated qMRI maps MAY be stored as part of a raw BIDS dataset, where as they MUST be stored in a derivative BIDS dataset if they were post-generated.

This reads great! Actually, this was something we originally wanted to mention in the proposal, but at that time it seemed like a detail and we decided not to push for it. I'm so glad that now is the time :) Having this separation is important and adds value.
