### ISSUE TITLE
BIDS motion -- how to categorize IMU data as a modality?

### ISSUE THREAD

**Issue by rmndrs89** [bids-standard/bids-specification#1818]
Dear all,

I have a general question regarding organizing data in a BIDS-like format. According to [common principles](https://bids-specification.readthedocs.io/en/stable/common-principles.html#definitions), for recording techniques like EEG, MEG or iEEG, the technique is sufficiently uniform to define the modality. However, at the same level, `motion` is defined as a unique modality. 

What if we work with inertial measurement unit (IMU) data? Should we categorize this as a *sub-modality* of `motion` (e.g., `motion/imu`), or should it be at the same level as `eeg` and `meg`? 
I am aware that there is an [extension](https://bids-standard.github.io/bids-examples/#motion) of BIDS specifically for motion analysis.

Best regards,
Robbin

**Comment by sappelhoff** [comment]
cc @sjeung @JuliusWelzel

**Comment by JuliusWelzel** [comment]
Hi, 

thanks @sappelhoff for pinning us. IMUs would go into a `motion` directory, no sub-modality. Each channel from the an IMU can be represented as described in the extension.

Best
Julius
