### ISSUE TITLE
formatting issue

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#1820]
![image](https://github.com/bids-standard/bids-specification/assets/39889/e302e5d7-3546-43cb-9a7e-39bf19980cf3)

https://bids-specification.readthedocs.io/en/stable/modality-specific-files/task-events.html

**Comment by Remi-Gau** [comment]
fixed on latest:

![image](https://github.com/bids-standard/bids-specification/assets/6961185/78899acc-2d81-4408-b232-a9af7dabb0fc)

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/task-events.html

**Comment by yarikoptic** [comment]
yes, was fixed in 943c20e619567855ccee2896b65c1001f338010c .

I wish bids-specification had patch releases more often with just such "bug fixes".  Might be worth discussing/establishing some kind of "maint" branch and making releasing easy and frequent from it?

meanwhile, closing
