### ISSUE TITLE
Description of intracranial stimulation parameters in *events.json

### ISSUE THREAD

**Issue by ezemikulan** [bids-standard/bids-specification#184]
On the [specification](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html#electrical-stimulation) it says that the description of the electrical_stimlation_\<label> columns should be placed in the *_electrodes.json file.

_Electrical stimulation parameters can be described in columns called electrical\_stimulation\_\<label>, with labels chosen by the researcher and optionally defined in more detail in an accompanying \_electrodes.json file (as per the main BIDS spec)._

 Shouldn't it be placed in *_events.json instead?

**Comment by dorahermes** [comment]
Thanks for catching this error! Would you like to make a pull request to fix this?

**Comment by ezemikulan** [comment]
Sure
