### ISSUE TITLE
Background suppression timing for ASL

### ISSUE THREAD

**Issue by michaelf500** [bids-standard/bids-specification#1842]
In the ASL section, under pcasl, 
https://bids-specification.readthedocs.io/en/stable/appendices/arterial-spin-labeling.html
the specification reads "Additionally, the BackgroundSuppressionPulseTime's is required in case BackgroundSuppression was applied."

However, I think the BackgroundSuppressionPulseTime is only a recommended parameter, not a required one (at least that is what the bids validator v 1.14.6 says, and it is not possible on our Philips system to find out from dicom what the backgroundsuppressionpulsetime is).  

This should be changed to say 'recommended' not 'required'

Thanks

Michael

**Comment by tsalo** [comment]
I agree. Do you want to open a PR to fix it?

**Comment by tsalo** [comment]
Should have been closed by #1891.
