### ISSUE TITLE
[BUG] Incorrect description of DWI "TRACE" image

### ISSUE THREAD

**Issue by Lestropie** [bids-standard/bids-specification#1862]
### Describe your problem in detail.

Prompted by work happening in #1831, but is actually a consequence of #1725.

Having acquired data with all scanner-generated derivatives enabled, I can confirm that the "`*_TRACEW`" image produced by the Siemens product DWI sequence is *not* the trace of the diffusion tensor, as the specification currently states; rather, it is a "trace-weighted image", being the mean intensity of *b*>0 data.

(Unfortunately I did not think to obtain multi-shell data to find out whether the sequence does what one would naturally expect for multi-shell data, being a 4D series with a trace-weighted image volume per unique *b*-value. It's possible that whether or not it does this will depend on the scanner base software version / sequence used.)

### BIDS specification section

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/magnetic-resonance-imaging-data.html#diffusion-imaging-data

**Comment by effigies** [comment]
Is the proposal to create TRACEW to mean trace-weighted in addition to, or in lieu of TRACE?

**Comment by Lestropie** [comment]
I would personally opt to:
1. Rename `TRACE` to `trace`
2. Change description to reflect that the content of these scanner-generated images is the mean b>0 image intensity, not the trace of the estimated tensor

I'm not aware of any DWI sequence that exports as a scanner-generated derivative the trace of the estimated tensor, so don't see any merit in keeping both parametric maps described alongside one another in the specification. If there's another vendor that does generate such data, happy to stand corrected, I have little to no experience outside of Siemens. But I think this is best treated as an erroneous description.

**Comment by effigies** [comment]
cc @neurolabusc I believe the ADC/TRACE definitions were motivated by your use case. Does this make sense to you?

**Comment by neurolabusc** [comment]
@effigies on this topic I am a user and not an expert. Following advice from experts, our existing BIDS compatible dataset on [OpenNeuro](https://openneuro.org/datasets/ds004889/versions/1.1.2) provides images generated by the scanner manufacturer with names like `sub-1001_rec-TRACE_dwi.nii.gz` and `sub-1001_rec-ADC_dwi.nii.gz` in the `dwi` folder, not a derivatives folder. This archive includes data from GE, Siemens and Philips, and it is clear that some variation exists in terms of the formula for ADC and TRACE. 

@Lestropie is doing a great job of developing a community consensus on diffusion topics.
