### ISSUE TITLE
[BUG] Should subsection "Task events" be under "Modality specific files" as opposed to "Modality agnostic files"?

### ISSUE THREAD

**Issue by oesteban** [bids-standard/bids-specification#1868]
### Describe your problem in detail.

Tasks files do not seem modality-attached, and it is my experience that finding them under modality-specific is confusing for newcomers, especially those with more training in multimodal behavioral experiments.

### Describe what you expected.

I believe tasks description and metadata should better be under modality agnostic.

Stimulus are likely to fall under the same problem.

### BIDS specification section

https://bids-specification.readthedocs.io/en/stable/modality-specific-files/task-events.html

**Comment by yarikoptic** [comment]
It is already in Modality specific files:
![image](https://github.com/user-attachments/assets/be133922-d505-43ab-a4b4-6a937c2c7509)

May be you meant "the other way"? But it seems that the section names (agnostic vs specific) is merely to separate which files go above `<modality>/` (e.g. `anat/`, `func/`, etc) folders and which go under, so rather reflect not "specificity" but rather "location"; and presence of `_events` file is also "modality specific" (i.e. we do not allow it ATM for `anat`) as coded in https://github.com/bids-standard/bids-specification/blob/HEAD/src/schema/rules/files/raw/task.yaml#L60 making them "modality specific".

But overall I feel that in principle we could
- remove "Task" from "Task Events" . After all we say

> The purpose of this file is to describe timing and other properties of events recorded during a run. Events are, for example, stimuli presented to the participant or participant responses (see Definitions). A single event file MAY include any combination of stimulus, response, and other events

So it could be events not associated with any task!  It could be annotation of some events happening during anatomical MRI acquisition (when subject blinked, or wiped nose, or ...).

- then `_events` could become applicable to any data file, and thus despite being stored along with data file in modality specific folder, become a modality agnostic file altogether.

Should we change the title? ;-)

**Comment by oesteban** [comment]
> May be you meant "the other way"?

Yes, that's what I meant. Thanks for making it clearer :)



> * remove "Task" from "Task Events" . After all we say
> 
> 
> > The purpose of this file is to describe timing and other properties of events recorded during a run. Events are, for example, stimuli presented to the participant or participant responses (see Definitions). A single event file MAY include any combination of stimulus, response, and other events
> 
> So it could be events not associated with any task! It could be annotation of some events happening during anatomical MRI acquisition (when subject blinked, or wiped nose, or ...).

I don't know the specs with sufficient depth to be sure that we can just remove "Task" from "Task Events". If that is the case I'm +1 on this idea -- it would simplify things so much (e.g., #1751 and #1692 [seems like I'm partially repeating myself, I had forgotten of these when I posted])

> Should we change the title? ;-)

Sure -- and also close if you think #1692 and/or #1751 are already covering this.

Thanks for looking into this

**Comment by yarikoptic** [comment]
Ha, @VisLab thought alike me on removing "Task" in https://github.com/bids-standard/bids-specification/issues/1751#issuecomment-2022974330 . Indeed I feel like this issue is largely a duplicate of the

- #1751 

so let's try to remember it exists and close this one for now.

**Comment by oesteban** [comment]
Duplicate of #1751.
