### ISSUE TITLE
Use a Discourse instead of an email listserv

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/bids-specification#189]
The recent spat of spam job listing emails on the BIDS listserv made me remember an idea I had a while back:

What do folks think about using a Discourse forum instead of an email listserv? A few points of information from me:

* Discourse is free for open projects (https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/)
* it provides a platform for communication that you have much more control over compared to an email listserv. For example, you can define multiple threads/topics/tags, people can mark posts as "questions" or "answers", you can run polls, etc
* It lets you respond to / get notifications of issues via email in case people want to keep communicating in that way.
* It lets you moderate more effectively and control who can post what based on their previous activity in the community
* It gives people more of a personal identity, and can help people build their own personal image within the community

Given that BIDS is a project that is largely community-driven and requires lots of community conversations, I think it could particularly be useful here. We've been using it over at Jupyter (discourse.jupyter.org) and have generally really liked the results.

Would be curious what people think about this!

**Comment by satra** [comment]
@choldgraf - we are already using discourse for neurostars.org (which handles a lot of the software around bids). perhaps we could just continue to use that instead of another discourse?

**Comment by sappelhoff** [comment]
> recent spat of spam job listing emails on the BIDS listserv

@choldgraf just to be clear: are you talking about the ["google forum/maillist"](https://groups.google.com/forum/#!forum/bids-discussion)?

I personally like discourse as well, e.g., the one for [psychopy](https://discourse.psychopy.org/) or as @satra mentions, our [neurostars](https://neurostars.org/). However, I think the Google forum/mailinglist helps to reach a few people who want to only interact via email instead of jumping on a new platform. What do others think?

**Comment by nicholst** [comment]
I was under the impression that Discourse can be configured so that you can
interact with it in an email-only fashion, if that's your preference.

**Comment by choldgraf** [comment]
@nicholst I believe that's the case, yes.

@sappelhoff yep, that's the listserv I was talking about.

@satra if there's already a place that could be used for this discussion, I'm +1 on using something like this instead of creating a new thing

**Comment by emdupre** [comment]
Just to say -- I'm :+1::+1: on moving the mailing list over to a discourse board ! 

Using NeuroStars makes sense to me. Right now there are only a small number of folks who consistently actively engage on NeuroStars (just looking at [the Thank You badge](https://neurostars.org/badges/38/thank-you)), so this could be a good way to encourage more community buy-in.

And of course, an additional benefit of discourse forums over mailing lists generally is that they have good [default community standards](https://www.discourse.org/features) (that can be updated by the maintainers, of course).

**Comment by effigies** [comment]
If we're going to move over to NeuroStars, I think NeuroStars will need to move to a more organized system than just (most-recent-first + tags). With just the relatively low activity that's currently on, it's already a little overwhelming as someone who tries to answer questions. For threaded conversations on the standard, I think it will be even harder.

**Comment by emdupre** [comment]
Discourse does support more organization -- I think this is something @choldgraf would be more familiar with, though !

I do think, though, that at least right now the organization is almost a direct parallel of the mailing list -- so I don't know that we'll be losing anything in the move.

**Comment by satra** [comment]
@effigies - one can subscribe to tags of relevance for emails and other things.  personally, i am not a big fan of categories. i think tags serve a similar role and has the additional flexibility of cross linking across "categories".

if needed people can do something like this to filter to a direct tag (if that's all they care about): https://neurostars.org/tags/bids

**Comment by effigies** [comment]
What we'll be losing right now is that the mailing list will be interspersed with fMRIPrep help, queries about acquisition sequences, and quick "How do I modify my NIfTI file in X way?" type questions.

@satra responded as I typed... Perhaps tag subscriptions are sufficient.

**Comment by effigies** [comment]
I guess in any event, we'll want some kind of on-boarding doc to get people to "How do I approximate the Google Groups experience on NeuroStars?"

**Comment by emdupre** [comment]
We could add it to [the FAQ](https://neurostars.org/faq). Or we could pin an introductory message as @choldgraf has done for the Jupyter discourse: https://discourse.jupyter.org/t/welcome-to-discourse/8 ?

**Comment by KirstieJane** [comment]
The only worry I have with this proposal is that there are a lot fewer people who comment on issues/PRs at GitHub than there were when discussions happened on the mailing list. And I think moving to discourse may drop participation down even further.

Part of me thinks that that's just something we'll have to live with - email is ubiquitous but doesn't scale well and we can put effort into bringing people into the BIDS ecosystem though these other communication routes. I guess my point is that there will be a cost to switching away from the mailing list. And I'm (very lightly) of the opinion that we'd lose more than we'd gain at this point.

Happy to be argued to have a more positive outlook though! It's a chicken and the egg problem and maybe if we move conversations there they will come 😉

**Comment by sappelhoff** [comment]
> We could add it to the FAQ. Or we could pin an introductory message as @choldgraf has done for the Jupyter discourse:

That sounds cool. And then we should have a similar "banner" for the google group, and also "freeze" it if possible. That is, writing to it is impossible, but browsing old contents is still supported. Is that possible? And the banner on the google group would obviously link to neurostars.

I share @KirstieJane's slight concern and remember the similar situation when moving from Google Docs to Github. But I am hopeful that the chicken and egg problem might work in our favour for this. :-)

**Comment by franklin-feingold** [comment]
hey - I want to circle back to this issue. This issue came up (information diffusion and correspondence) during the BIDS community discussion and thank you all for your thoughts on this! Moving this forward - from this conversation it appears potentially NeuroStars or a discourse channel could be a solution (as to not lose them in GitHub issues). NeuroStars could be good as to reduce the number of channels to monitor and can help unfamiliar users get introduced to that resource. I think the scope could be limited to more conceptual hashing out (it can be expanded out too if we think so). It would be good to identify the scope to make it easier for documentation and routing

**Comment by sappelhoff** [comment]
see also this somewhat post by @effigies https://github.com/orgs/bids-standard/teams/everyone/discussions/7

it's quite hard to find when not navigating directly via the notification

**Comment by nicholst** [comment]
+1 for NeuroStars BIDS tag/channel

**Comment by sappelhoff** [comment]
> +1 for NeuroStars BIDS tag/channel

There is already a `bids` tag:

![image](https://user-images.githubusercontent.com/9084751/60952258-39b27b00-a2fb-11e9-8683-b1f29e47df8d.png)

It's also quite easy to subscribe to a tag, see this [post](https://neurostars.org/t/how-can-i-subscribe-to-a-tag/2777/2?u=sappelhoff)

If by `channel` you mean a `category`, we currently have the following categories:

![image](https://user-images.githubusercontent.com/9084751/60952162-0a9c0980-a2fb-11e9-9f76-61dc3bf43ba4.png)

... I don't know what benefit the `category` would offer over the `tag`. Anyone else?

To get a BIDS category, we'd probably have to ask either an admin or a moderator, see the list here: https://neurostars.org/about

perhaps that would need to be discussed with the owners of the Neurostars page as well. That seems to be INCF:

![image](https://user-images.githubusercontent.com/9084751/60952012-b002ad80-a2fa-11e9-9a0b-c3bca1cd5295.png)


Personally, I think that the tag suffices. As long as more people know how to use it and how to subscribe to it (see my [link](https://neurostars.org/t/how-can-i-subscribe-to-a-tag/2777/2?u=sappelhoff)) But I am happy to be convinced that a `category` offers other advantages.

**Comment by choldgraf** [comment]
IMO tags are a lot less-discoverable than channels, which is the main difference between them. I think we can expect "power users" to use tags, but I don't think we can expect casual or new users to use tags without making considerable effort to make them more discoverable :-/

**Comment by sappelhoff** [comment]
... and a "channel" would basically be a separate site (similar to neurostars.org) with its own categories and tags?

**Comment by sappelhoff** [comment]
For now, [we have decided to move to the BrainHack Mattermost](https://bids.neuroimaging.io/2020/06/24/Join-the-BIDS-community-on-the-BrainHack-Mattermost.html).

For communication channels, we now have:

1. google mailing list for announcements
1. twitter for smaller announcements + "social media"
1. neurostars for day to day support
1. GitHub issues for bugs and feature requests
1. mattermost for "instant messaging" type of communication

We can of course revisit *this* issue (about using discourse) in the future when it turns out that we need new solutions. Thanks for bringing it up back then @choldgraf.
