### ISSUE TITLE
[ENH] Add a community label

### ISSUE THREAD

**Issue by emdupre** [bids-standard/bids-specification#193]
I'd like to make a "Community" label for BIDS issues and PRs, but I think it's something that would be nice to have community buy-in, first ! :smile_cat: 

The reason I'm arguing for such a label is that there are a lot of discussions we have had -- and will continue to have -- around how we engage and develop our community (#189, #176, #160, #104, immediately come to mind).

It'd be nice to immediately find these discussions so that we can highlight both what decisions have already been made as well as how we think about our community and contributors.

If this is of interest, I can go ahead and create the label and apply to all of the above issues / PRs !

**Comment by effigies** [comment]
:+1:

**Comment by PeerHerholz** [comment]
👍

**Comment by franklin-feingold** [comment]
👍

**Comment by KirstieJane** [comment]
Endorsed! 🚀 🌟 🤗

**Comment by sappelhoff** [comment]
:+1:

**Comment by emdupre** [comment]
I think this meets the merge conditions, so I'm on it ! Thanks everyone :sparkles:
