### ISSUE TITLE
Update (new version) of MEF3 format (MED).

### ISSUE THREAD

**Issue by MEDFormat** [bids-standard/bids-specification#1931]
Hello,

I am Matt Stead, the creator of all the MEF formats (1-3).  The new version MEF version (MED) is faster & produces better compression than its predecessors. It continues to be HIPAA & IRB compliant. A fuller description of MED is available on https://MEDFormat.org.

I currently have 4 groups asking me about official BIDS compatibility. 

MED data can be read in open source multiple tools (Matlab, FieldTrip, EEGLab, Python , Neo).  

These tools are freely available in compiled form for all major platforms (MacOS, Linux, Windows) as well as having source code and specification documents available on https://github.com/MEDFormat.  

There are also multiple free data converters (MEF, EDF, DAT, Neuralynx (NCS & NRD), & NATUS) available.

I would be happy to make the pull request for this.

@bids-standard/raw-electrophys-ieeg

**Comment by effigies** [comment]
FWIW I'm +1 on this, but I don't work with these data.

I believe the places to update in the schema would be:

* https://github.com/bids-standard/bids-specification/blob/master/src/schema/objects/extensions.yaml
* https://github.com/bids-standard/bids-specification/blob/master/src/schema/rules/files/raw/ieeg.yaml

I did open https://github.com/MEDFormat/MEDPython/issues/6, though. The usability of a GPL'd Python library is questionable if users do not want to GPL their own code. I am having trouble digging up references, but I recall seeing some lack of clarity whether Python's import mechanism triggered LGPL or not. IIRC the most similar license that was definitely safe for use in non-GPL Python projects was the Mozilla Public License v2.

**Comment by dorahermes** [comment]
I am +1 on this as well, as long as we can make sure that the old MEF3 format remains valid.

**Comment by cimbi** [comment]
Totally agree with this we already started using MED in BIDS.

**Comment by EmmanuelBarbeau** [comment]
Hi all, we fully support this as we would also like to use MED in BIDS in our Epilepsy Research Group.

**Comment by michaelpereira73** [comment]
Hello everyone, we are also a few research groups in Grenoble, France to use the MED format and are hoping for it to be included in the BIDS format! Thank you.

**Comment by KLehongre** [comment]
Hello, I confirm that having MED in BIDs would be really useful for the management and sharing of the data of our database. Thank you!

**Comment by tjr1** [comment]
We'd be very glad to have both MED and MEF3 in BIDS!

**Comment by dorahermes** [comment]
I think @effigies described the next steps above. Are there any examples you are interested in adding as well?

**Comment by MEDFormat** [comment]
Hi Dora,

I’ll try to get into this tomorrow.  I’ve been busy adding parity capabilities to MED library (optional damage recovery mechanism).  think it will be finished today.

I think I have the info I need to do this.  It looked pretty easy.


Cheers, Matt

￼

Matt Stead
***@***.***

**Comment by MEDFormat** [comment]
Hi Chris,

I did the changes & pull requests that you recommended, but on one it failed a check:
https://github.com/bids-standard/bids-specification/pull/1957￼
Update ieeg to include MED.yaml by MEDFormat · Pull Request #1957 · bids-standard/bids-specification
github.com

The check error is in "schemacode_ci / Validate schema”

Which gives this for the test details:
=========================== short test summary info ============================
FAILED tools/schemacode/bidsschematools/data/tests/test_rules.py::test_rule_objects - AssertionError: Undefined objects found in rules: files.deriv.preprocessed_data.ieeg_ieeg_common.extensions[0] == .medd/
files.raw.ieeg.ieeg.extensions[0] == .medd/
============ 1 failed, 1 passed, 66 deselected, 2 warnings in 7.59s ============


I looked around for that file, but I could not find it.

Any chance you can point me to it?


Cheers, Matt

￼

Matt Stead
***@***.***

**Comment by effigies** [comment]
I'll merge those into a single PR...

**Comment by effigies** [comment]
Hi all. If iEEG users (ping @dorahermes @cimbi @EmmanuelBarbeau @michaelpereira73 @KLehongre @tjr1, who have chimed in already) could have a review of https://github.com/bids-standard/bids-examples/pull/469/files to make sure that it looks correct, that would be greatly appreciated.

@MEDFormat provided an emptied data directory, and I updated it along the lines of the already existing `ieeg_epilepsy` example. Validation is passing on the schema validator using the schema changes proposed in #1956. I have not made a plan to update the legacy validator, though it would not be difficult if someone wants this to be available in the legacy validator (you would just update [these lines](https://github.com/bids-standard/bids-validator/blob/bec5fea5318953073dc8b97908f11a77ca00845e/bids-validator/bids_validator/rules/file_level_rules.json#L454-L463)).

The main thing that needs review is that this dataset would be understandable to iEEG researchers and work with BIDS tools.

**Comment by MEDFormat** [comment]
Hi Chris,

From what I can see it looks like MED is BIDS approved.  If I’m wrong about that, please let me know.

Cheers, Matt

￼

Matt Stead
***@***.***

**Comment by Remi-Gau** [comment]
> From what I can see it looks like MED is BIDS approved. If I’m wrong about that, please let me know.

just to be pedantic: things become "official"' in BIDS when there is a new release (usually when a BIDS extension proposal is merged), so until there is a new release, features that have been merged in the default branch of the specification are not yet will only become official BIDS approved on the next release

We usually have [1or 2 releases a year](https://github.com/bids-standard/bids-specification/releases) and the last one was in September.

**Comment by MEDFormat** [comment]
Thanks, Remi.


Cheers, Matt

￼

Matt Stead
***@***.***
