### ISSUE TITLE
[FIX] Improvements to the "entity table"

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/bids-specification#200]
We have a page that lists all of the key-value pairs that are used, and which of the specifications require them / have them optional / etc. Here are a couple things that could improve the layout / clarity of the table (originally mentioned in #198 

* I think the table should be transposed. The columns will continue growing while the rows probably won't, and already we have a wider-than-higher table, which I think would render better if it were transposed. This is pretty easy to do with a little pandas, happy to try helping out here.
* Could we add lists to the bottom of this table that include the list of extensions associated with each type of file? I think that'd make the table a bit easier to parse since currently some cells are a lot bigger than others.

**Comment by sappelhoff** [comment]
as part of this PR, or an additional one, we can also add "links" to the spec for each of the `entities` such as `sub`, or `proc`.

I imagine it in a way that users can simply click on `proc` and then are directed to the part of the spec that explains what `proc` actually means. Robert has suggested to use invisible "anchors" for this. But an easy first step would be to simply link to the "nearest" heading ... then we wouldn't have to insert anchors.
