### ISSUE TITLE
BEP Template

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#201]
Following the recent BIDS Computational Models meeting, we decided that, in addition to a few pull requests, it would be good to start some new BEPs, which are generally easier to get going on Google Docs, even if they'll eventually become PRs over here.

I wrote a [BEP Template](https://docs.google.com/document/d/1W7--Mf3gCCb1mVfhsoRJCAKFhmf2umG1PFkyZ1jEgMw/edit) to take care of a lot of the boilerplate and give some examples showing conventions we can use. Does this make sense to link somewhere either in the specification or in our contributors guide?

Also, any additions/edits on the guide itself are welcome.

**Comment by sappelhoff** [comment]
Great, thanks @effigies! I think the [contributor guide](https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/edit?usp%3Dsharing&sa=D&ust=1537468908724000) would be a good place for linking the new template.

**Comment by sappelhoff** [comment]
@chrisgorgo could you grant me permissions for the [contributor guide](https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/edit?usp%3Dsharing&sa=D&ust=1537468908724000) so that I can accept @effigies's suggestion?

**Comment by sappelhoff** [comment]
I would also rename the `contributor guide` to `BEP Lead Guidelines` as suggested in this [comment](https://github.com/bids-standard/bids-specification/issues/160#issuecomment-482606049)

cc @nicholst @emdupre

**Comment by sappelhoff** [comment]
done: https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/

thanks @effigies!
