### ISSUE TITLE
Naming Convention For MRI Scans in Scanner

### ISSUE THREAD

**Issue by mstraccia** [bids-standard/bids-specification#206]
BIDS is a useful way to organize brain imaging data but there appears to not yet be a convention on how to name the runs in the scanner before the data is put into the BIDS format. This is important because just looking the scans parameters, certain BIDS labels cannot be figured out without the user providing more information to the BIDS converter (e.g. the converter cannot tell if the scan is a resting state scan, if the participant was doing a task, what the run number is, etc). Different codes, such as heudiconv, has the user upload a file to inform the code what the name of the run is in the scanner and what it should be named as in BIDS format. This is unfortunate because it requires an extra step by the user and chance of a mistake or confusion by those not very familiar with the process. It would be much easier if a convention was created on how to name each scan so the code can automatically create the correct labeling without the need of uploading an additional file created by the user. 

The details of what this naming convention should be is less important as agreement on the convention and having MRI groups around the world adopting the same convention.

Here is what what I propose and I'm interesting in people's feedback:

The name of run should mostly be in BIDS format already. The only changes should be the exclusion of sub-<label> and instead the first word should be the contrast label (for functional data)/modality label (for anatomical data). If needed the user can add _XX_ at the end for additional notes about the scan. Anything after _XX_ the code will just ignore when putting in BIDS format.

Functional data:
ContrastLabel_(BIDS format for func)_XX_(any personal notes)
BIDS format for func: [_ses-<label>]_task-<label>[_acq-<label>][_ce-<label>][_dir-<label>][_rec-<label>][_run-<index>][_echo-<index>]
The contrast label names are BOLD, CBV, and Phase
Ex: BOLD_task-stroop_run-1_XX_AP_0.8TR   --->  sub-01_task-stroop_run_1_bold.nii.gz

Anatomical data:
AnatomicalModalityLabel_(BIDS format for anat)_XX_(any personal notes)
BIDS format for anat: [_ses-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>]
Examples of contrast labels: T1w (or MPRAGE), T2w, PD (or ProtonDensity), etc.
Ex: MPRAGE_ses-2_XX_6min_1mmx1mmx1mm   --->  sub-01_ses-2_T1w.nii.gz

After there seems to be some agreement, we have see if researchers and techs at universities can start using this labeling convention when setting up scans for users.

Does anyone have any feedback or suggestions?

**Comment by mstraccia** [comment]
Same topic on NeuroStars: https://neurostars.org/t/naming-convention-for-mri-scans-in-scanner/4096

**Comment by effigies** [comment]
You may want to look at https://github.com/repronim/reproin

**Comment by effigies** [comment]
Closing for now. Please reopen if this needs further discussion.
