### ISSUE TITLE
[INFRA] Add github url to the trailer of the page

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#215]
e.g. there is where ATM it is just `powered by MkDocs and Material for MkDocs`, if we could reliably add github link there (ideally jumping to the corresponding file) - would be great.  Otherwise - anywhere and anyhow on the page, at least leading to the top of this repository, would be better than nowhere ;)

**Comment by sappelhoff** [comment]
I think replacing the `powered by MkDocs and Material for MkDocs` footer with a link to GitHub would be great.

It might involve creating a new footer.html file, see `Overriding partials` [here](https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials)
