### ISSUE TITLE
[INFRA] BIDS needs logo

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#216]
There is no logo for organization, some academic hat in the otherwise beautiful  https://bids-specification.readthedocs.io/ (makes hard to locate the tab with bids among other 10s of tabs ;)).  So someone with artistic skills should give it a shot.  But since it is probably worse to file an issue and not to suggest some version, here is my humble ugly attempt

![bids-yarik-logo1](https://user-images.githubusercontent.com/39889/56909174-b3b1c280-6a75-11e9-960f-d3b600f8a52e.png)

I think you could guess on what I hoped it to look like, although someone might argue it is more of a burger on a stick ;)

**Comment by sappelhoff** [comment]
+1 for this idea, and thanks for a draft!

I remember that this issue came up before, see: https://github.com/bids-standard/bids-validator/issues/492

However as far as I know, it never lead to anything serious. Perhaps we can have a collection of logos and then vote on which one we want? 

To consider:
- we probably can't pay anyone money for this
- it should have an appropriate license for us

I have reached out to an artist that I know, perhaps she'll give it a shot just for fun: Then we'd already have two drafts :-)

**Comment by franklin-feingold** [comment]
Following up on this - I have just started a design competition to create our BIDS logo!

The competition can be found here: http://99d.me/c/jmvi

Feel free to pass around if you may know anyone interested in submitting!

**Comment by franklin-feingold** [comment]
We are starting to get some entries. They can be seen here: https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries 

let me know if there may be thoughts on the designs

**Comment by nicholst** [comment]
Amazing we have so many options so quick!

While many are simply pleasing to the eye, it would be magic if it could actually have some meaning, link to the content/concept of the project.  For that reason, I'm draw to the direction of 

https://99designs.co.uk/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/12

The brain outline is awful, I'll admit, but imagine a half-hemisphere that quickly reminds you of a brain, and an iconic representation of metadata, i.e. dotted lines emerging from the other half.  

If we had something snappy along those lines that'd be cool.

**Comment by franklin-feingold** [comment]
+1! I agree that the file structure needs to be incorporated somehow. I have been submitting feedback to the entries to please integrate that into their design (12 is only one currently to do so, but there will be resubmissions)

**Comment by yarikoptic** [comment]
yeah, if 12 may be flipped horizontally and had more obvious file hierarchy tree - could be the one.
Which font is that though? we don't want to end up with some proprietary one used/embedded into the end product

**Comment by franklin-feingold** [comment]
the designer resubmitted the design as 42, I think it is getting closer. The file structure seems present (potentially reducing one of the lines more to provide more leveling) the flipping I am not sure.
The font should be fine, we will be the owners of the copyright at the end of it so everything that makes it up should be able to do that.

**Comment by chrisgorgo** [comment]
Design 45 is pretty cool too!

**Comment by sappelhoff** [comment]
Since this is getting serious, I am making some more people aware of this issue: @bids-standard/bep_leads

**Comment by CPernet** [comment]
I also vote for the idea of have a file structure! [78](https://99designs.co.uk/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/78) for looks even better than 12/[42](https://99designs.co.uk/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/42) IMO

**Comment by francopestilli** [comment]
I like [78](https://99designs.co.uk/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/78) too! @CPernet

**Comment by eduff** [comment]
78 better brain, but the file structure seems more elegant in 42 I think

**Comment by yarikoptic** [comment]
#78 !  better brain, better files, from brain (DICOMs) to files - left to right.  good
I like and dislike (there is nothing special about D) notch on D

**Comment by yarikoptic** [comment]
re #78 -- is there a way to verify provenance on the brain/font?  I mean if brain is not drawn by the artist, it could be covered by a copyright/license etc

**Comment by franklin-feingold** [comment]
Thank you for your feedback! I agree 42 and 78 are looking very nice. 

Regarding the timing - there is about 1 day left of the first round. Then finalist (I believe 6) are put into the final round for 3 days. Then 14 days to pick the winner. Once the winner is selected the handover begins (and the discussion of @yarikoptic concerns of copyrights/licensing)

**Comment by tyarkoni** [comment]
I like 78 conceptually and aesthetically, but the brain looks a little funny to me—it brings to mind a sponge more than a brain. I think my current favorite is [50](https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/50), which looks great and IMO is sufficiently abstract that the same graph-y object can be interpreted as both a brain and a filesystem (aesthetically, I like some of the same artist's other submissions even better, e.g., [55](https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/55), but I think 50 really nails the idea).

**Comment by effigies** [comment]
I do like the idea that we might brand a conference room window with this.

**Comment by oesteban** [comment]
For me, 45 and 78 go far ahead. It must be that my sponge is blind to that brain...

I think 50 is pretty elegant, but I don't see the filesystem side of it.

Please don't 42 and 55.

**Comment by yarikoptic** [comment]
> it brings to mind a sponge more than a brain

and the difference is (especially as we grow older)...? ;)

> I think my current favorite is [50](https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/50),

I didn't search for them but both 50 and 55 (as many others) gave me the feeling of some used with the brains design pattern already ... to me 50 also doesn't quite actually point to "filesystem" concept unless you take it as your prior to look for.

**Comment by nicholst** [comment]
[78](https://99designs.co.uk/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/78) is on point but clunky.  I'm drawn to the brain-out-of-folders (eg [64](https://99designs.co.uk/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/64)) but worry it won't read well at varying scales (i.e. especially small ones).

I keep coming back to [45](https://99designs.co.uk/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/45)... the brain in a folder... if the folder shape is sharpened I think it'll read well at a variety of scales.  Just don't like the pointy brain stem.

**Comment by tyarkoni** [comment]
I prefer 45 to 78. Agree re: the pointy brain stem, but I assume once we acquire it, we can do whatever we like, and it would be trivial to remove the pointy part outside the folder.

**Comment by oesteban** [comment]
@franklin-feingold 
> Once the winner is selected the handover begins (and the discussion of @yarikoptic concerns of copyrights/licensing)

What if the discussion ends quickly with "_yes, I copied it without looking at the license, which happens not to allow it_"? That would be a big deal.

**Comment by effigies** [comment]
I suspect fraudulent activity would probably have negative consequences for the designer and we'd get our money back.

Also: [Who purchases stock art, the customer or designer? When? ](https://support.99designs.com/hc/en-us/articles/204275409-Who-purchases-stock-art-the-customer-or-designer-When-)

**Comment by oesteban** [comment]
Okay, since the logos don't have any watermarks we can assume they are original, correct?

**Comment by teonbrooks** [comment]
are we supposed to vote here or on 99designs?

**Comment by sappelhoff** [comment]
> are we supposed to vote here or on 99designs?

@franklin-feingold --> can you answer this question? Also, once we have the six finalists we could consider pinging the mailing list to get some more votes from the community - what do you think?

**Comment by HenkMutsaerts** [comment]
I'm also a bit confused as to where to vote or find this discussion.

This would be my ranking:

Choice 1: *12* good because the brain is at the letters side, reads good,
simple.
But font can be bit less bold, bit better
Choice 2: *88* / *78*
Choice 3: *50* best font
Choice 4: *86 53 49* bit too modernistic/unclear

Best wishes/hartelijke groet,

*Henk(-Jan) Mutsaerts, MD PhD*

Amsterdam UMC/ UZ Ghent

Phone: +31 6 4390 8284; Skype: hj.mutsaerts

**Comment by chrisgorgo** [comment]
Oh wow this one evolved pretty nicely!
https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/88

**Comment by danlurie** [comment]
My favorites are 12/42. Prefer 42, because the type is more interesting. If we get the logo as vector paths instead of type, fonts shouldn't be an issue

I agree that the brain on 78/88 looks a bit off. Prefer 78, because the details in 88 will make it difficult for the logo to work well when reproduced at small sizes)

**Comment by francopestilli** [comment]
@chrisgorgo I like [#88](https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/88) but the brain there is a bit weird. The rest is well developed, but don't we think the brain picture there can look a bit squished? :-)

**Comment by chrisgorgo** [comment]
> I like [#88](https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/88) but the brain there is a bit weird. The rest is well developed, but don't we think the brain picture there can look a bit squished? :-)

It's reused from some public library of vector images (I saw it before somewhere). We can always ask candidates to refine the design in the second phase. This is the procedure: https://support.99designs.com/hc/en-us/articles/204109459-How-long-do-design-contests-take-and-what-s-involved-

**Comment by franklin-feingold** [comment]
Regarding voting - we can vote here or on 99designs, I am collecting feedback for both. Please feel free to continue listing the numbers I can connect it to the designer. We choose the top 6 designers (not concepts) to move forward to the final round. The top 6 need to be chosen by noon PST Wednesday (5/22). 

For choosing the final design we can run a poll to share on our different mediums to collect feedback for 1 week before a final decision is made. We are going to have 3 days to move toward a final design to vote on and it appears we will get the original files so they can likely be touched up if need be.

**Comment by robertoostenveld** [comment]
I like 88, 78, 72, 71, 45 because they relate somehow to files/folders.
I like the colors in 9, 3, and 3.

**Comment by Gilles86** [comment]
Cool stuff. I like 89, 88, 78, 73 most. :)

**Comment by franklin-feingold** [comment]
Thank you all for your feedback, please feel free to continue submitting! We have a few more days before choosing the finalist! I have taken a tally and here is where we are at - 

We currently have identified 6 designers with potentially multiple different designs:
Johnsmithaps, Nilangle, Feliana, Pixeleiderdown, Design Channel, and Katsuo

**Comment by effigies** [comment]
The only ones I thought were decent were

1) nilangle ([12](https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/12), [42](https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/42), [104](https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/104)), and I preferred the font in 12 to that in 42/104, but liked a little bit the non-uniformity of the "files" in 104.
2) johnsmithaps ([78](https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/78), [88](https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/88)), though the lines sticking into the brain kind of break the directory structure appearance.

In both cases, the brain could stand a shape and sulcus pattern that looks a little more like a real brain.

[103](https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/103) would make a good logo for an anarchist chat app.

**Comment by franklin-feingold** [comment]
The final round has begun with the 6 finalist I mentioned [previously](https://github.com/bids-standard/bids-specification/issues/216#issuecomment-494097384)

> Johnsmithaps (88, 78, 45), Nilangle (42, 12), Feliana (50, 55), Pixeleiderdown (86, 53, 49), Design Channel (71, 72, 73), and Katsuo (89)

Please feel free to continue giving feedback and comments that I can pass onto the finalist! We have 3 more days to tinker with the design before the final polling begins next week to make the final decision!

**Comment by nicholst** [comment]
FWIW I think, of this lot, there are my favorites: 88, 45 (though still
needs work) and 72.

I like the brain graph of 72 but like the typography in 45 more.  88 is
undeniably the most literal spot-on one (and good typography) ... but
something about the 3 heavy lines and the half brains leaves me not
enthusiastic enough to rule out the others.

**Comment by franklin-feingold** [comment]
Update on the competition - we are ready to vote for our winning design! I have compiled all of our feedback into [this survey](https://forms.gle/kCeVzguM6wnSmpuv6) to capture our voting. In this round we are voting on our favorite design concept, we can still work with the winning designer to make small adjustments.

**Comment by Remi-Gau** [comment]
1 - means "most preferred" and 5 "least preferred" or the other way around?

**Comment by franklin-feingold** [comment]
Yup! 1 - most preferred 5 - least preferred.

**Comment by chrisgorgo** [comment]
Are these designs final or can they be tweeked? If https://99designs.com/logo-design/contests/design-brain-imaging-data-standard-logo-916110/entries/158 wins we should modify it a bit so the folder/file hierarchy would be realistic (right now it shows a folder being a child of a file).

**Comment by franklin-feingold** [comment]
These designs can be tweaked (most of our designer finalists are open to continuing the modifications if selected), the final logo will be modified (if needed) to be realistic

**Comment by sappelhoff** [comment]
Now we do have a logo, see: https://twitter.com/BIDSstandard/status/1136715977737924608

Next we should 
- provide the logo as .png and as a vector graphics format
- include the logo on our specification (favicon, and others)
- put the logo on our slides
- ...

**Comment by franklin-feingold** [comment]
tracking BIDS logo distribution - https://github.com/bids-standard/bids-specification/issues/244
