### ISSUE TITLE
List of licences is too small

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-specification#218]
Can you expand  the list of licenses in the appendix by adding more restrictive ones?

For example, in our research we sign an agreement with subjects that taken data will be used for scientific purpose only, so we can not apply a license that gives up all rights on dataset.

Unfortunately I have no knowledge in this matter, so I can not suggest additional licenses.

**Comment by sappelhoff** [comment]
I assume you are referring to [Appendix II](https://bids-specification.readthedocs.io/en/stable/99-appendices/02-licenses.html):

As far as I understand it, this appendix is not "prescriptive". That is, BIDS does not force you to apply a specific license. After all, BIDS can also be used in a within-lab-only environment, without sharing outside - and in these cases, a more restrictive license would be fine.

Perhaps I am wrong though, happy to get input from the community - also regarding license recommendations. 

For that, it'd be helpful though to know what exactly your subjects have given consent to @nbeliy!

**Comment by nbeliy** [comment]
Here the agreement (it's in french).
[4.Ethique_Gabarit_2011_Partie3_info_sujet_consentement_eclaire_amendement_AVRIL18 (1)-1.pdf](https://github.com/bids-standard/bids-specification/files/3147626/4.Ethique_Gabarit_2011_Partie3_info_sujet_consentement_eclaire_amendement_AVRIL18.1.-1.pdf)

Important part:

> Les données codées et les résultats de l'étude pourront également être transmis à GE Healthcare, la société pharmaceutique qui fournit le [18F]flutemetamol, en vue de recherches futures et de développement du produit. Tout événement indésirable qui pourrait survenir dans le décours de l’administration du [18F]flutemetamol sera rapporté à GE Healthcare pour mettre à jour la brochure d’information.

**Comment by sappelhoff** [comment]
So in english (Google Translate):
> The coded data and study results may also be sent to GE Healthcare, the pharmaceutical company supplying [18F] flutemetamol, for future research and product development. Any adverse events that may occur during the course of administering [18F] flutemetamol will be reported to GE Healthcare to update the information leaflet.

To me this sounds like you can't share the data with anyone other than GE Healthcare :thinking:

**Comment by nbeliy** [comment]
Indeed, but we wish still use BIDS as fully compatible as possible.
Also, having more flexible list of licenses will help motivate my superiors to change the agreement and make datasets public.

**Comment by sappelhoff** [comment]
> Indeed, but we wish still use BIDS as fully compatible as possible.

sure there is no problem to use BIDS and not share the data publicly

> Also, having more flexible list of licenses will help motivate my superiors to change the agreement and make datasets public.

as I said: the licenses listed in [Appendix II](https://bids-specification.readthedocs.io/en/stable/99-appendices/02-licenses.html) are merely examples, not requirements. I will open a PR to make this clear.

As for additional license examples, I don't know who of us (BIDS-community) is an expert on this. Perhaps @choldgraf?

**Comment by choldgraf** [comment]
hmmm - actually I believe that licensing data is generally a bit more poorly-understood than licensing code or content. I can ask around w/ the librarians at Berkeley to see if they know anything, or this feels like something the Twittersphere might be helpful in answering

**Comment by effigies** [comment]
So I see two restricted cases:

1) Data can't be shared.
2) Data can be shared, but on less permissive terms.

In the first case, I'm not sure we need to really make a particular accommodation apart from "License as you see fit."

In the second, it might be useful to keep a list of known non-free licenses that people are actively sharing BIDS datasets under. This would target three audiences:

1) Dataset curators. Having a library of existing less-permissive licenses that still allowing some degree of sharing reduces work, promoting sharing.
2) IRBs, lawyers and other administrators. A list of licenses provides concrete terms to compare to their legal and ethical requirements, making approval of sharing more likely.
3) Repositories. A small set of licenses may be reviewed for whether or not the repo can/will comply with the terms, and they can then make assertions and build automated accession constraints. This makes it safer to accept less-permissive datasets. In turn, this makes the licenses more attractive to curators and administrators. A repository might also write its own set of licenses that it's willing to accept.

I don't see this as something we need to do anything about right now, to be clear. But when restricted datasets do start being published, I would be up for including a list/table of known licenses in the appendix.

**Comment by sappelhoff** [comment]
closing as answered. To be reopened when we see more cases of publicly shared restricted datasets.
