### ISSUE TITLE
[iEEG] DCOffsetCorrection does not apply to raw data

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-specification#237]
This is listed as *"RECOMMENDED. A description of the method (if any) used to correct for a DC offset. If the method used was subtracting the mean value for each channel, use "mean"."*

It is not specified for MEG, nor for EEG. I don't consider it appropriate for raw iEEG data, which is what the specification refers to. De-meaning is a procedure used in offline processing, not during recording. I believe this should be specified in the derivatives instead.

**Comment by robertoostenveld** [comment]
I propose to remove the field from the specification. Of course we should also check the validator.

@choldgraf @dorahermes @sappelhoff @ftadel, what is your opinion about this?

**Comment by dorahermes** [comment]
This was added after discussion with @voytek in the google doc because he records with [Biosemi](https://www.biosemi.com/faq/adjust_gain.htm). I personally have never encountered this, but also have never specifically looked into it. 
@choldgraf do you remember the details?

**Comment by robertoostenveld** [comment]
this relates to https://www.biosemi.com/faq/adjust_filter.htm and to https://www.biosemi.com/faq/adjust_filter_activeone.htm. I don't see why that would not be represented in the `SoftwareFilters` specification.

**Comment by dorahermes** [comment]
The DCOffsetCorrection was added before we detailed the Hardware/SoftwareFilter specifications, if it is redundant now it should be removed.
