### ISSUE TITLE
Run format for different tasks

### ISSUE THREAD

**Issue by dlevitas** [bids-standard/bids-specification#238]
Hello,

I think the way I'm naming my files follows the proper BIDS heuristic; however, I wanted to double check. I've got data from a single session in which two tasks were performed, "ntask" and "rest". For each new task, I have the runs start back at one, so my naming convention for the functional runs is:
```
sub-100_task-nback_run-01_bold.nii.gz
sub-100_task-nback_run-02_bold.nii.gz
sub-100_task-rest_run-01_bold.nii.gz
sub-100_task-rest_run-02_bold.nii.gz
```

Is this the correct naming convention, or do the ```task-rest``` runs need to be ```run-03``` and ```run-04```?

Thanks for the clarification.

Dan

**Comment by effigies** [comment]
This is correct. Run only needs to be unique within a given task.
