### ISSUE TITLE
BIDS logo distribution

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#244]
Checklist of locations to put BIDS logo
- png on bids-specification: [white writing](https://github.com/bids-standard/bids-specification/blob/master/Whitelogo_transparent-background.png) and [black writing](https://github.com/bids-standard/bids-specification/blob/master/Logo-transparent-background.png)
- make a favicon: put on [bids website](https://bids.neuroimaging.io/) (https://github.com/bids-standard/bids-website/pull/47) and RTD (https://github.com/bids-standard/bids-specification/pull/246)
- update [bids website](https://bids.neuroimaging.io/) (https://github.com/bids-standard/bids-website/pull/47)

Please feel free to put other locations that may make sense

**Comment by effigies** [comment]
A vector graphics format would be appreciated.

**Comment by franklin-feingold** [comment]
svg inside of the [BIDS logo files folder](https://github.com/bids-standard/bids-specification/tree/master/BIDS%20logo%20files)

**Comment by sappelhoff** [comment]
The Favicon is added, but it would be nice to also replace the logo, i.e. the symbol that is currently the "graduate hat" in the upper left corner: https://bids-specification.readthedocs.io/en/latest/

**Comment by sappelhoff** [comment]
I think the logo is everywhere where it needs to be, closing for now. Thanks for the efforts to all involved :+1:
