### ISSUE TITLE
BIDS Governance Discussion Resources 

### ISSUE THREAD

**Issue by jdkent** [bids-standard/bids-specification#245]
A followup from @arokem at the OHBM BIDS discussion suggesting we can look towards the python transition from BDFL to their current steering counsel for inspiration on selecting/modifying the BIDS governance structure. The python community put a decent amount of work aggregating/summarizing governance structures from other open source projects.

[PEP 8000](https://www.python.org/dev/peps/pep-8000/) gives an overview of the relevant PEPs for selecting how do we vote for a new governance structure, what options do we select from, what other governance structures are out there (Rust is included).

If you want a more personal account of their process, Brett Cannon (A python core developer and current member of the steering counsel), talked on a couple podcasts about the process.
- [talk python to me](https://talkpython.fm/episodes/show/209/inside-python-s-new-governance-model)
- [the changelog](https://changelog.com/podcast/348)

For where we are currently, #104 should be an essential read, with @KirstieJane's [excellent comment](https://github.com/bids-standard/bids-specification/pull/104#issuecomment-445920497) outlining considerations for the decision making process.

What are other people's good reads/resources on governance/decision-making topics?

**Comment by franklin-feingold** [comment]
Hi @jdkent 

Thank you for raising this and sharing these resources! This is an important discussion to be had and after the OHBM BIDS community meeting the need is there for more organized structure. I think an important aspect will be having this conversation in the open to allow all thoughts and concerns to be aired so we can create the best governance structure for us (taking inspiration from projects like Python, Rust, W3C, etc; and others identified by Kirstie)

A potential proposal is being generated and distributed for community feedback (could be kicked back and a broader conversation be needed). I will open another issue to keep it separate from this one (I think it is great to have a record of governance resources if others in the community want to crowdsource these resources). 

WIll be fantastic to have all thoughts on it. WIll be a google document to allow more fluid conversations and enable easier contribution.

**Comment by franklin-feingold** [comment]
thank you for providing this! the governance proposal has now been approved! working on [the conversation](https://github.com/bids-standard/bids-specification/pull/354) and putting it into this repo!
