### ISSUE TITLE
Centralizing BIDS resources

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#247]
Hi BIDS Community!

It was great hearing from some of you at the BIDS community meeting over OHBM last week. One big takeaway from that meeting was the need to centralize the many resources generated that are associated with BIDS. I have started a [google doc](https://docs.google.com/document/d/1u680oW6ktEXKyE6_V3kcdZAZ5Ma445ZwG9_oBuE7z1A/edit) to begin aggregating all of the different resources we have. Please feel free to add any not listed!

Potential steps in this process: 
- Collect all the resources and materials
- Create a figure displaying all the resources (make easier to navigate the project)
- build out the https://bids.neuroimaging.io/ site with the different high-level categories. 

Thank you for your help and contribution!

**Comment by sappelhoff** [comment]
@franklin-feingold I think this issue is kind of the "predecessor" of what you are working on currently (re-structuring BIDS organization into three "pillars" spec, tools, community), right? 

Should we close it? Or leave it open until the ideas are more fleshed out and discussed?

**Comment by franklin-feingold** [comment]
yep! I think this can be closed and when the proposal is being hashed out new issues can be made as needed (perhaps in a better place for those conversations to live!). The main purpose behind this issue is being addressed with the restructuring
