### ISSUE TITLE
Clarifying specific field maps naming convention

### ISSUE THREAD

**Issue by dlevitas** [bids-standard/bids-specification#251]
Hello,

I've got a protocol that has two separate pairs of field maps (since participants take a short break in the middle of the session). The field maps consist of two magnitude files and a phase difference file. Currently, the naming of the .nii.gz output in ```fmap``` :

```
sub-1_run-01_magnitude.nii.gz
sub-1_run-01_phasediff.nii.gz
sub-1_run-02_magnitude.nii.gz
sub-1_run-02_phasediff.nii.gz
sub-1_run-03_magnitude.nii.gz
sub-1_run-04_magnitude.nii.gz
```

I can't find an exact example of this in the BIDS spec, but it seems like the proper naming convention should be:
```
sub-1_run-01_magnitude1.nii.gz
sub-1_run-01_magnitude2.nii.gz
sub-1_run-01_phasediff.nii.gz
sub-1_run-02_magnitude1.nii.gz
sub-1_run-02_magnitude2.nii.gz
sub-1_run-02_phasediff.nii.gz
```

Would this be correct, or is the first way acceptable?

**Comment by sappelhoff** [comment]
Did you run it through the [BIDS-validator](https://bids-standard.github.io/bids-validator/)?

**Comment by dlevitas** [comment]
I did, and it failed the BIDS validation, though not because of the naming convention (that was a warning instead). The error was that my phasediff.json file didn't contain the fields ```EchoTime1``` and ```EchoTime2```. Once I added those two field, there were no error messages. I am also using the naming convention from my 2nd example in my original post.
