### ISSUE TITLE
KRISS MEG data question

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#253]
I am currently updating the BIDS validator to account for "Father level" directories (or their absence) and was stumbling over KRISS MEG data: https://bids-specification.readthedocs.io/en/latest/99-appendices/06-meg-file-formats.html#kriss

... in the example, there is no "visualization" of the `_digitizer.txt` file ... do we have a BIDS example for this somewhere? 

Would a valid BIDS file be `sub-<label>[_ses-<label>]_task-<label>[_run-<index>]_meg_digitizer.txt`?

Help would be appreciated. Please tag MEG folks @robertoostenveld @jasmainak

**Comment by jasmainak** [comment]
You can’t do _meg_digitizer.txt. It goes against how BIDS works. It should be _digitizer.txt.

**Comment by sappelhoff** [comment]
mmh okay, I can add that to the RegExp of the BIDS-validator (see https://github.com/bids-standard/bids-validator/pull/789) ... but we should also add it to the specification at the point that I linked in my original post.

I just think that this needs to be done/verified by a Person who has worked with KRISS

**Comment by sappelhoff** [comment]
see the fix here: https://github.com/bids-standard/bids-specification/pull/248/commits/2f2a5831ecf6e2d20f06fb26dce3fefe5db89ab4

**Comment by jasmainak** [comment]
Fix LGTM. I don't know who does KRISS :) maybe @robertoostenveld can help

**Comment by robertoostenveld** [comment]
Nope, I also don't know who uses a KRISS system. I also do not have any example data from that system, and afaik FieldTrip does not support it. Perhaps we should reach out to https://www.orionmeg.com? Or simply ignore it until it becomes a concrete issue?

**Comment by sappelhoff** [comment]
Thanks Robert, ... yes - let's ignore it until a User has a case :-)
