### ISSUE TITLE
Misleading paragraph in Common Principles

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#262]
I'd like to draw attention to this section of the spec:

https://github.com/bids-standard/bids-specification/blob/76068e0b1fa7588bb589dbd7ea58b012ca108ab0/src/02-common-principles.md#L414-L418

Rendered:
> Additional files and folders containing raw data may be added as needed for special cases. They should be named using all lowercase with a name that reflects the nature of the scan (e.g., `calibration`). Naming of files within the directory should follow the same scheme as 
above (e.g., `sub-control01_calibration_Xcalibration.nii.gz`)

This seems to violate the usual rules that unspecified files are generally invalid. It also suggests a naming scheme that is invalid, with a bareword "calibration". This has led to a user believing that `sub-X_calibration_ASSET.nii.gz` is a valid filename ([Neurostars #4540](https://neurostars.org/t/bids-validator-errors/4540)), and I would say this is a reasonable interpretation, but it is otherwise wholly incompatible with BIDS as it stands.

I'm not sure if this is salvageable or should simply be deleted.

----

To note that this issue has been here for a bit, I'm quoting section 7 of the [1.0.0 spec](https://bids.neuroimaging.io/bids_spec1.0.0.pdf) in full:

> # 7 Directory structure (single session example)
> This is an overview of the folder and file structure. Because there is only one session, the session level is not required by the format. For details on individual files see descriptions in the next section:
>
> * sub­-control01/
>   * anat
>     * sub­-control01_T1w.nii.gz
>     * sub­-control01_T1w.json
>     * sub­-control01_T2w.nii.gz
>     * sub­-control01_T2w.json
>   * func
>     * sub­-control01_task­-nback_bold.nii.gz
>     * sub­-control01_task­-nback_bold.json
>     * sub­-control01_task-­nback_events.tsv
>     * sub­-control01_task­-nback_physio.tsv.gz
>     * sub­-control01_task­-nback_physio.json
>     * sub­-control01_task-­nback_sbref.nii.gz
>   * dwi
>     * sub-­control01_dwi.nii.gz
>     * sub­-control01_dwi.bval
>     * sub­-control01_dwi.bvec
>   * fmap
>     * sub-­control01_phasediff.nii.gz
>     * sub­-control01_phasediff.json
>     * sub­-control01_magnitude1.nii.gz
>     * sub­-control01_scans.tsv
>     * Additional files and folders containing raw data may be added as needed for special cases.  They should be named using all lowercase with a name that reflects the nature of the scan (e.g., "calibration").  Naming of files within the directory should follow the same scheme as above(e.g., "sub-control01_calibration_Xcalibration.nii.gz")
> * code
>   * deface.py
> * Derivatives
> * README
> * participants.tsv
> * dataset_description.json
> * README
> * CHANGES

**Comment by sappelhoff** [comment]
> Additional files and folders containing raw data may be added as needed for special cases. 

yes, this sounds very odd - I wonder how/why it got in.

I currently tend towards the "delete it" option

**Comment by nicholst** [comment]
+1 for deleting that paragraph.  As I read it, it is proposing that new datatypes can be added as any user sees fit, e.g., with `calibration` sitting next to `anat`, `func`, etc, violating a core BIDS principle.

**Comment by effigies** [comment]
Thanks to both for the confirmation. That's my assessment as well. I'm guessing it's language that got rejected early on, but somehow got lost in a Google doc suggestion mess, and nobody read very carefully until "calibration" got searched for directly.

Will open a PR.
