### ISSUE TITLE
Add twitter badge to gh and website

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#266]
Adding a BIDS twitter badge/reference to the:

- [x] github readme
- [x] RTD rendering (probably on the index)
- [x] BIDS .io website

Please feel free to add other locations our twitter badge can be

Edit: https://github.com/bids-standard/bids-specification/pull/268 addresses point 1 and 2
https://github.com/bids-standard/bids-website/pull/49 addresses point 3

**Comment by sappelhoff** [comment]
What badge did you have in mind? Or are you talking about a handle in text form like: [`@BIDSstandard`](https://twitter.com/BIDSstandard)

**Comment by franklin-feingold** [comment]
I was thinking of something like this 
![Screen Shot 2019-07-11 at 11 38 10 AM](https://user-images.githubusercontent.com/35307458/61076133-62587480-a3d0-11e9-90b2-625b212bc575.png)

but a follow us badge. not a text handle but the visual figure

**Comment by KirstieJane** [comment]
You can make a badge in the README using shields.io: https://shields.io/category/social

`http://img.shields.io/twitter/follow/bidsstandard.svg?style=social`

renders as

![](http://img.shields.io/twitter/follow/bidsstandard.svg?style=social)

**Comment by franklin-feingold** [comment]
Yes! that's perfect thank you @KirstieJane !
