### ISSUE TITLE
Examples for use of "phenotype" saving survey data in BIDS

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#280]
I got a request of Karin Jensen, who wants to handle survey data in BIDS next to the MRI data.

I directed her to the **Participants file** section of our specification (see [here](https://bids-specification.readthedocs.io/en/latest/03-modality-agnostic-files.html#participants-file)), where we talk about the `phenotype` directory.

Unfortunately, the paragraph is not accompanied by an example, so there are several open questions such as:
1. where do I place the `/phenotype` directory?
1. how do I name my files in the `/phenotype` directory?

Does somebody have an example at hand to share and discuss? It would also be great to update the specification with an example (a constructed, simplified one).

**Comment by franklin-feingold** [comment]
Thank you for sharing the question! 

> where do I place the /phenotype directory?

The `/phenotype` folder can be placed at the root with the `dataset_description.json` file and `sub` folder. 

> how do I name my files in the /phenotype directory?

On [OpenNeuro dataset 000030](https://openneuro.org/datasets/ds000030) is an example of how to name phenotypic files.

**Comment by sappelhoff** [comment]
Cool - that looks nice. I added a "good first issue" label. Somebody can make a PR to the specification, working on the phenotype section and weaving the example of the OpenNeuro dataset into the text.
