### ISSUE TITLE
Announcement: GitHub teams

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#285]
I've created a [set of GitHub teams](https://github.com/orgs/bids-standard/teams/everyone/teams) that should allow us to better titrate our calls for people's eyes than simply saying @bids-standard/everyone or @bids-standard/bep_leads.

Those teams are arranged [hierarchically](https://help.github.com/en/articles/about-teams#nested-teams) under @bids-standard/everyone, splitting by raw, derivatives and models, and then by increasingly specific components, as discussed in [this thread](https://github.com/orgs/bids-standard/teams/everyone/discussions/7?from_comment=8#discussion-7-comment-8).

<img width="782" alt="A partially expanded hierarchy of teams" src="https://user-images.githubusercontent.com/83442/61895513-dc185400-aee0-11e9-8749-7db178f05db4.png">

The hierarchy allows you to join the most specific teams you care to hear from, and you will receive notifications from parent levels. For instance, I can join @bids-standard/raw-electrophys-ieeg, and I will get notified when people mention @bids-standard/raw-electrophys-ieeg, @bids-standard/raw-electrophys, @bids-standard/raw or @bids-standard/everyone.

From the shouting-into-the-void perspective, you now have a choice of appropriately sized voids. For example, I might be working on an anatomical derivative, and now I need to decide whether this mostly affects other anatomical derivatives, in which case I should mention @bids-standard/derivatives-mri-anat, or perhaps I need thoughts about how it interacts with other derivatives, so I might instead mention @bids-standard/derivatives-mri (and the functional and diffusion folks will see) or even @bids-standard/derivatives (and the electrophys folks will see, too).

Happy to hear any feedback, and look forward to seeing if this helps improve people's experience with hearing about the issues that interest them most.

**Comment by sappelhoff** [comment]
Great, thanks @effigies! Perhaps a visual guide on how to actually join a team would be good?

---

1. Navigate to the **teams** site of bids-standard

![image](https://user-images.githubusercontent.com/9084751/61901136-62538b00-af1f-11e9-9335-d0a560816d1d.png)

---

2. You'll see the "everyone" team. Now click on the dropdown menu where it says "27 Teams" in the picture


![image](https://user-images.githubusercontent.com/9084751/61901161-70a1a700-af1f-11e9-94a6-e222a683dccd.png)

---

3. Click on the team or sub-team that you want to join, and then in the upper right navigation click on "Members"

![image](https://user-images.githubusercontent.com/9084751/61901205-8911c180-af1f-11e9-829b-442bc53811b6.png)

---

4. There should be a "Request to join" button, which you can use to join the team

![image](https://user-images.githubusercontent.com/9084751/61901264-a777bd00-af1f-11e9-9168-cd884cadc5cc.png)

**Comment by Hboni** [comment]
This is a great idea, but I wanted to join a specific team, following @sappelhoff instruction, but I couldn't reach the teams' page. Github only says that I am not a member of any teams.

![github_teams_issue](https://user-images.githubusercontent.com/27290853/61932011-9744f980-af82-11e9-863e-8a8136b1bb91.png)

**Comment by sappelhoff** [comment]
@Hboni yes, it seems you have to [become a member of the GitHub organization first](https://help.github.com/en/articles/about-teams). Perhaps @franklin-feingold  can send you an invitation.

For all others: If you run into this problem, just ping in this thread

**Comment by effigies** [comment]
If anybody has the permissions to give me extra permissions, I would like to spread "maintainer"-ness to new members of each group, and you all won't have to wait on (just) me to approve you to join.

I don't know who the owners/admins of the organization are, though I expect @chrisgorgo definitely is...

**Comment by KirstieJane** [comment]
I just made you an admin @effigies. Others with the power can revert that, but I doubt it will be a controversial move...

**Comment by effigies** [comment]
Thanks @KirstieJane! Maybe I should preemptively de-admin everyone else, to keep things from getting out of hand.

**Comment by arokem** [comment]
@franklin-feingold : Could I please be added to the org, so that I can join teams?

**Comment by effigies** [comment]
Hmm. IDK if there is a permission to bump people's privileges within individual teams without just making them organization owners. @sappelhoff I'm inclined to give you this power as well. Hopefully that will make you someone who can accept team requests.

I figure BEP leads (at least for merged BEPs and those that have relevant teams, like PET) should get these permissions as well, but I'll wait for a second before I go ahead.

@arokem Invitation sent.

**Comment by effigies** [comment]
Okay, I've figured out how to bump people up to maintainerdom:

In the team members:

<img width="421" alt="Screen Shot 2019-07-26 at 09 41 32" src="https://user-images.githubusercontent.com/83442/61955755-b2ffce00-af89-11e9-9e2b-53757bd85503.png">

Select your victim, go to the dropdown and click "Change role...":

<img width="425" alt="Screen Shot 2019-07-26 at 09 41 49" src="https://user-images.githubusercontent.com/83442/61955780-be52f980-af89-11e9-8c89-e0ac982bb905.png">

And grant power beyond their mildest dreams:

<img width="447" alt="Screen Shot 2019-07-26 at 09 42 00" src="https://user-images.githubusercontent.com/83442/61955819-d591e700-af89-11e9-8778-72978fd056c5.png">

**Comment by Hboni** [comment]
Can I be added to join teams please ? @effigies @franklin-feingold

**Comment by effigies** [comment]
@Hboni Added you to the organization and the everyone team.

**Comment by sappelhoff** [comment]
Done @Hboni now you can join teams and get accepted by the respective moderators 👍

**Comment by Andesha** [comment]
Hello! Can I please be added to to join teams as well? @effigies 

Thanks in advance :)

**Comment by effigies** [comment]
@Andesha Done. If you don't have an email, you can go to https://github.com/orgs/bids-standard to join the organization.

**Comment by jadesjardins** [comment]
@effigies thanks for organizing the teams! I would like to be added to the organization.

**Comment by dnacombo** [comment]
Hello! Can I please be added to to join teams as well? @effigies

Thanks in advance :)

**Comment by effigies** [comment]
@dnacombo https://github.com/orgs/bids-standard

**Comment by jhlegarreta** [comment]
@effigies May I be added to the organization so that I can join the teams I am interested in? Thanks.

**Comment by effigies** [comment]
@jhlegarreta https://github.com/orgs/bids-standard

**Comment by martcous** [comment]
@effigies Can I please be added as well? Thanks!

**Comment by effigies** [comment]
@martcous https://github.com/orgs/bids-standard

**Comment by Horschig** [comment]
@effigies could you please add me, too? Thanks!

**Comment by effigies** [comment]
@Horschig https://github.com/orgs/bids-standard

**Comment by emdupre** [comment]
Could we add a team for the BIDS Steering committee ? I realized I wanted to ping them in #371 but it doesn't seem that a team yet exists !

**Comment by effigies** [comment]
@emdupre Created @bids-standard/steering. 4 of five members are on it now. Pending invitation to the organization for @guiomar.

**Comment by guiomar** [comment]
Thanks! I'm not very expert on GitHub, should I need to do something?

**Comment by effigies** [comment]
@guiomar Go to https://github.com/orgs/bids-standard. There should be some button to click to join the organization.

**Comment by robertoostenveld** [comment]
> Thanks! I'm not very expert on GitHub, should I need to do something?

I have just updated your invitation to join the bids-standard organization (which is required to be in a team). I hope this resulted in you receiving the invitation email once more.

**Comment by yarikoptic** [comment]
Should this issue stay open?
