### ISSUE TITLE
BIDS Maintainers guide

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#288]
hey BIDS Community!

I started putting together a document detailing our [BIDS Maintainers](https://docs.google.com/document/d/11U43QmYVZUVdCxpJeezmYpkHf4sbzWjjN2EIjbk4Pfo/edit?usp=sharing) responsibilities and procedure to becoming a Maintainer. Please feel free to comment and share your ideas!

Thank you!

**Comment by sappelhoff** [comment]
Should we announce a timeline when we will merge this document? True to our motto: "Start with something good and make it better" (as opposed to "wait till its perfect"?)

How about end of August? Earlier would be fine with me.

**Comment by franklin-feingold** [comment]
I can convert the google doc to md and open a PR to get this moving forward and closer to merged

**Comment by sappelhoff** [comment]
based on the discussion in #316 I overhauled the draft and prepared a new version, based on input by @effigies and the blog post by Matthew Rocklin.

the new draft is:

- shorter
- less hierarchical
- still captures key points
- is more abstract (leaves more things up to discussion among maintainers)

Please offer your opinions @franklin-feingold @effigies @emdupre

**Comment by effigies** [comment]
This looks good to me.

**Comment by franklin-feingold** [comment]
thank you for revisiting this! I have added some comments in - some may perhaps be discussion points for the group when more members come aboard

**Comment by emdupre** [comment]
Thanks @sappelhoff ! I left some additional comments. One general point (that I put in my top comment) is that I'm really not sure on the purpose of this document. Right now it feels like a list of responsibilities once someone is designated a maintainer, but I leave feeling really uncertain why anyone would _want_ to become a maintainer.

If this document is only designed to list responsibilities, I think we'll need to be significantly more detailed (perhaps once more members join, as @franklin-feingold suggested). Personally, I think an in-depth listing of responsibilities might be tricky, though, and I like the current high-level approach &mdash; I just think it needs a balance with some of the "rights" or perhaps "job benefits" that come from acting as a maintainer.

**Comment by sappelhoff** [comment]
@franklin-feingold perhaps it's also a good time to come back to this issue when you are discussing "maintainer specialites" (see crosslink: https://github.com/bids-standard/bids-specification/pull/441#discussion_r402502689 )

**Comment by franklin-feingold** [comment]
yep! 

providing some context: I am beginning to expand our definition of a Maintainer. I am proposing to add a `specialty` to the role. This `specialty` can be viewed as a particular sub-domain of BIDS - a few examples can be overseeing a particular modality or feature of the community development efforts. This would give us the capability to nurture and credit more diverse contributions and build the Maintainers Group. A Maintainer can act outside of their `specialty` but their primary responsibility will be their specialty of choice.

**Comment by sappelhoff** [comment]
partially closed with https://github.com/bids-standard/bids-specification/pull/467 ... the [main doc for maintainers guidelines](https://docs.google.com/document/d/11U43QmYVZUVdCxpJeezmYpkHf4sbzWjjN2EIjbk4Pfo/edit) is not fixed and still in flux (although there haven't been any changes in a long time). It's now linked from the WIKI, so I am closing this issue and encourage all people to directly comment on the google doc or schedule to join the maintainers group biweekly meeting (contact Franklin or me).

**[BIDS-Maintainers-Documents](https://github.com/bids-standard/bids-specification/wiki/BIDS-Maintainers-Documents)**
