### ISSUE TITLE
Electrode anatomical area field for iEEG *_electrodes.tsv 

### ISSUE THREAD

**Issue by ezemikulan** [bids-standard/bids-specification#296]
I think it would be good to have an optional field to specify the anatomical area in which the electrodes are located, as extracted from Freesurfer for example. And maybe also another field to specify the atlas used (i.e. Destrieux vs Desikan-Killiany).

**Comment by sappelhoff** [comment]
Hi @ezemikulan, can you provide an example for your suggestion?

Let me tag some iEEG people:

@bids-standard/raw-electrophys-ieeg 

cc @choldgraf @dorahermes

**Comment by ezemikulan** [comment]
Sure,  *_electrodes.tsv would be something like this:

name | x | y | z | size | manufacturer | material | area
-- | -- | -- | -- | -- | -- | -- | --
K13 | 0.04532 | -0.01122 | 0.06966 | 7.5 | Dixi Medical | PtIr | ctx-rh-postcentral
N2 | 0.01348 | -0.02962 | 0.07457 | 7.5 | Dixi Medical | PtIr | ctx-rh-postcentral
N10 | 0.04132 | -0.03118 | 0.07672 | 7.5 | Dixi Medical | PtIr | ctx-rh-paracentral
S1 | 0.03478 | -0.00336 | 0.03974 | 7.5 | Dixi Medical | PtIr | ctx-rh-paracentral
S3 | 0.04176 | -0.00366 | 0.0411 | 7.5 | Dixi Medical | PtIr | ctx-rh-postcentral
S5 | 0.04865 | -0.00394 | 0.04232 | 7.5 | Dixi Medical | PtIr | ctx-rh-insula

and maybe a field in *_coordsystem.json that would be called _iEEGAnatomicalAtlas_ or something like that which would specify the atlas used, for instance: Destrieux Atlas (or the reference to the corresponding publication).

**Comment by robertoostenveld** [comment]
I think that this is possible with the current specification. The specification does not forbid the inclusion of additional columns, right?

There should in that case be a corresponding *_electrodes.json sidecar that defines the values in the "area" column. See https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#tabular-files

**Comment by ezemikulan** [comment]
Great, thanks, I thought that column names could only to be the REQUIRED, RECOMMENDED and OPTIONAL ones described in the specification.
