### ISSUE TITLE
Metadata for frame of reference

### ISSUE THREAD

**Issue by c42f** [bids-standard/bids-specification#308]
Hi BIDS people, thanks so much for making and maintaining this standard!

In a current project we are matching single voxel spectroscopy voxel locations against T1 weighted anatomical images for the purposes of [partial volume correction](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4849426/) of metabolite concentrations. This relies critically on having a shared frame of reference between the two acquisitions.

The dicom field [FrameOfReferenceUID](http://dicom.nema.org/medical/dicom/2016e/output/chtml/part03/sect_C.7.4.html) appears to be the correct metadata to hook onto here. The sticking point is that it contains potentially identifying information (a date and time, etc) but it would still be very useful to preserve in privately held bids formatted archives. (See also a [related dcm2niix discussion](https://www.nitrc.org/forum/message.php?msg_id=25278).

A reasonable solution which is adopted in the RSNA CTP Dicom Anonymizer is to [hash all UIDs](https://mircwiki.rsna.org/index.php?title=The_CTP_DICOM_Anonymizer#.40hashuid.28root.2CElementName.29). After hashing, the UIDs can still be compared to each other in order to associate images but no potentially identifying information remains.

It would be extremely helpful if the standard BIDS metadata could include an equivalent of FrameOfReferenceUID. Taking anoymization seriously, I'd suggest a cryptographic trap door function designed for resistance to brute force attacks rather than an extremely cheap hash like MD5. A key derivation function designed for hashing passwords might be appropriate; [Argon2](https://en.wikipedia.org/wiki/Argon2) for example.

CC @darrencl

**Comment by sappelhoff** [comment]
tagging @bids-standard/raw-mri because I am unfamiliar with this topic.
