### ISSUE TITLE
BEP 027: BIDS Execution

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#313]
This is an announcement of a BIDS Extension Proposal for BIDS Applications and execution descriptions. This BEP is intended to supersede the BIDS Apps paper (doi:[10.1371/journal.pcbi.1005209](https://doi.org/10.1371/journal.pcbi.1005209)) and build upon our experience over the last 3 years or so of application development and deployment.

I believe the next available BEP number is 27. If there are no objections, I will open a pull request adding this as BEP027.

* [BEP draft](https://docs.google.com/document/d/104HLZedFtx0TaXEUwd7eyWvJUlc0CcSUtCzwjNgmGxE/)

This document is a partial draft, with some need to flesh out some details, but I think the broad outlines of what we're trying to do are here and ready for broader comment.

**Comment by effigies** [comment]
/cc Co-moderator @gkiar and listed contributors @glatard @prioux.

Other commenters on the draft:

* @edickie 
* @jbpoline 

Also should probably just ping @bids-standard/everyone, what with this being an announcement and all. Will additionally announce on bids-discussion and Neurostars.

**Comment by sappelhoff** [comment]
Thanks @effigies, I am +1 for you to open a PR and adding this to our BEP list.

I am only wondering why we should call this "BIDS-Execution" instead of "BIDS-Apps 2.0", but see the comment on your BEP google doc.

**Comment by omar-rifai** [comment]
Hello @all, 

As part of improving traceability of our software, I'm looking to implement something similar to what is proposed in this BEP. Does anyone know if this proposal is still of interest and whether it is likely to be integrated in future specifications?

Cheers,

**Comment by effigies** [comment]
It is still of interest, but the amount of time I have to devote to it is very limited. Happy to help bring someone up to speed if they want to push on it.

**Comment by adelavega** [comment]
Omar, it is definitely still of interest, and I'd be happy to help as well. Maybe we should set a date to meet about this sometime this summer? I'm hopeful this BEP should not be quite as much work as StatsModels, but I also don't want to jinx it.

**Comment by francopestilli** [comment]
i wonder whether the work done around github.com/brainlife can be reused here @soichih, if it is we could perhaps put some cycles? @guiomar

**Comment by gkiar** [comment]
Hey all, I am in the same boat. Perhaps we could focus on this as an OHBM hackathon project? I don't think it takes a lot to get a coherent draft of this finalized, given the previous spec and already substantial integration of Boutiques, so having a few heads poking for a few days will go a long way.

**Comment by gkiar** [comment]
Hi again, I created a project for the OHBM hackathon (linked [here](https://github.com/ohbm/hackathon2021/issues/6)), so next week at the hackathon we can see who is around to make some progress on this.

**Comment by rob-luke** [comment]
Im interested in this BEP as I am starting to build projects around the bids-app idea for fNIRS data (see BEP030) and EEG. Are you planning that this BEP (execution) will be compatible with all BIDS modalities? If so, I'd be pleased to try and join for the hackathon (depending on timezone issues, Im in Australia).

**Comment by gkiar** [comment]
Hey @rob-luke — it'd be great to work with you on this! The goal of this BEP is not to be prescriptive to any one modality or domain within BIDS, but rather define a strict set of arguments which are deemed essential for any BIDS-related analysis, another which are universally relevant if not mandatory, and define the standard which will govern how these and any optional extensions are integrated such that apps are maximally inter-operable and interpretable. The form it is currently in is basically throwing the previously published spec in a blender with Boutiques, which provides a schema standard and some tools for validation.

**Comment by omar-rifai** [comment]
Great, thanks @gkiar for setting this up. I won't be able to join next week but probably someone from my team will.

**Comment by ghisvail** [comment]
@gkiar I'd be keen to sync with you all on this topic if that's ok. I work with @omar-rifai who cannot join this week unfortunately. What's the next time you are planning to meet?

**Comment by gkiar** [comment]
Hey @ghisvail, I think we'll follow the OHBM schedule and I'll give the pitch tomorrow afternoon, then we can schedule a time to sit down likely right after that (1-2ish, EST). If you join the mattermost, via the link shared [here](https://github.com/ohbm/hackathon2021/issues/6), we can coordinate more specifically then.

**Comment by sebastientourbier** [comment]
Hi @gkiar! Thanks to bring this back!
Happy to join the team during the OHBM hackathon!

**Comment by Remi-Gau** [comment]
This BEP has been 'merged' and the official spec can be found here: https://bids-standard.github.io/execution-spec/
