### ISSUE TITLE
metadata at wrong level ?!

### ISSUE THREAD

**Issue by jcolomb** [bids-standard/bids-specification#327]
Dear all, 
I am just starting with BIDS and this might be an obviously mislead issue, sorry if it is.

When thinking data management, I would like the data + metadata to be created along with the experience, and then the folder simply aggregated in a "data folder". This would have 2 consequence that do not work well with BIDS:

1. the unit of the experiment is the session, not the subject
2. metadata (like "participants.tsv") would be inside the session folder

One could make a work around and create some code moving folders and concatenating metadata files when time to archive the data has come, but I wonder if the specification should not allow that structure ??

**Comment by tyarkoni** [comment]
Hi @jcolomb,

I think this is a non-starter at this point, unfortunately. There are many legitimate arguments one could make for various structures other than the one BIDS ended up with, but at this point the present subject/session structure is baked into the spec, and adding flexibility at this level would run against the core design philosophy of keeping it simple.

One thing I would point you to if you haven't already seen it is [PyBIDS](https://github.com/bids-standard/pybids), which relieves you of having to care much about what the actual directory structure is like (at least once it's created) when you're working with BIDS files.

**Comment by sappelhoff** [comment]
> There are many legitimate arguments one could make for various structures other than the one BIDS ended up with, but at this point the present subject/session structure is baked into the spec, and adding flexibility at this level would run against the core design philosophy of keeping it simple

I completely agree with this.

**Comment by sappelhoff** [comment]
Closing this now, but thanks for your input @jcolomb and remember that backwards INcompatible proposals can always be made for BIDS 2.0 [in the bids 2.0 gdoc](https://docs.google.com/document/d/1LEgsMiisGDe1Gv-hBp1EcLmoz7AlKj6VYULUgDD3Zdw/edit?ts=5ec29f62#)
