### ISSUE TITLE
Whole brain reference image: How to name it?

### ISSUE THREAD

**Issue by dangom** [bids-standard/bids-specification#329]
It's common practice to acquire a whole brain EPI reference scan to aid the registration of limited FOV acquisitions. Currently, I don't see these mentioned in the spec.

I figured I could name them `sub-01_task-foo_wbref`, in analogy to the sbref images, but other alternatives came to mind:

- `sub-01_acq-wbref_bold` - ugly and generic, but would fit the spec as is
- `sub-01_acq-wbref_epi`, analogy to the reversed polarity epi's for dist. corr

Has anyone faced this issue before? I'd be happy to hear what your suggestions are.

**Comment by sappelhoff** [comment]
I have not faced this issue before, but if you have a solution that fits the spec as it is (albeit "ugly and generic"), that sounds good to me.

I am not an MRI expert myself, so let me tag some people who might have faced similar issues: @bids-standard/raw-mri-anat

**Comment by dangom** [comment]
I chose to keep the `sub-01_task-foo_wbref` variant, as I think the `_bold` suffix is too suggestive of an fMRI run, unlike this particular dataset. Look forward to see what others say. Thanks for your response!

**Comment by franklin-feingold** [comment]
@dangom by chance have you tested this implementation against [the validator](https://bids-standard.github.io/bids-validator/)? As you mentioned it is not defined in the specification so I have a sense the validator will flag it. Conforming to the standard - the epi case you defined appears to be close because it is a reference image and descriptive. I think this would be placed in the `fmap` directory

**Comment by dangom** [comment]
No, I haven't tested it against the validator. I don't think we have any tool out there yet that makes use of BIDS compliant whole-brain references. The dataset is definitely an anatomical reference, so I placed it in anat.

The epi name could work though. I'd be willing to adopt it if such a use case eventually made its way into the standard. I could also foresee a "IntendedFor" field in the sidecar json, for whole brain references that are distortion matched to the functional run.
