### ISSUE TITLE
make a "bids-maintenance" GitHub user, and let it do the automatic work

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#332]
> Speaking of `bids-maintenance`, that might be a more sensible user than Franklin for automatic commits to the main repository.

_Originally posted by @effigies in https://github.com/bids-standard/bids-validator/issues/781#issuecomment-528369499_

Over there, we discussed that it might make sense to create a new GitHub user called `bids-maintenance` which we can use to do tasks such as:

- automatic changelog commits (currently done via Franklin's account)
- making an entry on Zenodo for getting a citable DOI

The access to this account should be limited to BIDS maintainers.

**Comment by franklin-feingold** [comment]
+1

though, a blocking point is the Zenodo entry to get a citable DOI. This conversation is captured in https://github.com/bids-standard/bids-specification/issues/66

**Comment by sappelhoff** [comment]
Am I correct that currently the only "automatic" work is pushing the changelog entry?

On these lines: https://github.com/bids-standard/bids-specification/blob/c6037c563cd1a6a454fcd835f19cf34f33e8f1b4/.circleci/config.yml#L132-L134

@effigies @franklin-feingold

**Comment by effigies** [comment]
I think so, yes. We just need to change the `user.email` to the email associated with the bot user. The name is probably fine as-is.

**Comment by franklin-feingold** [comment]
yes I think so too - I think our automatic processes can be handled by Circle pretty well (and centralize where the automatic work is being processed)

**Comment by effigies** [comment]
I created @bids-maintenance.
