### ISSUE TITLE
Information regarding the BIDS governance and Steering Group elections

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#340]
We are quickly approaching our vote for ratifying our [BIDS governance document](https://docs.google.com/document/d/1R-J2lL9V_wIkYhye4zH-feyl4P4J8NyO40rIYyY141o/edit) and inaugurating our first BIDS Steering Group! Voting will commence on October 1 and run through October 15.

We will be using Google Forms as our platform for this first election. There will be two forms: one will be the vote and the other will be the verification. The forms have been created separately to dissociate contact information from voting information, and no attempt will be made to re-associate these data. Contact information will be used to ensure that the number of votes matches the number of voters, making fraudulent voting easier to detect. In the case of apparent fraud, the email addresses will be used to re-run the election on a platform that authenticates votes, instead of an open Google Form.

Under the Governance Document, an email list of Contributors must be maintained by the Steering Group. The verification form allows voters to opt-in to having their email retained for this purpose. All email addresses will be deleted immediately once the election results have been verified, with the exception of voters who opt to have their email address retained.

Ratification of the Governance Document is a mandatory vote, with “Yes” indicating approval of the document, and “No” indicating rejection. A simple majority of “Yes” votes will ratify the document. Failure to achieve a majority will nullify the election.

The Steering Group candidates are organized into slates. Slates are voted on according to a ranked ballot, **with the preferred slate ranked as “1”**, second choice as “2”, and so on. Votes will be tabulated according to the [instant-runoff](https://en.wikipedia.org/wiki/Instant-runoff_voting) method. A ballot will be considered invalid if multiple slates receive the same rank.

If you have any questions regarding this process please feel free to email Franklin (ffein@stanford.edu)

Thank you in advance for taking the time to vote!
Franklin

**Comment by emdupre** [comment]
Thank you, @franklin-feingold ! I'll assume you'll update us here once the google forms are available ?

**Comment by franklin-feingold** [comment]
voting has opened! more information in - https://github.com/bids-standard/bids-specification/issues/342
