### ISSUE TITLE
BIDS Governance and Steering Group voting has opened!

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#342]
The time has come to vote on our [BIDS Governance document](https://docs.google.com/document/d/1R-J2lL9V_wIkYhye4zH-feyl4P4J8NyO40rIYyY141o/edit?usp=sharing) and for the inaugural [Steering Group](https://docs.google.com/document/d/1yb6j3a90serWbtab7ukSMyecs16sGfYTSGftH-4ArvA/edit?usp=sharing)! Voting opens today (October 1) and runs through October 15, 2019, closing at 11:59pm Pacific Daylight Time (UTC -7). Votes will be recorded using a [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfG76N3dnazONsfCsWAXccgrizmb1gm233pJSow3TmTUi3_Fw/viewform) and a separate form for [email validation](https://docs.google.com/forms/d/1zr-w3M2K7ApaW3yePXNRc1zYMhIiDsOVnG15nJ1sgx4/edit) to make sure the vote is confirmed. The forms have been created separately to dissociate contact information from voting information, and no attempt will be made to re-associate these data. Contact information will be used to ensure that the number of votes matches the number of voters, making fraudulent voting easier to detect. The verification form allows voters to opt-in to having their email retained for this purpose. All email addresses will be deleted immediately once the election results have been verified, with the exception of voters who opt to have their email address retained.

Ratification of the Governance Document is a mandatory vote, with “Yes” indicating approval of the document, and “No” indicating rejection. A simple majority of “Yes” votes will ratify the document. Failure to achieve a majority will nullify the election.

Steering Group candidates are organized into slates of five candidates, and the winning slate will form the inaugural Steering Group. Slates are voted on according to a ranked ballot, with the preferred slate ranked as “1”, second choice as “2”, and so on. Votes will be tabulated according to the [instant-runoff](https://en.wikipedia.org/wiki/Instant-runoff_voting) method. A ballot will be considered invalid if multiple slates receive the same rank.

In addition, we are getting very close to finalizing our BIDS-Derivatives extension! We are looking for more feedback from community! The relevant conversations can be found in a [GitHub pull request](https://github.com/bids-standard/bids-specification/pull/265). This pull request has identified a few conversations left to reach a consensus before the final review! 

If you are interested in particular modalities in BIDS, we have established [teams on GitHub](https://github.com/bids-standard/bids-specification/issues/285) to more easily follow the conversations that are most relevant to you! We also have a [starter kit](https://github.com/bids-standard/bids-starter-kit) to help you get started using BIDS or finding ways to contribute to the effort!

If you have any questions regarding this process or BIDS please feel free to email Franklin (ffein@stanford.edu)

Thank you in advance for taking the time to vote!
Franklin

**Comment by KirstieJane** [comment]
Thanks @franklin-feingold!! Exciting times!

I was just chatting with a friend and she said it was hard to find the links to the slates in the google form. Would you mind adjusting the wording at the top of that form to make it a little clearer that you can find more information about the group members at the google doc? Something like, under the "Rank slates by preference" title add a description of "Short summaries of the proposed teams are available at [insert short link rather than whole link]".

I think it makes sense to also include the closing date on the google form if you can, just in case that's the link folks bookmark 😺

**Comment by emdupre** [comment]
> it was hard to find the links to the slates in the google form

:+1: on this -- not sure if it would be possible to create a bookmark to each group's statement and directly link next to their slate ? In addition to linking to the whole document at the top !

I'll admit I skimmed through the preamble and almost went to vote without realizing I had access to the statements :sweat_smile: Would be great to make this clearer, if possible !

**Comment by KirstieJane** [comment]
☝️ that was the friend 😉

**Comment by franklin-feingold** [comment]
Thank you @KirstieJane and @emdupre ! I have rephrased to make more clear where to find the proposed short summaries for each proposed Steering Group slate with the date the election is closed. 

> not sure if it would be possible to create a bookmark to each group's statement and directly link next to their slate ?

I tried doing this, but the text would get blown out and make the column bleed down the page. Hopefully with the 2 places at the top linking to the information will provide the locations and ease to have an understanding of each slates focus and making an informed vote :smiley:

**Comment by KirstieJane** [comment]
Sorry to be super picky. Can you move "Short summaries of the proposed slates are available at https://tinyurl.com/y37wk4zh" to the "description" of the question on the voting? Its still super easy to just skim over the "preamble" 😬

**Comment by franklin-feingold** [comment]
no worries - all set

**Comment by franklin-feingold** [comment]
@bids-standard/everyone - **Today is the last day** to vote for the [Steering Group](https://docs.google.com/document/d/1yb6j3a90serWbtab7ukSMyecs16sGfYTSGftH-4ArvA/edit) and [Governance document](https://docs.google.com/document/d/1R-J2lL9V_wIkYhye4zH-feyl4P4J8NyO40rIYyY141o/edit)! 
We are using a [Google form](https://docs.google.com/forms/d/e/1FAIpQLSfG76N3dnazONsfCsWAXccgrizmb1gm233pJSow3TmTUi3_Fw/viewform) to vote and an [email verification](https://docs.google.com/forms/d/1zr-w3M2K7ApaW3yePXNRc1zYMhIiDsOVnG15nJ1sgx4/edit) form to confirm the vote. 
Thank you for taking the time to vote!

**Comment by franklin-feingold** [comment]
results have been posted here: https://github.com/bids-standard/bids-specification/issues/355 !
