### ISSUE TITLE
requirement of channels.tsv is not consistent for MEG, EEG and iEEG

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-specification#344]
@bids-standard/raw-electrophys while looking at https://github.com/bids-standard/bids-examples/tree/master/ds000117 I noticed that to my surprise channels.tsv is missing. Subsequently I realized that according to https://bids-specification.readthedocs.io/en/stable/ it is RECOMMENDED for MEG (i.e. it SHOULD be there but it is not required and ds000117 is therefore compliant), whereas for EEG and iEEG it is not specified whether the channels file MUST, SHOULD or MAY be present. 

I had in my mind that it MUST be present. I have also been explaining it like that to EEG and iEEG folks (and probably also to MEG folks).

I consider it undesirable that the specification (for EEG and iEEG) is not explicit. Furthermore, I would consider it undesirable that the same file for the three electrophysiology specifications would have different requirements. What is your take on this?

**Comment by dorahermes** [comment]
+1 (I also had in my mind that _channels.tsv was required)

**Comment by teonbrooks** [comment]
agreed, I think that at the minimum it should be SHOULD for all three modalities. I would also agree and argue that it should be MUST for them as well.

**Comment by jasmainak** [comment]
sounds fair to me.

**Comment by CPernet** [comment]
+1 same for all three modalities
+1 for MUST channels.tsv (while electrodes.tsv can stay optional)

**Comment by robertoostenveld** [comment]
If we implement SHOULD for all, it would not break compatibility with existing datasets, but only loosen the requirement for MEG. 

If we implement MUST for all, we have to consider that there could be valid EEG and iEEG datasets out there without  channels.tsv. These existing datasets (either in public or private archives) do comply with BIDS v1.2.1 (or whatever number we are at right now). In this case we have to ensure that the validator still considers these older datasets as valid. I actually have no idea whether BIDS versioning is already part of the validator, I don't recall seeing it.   

Content wise I would prefer MUST, but realize that the amount of work for SHOULD is much more manageable.

**Comment by jasmainak** [comment]
>  I actually have no idea whether BIDS versioning is already part of the validator, I don't recall seeing it.

yeah unfortunately it is not :( There isn't a validator for every BIDS version that comes out.

hmm ... it's a bit weird that `channels.tsv` is missing for some datasets because the [regular expression rules for the validator](https://github.com/bids-standard/bids-validator/blob/392af3ca8c6a172c5e87b210c0b56ec45989d92d/bids-validator/bids_validator/rules/file_level_rules.json) seem to suggest that it is implemented similarly for all three modalities

**Comment by sappelhoff** [comment]
> Content wise I would prefer MUST, but realize that the amount of work for SHOULD is much more manageable.

I agree, +1 for a consistent SHOULD.
