### ISSUE TITLE
Guidelines for multiple desc fields for derivatives

### ISSUE THREAD

**Issue by ToeKneeFan** [bids-standard/bids-specification#351]
According to the BIDS 1.3.0-dev specification, the `desc` keyword should be used to distinguish between files.

> When necessary to distinguish two files, the `_desc-<label>` keyword-value should be used. This includes the cases of needing to distinguish both differing inputs and differing outputs (e.g., `_desc-T1w` and `_desc-T2w` to distinguish brain mask files derived from T1w and T2w images; or `_desc-sm4` and `_desc-sm8` to distinguish between outputs generated with two different levels of smoothing).

What should be done when multiple labels are appropriate in the desc field (and they don't fit into any approved keywords)? For example, both `desc-sm4` for smoothing and `desc-aparc` for parcellation? Are multiple `desc` fields allowed? (assuming that separating them into different data sets with different metadata files would not be desirable)

**Comment by sappelhoff** [comment]
Hi @AnonymousBoba - Multiple `desc` fields are not allowed.

Perhaps you can combine your desc parameters into something like `desc-sm4aparc`?

**Comment by AnonymousBoba** [comment]
@sappelhoff Thank you, that sounds like a sensible choice for parsing reasons. I was hoping to maintain some separation between the `desc` components, and I don't believe non-alphanumeric characters are allowed in labels, though I suppose I can try concatenation.

Perhaps allowing `+` or `-` would be helpful in these cases (https://github.com/bids-standard/bids-specification/issues/226).

Is the uniqueness of keywords explicitly stated in the BIDS specification? Or is it more implied?

**Comment by sappelhoff** [comment]
I see @yarikoptic being very happy about you bringing up #226 ;-)

I am not entirely sure whether (and where) we state that keywords must be unique - I'd have to search for it myself. Perhaps somebody else can chime in.
