### ISSUE TITLE
BIDS Steering Group election and Governance results

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#355]
We are excited to announce the winning slate of the BIDS election is the Guiomar Niso chaired slate with Melanie Ganz, Robert Oostenveld, Russ Poldrack, and Kirstie Whitaker! Congratulations to them and thank you to all the slates and voters for making this a successful election!  

Our winning slate represents multiple imaging modalities (MRI, MEG, EEG, iEEG, and PET) from around the world with several differing perspectives and expertise. The group members have been influential in pushing the BIDS Initiative initially and in extending BIDS into more imaging modalities. Their wealth of expertise will push BIDS forward into the derivative space, integrating across the modalities, sharing tools and apps, with a focus on reproducibility in the long-term. To learn more about this group please visit their [description page](https://drive.google.com/file/d/1mv_fOjeQbpAu6fVPKnTerXp-it6F59wi/view). We have also shared the [voter data and code](https://github.com/bids-standard/bids-specification/wiki/BIDS-Steering-Group-Election-data) used to determine the results. 

Please join me in Congratulating Guiomar, Melanie, Robert, Russ, and Kirstie!

We will be welcoming our Steering Group with our accepted [Governance document](https://docs.google.com/document/d/1R-J2lL9V_wIkYhye4zH-feyl4P4J8NyO40rIYyY141o/edit#)!

**Comment by sappelhoff** [comment]
Congratulations! :-)
