### ISSUE TITLE
Provenance enhancement for BIDS

### ISSUE THREAD

**Issue by satra** [bids-standard/bids-specification#368]
This has come up in many contexts around BIDS derivatives, but also in the context of several BIDS datatypes which require post-acquisition processing. 

https://docs.google.com/document/d/1vw3VNDof5cecv2PkFp7Lw_pNUTUo8-m8V4SIdtGJVKs/edit#

**Comment by satra** [comment]
there is an updated version of the document open for comments and suggestions.

**Comment by sappelhoff** [comment]
this is now discussed in https://github.com/bids-standard/bids-specification/pull/487
