### ISSUE TITLE
HowToAcknowledge not explicit in data type.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/bids-specification#372]
Text for the field in dataset_description.json in the current spec:

"OPTIONAL. Instructions how researchers using this dataset should acknowledge the original authors. This field can also be used to define a publication that should be cited in publications that use the dataset."

bids-standard/bids-validator#772 We had settled on the validator interpreting this field as a string. This breaks an example we have in bids-examples:
https://github.com/bids-standard/bids-examples/blob/master/ds000248/dataset_description.json#L10

Should a data type be added for this field, and should it be string, an array of strings, either a string or a an array of strings, or some other type.

From discussion with @effigies.

**Comment by effigies** [comment]
@bids-standard/raw

**Comment by sappelhoff** [comment]
the example you link to was prepared by me: I use an array of strings ... each entry in the array is one source to acknowledge.

I see that this is not very machine readable and that a simple string would be more straight forward. And a string would also be more in line with what is written in the [specification](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#dataset_descriptionjson).

**Comment by effigies** [comment]
Well, I don't hear a great clamoring for preserving lists, and if it's just the one example, clarifying that it should be a string makes sense to me.

At least three OpenNeuro datasets will be affected:

```
$ grep -rI '"HowToAcknowledge":\[' ds*/dataset_description.json
ds000222/dataset_description.json:{"Name":"Sequential Inference VBM","BIDSVersion":"1.0.0rc1","License":"PDDL","Authors":["Thomas H B FitzGerald","Dorothea Haemmerer","Karl J Friston","Shu-Chen Li","Raymond J Dolan"],"HowToAcknowledge":["Citation of FitzGerald et al. Sequential inference as a mode of cognition and its correlates in fronto-parietal and hippocampal brain regions. PLoS Computational Biology (2017)","This data was obtained from the OpenfMRI database. Its accession number is ds000222"]}
ds000235/dataset_description.json:{"Name":"Whole-brain background-suppressed pCASL MRI with 1D-accelerated 3D RARE Stack-Of-Spirals Readout- Dataset 2","BIDSVersion":"1.0.0rc1","License":"PD","Authors":["Marta Vidorreta","Ze Wang","Yulin V. Chang","Maria A. Fernandez-Seara","John A. Detre"],"Acknowledgements":"Tiejun Zhao","HowToAcknowledge":["We  are  grateful  to  Tiejun  Zhao  from  Siemens  Healthcare  for  his  valuable  help  in  the  implementation of the online reconstruction algorithm of the sequence for the Siemens platform.","This data was obtained from the OpenfMRI database. Its accession number is ds000235."],"Funding":"NIH grants no. P41EB015893 and MH080729, and NSFC grant no. 81471644, and Hangzhou Innovation Seed Fund"}
ds000236/dataset_description.json:{"Name":"Whole-brain background-suppressed pCASL MRI with 1D-accelerated 3D RARE Stack-Of-Spirals Readout- Dataset 3","BIDSVersion":"1.0.0rc1","License":"PD","Authors":["Marta Vidorreta","Ze Wang","Yulin V. Chang","Maria A. Fernandez-Seara","John A. Detre"],"Acknowledgements":"Tiejun Zhao","HowToAcknowledge":["We  are  grateful  to  Tiejun  Zhao  from  Siemens  Healthcare  for  his  valuable  help  in  the  implementation of the online reconstruction algorithm of the sequence for the Siemens platform.","This data was obtained from the OpenfMRI database. Its accession number is ds000236."],"Funding":"NIH grants no. P41EB015893 and MH080729, and NSFC grant no. 81471644, and Hangzhou Innovation Seed Fund"}
```

Each of these was OpenFMRI, so we can go in and manually fix them up.

**Comment by effigies** [comment]
Well, here's a case of us hitting this in the wild: https://neurostars.org/t/problem-uploading-dataset-to-openneuro-not-a-valid-bids-dataset-error/5532

**Comment by emdupre** [comment]
My 2c would be to enforce HowToAcknowledge as a string. It's intended to be added to human-centered documentation (manuscripts, etc), where having more than one sentence (as in all the linked cases) shouldn't be a hindrance, I'd think !

**Comment by teonbrooks** [comment]
I agree with @emdupre that we should enforce it as a string

**Comment by effigies** [comment]
Sounds like consensus. I'll update those datasets on OpenNeuro. Would somebody like to propose some clarifying language for the spec?

**Comment by sappelhoff** [comment]
> Would somebody like to propose some clarifying language for the spec?

```diff
- OPTIONAL. Instructions how researchers using this  dataset should
- acknowledge the original authors. This field can also be used to define
- a publication that should be cited in publications that use the dataset.
+ OPTIONAL. A string of text containing
+ instructions how researchers using this  dataset should
+ acknowledge the original authors. This field can also be used to define
+ a publication that should be cited in publications that use the dataset.




```

**Comment by effigies** [comment]
I was looking for other examples, and at least in [common derivatives](https://bids-specification.readthedocs.io/en/common-derivatives/05-derivatives/03-imaging.html), we state a type with:

```
REQUIRED. Boolean.
```

Would it work for people to specify types with:

```
OPTIONAL. String.
```

Or maybe:

```
OPTIONAL. `string`.
```

This would tie into @yarikoptic's suggestion in #350.

**Comment by sappelhoff** [comment]
I would be +1 to specify the expected variable type like I [commented before](https://github.com/bids-standard/bids-specification/issues/350#issuecomment-544443553):

> it'd be good to consistently advertise the expected data type in the spec and validate it.

**Comment by VisLab** [comment]
On a related note:  has there been any consideration of an optional field
in the description for IRB information or is this something that goes into
the How-to-Acknowledge?   Most journals require authors to provide IRB
information for any data that they use in a publication.

**Comment by sappelhoff** [comment]
We are now quickly running from one issue into three issues with this thread. Let's divide and conquer.

- @VisLab I have opened a new issue for your question: #379 
- regarding specification of datatypes, I suggest we continue discussion in #350 

as for **this** thread: It was about whether we want to accept STRING only for the `HowToAcknowledge` field ... and make this clear in both validator and spec.

So far, everybody has agreed that STRING would be good. I suggest to go ahead with this, make the adjustments, and close this issue (continuing the open points in their own issues as linked above).

**Comment by effigies** [comment]
Sounds good to me.
