### ISSUE TITLE
Request for feedback: Reorganizing the bids website

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#376]
The Steering Group has requested for community feedback an idea to organize the [bids website](https://bids.neuroimaging.io/). The proposal and conversation can be found on [NeuroStars](https://neurostars.org/t/request-for-feedback-reorganizing-bids-website/5476)

**Comment by robertoostenveld** [comment]
The website has been reimplemented. Thanks for the feedback (through the various channels)! Further improvements will still be made; comments and contributions are welcome on http://github.com/bids-standard/bids-website
