### ISSUE TITLE
Optional field for IRB information?

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#379]
Has there been any consideration of an optional field
in the description for IRB information or is this something that goes into
the How-to-Acknowledge?   Most journals require authors to provide IRB
information for any data that they use in a publication.

_Originally posted by @VisLab in https://github.com/bids-standard/bids-specification/issues/372#issuecomment-561865392_

**Comment by effigies** [comment]
The README file is completely free-form and seems an appropriate place to put IRB information. If there's a database of IRBs that might be linked to in a semantic-web sort of way, then a field in the JSON metadata makes sense.

**Comment by yarikoptic** [comment]
IMHO I think it might be worth considering free form value for a field in dataset_description.json . Special treatment could be done by tools if value found to be a URL or match some specific id pattern

**Comment by effigies** [comment]
Well, I can find a database of IRBs from the [US Dept of Health and Human Services](https://ohrp.cit.nih.gov/search/irbsearch.aspx), so a machine-parseable field seems reasonable. Also looks like terminology for [ethics committees](https://en.wikipedia.org/wiki/Ethics_committee) varies internationally, so a generic name might be better than IRB.

And is this meant to encode the committee itself, the committee-approved protocol or both?

**Comment by PeerHerholz** [comment]
+1 re a more generic name (based on experience from EU). 

I would vote for encoding both, thus only creating one additional field. The "how" is maybe not that straight forward though. What about something like `<committee>_<committee-approved_protocol_id>`?  The naming scheme of the committee would however be another thing as some are university-wide, some specific for an institute/department, etc. .

**Comment by satra** [comment]
this field should be allowed to be a list. many datasets comprise data collected under different IRB protocols.

**Comment by VisLab** [comment]
-1 for README

I am just going through the process of uploading a study to openNeuro.  The README's are a mixed bag, and curators are unlikely to think about IRB info unless they see a field for it. This information may not be easy to find after a few years.

**Comment by effigies** [comment]
@PeerHerholz 

> I would vote for encoding both, thus only creating one additional field. The "how" is maybe not that straight forward though. What about something like `<committee>_<committee-approved_protocol_id>`? The naming scheme of the committee would however be another thing as some are university-wide, some specific for an institute/department, etc. .

I would leave it free-form, and leave room for structured data. Then if schema.org standardizes how to describe ethics committees/protocols, we'll be able to accommodate direct inclusion of those objects.

**Comment by PeerHerholz** [comment]
Totally agree! How would one incorporate @satra's point? A list of `str`?

**Comment by effigies** [comment]
Can we just say a list, without specifying the content?

**Comment by PeerHerholz** [comment]
Would be fine with me, I have no strong opinions wrt this.

**Comment by VisLab** [comment]
Has any consensus been reached on this?  I think it is very important to have the provenance of the data if people are going to be able to use it in analysis publications.  Here is an example:

> Army Human Research Protections Office (Protocol ARL-20098-10051, ARL 12-040, and ARL 12-041) 

I think a string would be fine.  Every institution has their own format.

**Comment by sappelhoff** [comment]
Re-reading the thread it sounds like there is an agreement about adding a new OPTIONAL field to the `dataset_description.json`.

To move forward we need a dedicated person to make a concrete proposal in the form of a pull request to the specification.

This concrete proposal can then be further refined, explosed to the larger community, and eventually merged into the spec.

**Comment by effigies** [comment]
My impression is that response is positive and the concerns are:

1) Allowing multiple protocols.
2) Avoiding US-centric language
3) Not over-prescribing format

So I'd propose the following addition to `dataset_description.json`:

```Markdown
| ResearchProtocols | OPTIONAL. A list of research protocols approved by relevant ethics committees. |
```

And add to the example:

```YAML
{
  ...
  "ResearchProtocols": ["Army Human Research Protections Office (Protocol ARL-20098-10051, ARL 12-040, and ARL 12-041)"],
  ...
}
```

Open to an alternative if we want "Review" or "Ethics" to be more easily searchable. We can also list country-specific acronyms, such as IRB (USA), REC (UK), MREC (Netherlands), CPP (France), REB (Canada) and HREC (Australia) if that would be more helpful. (These are the ones available on [Ethics comittee](https://en.wikipedia.org/wiki/Ethics_committee).)

**Comment by satra** [comment]
@effigies - I would separate protocols from approvals. There can be another list of `"ResearchProtocols"` - a la protocols.io.  I think this should be made specific to `"EthicsApprovals"`

regarding country specific things, most people in the DOD sector use the term HRPO rather than IRB. so i would stay away from country-specific names.

**Comment by effigies** [comment]
Do we want to simultaneously add protocols then? Or separate proposals?

**Comment by VisLab** [comment]
I like the term "EthicsApprovals"   Can we just add that with a recommended string as argument.

**Comment by effigies** [comment]
Proposal at #412.
