### ISSUE TITLE
Duplicate "inheritance principle" section

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#38]
Not a big deal but I noticed there is a repeat of the `inheritance principle` section in the [intro ](https://github.com/bids-standard/bids-specification/blob/master/src/01-introduction.md) and the [common principles](https://github.com/bids-standard/bids-specification/blob/master/src/02-common-principles.md) parts.

Also I wonder if some sections of [intro ](https://github.com/bids-standard/bids-specification/blob/master/src/01-introduction.md) would not be better in [common principles](https://github.com/bids-standard/bids-specification/blob/master/src/02-common-principles.md).

e.g [definitions](https://github.com/bids-standard/bids-specification/blob/master/src/01-introduction.md#definitions), [compulsory/optional](https://github.com/bids-standard/bids-specification/blob/master/src/01-introduction.md#compulsory-optional-and-additional-data-and-metadata), [raw VS derived](https://github.com/bids-standard/bids-specification/blob/master/src/01-introduction.md#sourcevs-raw-vs-derived-data)

**Comment by chrisfilo** [comment]
Thanks for spotting. Next time please create one issue per suggestion. It makes managing the project easier.
