### ISSUE TITLE
OHBM 2020 - BIDS-Derivatives poster 

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#382]
@effigies is planning to submit an abstract to OHBM2020 for BIDS-Derivatives and inviting contributors to provide feedback and sign on as co-authors

More information can be found here: https://groups.google.com/d/msg/bids-discussion/2ti6ev7isX0/-hIYV_JQAQAJ

cc: @bids-standard/derivatives

**Comment by emdupre** [comment]
Thanks, @franklin-feingold and @effigies ! Do you think it would make sense to additionally ping everyone who attended the BIDS derivatives sprint last year ? Just to make sure they've seen this !
