### ISSUE TITLE
Valid letter characters for labels

### ISSUE THREAD

**Issue by apjanke** [bids-standard/bids-specification#385]
In the "Common principles" section, "Participant names and other labels", in v1.3.0-dev, it says this:

> BIDS uses custom user-defined labels in several situations (naming of participants, sessions, acquisition schemes, etc.) Labels are strings and MUST only consist of letters (lower or upper case) and/or numbers.

Should this specify what exactly is allowed as a "letter" or number here? That is, some filesystems support Unicode filenames and non-English scripts, or letters with accents etc. Should "letter" be restricted to the ASCII letters and numbers `[a-zA-Z0-9]`, or should any character of Unicode category Letter or Number be allowed?

I see that some other parts of the standard are explicit about exactly which letters are allowed in some places.

**Comment by robertoostenveld** [comment]
this relates to #226

**Comment by apjanke** [comment]
Oh, yep: seems to be covered pretty well starting at https://github.com/bids-standard/bids-specification/issues/226#issuecomment-548864804.

Closing as a duplicate of #226.
