### ISSUE TITLE
JSON data dictionary for TSV is not specific enough 

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-specification#387]
In https://github.com/bids-standard/bids-examples/issues/173 @apjanke identified that the format for the JSON data dictionary to accompany the TSV files is underspecified. The specification is at https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#tabular-files.

**Comment by sappelhoff** [comment]
You are referring to this part of the spec:

> Tabular files MAY be optionally accompanied by a simple data dictionary in a JSON format (see below). The data dictionaries MUST have the same name as their corresponding tabular files but with .json extensions. If a JSON file is provided, it MAY contain one or more fields describing the columns found in the TSV file (in addition to any other metadata one wishes to include that describe the file as a whole). Note that if a field name included in the JSON sidecar matches a column name in the TSV file, then that field MUST contain a description of the corresponding column, using an object containing the following fields: ...

The confusion is coming from the file: https://github.com/bids-standard/bids-examples/blob/master/eeg_face13/task-faceFO_events.json

which contains the following content:

```JSON
[]
```

which is in fact, a [valid JSON file](https://jsonlint.com/).

However, what we would expect from the BIDS perspective is a [JSON Object](https://www.w3schools.com/js/js_json_objects.asp).

So I would propose to clarify the spec with the following changes, ordered by sentence number in the cited paragraph above:

```diff
-Tabular files MAY be optionally accompanied by a simple data dictionary in a
-JSON format (see below).
+Tabular files MAY be optionally accompanied by a simple data dictionary
+in the form of a [JSON object](https://www.w3schools.com/js/js_json_objects.asp)
+within a JSON file.
```

```diff
-The data dictionaries MUST have the same name as their corresponding tabular files
-but with .json extensions.
+The JSON files containing the data dictionaries MUST have the same name as their
+corresponding tabular files but with `.json` extensions.
```

```diff
-If a JSON file is provided ...
+If a data dictionariy is provided ...
```

```diff
-Note that if a field name included in the JSON sidecar ...
+Note that if a field name included in the data dictionary ... 
```

**Comment by sappelhoff** [comment]
cc @robertoostenveld @apjanke to check my suggestion and to improve on it or accept it so that I can go ahead and make a pull request

**Comment by apjanke** [comment]
I like this new wording. It seems a lot clearer and unambiguous to me.
