### ISSUE TITLE
BIDS usage (Centers/Initiatives/Databases)

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#396]
BIDS is being implemented in several Centers, large-scale initiatives and databases around the world. It will be very useful to record this information (to later put on the website or a potentially more useful location)

To do this, I have started a [google sheet](https://docs.google.com/spreadsheets/d/1aySjPpEGGQwFcOavkQdcvk2t2UMXt_zoTzWLWUmq20M/edit#gid=0)

Thank you!

**Comment by sappelhoff** [comment]
Hey @franklin-feingold I am closing this now, because it's buried deep i the issues list and we can more easily re-post it as an announcement on mailing list, neurostars, or other channels.

feel free to re-open if you have other plans with this issue :)

**Comment by franklin-feingold** [comment]
yep that's fine - I want to think through how to better address capturing this information 👍
