### ISSUE TITLE
BIDS specification inconsistencies

### ISSUE THREAD

**Issue by civier** [bids-standard/bids-specification#399]
There is inconsistencies in the BIDS specification between the information here:
https://bids-specification.readthedocs.io/en/stable/
and here:
https://github.com/bids-standard/bids-starter-kit/wiki/The-BIDS-folder-hierarchy
For example, in the file name format for the fmap files.
The first source seems to be compatible with the validator included in fMRIprep, but why are they different?

**Comment by franklin-feingold** [comment]
answered on [NeuroStars](https://neurostars.org/t/inconsistant-bids-specification/5905)
