### ISSUE TITLE
Clarifications needed for EEG coordinate system

### ISSUE THREAD

**Issue by nbeliy** [bids-standard/bids-specification#416]
Dear BIDS experts,
 I'm a little bit confused about the naming of coordinates related files for https://bids-specification.readthedocs.io/en/v1.2.1/04-modality-specific-files/03-electroencephalography.html#coordinate-system-json-_coordsystemjson

For the data and the channels the template is 
```
sub-<label>[_ses-<label>]_task-<label>[_run-<index>]_eeg
```
But for the electrodes, the task entity is missing while acquisition appears:
```
[sub-<label>[_ses-<label>][_acq-<label>][_run-<index>]_electrodes
```
And for coordinates run disappears:
```
[sub-<label>[_ses-<label>][_acq-<label>]_coordsystem
```

Is this naming inconsistencies are intended, and what the reason behind it?

**Comment by sappelhoff** [comment]
If I remember correctly, the reasoning was as follows:

- A dataset and the channels recorded in this dataset can (do) differ task by task, a task label makes sense
- The **electrodes** used in a session and for a subject are independent of a task, because it is assumed that you do not apply new electrodes for a new task, thus: no task label
    - the **acquisition label** appears for use cases where two separate measurements of electrode coordinates are performed ... for example one before the recording and one afterwards --> `acq-pre`, `acq-post`
- The **coordinate system** used depends on the subject and session (and potentially acquisition, e.g., for the case where you digitize electrode coordinates with two devices, e.g. `acq-device1`, `acq-device2`) ... this is assumed to be independent of task, or run

What I currently cannot explain is why we permit a `run` label for the electrodes file name template. :thinking: 

cc @robertoostenveld

**Comment by robertoostenveld** [comment]
correct, electrodes (positions) and coordinates (in which they are expressed) are required to remain constant in a session. If not, then the data must be represented over multiple sessions (which can be on the same day). Also, if multiple EEG systems are being used in succession on the same subject (e.g. with dry electrodes), it should be represented in multiple sessions. 

Different sampling rates and/or filter settings of the amplifier can happen within a session, as (of course) multiple runs of the same task, or different tasks in different (EEG) files.

Electrode positions are (potentially noisy) measurements that can be done multiple times, hence the `acq` label. The coordinate system is a definition,  which only needs to be specified once. 

I also do not recall why there is an optional `run` label for electrodes. I do not see the use case for it. Looking in the draft [google doc](https://docs.google.com/document/d/1ArMZ9Y_quTKXC-jNXZksnedK2VHHoKP3HCeO5HPcgLE/edit#), I also don't see it there.

**Comment by robertoostenveld** [comment]
PS this question about the _use_ of BIDS would be better suited on https://neurostars.org/tags/bids or on https://groups.google.com/forum/#!forum/bids-discussion. This github repository is for the ongoing _development_ of the specification.

**Comment by robertoostenveld** [comment]
Dear Nikita,

if your question has been answered, could you please close this issue? If not, please feel free to ask a follow-up question.

thanks
Robert

**Comment by nbeliy** [comment]
I still confused,

1. coordinates:
  For a given session it is expected to maintain same coordinate system, so having template for coordinate `sub-xxx_ses_yyy` makes cense. But then @sappelhoff says that coordinates can change for two different devices, while @robertoostenveld says that different devices should be different sessions, and in this case usage of `acq` is not justified.

2. electrodes:
  So if I understand correctly, the electrodes measurements are considered as independent measurement from proper EEG

3. EEG data
  How, without `acq` distinguish two measurement within same session and with same task, but with different acquisition parameters (e.g. different sampling frequency or different task duration)? Putting it to run isn't transparent and can be confusing.

**Comment by sappelhoff** [comment]
Hi @nbeliy 

Regarding your first point:

> But then @sappelhoff says that coordinates can change for two different devices

I was making up an example, for which you *may* need the `acq` parameter for a **coordinates** file. 

This is what @robertoostenveld said:

> Electrode positions are (potentially noisy) measurements that can be done multiple times, hence the acq label. The coordinate system is a definition, which only needs to be specified once.

It is true that a coordinate system only **needs** to be specified once.

However in my **example**, a researcher for whatever reason decided to record the electrode positions (the same electrodes, in the same place, on the same subject, in the same session) **twice** with two different electrode-position-recording-systems. --> in such a case, you can use the `acq` parameter to couple some **electrodes** file 1 resulting from a recording of  electrode-position-recording-system1 with a **coordinates** file 1 ... and some **electrodes** file 2 resulting from a recording of  electrode-position-recording-system2 with a **coordinates** file 2


# point 2

> So if I understand correctly, the electrodes measurements are considered as independent measurement from proper EEG

Could you please clarify what you mean by this? What do you mean by proper EEG? 

Electrode measurements always relate to the electrodes **on** a subject **during** an EEG recording session.

# point 3

You could change the task label for tasks with a longer duration. E.g., `sub-XX_task-MyTaskShort` and `sub-XX_task-MyTaskLong`.

To see the reasoning for why we don't have an `acq` parameter for EEG files, please see the discussion in https://github.com/bids-standard/bids-specification/pull/198

specifically, please take a look at the draft table for that PR, which can be found here: https://docs.google.com/spreadsheets/d/1pYr8nigiJ6wm8cGaLjj2TsY-or8ELGcjAUXZifktd_4/edit#gid=0 --> the comment thread in Cell A 18 may be the explanation you are looking for.

**Comment by nbeliy** [comment]
Following disscussion in #198 and #188 I see clearer now. Will it be possible include part of it in documentation?

>Could you please clarify what you mean by this? What do you mean by proper EEG?

I meant that there no direct association in name between electrode positions and EEG data file. 
For ex. if I have 3 tasks in one session, and before each task I want to measure electrodes positions, I will not have direct 1-to-1 correspondance in electrodes and data files:
```
sub-xxx_acq-task2_electrodes.tsv
sub-xxx_task-task2_electrodes.tsv
sub-xxx_acq-task2_electrodes.tsv
sub-xxx_task-task2_electrodes.tsv
sub-xxx_acq-task3_electrodes.tsv
sub-xxx_task-task3_electrodes.tsv
```
Or, even more, If for each task I want to measure positions before and after? The `acq` will become `preTask1` and `postTask1`, moving likeness of the names even further apart. 
Should, in this case the `_electrodes.tsv` appear in `_scans.tsv`, like fmap in MRI?

**Comment by dorahermes** [comment]
I would agree with the suggestion from @robertoostenveld above, that the definition of a session assumes that the electrode positions are consistent within the session and if electrodes are moved a different session should be created. 

You can add a FAQ in the [bids-starter-kit](https://github.com/bids-standard/bids-starter-kit/wiki/FAQ) if you think this requires clarification.

**Comment by satra** [comment]
@dorahermes - it may be useful to clarify if this is specifically in the notion of a session in EEG, or more generally.  for example, in MRI, we consider a session a **logical session**. thus if a person is taken out of the scanner and put back in, while all kinds of references change, it would still be considered the same session. in fact it was argued and agreed that if a person came on day1 to do a set of scans, could not finish and came on day2 to complete, that would be considered a single session. but there is a lot of flexibility around the notion of a session when original bids was developed.

**Comment by robertoostenveld** [comment]
> I meant that there no direct association in name between electrode positions and EEG data file.

The direct association is that the electrodes file is in the same directory as the EEG data, and that it has the same `sub` and `ses`.

**Comment by nbeliy** [comment]
> The direct association is that the electrodes file is in the same directory as the EEG data, and that it has the same sub and ses.

For me , it's more an indirect association. But I got answers on my questions, so I close the issue.
I think the clarifications on the interpretation of session and acquisition specific to EEG must appear on EEG page.

**Comment by robertoostenveld** [comment]
further clarification of the specification is always welcome, feel free to do a pull request.
