### ISSUE TITLE
[INFRA] use github issue templates

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-specification#418]
We sometimes get questions about the _use_ of BIDS through the issues section of this repository. I feel that those are better directed to another channel, where non-developers can contribute and where knowledge remains more visibly accessible. 

How about setting up [issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) to direct people to the most appropriate place for support?  

I have just tried that myself in a sandbox repository, see https://github.com/fieldtrip/playground/issues

**Comment by sappelhoff** [comment]
I think that's a good idea!

**Comment by effigies** [comment]
Yes, particularly the redirections to other places seems valuable.
