### ISSUE TITLE
Need to clarify BESA coordinates in EEG section

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#420]
One of the restricted keywords for EEG coordinate systems is `BESA`:

https://bids-specification.readthedocs.io/en/stable/99-appendices/08-coordinate-systems.html#eeg-specific-coordinate-systems

The way this keyword is currently described is ambiguous, and it seems to suggest that the BESA keyword refers to an idealized, spherical coordinate system instead of a measured coordinate system (which will in practice never be on a sphere).

The link further describing BESA (see [here](http://wiki.besa.de/index.php?title=Electrodes_and_Surface_Locations#Coordinate_systems)) is furthermore ambiguously referring to three different coordinate systems:

- "device" (this coordinate system is irrelevant for us)
- "head" (this coordinate system is identical with another keyword we have: `Captrak`)
- "besa" (the spherical model we are also referring to in the spec text)

This situation should be resolved for the following reasons:

1. BIDS is about data, not copying templates --> we want to share measured electrode positions, not positions that are computed (simulated) on a sphere. Such position templates can be supplied by the analysis software.
1. Even assuming the case that BESA was unambiguously referring to the "head" coordinate system, we'd have a duplicate with the `Captrak` keyword

This error was brought to @robertoostenveld and my attention in a recent talk with @kucint and brain products.

---

For a fix, it'd be great to just delete the BESA keyword. Unfortunately, that change is **not backward compatible**.

The alternative is to write clarifying text and add it to the spec (and remove all ambiguity).

Dear EEG and BIDS people, hat are your opinions on this situation and potential solutions? 

--- 

Furthermore, the clarifications for `Captrak` should be extended as well, currently we are only referring to that information on the [fieldtrip](http://www.fieldtriptoolbox.org/faq/how_are_the_different_head_and_mri_coordinate_systems_defined/#details-of-the-captrak-coordinate-system) site.

**Comment by jasmainak** [comment]
how many datasets on openneuro actually use this coordinate system? I would consider it a "bugfix", so perhaps backward compatibility is not necessary as long as not too many datasets are impacted.

**Comment by sappelhoff** [comment]
I manually searched all datasets on OpenNeuro that have EEG data and checked if they have a `*coordsystem.json` for the EEG modality.

These are the datasets I could find:
- https://openneuro.org/datasets/ds002691/versions/1.0.0
- https://openneuro.org/datasets/ds002680/versions/1.0.0 
- https://openneuro.org/datasets/ds002578/versions/1.0.0
- https://openneuro.org/datasets/ds002218/versions/2.0.0
- https://openneuro.org/datasets/ds001971/versions/1.1.1
- https://openneuro.org/datasets/ds002718/versions/1.0.0
- https://openneuro.org/datasets/ds002662/versions/1.0.0

interestingly, none of them have a *valid* `*coordsystem.json` for EEG, because they are all using `ARS` for the `EEGCoordinateSystem`, which is *not* one the [list of restricted keywords for EEG](https://bids-specification.readthedocs.io/en/stable/99-appendices/08-coordinate-systems.html#eeg-specific-coordinate-systems).

cc @robertoostenveld 

I see this as evidence that we should do two things:
1. remove BESA as a bugfix ... not backward compatible, but it didn't make sense in the first place, so I don't think anyone used it
1. make `bids-validator` more carefully check the `EEGCoordinateSystem` field:
    1. Accept only `captrak` or `other`
    1. if `other` is specified, enforce that `EEGCoordinateSystemDescription` contains information
