### ISSUE TITLE
BEP030: Extend BIDS to add near-infrared spectroscopy (NIRS)  

### ISSUE THREAD

**Issue by rob-luke** [bids-standard/bids-specification#438]
I would like to propose extending BIDS to include near-infrared spectroscopy (NIRS) .

I have taken a look at the [currently-active BEPs](https://bids.neuroimaging.io/get_involved.html) and could not see anything NIRS related. Is there already support for NIRS? And if not, is there sufficient interest for me to start a proposal?

**Comment by sappelhoff** [comment]
Thanks for opening the issue Robert. I think NIRS support in BIDS would be great. There is already a similar initivative in the NIRS community: https://github.com/fNIRS/snirf

I am not sure in how far BIDS and SNIRF are parallel or whether they could be joined.

It'd be great to discuss this with the NIRS community and SNIRF developers!

**Comment by rob-luke** [comment]
Thanks Stefan, I was unaware of SNIRF. It seems very well specified.

**Comment by lpollonini** [comment]
Coincidentally, my collaborative group has been discussing this for the last few weeks, so I definitely second Robert's proposal and will be interested in actively participating. Please let me know the next steps, thanks!

**Comment by rob-luke** [comment]
Thats great news @lpollonini. There is a [BIDS extension proposal guide](https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/edit), and a [BIDS extension template](https://docs.google.com/document/d/1W7--Mf3gCCb1mVfhsoRJCAKFhmf2umG1PFkyZ1jEgMw/edit#heading=h.4k1noo90gelw). I am happy to make a start on the proposal document and put it online for us to edit/comment (I will post link in this thread). And in the meantime try and get a few more people interested. @lpollonini is this plan ok with you?

@sappelhoff is this the usual way to proceed? Whats the simplest/cleanest BEP that you would recommend I take a look at to get started?

**Comment by lpollonini** [comment]
Sounds good to me, Robert.
I will wait for Stefan to educate us on the process (or anything we are missing), and then we can start coordinating the effort.

**Comment by sappelhoff** [comment]
Hi @rob-luke and @lpollonini, indeed what you suggest sounds like a good workflow. Let me add to that:

1. as a starting point, please read the [governance](https://bids.neuroimaging.io/governance.html) document (it's not too long), specifically the parts relating to a BIDS Extension Proposal (BEP)
1. use the two documents you linked for more guidance
1. get as many people interested as possible, forming a core team and a team of people to review regularly and provide opinions

In addition, I think it'd also be cool to start this off with a short call, where everybody can explain their backgrounds / motivations, and ask open questions that are not easily addressed in our docs. I would leave organizing that call to you (we could find a suitable date via email, and then post the decision here for more interested people to join).

As current example BEPs I recommend:
- [PET](https://docs.google.com/document/d/1mqMLnxVdLwZjDd4ZiWFqjEAmOmfcModA_R535v3eQs0/)
- [ALS](https://docs.google.com/document/d/15tnn5F10KpgHypaQJNNGiNKsni9035GtDqJzWqkkP6c/)

@franklin-feingold @effigies did I forget some crucial hints?

**Comment by robertoostenveld** [comment]
Hi @rob-luke and others

Last week we were meant to have a relatively small fNIRS toolkit course at the Donders, similar to these https://www.ru.nl/donders/agenda/donders-tool-kits/. This would be the first fNIRS toolkit for us, but we might make it into a yearly event. However, given the current situation the fNIRS toolkit has been postponed for now. 

In this fNIRS toolkit course, I was to present on precisely BIDS and NIRS. I have just posted my slides online, see [The Brain Imaging Data Structure and its use for fNIRS](https://www.slideshare.net/RobertOostenveld/the-brain-imaging-data-structure-and-its-use-for-fnirs). I had planned to discuss how BIDS relates to SNIRF (which I consider perfectly compatible) and to propose "BEM028"? as BIDS for NIRS.

**Comment by robertoostenveld** [comment]
From my perspective related to this are https://github.com/fieldtrip/fieldtrip/issues/1161, https://github.com/fieldtrip/fieldtrip/blob/master/data2bids.m (which includes some preliminary NIRS support) and documentations and examples that we have at http://www.fieldtriptoolbox.org/example/bids/ (no NIRS example yet, but that could be added). With @helenacockx we just finished the first draft fNIRS dataset in BIDS format.

**Comment by rob-luke** [comment]
Hi @robertoostenveld,

It seems this issue came at a good time for all of us then. I am definitely on the same page as the slides you linked. How do you feel about the plan that Stefan proposed? Should I try and organise a call via email for the people in this thread? And in the meantime we see who else is interested. Or are you much further along this process?

**Comment by robertoostenveld** [comment]
Yes, please follow the plan that @sappelhoff outlined. I.e. get multiple people with different backgrounds (i.e. different labs/systems, but also acquainted with different softwares) involved, and get them to converge using a google doc.

**Comment by lpollonini** [comment]
I agree with everything, and will start reach out to people who may be interested in joining in. How long we should give ourselves to form ideas and schedule the introductory call? Would 10-14 days be acceptable  considering the current situation (people doing lots of online teaching./mentoring, dissertation defenses coming up, etc.)? Maybe sooner? Thanks!

**Comment by robertoostenveld** [comment]
Planning it within 2 weeks sounds acceptable to me. Also, people that might miss out on the first online meeting should be able to join the process later. The first meeting would be more on setting goals and agreeing on a style of working, than on tossing arguments around and deciding.

**Comment by robertoostenveld** [comment]
April 9 works for me, April 10 is Good Friday, which for me (and I suspect a lot of people) is a day off. Although week and weekend-days are now more similar while working at home, I think we should respect holidays if possible.

**Comment by lpollonini** [comment]
I agree, and I apologize. Good Friday was not marked on my calendar.
April 9th is good for me.

**Comment by sappelhoff** [comment]
9th of April 2pm Berlin time sounds good to me :+1:

**Comment by lpollonini** [comment]
Is there a preferred meeting platform that BEP people have been using successfully?
I would like to share this thread with the fNIRS community at large (500+ SfNIRS members and 1,300 on the Facebook group) and even if a small fraction will participate, we want to make sure the e-meeting remains manageable.

**Comment by rob-luke** [comment]
9th of April is good for me too.

I have created a zoom call that anyone can join with details below (no account required by attendees). But happy to use another platform if people prefer. I am also happy to take minutes for the meeting / record the session.

```
Time: Apr 9, 2020 10:00 PM Australia/Melbourne 
Join from a PC, Mac, iPad, iPhone or Android device: 
    Please click this URL to start or join: https://macquarie.zoom.us/j/338374702
 
Join from dial-in phone line: 
    Dial: +61 2 8015 2088
    Meeting ID: 338 374 702 
    International numbers available: https://macquarie.zoom.us/u/acPY47YGNU 

Join from a H.323/SIP room system: 
    Dial: 61262227588
    or SIP:7588@aarnet.edu.au
    or H323: 338 374 702@182.255.112.21  (From Cisco)
    or H323:182.255.112.21## 338 374 702  (From LifeSize or Polycom)
    or 162.255.36.11 or 162.255.37.11 

    Meeting ID: 338 374 702
```

**Comment by rob-luke** [comment]
@hamishib you may be interested in this.

**Comment by hamishib** [comment]
Great initiative @rob-luke, I will join the Zoom and see if I can contribute :)

**Comment by robertoostenveld** [comment]
As I am always confused with time zone differences (and even more so around daylight savings time changes), I scheduled it on  [arewemeetingyet](https://arewemeetingyet.com/Melbourne/2020-04-09/22:00/Extend%20BIDS%20to%20add%20near-infrared%20spectroscopy#eyJ1cmwiOiJodHRwczovL21hY3F1YXJpZS56b29tLnVzL2ovMzM4Mzc0NzAyIn0=)  to shows the meeting in everyones own timezone.

**Comment by sappelhoff** [comment]
hehe. Good call @robertoostenveld it seems that @rob-luke scheduled the meeting for a different time than @lpollonini proposed in https://github.com/bids-standard/bids-specification/issues/438#issuecomment-606000873

the arewemeetingyet link tells me that we meet at 10:00 (am!) UTC + 10 ... which would be 22:00 in Berlin ... would still be borderline okay with me. But just a heads up that this might be a confusion.

**Comment by robertoostenveld** [comment]
hmm, the confusion apparently is not yet gone. This is what I see 
![Screenshot 2020-03-31 at 10 53 02](https://user-images.githubusercontent.com/899043/78006903-e1665200-733d-11ea-8daf-e33f5396e092.png) which is 14:00 in Central Europe Time. That works for me.

**Comment by rob-luke** [comment]
> which is 14:00 in Central Europe Time

Isn't that what was proposed above? The call is scheduled for 10pm Aus time, which I checked was 2pm EU and 7am Houston. How did you get 10am Berlin time?

**Comment by sappelhoff** [comment]
okay, I just misread the output :man_shrugging: I was confused by the time underneath the "For your calendar" heading.

So everything is fine, sorry :-)

**Comment by rob-luke** [comment]
Ok cool. But I am open to other suggestions too. Taking calls at odd hours comes with the territory when you live upside down.

**Comment by rob-luke** [comment]
@robquant this might be of interest to you too.

**Comment by robquant** [comment]
@rob-luke Thanks for the hint!

**Comment by rob-luke** [comment]
It was nice to meet everyone on the call.

I can create the draft google doc based on the BIDS spec template tomorrow and email around a link. Did anyone record who put there hands up to be in the smaller committee? If we gather those emails I can set the write access permissions. Then we can also discuss a preferred method of communication.

My email is robert.luke@mq.edu.au

**Comment by lpollonini** [comment]
Thanks Robert, I just started an e-mail thread...

**Comment by manipulative** [comment]
waiting for good news from you guys!

**Comment by lpollonini** [comment]
Hello @manipulative, we have formed a core working group as a result of the initial meeting and we'll be posting he a link to the BEP draft (as soon as ready) for anyone to comment on.

**Comment by manipulative** [comment]
Hi @lpollonini , I do some hyperscanning researches by fNIRS. Thanks for your contribution to bids of fnirs!

**Comment by robertoostenveld** [comment]
Hi @lpollonini is there already a google doc online with a draft that I (and others) can read and/or contribute our ideas to?

**Comment by rob-luke** [comment]
Yes. We have a google doc. I can open access and post here tomorrow.

**Comment by rob-luke** [comment]
Unless one of the others with access does it before then

**Comment by robertoostenveld** [comment]
I propose to share it such that others (i.e. people that do not explicitly have permissions) can only make suggestions. That ensures that the BEP leads keep in charge of all the edits and are aware of all changes to the actual text.

**Comment by manipulative** [comment]
Also want to view and comment it too

**Comment by rob-luke** [comment]
The document can be found [here](https://docs.google.com/document/d/1FzPt7TVpIAtlhrF9_9b2VBCZOrRXJASEMyHndhDQKl8/edit?usp=sharing).

I have set the access to public with only ability to add comments (I think, see figure below). If anyone has issues accessing please comment in this thread and we can address it.

![image](https://user-images.githubusercontent.com/748691/80574718-b27af300-8a45-11ea-886b-b7de4e4e8c3d.png)

**Comment by sappelhoff** [comment]
This BEP is now official: BEP030, see: https://github.com/bids-standard/bids-website/pull/123

**Comment by rob-luke** [comment]
The BEP has had some attention lately. I will now create an example dataset according to the current specification.

Now would be a good time to collect some edits/reviews/comments on the document if anyone is available or can share the link... https://bids.neuroimaging.io/bep030 

I am particularly interested to gather comments from users of different NIRS types and vendors than I have experience with (e.g. frequency domain NIRS devices).

**Comment by rob-luke** [comment]
Brief update:

* The BEP is shaping up nicely and has recently had many changes and comments resolved.
* A call for public review will be made in the society for fNIRS April newsletter.
* A pre-review by the experts in this conversation would be appreciated before the public call.
* Please unresolve any comments you think were prematurely closed.
