### ISSUE TITLE
BEP029: Extend BIDS to add motion capture and movement data

### ISSUE THREAD

**Issue by sjeung** [bids-standard/bids-specification#443]
Hi, I would like to start extending BIDS to cover movement data, including live motion capture as well as virtual transform data. I have [asked around on ResearchGate](https://www.researchgate.net/post/Interest_in_extending_Brain_Imaging_Data_Structure_BIDS_spec_to_motion_data) and a couple of other threads to see if there is ongoing work along the line and have not identified any yet- Here is the Google Doc for the proposal as a starting point. We would like to converge more opinions and contribution from anyone interested : https://docs.google.com/document/d/1iaaLKgWjK5pcISD1MVxHKexB3PZWfE2aAC5HF_pCZWo/edit?usp=sharing

**Comment by effigies** [comment]
In BIDS-Derivatives, we have some basic [Motion-related time series](https://bids-specification.readthedocs.io/en/derivatives/05-derivatives/05-functional-derivatives.html#motion-related-time-series). To the extent that we're describing similar things, common formats and naming conventions would be good to settle on.

**Comment by sjeung** [comment]
@effigies Hi, thanks for pointing me to it! This indeed covers some of the important aspects in movement data specs. This also can be another motivation for us to call it BIDS-motion instead of BIDS-move. Matching the formats, we can try labeling channels with "type_component" like in "trans_x" and "rot_x". I have one question regarding the time series here - is the translation time series representing translation between frames or is it always from a fixed reference point? If latter is the case, we may as well consider replacing the concepts "position" and "orientation" in the current spec with "translation" and "rotation".

**Comment by effigies** [comment]
Fixed reference is what I've always seen, but if there's a situation where it's done framewise, we can either come up with a new name or add a metadata field to disambiguate.

**Comment by robertoostenveld** [comment]
I think this is also interesting for @helenacockx

**Comment by robertoostenveld** [comment]
At the Donders we have looked at BIDS for movement data, and converted some example datasets to a BIDS-like format. Those can be found on http://www.fieldtriptoolbox.org/example/bids_motion/. We now also have some inhouse XSens datasets in a BIDS-like organization (combined with NIRS), but the format is still preliminary.

**Comment by robertoostenveld** [comment]
The actual example is on ftp://ftp.fieldtriptoolbox.org/pub/fieldtrip/example/bids_motion (currently only one, the other is still locally on my computer but could be shared if people are interested).

**Comment by sjeung** [comment]
Hello @robertoostenveld and @helenacockx, it was very nice seeing you in the NIRS meeting. And thanks, I saw the example data set and the style we are aiming for in BIDS-move (or motion) will be pretty much like that with just some more specifications. This relates to one of my biggest question at the moment - do you think this specification deserves an extension of its own or can be an addition to the existing continuous data specs for physiological and other continuous recordings?
Either way, my impression after the meeting was that we would first have to identify more people who are interested. Now that we have a GoogleDoc set up I will start sending around the link to the doc and this thread. MoBI conference 2020 would have been a great opportunity for that, but unfortunately it's the special year...

**Comment by helenacockx** [comment]
Hi sjeung. Indeed very nice to meet! As far as I understand, you could indeed add the motion data as another recording of continuous physiological data. However, I think that it would be very valuable if motion data could stand on its own. I am indeed working with motion data from xsens (synchronuously with nirs and video data) and trying to put the whole dataset in a BIDS-like format. The motion tracking system of Xsens that I am using consist of 17 IMU's attached to different body parts (see https://www.xsens.com/products/mvn-analyze). If you are interested to know more about this system and how data is saved, please let me know and I would be happy to help!

**Comment by sjeung** [comment]
@helenacockx great! I would definitely like to know more about your set-up, especially the time synchronization aspect and axes definition. 
Me and @timo-berg will start converting a data set from MoBI.set (eeglab + mobilab plugin) to a pseudo-BIDS format as a starting point, but the raw data is in .xdf recorded through LabStreamingLayer (streamed from BrainVision recorder and Unity). The current specs on GoogleDoc is largely based on our experience from that setup, so we need to converge more information on different recording systems. We are also trying to find co-leads and contributors, so simply let us know if you'd like to be onboard.

**Comment by sjeung** [comment]
@effigies Perhaps we can distinguish position/orientation (measured from a fixed reference) and translation/rotation (measured with respect to an updating reference frame-by-frame). I am still looking for other parts of BIDS where these spatial quantities are defined and trying to see how to maintain consistency, so if this convention of calling them translation/rotation is well-established, BIDS-motion would also call it translation/rotation, clarifying that this is assumed to be with respect to a fixed reference, then give users an option to specify framewise updates.

**Comment by helenacockx** [comment]
If you would like that, we can schedule a meeting and I can explain to you our experimental set-up. I am not sure whether I would be experienced enough to contribute to the BIDS-move since my main focus is fnirs data, but we could discuss this during a meeting as well.

**Comment by sjeung** [comment]
@helenacockx Sure, it will be much appreciated. How about next week? In case there is anyone else in your group who is interested, they are welcome to join as well. As for time, any other days than Monday and Wednesday work for me. If the meeting will be just one-to-one or rather small, I suggest we use Skype.

**Comment by melanieganz** [comment]
Dear all, sorry for jumping in late. I have a very basic question, what kind of motion capture are you thinking about here? This is not completely clear to me. I also use an external motion correction device for MR and would like to join if you have a meting.

**Comment by sjeung** [comment]
Hello @melanieganz, the proposal was originally motivated by live motion capture data recorded during physical motion in mobile EEG recording, by means of trackers or optical markers. But I believe the specifications are eventually generalizable to any type of time series representing positions or orientations. In motion correction in MR context, there are specifications as Chris @effigies has linked above: https://bids-specification.readthedocs.io/en/derivatives/05-derivatives/05-functional-derivatives.html#motion-related-time-series. If your data set requires additional specifications, then the meeting could be relevant for you as well. The goal of the meeting that I have in mind is to talk about different setups and how the raw data are represented.

**Comment by robertoostenveld** [comment]
Hi @melanieganz, you should think about systems like https://www.vicon.com, https://www.xsens.com, https://www.qualisys.com, https://polhemus.com, but possibly also https://en.wikipedia.org/wiki/Kinect. I.e. the primary goal is to capture position or motion (=position over time) and the primary data comprises the position, or the acceleration/gyroscope/magnetometer data, or similar. 

Secondary data measured in the same experiment might be video, audio, or physiology (e.g. EEG or NIRS), but those would fall in their own section of the specification (since they could also be recorded by themselves).

**Comment by JuliusWelzel** [comment]
Hey everyone,

@robertoostenveld , thanks for the invite. Great join the development about this important BIDS extension. 
I am currently based in Kiel, Germany where so far we only did motion capture in big clinical cohorts focusing on IMU data, future studies will include EEG as well. We are currently working on a universal placing/coordinate layout for IMUs, which we hope makes IMU data more comparable across datasets..

**Comment by robertoostenveld** [comment]
FYI I have extended the http://www.fieldtriptoolbox.org/example/bids_motion/ example page; it now has XSens, Qualisys and Optotrak examples. The file formats for bids definitely need to be discussed, as well as the metadata in the json and channels.tsv, which is currently very limited in my draft examples.

**Comment by sjeung** [comment]
Hello @JuliusWelzel.  I am very happy to hear that you are interested. So far not too much thought has been put into how to describe the placing of the trackers and we definitely need more research in that regard. We are still looking for co-leads and contributors who work with motion data. Please have a look at the GoogleDoc linked at the top of this thread and jump in where you think should be complemented.

**Comment by sjeung** [comment]
@robertoostenveld Great! I myself haven't worked with the systems listed, so ideally we would find someone who is experienced with each of them. But I can start looking into how interpretable they are as it is now.

**Comment by sappelhoff** [comment]
This BEP is now official: BEP029, see: https://github.com/bids-standard/bids-website/pull/123

**Comment by sjeung** [comment]
Hi everyone, after a while of blank period from my side in the past month or so, I am looking forward to gaining more momentum for bids-motion by circulating this community survey. It would be great if you can copy, paste, share, spread, RT, like, spam, and so on. https://forms.gle/2hGzDUnberPAgNCB6

**Comment by robertoostenveld** [comment]
I have posted a request for people to fill out the questionnaire on the FieldTrip mailing list, see https://mailman.science.ru.nl/pipermail/fieldtrip/2020-July/040178.html

**Comment by sappelhoff** [comment]
I will retweet and spread with the Bids-standard Twitter account :+1:

**Comment by sjeung** [comment]
Thank you so much @sappelhoff @robertoostenveld. Me and @JuliusWelzel are planning a Skype call on the 18th of August to discuss interim results of the survey. In case you are interested and have time to join, please let us know (we can also move the meeting to the 20th or the 21st depending on your schedule). 

The main issues will be the raw data format and the possibility of incorporating time stamps. Although the discussion around time stamp stream is not exactly about motion data, it is frequently recorded together with motion data and people seem to find it useful.  At the moment we are investigating how helpful time stamps are compared to time synchronization method introduced in http://www.fieldtriptoolbox.org/example/bids_pom/, in two example studies from different labs.

**Comment by JuliusWelzel** [comment]
Protocol from the call on Tuesday (25.08.2020)
[BIDS_BEP_029_TC.pdf](https://github.com/bids-standard/bids-specification/files/5137355/BIDS_BEP_029_TC.pdf)

**Comment by arnodelorme** [comment]
Sein Jueng, Klaus Grumman, Clement Lee, Markus, and Arnaud Delorme met to discuss this topic today. As for eye tracking, the main issue with motion capture data remains synchronization of different data streams.

To move forward, we plan to create a synchronization timestamp .tsv file in BIDS that reflects XDF synchronization mechanisms (ping time every 5 seconds to sync streams). Once this is done, we can reconvene to discuss the usefulness of these files.

The goal is to 

- Generate template BIDS dataset on Github with
	- EEG data
	- timestamp synchronization file for EEG data from XDF formatted in a .tsv format
	- motion capture raw data 
	- timestamp file for motion data from XDF formatted in a .tsv format

Reconvene to discuss (hopefully, @robertoostenveld  and @sappelhoff  will be able to attend)

**Comment by sappelhoff** [comment]
FYI I created a "team" for bep029-motion just now that you can use to add people and then tag: @bids-standard/bep029 

@helenacockx @JuliusWelzel I just sent you invitations to join the bids org on GH

**Comment by sappelhoff** [comment]
closed in #981
