### ISSUE TITLE
task "label" sometimes referred to as "task_name" or "task_label"

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#445]
There seems to be some cases where the `label` place holder for `task`changes a bit:

It seems that in most places it is just `label`. See fMRI section below.

```
sub-<label>[_ses-<label>]_task-<label>[_acq-<label>][_ce-<label>][_dir-<label>][_rec-<label>][_run-<index>][_echo-<index>]_<contrast_label>.nii[.gz]
```

But sometimes it is `task_label`: see the ieeg section below.
```
sub-<label>[_ses-<label>]_task-<task_label>[_run-<index>]_ieeg.json
```

And sometimes it is `task_name`: see the behavioral section below.
```
sub-<label>/[ses-<label>/]
    beh/
        sub-<label>[_ses-<label>]_task-<task_name>_events.tsv
        sub-<label>[_ses-<label>]_task-<task_name>_events.json
```

I don't think this is a big issue but I am always afraid that inconsistencies might confuse people, especially new-comers.

Or maybe there is a good reason for these differences?

**Comment by nicholst** [comment]
Good catch @Remi-Gau!

Seems like `task_label` and `task_names` are the anachronisms, and they could be changed to `label` as long as the surrounding text is clear about the meaning of the label.

**Comment by Remi-Gau** [comment]
OK I will open a pull request to change those.
