### ISSUE TITLE
naming multiple marker files for KIT MEG systems

### ISSUE THREAD

**Issue by monkeyman192** [bids-standard/bids-specification#45]
Currently the specification only has details on how to name a single marker file associated with KIT MEG systems ([see here](https://github.com/bids-standard/bids-specification/blob/master/src/99-appendices/06-meg-file-formats.md#kityokogawaricoh)).
MNE-python however is able to handle multiple .mrk files and averages them if more than one is provided.
I wrote a PR to export the .mrk files with MNE-BIDS (https://github.com/mne-tools/mne-bids/pull/114) but since we have no specification on what to call the files if multiple are used this PR cannot continue until this issue has been resolved.

While the majority of the time it seems only one .mrk file is ever used with any given .con file, sometimes the researchers will do a `-pre` and `-post` recording .mrk file. To this end I propose possibly having a `-pre` and `-post` tag after the `_markers` tag in the file name.
Eg.
```
sub-control01_ses-001_task-rest_run-01_markers[-pre|-post].<mrk,sqd>
```
Not sure if this is the best way to do it, so I am very open to better suggestions.
@teonbrooks

**Comment by robertoostenveld** [comment]
does the KIT acquisition software allow researchers to generate multiple .mrk files?

**Comment by teonbrooks** [comment]
Yeah, it is done on demand. I think that at max two files should be associated with a run. 

the one thing about the nomenclature of `pre-` and `post-` is dealing when there is just one marker file. does BIDS allow for key-value pairs to exist where one the key is specified?

**Comment by monkeyman192** [comment]
wrt. `-pre` and `post` I mean it more like the options for that are `markers`, `markers-pre` or `markers-post`, so not so much a key-value pair as just a tag (like already exists for just `markers`)

**Comment by teonbrooks** [comment]
> Acq would make most sense to me, i.e. acq-pre and acq-post.

+1

**Comment by jasmainak** [comment]
Agreed, so there is nothing to change and we can close this issue?

**Comment by teonbrooks** [comment]
> Agreed, so there is nothing to change and we can close this issue?

we need to make a PR against the specification to clarify labeling for markers using `acq-pre` and `acq-post`. we can let that PR close it. @monkeyman192 do you want to take a stab at including it? if not, I can

**Comment by monkeyman192** [comment]
yep, can make a PR for it :)
