### ISSUE TITLE
_scans.tsv should be accompanied with _scans.json to describe the columns

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#450]
[ATM "Scans file"](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#scans-file) can contain prescribed `acq_time` column (which could be anonymized or not) and an arbitrary number of additional columns: "Additional fields can include external behavioral measures relevant to the scan.".  I think the situation is similar to `_events.tsv` file which now is SHOULD have `.json` sidecar file describing additional columns in the file, so `_scans.tsv` SHOULD have corresponding (following inheritance could leave at the higher level) `_scans.json` which would describe additional columns and provide information about either `acq_time` is anonimized.

- Have you checked our contributing guide? I did some time back

- Is your idea backwards compatible? yes

- Is there already a group working on your idea? did search among issues - nope, not worth BEP
- Will your idea potentially require a large effort? shouldn't be

**Comment by effigies** [comment]
Sounds completely reasonable to me.

**Comment by sappelhoff** [comment]
Agreed, and it seems like this is already [allowed for in the validator](https://github.com/bids-standard/bids-validator/blob/f4d7c4038bea955557e6f8622809eaf7ccca56eb/bids-validator/bids_validator/rules/session_level_rules.json#L5)

so all that needs to be done is clarify the SCANS section in the spec. Do you want to make a PR @yarikoptic?
