### ISSUE TITLE
Question status BEP017 

### ISSUE THREAD

**Issue by dorahermes** [bids-standard/bids-specification#456]
What is the current status of BEP017? (BIDS Extension Proposal 17 (BEP017): Generic BIDS connectivity data schema. We are working on a BIDS app for some iEEG connectivity analyses and are happy to contribute an example if this is still moving forward.

@sappelhoff @eduff

**Comment by sappelhoff** [comment]
@franklin-feingold regularly inquires the current status from BEP leads and posts it in our [BEP table](https://bids.neuroimaging.io/get_involved.html#extending-the-bids-specification)

I have no further info on this, sorry!

Maybe @pauldmccarthy can say something.

**Comment by PeerHerholz** [comment]
Just wanted to mention, that we're currently actively working on this [here](https://docs.google.com/document/d/1ugBdUF6dhElXdj3u9vw0iWjE6f_Bibsro3ah7sRV0GA/edit?usp=sharing) and plan to reach out to the broader community soon.
