### ISSUE TITLE
Multiple values in an entity

### ISSUE THREAD

**Issue by darrencl** [bids-standard/bids-specification#468]
Hi, I am not sure if this has been asked before, but I am just wondering if there is a way to specify multiple values for an entity? For example, if I want to have multiple values in `acq-` key, how can those values be separated? Can I use symbol, like `+` for this, e.g. `..._acq-value1+value2_...`

Thanks!

**Comment by sappelhoff** [comment]
Hi @darrencl usage questions like this may find more / better replies on [Neurostars](https://neurostars.org/tags/bids) under the `bids` tag.

to answer your question: I have not seen `_acq-value1+value2_` anywhere and I don't think it'd be valid (i.e., pass the bids-validator). A hack for now may be to separate the values using camelcase: For example in a 2x2 task design where one factor has the the levels `Bandit` or `Sampling` and the other factor has the levels `Active` and `Passive`, you could specify the task entity as: `task-BanditPassive`

**Comment by sappelhoff** [comment]
@darrencl I hope you found a solution. Closing this issue now.
