### ISSUE TITLE
BEP: make `dir` optional for other than fmap modalities

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#47]
ATM, "Phase encoding direction" (`dir`) is a [required field](https://github.com/bids-standard/bids-specification/blob/6b22fbe93a04a8c38ced701b48dc83f6c09bf2d8/src/99-appendices/04-entity-table.md) for `fmap(epi)`.  But it is relevant for other sequences (`fmap`, `dwi`) but is not available in BIDS specification for them. To overcome this specification people resort to list the value in a flexible and omni-present `acq` field:
```shell
$> datalad -c datalad.search.index-egrep-documenttype=all search path:.*_acq-ap.*
search(ok): /home/yoh/datalad/openfmri/ds000221/sub-010001/ses-02/func/sub-010001_ses-02_task-rest_acq-AP_run-01_bold.json (file)
...
search(ok): /home/yoh/datalad/openfmri/ds000244/sub-01/ses-00/func/sub-01_ses-00_task-ArchiSocial_acq-ap_bold.nii.gz (file)
...
```
So it seems that demand is there and I do not see a reason why `dir` should not be allowed to be used in those cases.

**Comment by chrisfilo** [comment]
I am a bit skeptical:
- it makes the filenames potentially longer
- creates two ways to describe the same thing (`acq-PA` and `dir-PA`)

I'm also not sure there would be such a big benefit from this change in terms of usability.

**Comment by yarikoptic** [comment]
Length stays the same since len(acq) == len(dir), unless there is also actually something else to say about acq.
acq is too generic/non-specific, dir meaning is consistent with current use in fmap, and potentially would be used for the same purpose.
To me it is about clarity - again acq can't be interpreted pretty much, while dir could

**Comment by kaczmarj** [comment]
@chrisfilo - i agree with @yarikoptic. `dir` should be valid for all epi, or it shouldn't be a tag at all. 

it's confusing to have `dir` mean phase encoding direction for field map, and then `acq` _potentially_ mean phase encoding direction for dwi, bold, etc. i am bids-ifying a study that uses AP and PA direction for dwi and bold, and it's inconsistent to specify the phase encoding direction with `dir-` for the field maps but `acq-` for dwi and bold, when they represent the same information.

**Comment by chrisfilo** [comment]
Please make a pull request - we can see if anyone feels strongly against this.
