### ISSUE TITLE
proper set up of partisipants.json

### ISSUE THREAD

**Issue by MRIDude** [bids-standard/bids-specification#478]
I have a data set where we document the time passed since a treatment from an MR visit.  In some case we have participant that have never undergone treatment. It's not missing data. So how best do I document this in both the participants.tsv and  participants.json?

**Comment by franklin-feingold** [comment]
hi @MRIDude thanks for your question! Perhaps these can be n/a or sparsely recorded filling in the values you do have. In the json file, you can denote the recording scheme you choose  

[NeuroStars with the `BIDS` tag](https://neurostars.org/tag/bids) is also a good location to ask for BIDS help - the community is more active over there for answering questions
