### ISSUE TITLE
allowing an optional LICENSE file, next to README and CHANGES

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#481]
In BIDS we do not make any strong requirements or recommendations about licenses to use for the data. We have a very short [appendix on licenses](https://bids-specification.readthedocs.io/en/stable/99-appendices/02-licenses.html) and we ask users to specify the license in a string in the [dataset_description.json](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#dataset_descriptionjson) file.

I think it'd be reasonable to allow an optional LICENSE file in the same vein as the README and CHANGES.

**Reasons:**

In the review to get the EEG-BIDS paper published with the BIDS example datasets, a reviewer required a LICENSE file ... i.e., the string in the dataset_description.json file was not enough. So I added a LICENSE to [the example dataset](https://github.com/bids-standard/bids-examples/tree/master/eeg_matchingpennies) and then had to add also a  `.bidsignore`, because we don't allow a LICENSE file.

Thus my reasons for requesting a LICENSE file are ...

- it's a low cost feature
- it's probably required relatively often and is widely used
- people do it anyways but currently have to put a `.bidsignore` into the dataset additionally

**Possible issues I can imagine:**

- LICENSE file and `dataset_description.json` field could be in conflict (due to user error)

**Comment by satra** [comment]
> a reviewer required a LICENSE file

did the reviewer indicate a specific reason for this? Some licenses do require a specific statement to be added, but not necessarily a separate file.

**Comment by sappelhoff** [comment]
I just looked into the old emails again the exact reasoning was a bit different:

- I had an ODBL license (https://opendatacommons.org/licenses/odbl/summary/)
- On the Open Science Framework, I can't select this license from the dropdown menu, so I picked "other"
- the reviewer just saw the "other" and didn't know that there is a "license" field in dataset_description.json

Then I got this reply:

> ideally this [the license] would be stated on the landing page of the data record, it currently lists ‘Other’. If this is not possible, we would encourage you to upload a separate Licence file next to the Read Me file at OSF to highlight this.

**Comment by effigies** [comment]
This makes sense to me. Validation for consistency can probably check that the license name appears somewhere in the license file, and assume the curator isn't intentionally deceptive.

**Comment by sappelhoff** [comment]
during the maintainers meeting another reason to allow LICENSE files came up:

--> some licenses require that the full license text is shipped with whatever is being licensed that way.
