### ISSUE TITLE
Use RTD builds for PRs instead of CircleCI

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#484]
RTD people have an experimental feature of providing builds for PRs.  See e.g. https://github.com/con/open-brain-consent/pull/50 where it was already enabled and tested.

I do not have admin privileges for RTD for this project, so the most I could do is to pester RTD people to enable the feature for this repository, which I was told they have done!  So it is now for people with the super powers to actually make it work.  Should be quite straightforward, see https://docs.readthedocs.io/en/latest/guides/autobuild-docs-for-pull-requests.html for the documentation and common gotchas. In my case it was the need "to disconnect and reconnect to GitHub service" as now described in that document.

**Comment by effigies** [comment]
Enabled and added @yarikoptic as maintainer.

**Comment by effigies** [comment]
Possibly it only works with Sphinx?

**Comment by yarikoptic** [comment]
I think that it just needs adjusting permissions for RTD integration on github side.  
I have done already a cycle on RTD by removing the linkage to github and trying to add it again:

Could not add webhook for BIDS Specification. Make sure you have the correct GitHub permissions.
The project BIDS Specification doesn't have a valid webhook set up, commits won't trigger new builds for this project. See the project integrations for more information.

and indeed I have no super powers in this organization/repository.  @effigies please go to RTD, remove the hook and try to add it again in https://readthedocs.org/dashboard/bids-specification/integrations/123217/ (if you have super powers here on github for bids-standard organization)

**Comment by yarikoptic** [comment]
you can push or force push more to #485 to see if RTD emerges in the status.

**Comment by effigies** [comment]
There's definitely something wrong with the authentication. I have full permissions, but it wouldn't add the webhook. I added it manually, and it [builds](https://readthedocs.org/projects/bids-specification/builds/11132440/), but it won't push to the "checks" section.

**Comment by effigies** [comment]
Ah, had to go to https://github.com/settings/applications, find the app, click, and grant access to bids-standard. Then the webhook could be resynced.

**Comment by yarikoptic** [comment]
so it works, issue resolved, thanks @effigies !

**Comment by effigies** [comment]
While we're on the topic, do we want to drop the CircleCI doc build?

**Comment by sappelhoff** [comment]
wow, cool that this is possible now :-)

I'd say let's test it out for a bit and then remove CircleCI if we don't find any fault with the new RTD feature

**Comment by sappelhoff** [comment]
So far I am happy with it. From my side, we can switch the docs artifact from circleci off.

Then we can also use https://github.com/bids-standard/bids-specification/blob/master/.circleci/artifact_path to point to the PDF build of the docs.

the `artifact_path` should also become a GitHub action like we already have on the [bids-website](https://github.com/bids-standard/bids-website/blob/gh-pages/.github/workflows/artifacts_redirector.yml), because I think the way we currently have it is outdated and may not be supported in the future anymore.
