### ISSUE TITLE
Clarify XXXCoordinateSystem

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#493]
We talk about `XXXCoordinateSystem` at several points in the specification, but we never introduce what we mean by that.

The `XXX` is intended as a wildcard for EEG, MEG, or iEEG.

The specification should contain a brief paragraph to make this clear.

**Comment by jclauneuro** [comment]
+1. The Coordinates section needs better examples and the specs still need work. I didn't have time before the freeze to look into this unfortunately. Should we leave this for a future release given the v1.4.0 freeze?

**Comment by effigies** [comment]
I think this clarification could easily go into a 1.4.1, so delaying for now won't have much impact.

And a PR can be submitted now; it just can't be merged until after the release.
