### ISSUE TITLE
Clarify "acquisition time" in scans file

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#503]
In the description for the `scans` file, the specification says:

> If acquisition time is included it should be under `acq_time` header.

It would helpful to specify that the acquisition time should correspond to the beginning of acquisition (i.e., when the first data point for the run was acquired).

NOTE: This issue stems from https://github.com/nipy/heudiconv/issues/450#issuecomment-644923590.

**Comment by sappelhoff** [comment]
I agree that this should be clarified and it seems fairly uncontroversial to specfiy as "when the first data point for the run was acquired". PR welcome!
