### ISSUE TITLE
Copyright for BIDS specification is not stated anywhere

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#507]
License without a copyright is like a driver license without a driver. Might not be the best analogy but the point is that there should be some "entity" holding the copyright while releasing works under some license.  Since there is no particular person or official entity, I would recommend to do the same as many other projects do - announce that copyright belongs to the project and/or contributors. Something like

Copyright: 2020, BIDS Contributors

Issue came up to properly attribute copyright and license to BIDS logo derivative: a perspective logo for Open Brain Consent project https://github.com/con/open-brain-consent/pull/69

**Comment by sappelhoff** [comment]
Good point, PR welcome :-)

I agree with "BIDS Contributors" and I have also seen this custom over a wide array of projects.

**Comment by franklin-feingold** [comment]
+1 sounds good to me!

**Comment by sappelhoff** [comment]
@yarikoptic do you want to state `Copyright: 2020, BIDS Contributors` at the top of the `LICENSE` file? or did you have another place in mind?
