### ISSUE TITLE
BIDS for microscopy (BEP031)

### ISSUE THREAD

**Issue by mariehbourget** [bids-standard/bids-specification#510]
Hi everyone, I’m a student in NeuroPoly Lab at Polytechnique Montreal. We are looking into BIDS for histology and would like to start a conversation with the community. **[Here is our BIDS proposal for handling histology data, you can comment or make suggestions directly on the doc.](https://docs.google.com/document/d/1Nlu6QVQrbOQtdtcRarsONbX5SrOubXWBvkV37LRRqrc/edit?usp=sharing)**  Comments and feedback are welcome!
This is a continuation of the issue on [Neurostars](https://neurostars.org/t/bids-with-histology-data/7201).
Best,
Marie-Helene

**Comment by sappelhoff** [comment]
Hi @mariehbourget, thanks for sending this in. 

I realize that you started with a post on Neurostars (https://neurostars.org/t/bids-with-histology-data/7201) and saw that Franklin and Chris already gave some advice.

But if you want to get additional feedback from the BIDS community, it may be worth to also send an announcement with a bit more detail about the motivation via the mailing list (https://groups.google.com/forum/#!forum/bids-discussion)

**Comment by akhanf** [comment]
Hi Marie-Helene,

This is a really great initiative, thanks for starting this up! I do some mri-histology work, mostly in humans (surgical and post-mortem), and happy to contribute where I can and provide datasets too. 

Two questions that come to mind: 

1. What about whole-slide imaging file formats? For larger slides image tiling is required, basic formats like png are effectively unusable, and so hierarchical file formats are used that store low-res versions of the tiled images, along with all the full resolution tiles. Aperio svs (or bigTiff) is a common one, but a list of most of the popular ones can be found here: https://openslide.org/formats/. Would be curious to know how many people in this community are currently using those formats though, as they can be cumbersome to work with because of their size and limited support in viewers. Nifti could be a more flexible alternative for smaller sized images.

2. Would be an excellent opportunity to sort out standardized ways specifying coordinate systems and transformations between spaces (like MRI <-> histology) if the data are registered. 

Best,
Ali

**Comment by lazaral** [comment]
Hi Marie-Helene,

This is a great initiative - thank you for starting it! It would be really exciting to be able to share histology data in a standardised format. 

I've added some comments on the google doc - I'll spread the work to a few other preclinical people I think may be interested in being involved. Would be great to take OHBM as an occasion to have a meet up with those interested!

Best wishes, 
Alberto

**Comment by jpellman** [comment]
Just as a quick aside, it's probably worthwhile to check in with the [Bio-Formats](https://www.openmicroscopy.org/bio-formats/) folks before you get too deep into this.  [OME-TIFF](https://docs.openmicroscopy.org/ome-model/6.0.1/ome-tiff/specification.html) is already a fairly mature metadata standard and it's possible that you might end up duplicating some of the efforts that they've already made if you're not careful.

**Comment by jcohenadad** [comment]
> Would be an excellent opportunity to sort out standardized ways specifying coordinate systems and transformations between spaces (like MRI <-> histology) if the data are registered.

@akhanf that's a tricky one 😉

**Comment by satra** [comment]
@akhanf - great suggestions. part of the process should be about capturing the information about coordinates/coordinate systems. the standardizing part may take some effort, but we can learn from several prior things. 

it would be good to include:
1.  some considerations of what formats are suitable at what scales of data and for what purpose.  we are currently helping a group curate a rather complex dataset that has multiple MR and optical recordings at a variety of scales from TBs to 100s TBs for a given sample. there are considerations of image formats, derived objects in vector formats, compressions schemes, metadata, etc.,. as we understand the data **and** processes better we may come back here with some options.

2, what are the different generators of such data (which instruments, what is their native/exported format, etc.,.)?

**Comment by mariehbourget** [comment]
Hi @sappelhoff ,
We received great feedback and suggestions from the community and updated our working example accordingly. We were wondering what are the next steps to move forward and make this an official BEP? Thanks!

**Comment by sappelhoff** [comment]
hey @mariehbourget, that's nice! We'll discuss this in our upcoming maintainers meeting next Tuesday and get back to you very soon afterwards.

**Comment by sappelhoff** [comment]
Update: The current BEP proposal looks good and you seem to have found several contributors already --> we'll suggest to the steering group to make this BEP official. The next meeting is on the 30th, but I am very positive that we'll have good news then :-)

(i.e., feel free to keep working on the BEP until then)

**Comment by sappelhoff** [comment]
Hi Histology folks,

we have decided to make this BEP official, giving it the number 31 --> BEP031 :tada: 

I have lso prepared a PR that adds BEP031 to the list of all BIDS extension proposals: https://github.com/bids-standard/bids-website/pull/144

Please review whether that looks fine to you. Once that PR is merged, you'll be able to refer to your BEP using this address: https://bids.neuroimaging.io/bep031 ... that will then redirect to your Google Doc. If in the future you want to change where this link links to, you can simply edit a file on the bids-standarrd/bids-website repository and won't have to distribute an entirely new link.

Some important points to keep in mind when continuing to work on your BEP:

1. The microscopy data you are trying to introduce to BIDS is very different in kind to what we are currently having. To make integration as easy as possible, try to find collaborators / advisors that are well experienced with many different kinds of data supported in BIDS ... and with BIDS itsself
1. Please have a look at the bids-standard/bids-validator early on during your BEP development and think about how the data structure you are developing can be validated using our existing bids-validator ... and what extensions are needed

That's all from my side so far! Good luck and have fun.

**Comment by lazaral** [comment]
Fantastic news - thank you @sappelhoff!

**Comment by mariehbourget** [comment]
Great news! Thank you @sappelhoff for your help and advice.

**Comment by jgrethe** [comment]
@mariehbourget Wanted to suggest a collaboration.  The NIH Common Fund's Stimulating Peripheral Activity to Relieve Conditions ( SPARC) program is collecting microscopy data (and other data such as genomics, electrophysiology) with the addition of annotations and segmentation (via MBF Bioscience).  As part of this work, BIDS was used as a foundation for the data within SPARC ( https://sparc.science/help/3FXikFXC8shPRd8xZqhjVT ).  Information about samples is included and information about appropriate metadata for samples and subjects (e.g. from MINDS) is also included. We (including @tgbugs @bandrow ) are part of the SPARC curation core and would be interested in joining these discussions.

**Comment by jcohenadad** [comment]
Thank you for reaching out @jgrethe ! Glad to have you and your team being part of these discussions.

**Comment by mariehbourget** [comment]
Hi @jgrethe , thank you for reaching out and joining the discussion.
For the BIDS extension proposal for microscopy, we are looking into restricting the primary data to only one file format. This is to avoid having Apps down the line having to deal with multiple formats. As of now, we are mainly discussing between 2D image formats like PNG or Whole-slide imaging formats like OME-TIFF. We looked into the SPARC dataset structure and we are wondering if you have guidelines or best practices regarding file formats for your “primary” folder? Thanks!

**Comment by balbasty** [comment]
Hi,

Thanks for starting this community effort!

Two cents for the Martinos Center  (@brf2), where we're working with multimodal datasets that include 3D microscopy (OCT and light-sheet microscopy): it would be beneficial to make choices that are compatible with 3D datasets. I don't think that having separate BEP for 2D and 3D microscopy makes sense, there's way too much overlap between these. 

It would also be super useful to think about coordinates systems / spatial mapping (most microscopy formats don't include the equivalent of an affine transform). Having a look at what's done in the GIS community could be interesting: they have very similar problems as us (coordinate systems, large files, pyramids, etc).

I have added a few comments on the google doc.

Thanks again
