### ISSUE TITLE
RepetitionTime type in bold.json not specified.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/bids-specification#516]
bids-validator expects these to be a 'number' in the json schema for bold.json but the spec doesn't definitively say they can't be a string:

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#required-fields

bids-standard/bids-validator#674  shows that people have used strings for RepetitionTime before.

Should I update the schema in the validator to allow strings or should the specification be updated to enforce a specific type?

**Comment by effigies** [comment]
I would say it should be a number.

**Comment by satra** [comment]
@sappelhoff - here is one example issue, but could be generalized.

@yarikoptic and @dbkeator - this should also tie in with more formalism updates to schemas. This come up in general for other contexts like echo time, flip angle, etc.,. where we don't specify either data types or units in many cases.

**Comment by sappelhoff** [comment]
thanks @satra. Crosslink for other readers: https://github.com/bids-standard/bids-specification/pull/508#issuecomment-661173432

We'll discuss this in tomorrows Maintainers meeting and act soon :-)

**Comment by sappelhoff** [comment]
closed by #605
