### ISSUE TITLE
Add sub-{sub}_CT.nii.gz in anat directory to spec

### ISSUE THREAD

**Issue by alexrockhill** [bids-standard/bids-specification#524]
For intracranial eeg, adding a CT containing the positions of the implanted electrodes would be good to have in order to make the study fully reproducible.

**Comment by effigies** [comment]
[BEP 024: Computed Tomography](https://bids.neuroimaging.io/bep024) is working toward inclusion of CT in the standard.

From a quick look, this is a small BEP, and could probably be proposed as a PR in pretty short order.

**Comment by alexrockhill** [comment]
Cool, thanks for responding

**Comment by sappelhoff** [comment]
@alexrockhill if you have some time perhaps you could read that BEP and comment/review it from your use case. That'd probably be very helpful to the BEP!

**Comment by Hboni** [comment]
CT can be used in addition to several other imaging technics, with maybe specific information. We really need to discuss the organization for all those use cases. I will be happy to discuss with you @alexrockhill on the BEP to continue the development of the BEP!

**Comment by alexrockhill** [comment]
> CT can be used in addition to several other imaging technics, with maybe specific information. We really need to discuss the organization for all those use cases. I will be happy to discuss with you @alexrockhill on the BEP to continue the development of the BEP!

Great! I've been discussing [here](https://neurostars.org/t/ct-in-bids-format/9129/6) and [in the BEP](https://docs.google.com/document/d/1fqnJZ18x5LJC8jiJ8yvPHUGFzNBZ6gW2kywYrUKWtuo/edit#) if you want to add to those discussions or start a separate thread either are good with me
