### ISSUE TITLE
Unnecessary duplicates of sidecar JSONs (example: *_physio.json)

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#528]
I have an experiment with 5 "tasks" that are all very similar, but have distinct task labels (`ActiveFixed`, `ActiveVariable`, `YokedFixed`, `YokedVariable`, `description`).

In each of these tasks I collect eyetracking data with a small non-research grade eye tracker (Tobii 4C), and I include this eyetracking data in the following file per subj and task, according to the [physio section in the spec](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/06-physiological-and-other-continuous-recordings.html):

`sub-01/eeg/sub-01_task-ActiveFixed_recording-eyetracking_physio.tsv.gz`

(replace the task label with any of the five above).

I use a `*physio.json` file to describe the `physio.tsv.gz` --> and that's where the problem is:

1. all of my `physio.tsv.gz` files have the same columns and the same parameters, hence all `physio.json` files are the same
1. I still have to create one `physio.json` for each `task` label, hence I end up with 5 duplicates of the same `physio.json` files, with just a minor deviation in their file name:

Stored at the root, using the [inheritance principle](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#the-inheritance-principle):

1. `task-ActiveFixed_recording-eyetracking_physio.json`
1. `task-ActiveVariable_recording-eyetracking_physio.json`
1. `task-YokedFixed_recording-eyetracking_physio.json`
1. `task-YokedVariable_recording-eyetracking_physio.json`
1. `task-description_recording-eyetracking_physio.json`

It would be more sensible to just have a single `*_physio.json` instead of these 5 duplicates.

- Does somebody see a way how to do it with our current spec?
- If not, do we want to work something out?
- Am I alone with the opinion that this is an issue?

**Comment by satra** [comment]
technically you should be able to do: `recording-eyetracking_physio.json` or `sub-X_recording-eyetracking_physio.json` at the root level i think. there is nothing in the specification that disallows this as far as i can tell.

**Comment by sappelhoff** [comment]
:thinking: mmh okay, maybe I had a false memory --> but it seems you are right and even bids-validator is playing along.

I can even go as far as just to place a `physio.json` there.

I am gonna leave this open for a bit longer for other people to check, and then close if nobody chimes in. thanks a lot @satra

**Comment by sappelhoff** [comment]
yet for a single `events.json` (without a task entity) or a single `coordsystem.json` (without task entity) this fails. 

Maybe a validator error? @rwblair 

also pinging @robertoostenveld for his opinion

**Comment by rwblair** [comment]
When the validator is loading json schemas it isn't looking at root level for `events.json` or `coordsystem.json`:
https://github.com/bids-standard/bids-validator/blob/master/bids-validator/validators/json/json.js#L96

They also do not appear in our regex rules for determining if paths are valid:
https://github.com/bids-standard/bids-validator/blob/cb31b1130f327392292fdb2660a242cef4451b3e/bids-validator/bids_validator/rules/top_level_rules.json#L5

@sappelhoff whats the specific error being thrown by the validator?

**Comment by rwblair** [comment]
Guess with coordsystem there are different json schemas for eeg, ieeg, meg, but they don't have any fields in common. If you had  all three modalities in a dataset, and the required fields from the three schemas in a root level `coordsystem.json` would it be valid?

**Comment by rwblair** [comment]
For more root level context, `bold.json` is not allowed by validator:
https://github.com/bids-standard/bids-validator/blob/cb31b1130f327392292fdb2660a242cef4451b3e/bids-validator/utils/files/potentialLocations.js#L65

**Comment by sappelhoff** [comment]
error:

![image](https://user-images.githubusercontent.com/9084751/89549858-2b3dd800-d809-11ea-8d86-3d350caff018.png)


> If you had all three modalities in a dataset, and the required fields from the three schemas in a root level coordsystem.json would it be valid according to the specification?

very good point :thinking: that could be an argument against a root level coordsystem.json --> because if several modalities of the three (eeg, meg, ieeg) are present, one wouldn't know to which that json belongs.

how about events.json though?

**Comment by sappelhoff** [comment]
> For more root level context, bold.json is explicitly not allowed by validator:

what was the reasoning for this? Does somebody know?

**Comment by sappelhoff** [comment]
I am closing this now, because the original issues of duplicate `physio.json` files is rare anyways, because usually each TSV would get its own JSON in physio, because the JSON contains the `StartTime`, which is in many cases *not* equal across recordings (except when always set to zero, for example).

Regarding the remaining discussion with coordsystem and events, I am getting the impression that we are shooting ourselves in the foot with this.

A little duplication hurts less at this point than potentially introducing issues that we are currently not foreseeing.

Thanks everybody for the discussion.
