### ISSUE TITLE
Clarifying when ses-<label> is optional

### ISSUE THREAD

**Issue by Moo-Marc** [bids-standard/bids-specification#531]
It is clear that having a session level in the hierarchy is optional, but it is unclear to me whether it is optional in file names when a session folder is present.  For example, is this valid? `/sub-01/ses-01/anat/sub-01_T1w.nii.gz`

I would recommend clarifying this sentence under File name structure:

> For a data file that was collected in a given session from a given subject, the file name will begin with the string sub-\<label\>_ses-\<label\>.

Cheers

**Comment by effigies** [comment]
>  For example, is this valid? `/sub-01/ses-01/anat/sub-01_T1w.nii.gz`

No.

> I would recommend clarifying this sentence under File name structure:
> 
> > For a data file that was collected in a given session from a given subject, the file name will begin with the string sub-<label>_ses-<label>.

Could you submit this as a pull request?
