### ISSUE TITLE
Support run entity in behavior-only data

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#539]
This stems from https://github.com/bids-standard/bids-specification/pull/475#discussion_r458771295. Currently, pure behavioral data (i.e., behavioral experiments with no associated imaging) does not support the "run" entity, even though this entity appears to be fairly relevant.

Tagging @effigies, who initially identified this issue.

**Comment by sappelhoff** [comment]
it may be that this was simply overlooked when the spec was written up. +1 to add it now, should be fairly low-impact

**Comment by effigies** [comment]
I can see no downside to adding an optional run entity.
