### ISSUE TITLE
Automate rendering of elements from the schema

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#544]
To be done after #475 is merged (so in that diff we could actually see the difference to entity table).

We should use some mkdoc plugin (I hope there is one matching the need so we don't need to develop a custom one, try to analyze the offerings) to just produce entity table (and later other elements such as example paths etc) during mkdocs build:
https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#code-execution-variables--templating

That should automate and simplify contribution process, etc

**Comment by satra** [comment]
if it helps, we are using pytablewriter in reproschema. https://github.com/ReproNim/reproschema/blob/master/scripts/editProperties.py#L57

to generate these tables: https://www.repronim.org/reproschema/30_schema/#protocol

**Comment by satra** [comment]
looks like bids already does something similar.

**Comment by tsalo** [comment]
Now that we're adding more rendering steps (i.e., both the entity table and entity definitions), I think this is becoming more important. Not to mention that every change to the schema produces a frustrating merge conflict on the entity table.

**Comment by tsalo** [comment]
I'm trying to figure out the best way to do this, and I think there are a few good possibilities.

1. Embed scripts to generate tables and filename examples in text.
    - Running those code snippets would be part of the rendering procedure.
    - I don't know if `mkdocs` supports this.
1. Generate tables and filename examples with separate scripts, and then `include` them in the text.
    - I think this is probably easier, but I don't love the idea of separating things so much.
1. Incorporate text into scripts.
    - Kind of the opposite of the first idea.
    - This is how the entity table and entity definition pages are handled right now. The non-schema text portions of the pages are set in the functions.

Do those options make sense?

**Comment by tsalo** [comment]
It looks like [`pheasant`](https://pheasant.daizutabi.net) could be a useful `mkdocs` plugin for the first option.

**Comment by tsalo** [comment]
I think we can close this since we've started on pretty much all of the elements that could be rendered via separate PRs.

**Comment by yarikoptic** [comment]
And thank you @tsalo for that!
