### ISSUE TITLE
Emoji for contributors missing in PDF

### ISSUE THREAD

**Issue by sebastientourbier** [bids-standard/bids-specification#551]
In PDF version 1.4.0 hosted on Zenodo: https://zenodo.org/record/3890439, page 88 (Appendix I: Contributors), emoji for contribution type are not rendered.

**Comment by sappelhoff** [comment]
good catch, this seems related: https://superuser.com/questions/1366748/rendering-pdf-from-markdown-file-with-literal-emoji-characters-using-pandoc
