### ISSUE TITLE
add optional fields to some of the JSONs

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#552]
Some suggestions for some optional fields that could be added in json files.

The idea is that some of those data should (must?) be provided in the papers we write (cf COBIDAS) so it could make sense if they were included in the dataset metadata.

### dataset_description.json

- URL to pre-registration
- Information about eventual statistical power analysis

~- Financial grants info~
~- ethics: information about the IRB that approved for the data acquisition~

### Add in json files related to task files

- for all modality with tasks (func, eeg, meg, ieeg) 
  - Presentation software used
    - OS
    - Software
    - Version
    - URL to code of that was run to present the software
- for task fMRI 
  - if some design efficiency optimization

Let me know how you feel. If there is some enthusiasm for some of those I could open separate PRs to keep things and discussions modular.

**Comment by sappelhoff** [comment]
thanks for the suggestions @Remi-Gau 

I particularly like OS, software, Version, Url for better descriptions of tasks.

> Information about eventual statistical power analysis

could you go into a bit more detail and perhaps provide an example of what you would think such a field would look like?

**Comment by VisLab** [comment]
Just to mention.  The current BIDS specification of dataset-description has
Funding and EthicsApprovals fields.  However, the EthicsApprovals field was
not  in the JSON schema in the bids-validator.  Hence pull request #1031 to
the bids-validator, which was just merged.

**Comment by Remi-Gau** [comment]
@VisLab yup I did see your PR which made me realize I was out of date on that front. :smile: 

I crossed out the things that are already in the specs in my initial message.

**Comment by Remi-Gau** [comment]
> thanks for the suggestions @Remi-Gau
> 
> I particularly like OS, software, Version, Url for better descriptions of tasks.
> 
> > Information about eventual statistical power analysis
> 
> could you go into a bit more detail and perhaps provide an example of what you would think such a field would look like?

Will open separate issues for both of those

**Comment by sappelhoff** [comment]
I am closing this now, because @Remi-Gau started tracking the two proposals in two distinct issues with two distinct PRs each (I love it :+1: ) thanks Remi!
