### ISSUE TITLE
adding info about software and code used for stimuli presentation

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#558]
> I particularly like OS, software, Version, Url for better descriptions of tasks.

_Originally posted by @sappelhoff in https://github.com/bids-standard/bids-specification/issues/552#issuecomment-667657999_

Suggestions of fields to add:
- StimuliPresentationOS
- StimuliPresentationSoftware: ideally with RRID
- StimuliPresentationVersion:
- StimuliPresentationCode: URL to code of that was run to present the software

Would be added in the sub-sections:
- fMRI task information
- Sidecar JSON (*_ieeg.json)
- Sidecar JSON (*_eeg.json)
- for behavioral only results for consistency?

**Comment by sappelhoff** [comment]
closed in #573
