### ISSUE TITLE
[INFRA] Need to adjust github-changelog-generator

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#559]
brought up by @franklin-feingold :

> currently our changelog generator makes a new entry for each merged commit on our bids-specification repository. The problem comes up when we are working on a different branch (e.g., `bepXXX`) and merge commits into that branch --> then these commits would show up the changelog ALTHOUGH we'd actually only like commits merged into `master` to show up in the changelog

there is a setting to grant that only commits merged into `master` show up, ... we just need to figure out how to apply it.

cc @effigies @rwblair @tsalo

**Comment by franklin-feingold** [comment]
the github_changelog_generator parameter: `release-branch` should do it (https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples)
