### ISSUE TITLE
[Ephys] Add "ACCEL" as channel type for accelerometers

### ISSUE THREAD

**Issue by arnodelorme** [bids-standard/bids-specification#561]
- [x] PPG (plethysmography) should be added as an accepted channel type in https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html. It is a common channel recorded with EEG (in the Muse for example) but is different from ECG (heart as well but records blood flow instead of electro-cardiography). --> done in https://github.com/bids-standard/bids-specification/pull/570

- [ ] "ACCEL" for accelerometers should also be an accepted type as it is even more common than PPG (Muse, OpenBCI, etc...)

**Comment by sappelhoff** [comment]
tagging @bids-standard/raw-electrophys

**Comment by robertoostenveld** [comment]
for ACCEL it might be good to look into and align with [BEP 29](https://bids.neuroimaging.io/bep029) for "Virtual and Physical Motion Data" and into [BEP 30](https://bids.neuroimaging.io/bep030) for NIRS data. Many NIRS acquisition systems include accelerometers (since motion causes optode artifacts).

**Comment by sappelhoff** [comment]
> Many NIRS acquisition systems include accelerometers (since motion causes optode artifacts).

BEP030 is starting to introduce ACCEL [here](https://docs.google.com/document/d/1FzPt7TVpIAtlhrF9_9b2VBCZOrRXJASEMyHndhDQKl8/edit?disco=AAAAG755cH4)

it'd be good to get this channel type in separately from the nirs BEP (smaller PRs are easier to handle and review ... and better to coordinate between modalitites)

**Comment by effigies** [comment]
I would also support a small PR to introduce ACCEL. It seems to fit exactly with BEP030's plans and doesn't have an obvious conflict from skimming BEP029.

**Comment by rob-luke** [comment]
Yes, we need an ACCEL type for BEP30. If it hasn't been added elsewhere are you happy for me to open a small PR just for this?

**Comment by sappelhoff** [comment]
> Yes, we need an ACCEL type for BEP30. If it hasn't been added elsewhere are you happy for me to open a small PR just for this?

I think it'd be valuable to get input by @robertoostenveld @sjeung @helenacockx and @JuliusWelzel here.

Would adding `ACCEL` to the [list of channel types](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#channels-description-_channelstsv) be a sufficient feature to make proper use of it in MEG/EEG/iEEG and NIRS and motion tracking?

Or do we need a different solution? Or the proposed solution and an additional, parallel solution?

**Comment by robertoostenveld** [comment]
I am in principle fine with adding it. But in [BEP029](https://docs.google.com/document/d/1iaaLKgWjK5pcISD1MVxHKexB3PZWfE2aAC5HF_pCZWo/edit#heading=h.4k1noo90gelw) on page 18 it is suggested as `ACC`.

For efficiency reasons, I propose we discuss and agree on the whole list of new channel types at once, and not one by one. Here is the list copied from BEP029:

- POS: position
- ORNT: orientation
- VEL: velocity
- ACC: acceleration
- GYRO: gyroscope
- MAGN: magnetometer

Let me not directly comment on the labels, but let's first see whether people agree to the procedure.

**Comment by helenacockx** [comment]
Yes, I agree with Robert that it would make sense to include the whole list of motion channel types at once.

**Comment by helenacockx** [comment]
Please be aware that an extra column ‘component’ for the axis of the orientation should be added to the _*channels.tsv file in this case (e.g. x, y or z)

**Comment by sappelhoff** [comment]
just throwing another ball into the discussion: if we were include the whole bunch of channel types, it may be worth revamping the way channel types are communicated in the process.

See discussion in https://github.com/bids-standard/bids-specification/pull/570

mainly this comment by Robert (that I agree with):

> I think better (more maintainable, and more clear for people who read it) would be to have the channel types in an appendix. That would also be good for upcoming modalities (NIRS, motion). But that is considerably more work, and not in scope of this small PR.

the time to invest this work may have arrived now, and it would probably ease the integration of NIRS and Motion BEPs

**Comment by helenacockx** [comment]
and the *_coordinatesystem.json should also include the fields 'MotionCoordinateSystem' (+ MotionRotationRule & MotionRotationOrder)

**Comment by sjeung** [comment]
The list in Robert's comment seems to cover the most frequently used motion channel types. 
I see no issue with using keyword ACCEL instead of ACC, but seems like angular velocity  (ANGVEL) is missing from the list. 
If we agree on the channel types and labels here I would update BEP 029 accordingly. 

Another possibly relevant open question at the moment is whether we want motion channels put in a single channels.tsv file together with all other channels, which will result in some unused columns for other channels.

**Comment by rob-luke** [comment]
Great. I will change BEP30 to use `ACC` instead of `ACCEL`. I also agree with a unified list of channel types, we will be adding quite a few in the NIRS BEP too.

**Comment by JuliusWelzel** [comment]
The BEP30 is meeting with the BIDS steering committee on the 30th of march. We hopefully will have a good idea of how a new list of channel types would look like after the meeting, which then could be added to BIDS.

**Comment by rob-luke** [comment]
> The BEP30 is meeting with the BIDS steering committee on the 30th of march

I believe its May 20

**Comment by Remi-Gau** [comment]
browsing old issues

wasn't this addressed by the motion BEP? @sappelhoff @sjeung @JuliusWelzel @arnodelorme
