### ISSUE TITLE
PDF rendering: "link definition" comment sections are also rendered instead of being skipped

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#565]
I am talking about these sections: `[]: <> (################) []: <> (Link definitions) []: <> (################)`

such as at the bottom of [appendix8](https://github.com/bids-standard/bids-specification/blob/master/src/99-appendices/08-coordinate-systems.md)

looking like this in the PDF rendered form:

![image](https://user-images.githubusercontent.com/9084751/89769637-ba930600-dafd-11ea-81f1-6f924ee70c3b.png)

**are these sections even necessary**?

**Comment by effigies** [comment]
No, they're not necessary. That's just how you comment in Markdown. We can also switch to `<!-- comment -->`, if that's easier for pandoc.
