### ISSUE TITLE
Link to bids-2-devel repo in issue template

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#566]
The feature request issue template currently has the following text:

> - Is your idea backwards compatible? If not, please add it to the BIDS 2.0 Google Doc instead of opening an issue: https://docs.google.com/document/d/1LEgsMiisGDe1Gv-hBp1EcLmoz7AlKj6VYULUgDD3Zdw/

This should be replaced with the following:

> - Is your idea backwards compatible? If not, please open an issue in the bids-2-devel repository instead of here: https://github.com/bids-standard/bids-2-devel

**Comment by sappelhoff** [comment]
+1, will do it in #562, which is a PR that does several maint jobs --> feel free to review that one as well if you have some time @tsalo .
