### ISSUE TITLE
"Unknown" modalities are mentioned in the text

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#569]
ran into while reviewing https://github.com/bids-standard/bids-specification/pull/475  . Text refers to RARE and FLASHsubsampled although none such is listed among known modalities 

```
$> git grep -e RARE  -e FLASHsubsampled                                    
src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md:are used to record the same modality (e.g. RARE and FLASH for T1w) this field
src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md:distinction (e.g. just between RARE and FLASH, or between RARE, FLASH, and
src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md:FLASHsubsampled) remains at the discretion of the researcher.
```

**Comment by effigies** [comment]
These appear to be suggestions for `acq-` values.

https://github.com/bids-standard/bids-specification/blob/abf6f7329cf84fcf1eec819813c278daddcde35c/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#L156-L169

**Comment by yarikoptic** [comment]
nah, I think I just rushed into filing an issue... indeed it makes sense to annotate "peculiar" acquisitions  for which we have no suffix in `acq-`.
