### ISSUE TITLE
Define arbitrary units (or synonym) in specification

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#580]
The SI doesn't have a term for arbitrary/unknown units, as far as I can tell, which means that whatever term BIDS uses must be explicitly defined in the specification. BEP001 (#508) has adopted "arbitrary units (a.u.)", while [BEP009](https://docs.google.com/document/d/1mqMLnxVdLwZjDd4ZiWFqjEAmOmfcModA_R535v3eQs0) uses "unitless". According to [Wikipedia](https://en.wikipedia.org/wiki/Arbitrary_unit), alternatives include "unknown unit" or "procedure defined unit". Also, "a.u." can apparently be confused with "astronomical unit" or "atomic unit". Astronomical units probably won't come up in BIDS, but atomic units could. The abbreviation recommendations on wikipedia are "arb. unit" and "[arb'U]".

Whatever our decision is, the Units page of the specification should be updated and the choice in terminology should be fed back into the BEPs.

Note: This stems from [this Mattermost conversation](https://mattermost.brainhack.org/brainhack/pl/utu4itcjn3d7dysozb5sq36afe).

**Comment by melanieganz** [comment]
Thanks for catching this. We didn't catch it in BEPP009. I think we should be avoiding any confusion such as 'a.u.' with atomic units. I think your suggestion with arbitrary units  isgood, but in order to enhance processability should we have something without any  '.' or so? So could it be 'arbU'?

**Comment by tsalo** [comment]
I don't know if periods in json fields are a problem, but arbU works for me regardless.

**Comment by sappelhoff** [comment]
arbitrary units do not seem to be covered by our current RECOMMENDATION for units (CMIXF-12) ... so we'll have to make whatever we decide for (arbU, a.u., ...) another exception to our recommendation.

--> similar to how ° and µ are exceptions.

REF: https://bids-specification.readthedocs.io/en/latest/99-appendices/05-units.html

**Comment by effigies** [comment]
Aesthetically, I find `arbU` pretty ugly, so this comment is probably mostly motivated by that...

What about "arbitrary"? It's not clear that we need an abbreviation at all, as it will be used sparingly and the existing abbreviations can either be confused with other units or are kind of awkward. The units are incommensurable, so there's no automatic manipulation possible that would really motivate using the abbreviation from another standard.

**Comment by sappelhoff** [comment]
@tsalo a PR to introduce "arbitrary" is welcome, we could then continue discussion in the PR and get some more approvals.
