### ISSUE TITLE
Add altname or preferred variable name field to entities.yaml in schema

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#585]
This new field would specify the preferred variable name by which the entities are referred in other tools, like `pybids`. One example is the `ce` entity. The full name for the entity is "Contrast enhancing agent", the entity itself is `ce`, and the pybids variable is `ceagent`. To specify the preferred variable name (or shortened name) would make tools that use the schema more useable to outsiders.

The exact variable names could be taken directly from pybids at this point. I don't know if any other elements to the specification need this field, so please let me know if I'm missing something.

This came up in today's NIDM-Terms call. Tagging @jbpoline, @satra, and @yarikoptic.

EDIT: Perhaps a top-level YAML file should be added that describes the other YAML files/folders, in which case we have the YAML file/folder name (e.g., `datatypes`), the actual name ("Data type"), and some preferred variable name, as used in tools like pybids (`datatype`).

**Comment by effigies** [comment]
The rule we came up with for PyBIDS was that the entity's queryable name should have the entity key as an initial substring, and within that constraint it should be as readable as possible.

https://github.com/bids-standard/pybids/issues/489#issuecomment-531381408

**Comment by tsalo** [comment]
To be honest, the only one that's not easily inferred at the moment is `ceagent`, although I get why you didn't go with `contrast`. In the rest of the cases, I think we could just grab the first word in the entity name. Still, I think moving that field (and naming logic) here would be good.

**Comment by sappelhoff** [comment]
fyi @hoechenberger @adam2392 @agramfort @jasmainak
