### ISSUE TITLE
Define "modality" in Common principles

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#586]
This stems from #571 and #584. Essentially, there is some confusion about terminology for different elements of the specification that could be reduced by defining "modality" and differentiating it from "data type". Of course, the actual definition of modality is up for debate.

I think it would be best to define modality as a subtype of suffix. The reasons for this are:
- The term `modality_label` is used in the anatomical MRI section as a stand-in for all of the anatomical MRI-specific suffixes.
- The "associated modality" entity (`mod`) refers to the suffix of the file from which a defacing mask was created.
- Suffixes are not, however, all "modalities". See https://github.com/bids-standard/bids-specification/issues/584#issuecomment-682330359 and https://github.com/bids-standard/bids-specification/issues/571#issuecomment-673659040.

**Comment by tsalo** [comment]
One rough proposal: 

13. **Modality** - A distinct imaging data type. Modality is reflected in the file suffix, and is thus defined a subset of the suffix entity.

**Comment by sappelhoff** [comment]
It's good to start discussing this in more detail, thanks @tsalo 

I have no better proposal right now (sorry), but still want to point out that

> Modality - A distinct imaging data type. Modality is reflected in the file suffix, and is thus defined a subset of the suffix entity.

still seems to collide with what @hoechenberger says in https://github.com/bids-standard/bids-specification/issues/584#issuecomment-682330359

**Comment by hoechenberger** [comment]
> 1. A distinct imaging data type.

My trouble with this is that it's re-purposing the term "data type", which was described [in a comment](https://github.com/bids-standard/bids-specification/issues/584#issuecomment-682267866) as:

> The folders are "data types"

**Comment by effigies** [comment]
I'm not sure we're going to be able to be very principled with introducing a term this late in the game, and should settle with as brief a description of how it's used. What about:

> **Modality** - An indicator of the category of data recorded by a file. The modality is typically indicated in the **suffix** when applicable, but is not identical to the suffix. For MRI data, different pulse sequences are considered distinct modalities, such as `T1w`, `bold` or `dwi`. For passive recording techniques, such as EEG, MEG or iEEG, the technique is sufficiently uniform to define the modalities `eeg`, `meg` and `ieeg`. Overlaps with, but should not be confused with the **data type**.

**Comment by hoechenberger** [comment]
@effigies I like your proposal!

**Comment by agramfort** [comment]
works for me

>

**Comment by tsalo** [comment]
@effigies would you be willing to open a PR with your definition?

**Comment by effigies** [comment]
Opened #592.
