### ISSUE TITLE
Scans vs Sessions file nomenclature

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-specification#599]
Hi, I am noticing that what was previously the `sub-*_sessions.tsv` file is now renamed to `sub-*_scans.tsv`.

I think this nomenclature change is misleading. The scans are the individual NIfTI files inside the session directory, and there can be multiple per session.

Also, going along with the hierarchical principle which is applied at the subject level with the `participants.txv` file (i.e. the entries are documented by a `.tsv` file at the same hierarchical leve), it would make sense to document the sessions and only the sessions inside the subject-wise directory. If an extra `.tsv` file is needed for individual scans it can go inside the session-wise directory.

Would you support a PR for this change?

**Comment by sappelhoff** [comment]
> Hi, I am noticing that what was previously the sub-*_sessions.tsv file is now renamed to sub-*_scans.tsv.

Hi! What makes you think that?

To the best of my knowledge we didn't change anything about `sessions.tsv`, see:

https://bids-specification.readthedocs.io/en/latest/06-longitudinal-and-multi-site-studies.html#sessions-file

**Comment by TheChymera** [comment]
@sappelhoff you're right, I misread the documentation :) Thank you!
