### ISSUE TITLE
consistent "URI", "DOI", "URL": guidance on how to ensure an unambiguous link

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#601]
> DOI or URL basically means URI. 
Maybe we can shorten this and give some guidance on how to ensure an unambiguous link?

_Originally posted by @effigies in https://github.com/bids-standard/bids-specification/pull/573#r485096568_

See the rest of the thread for more information.

In short:
- trying to have some consistency in the specs on how URI are expressed would be a good thing. 
- especially if it can be done in pedagocial way (potentially in synch with the BIDS starter kit) and we can nudge users into providing unambiguous links to resources.

**Comment by effigies** [comment]
I think we can do this at the top of common principles, under the RFC2119 notice, or as an additional definition, following "File extension". If we want to do the latter:

The relevant RFC for URIs is [RFC 3986](https://tools.ietf.org/html/rfc3986). Perhaps something like:

> 1. **Uniform Resource Indicator (URI)** - A string referring to a resource.
>    URIs have the form `<scheme>:[//authority]<path>[?<query>][#fragment]`, as
>    specified in [RFC 3986](https://tools.ietf.org/html/rfc3986), and include URLs as a subset.
>    Other common URIs include Digital Object Identifiers (DOIs), which may be fully
>    specified as `doi:<path>`, for example, [doi:10.5281/zenodo.3686061](https://doi.org/10.5281/zenodo.3686061).
>    A given resource may have multiple URIs.
>    When selecting URIs to add to dataset metadata, it is important to consider specificity
>    and persistence.

**Comment by Remi-Gau** [comment]
Having our own "definition" as part of the spec was another option suggested in #573 .

I am in favor of that.

Should I start a PR? If so, should the scope of the PR to be add that definition AND update the whole specs?

**Comment by sappelhoff** [comment]
> Should I start a PR? If so, should the scope of the PR to be add that definition AND update the whole specs?

PR would be very welcome, and yes the scope sounds good!
