### ISSUE TITLE
Move/copy BIDS-Terms into schema

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#604]
Per today's NIDM-Terms call, we want to move the NIDM-Terms' [BIDS terms](https://github.com/NIDM-Terms/terms/tree/master/terms/BIDS_Terms) (extracted from the specification pdf) into the schema hosted in this repository. The terms may need to be reformatted (e.g., jsonld --> yaml) to better match the schema's current structure.

Additionally, some keys in the NIDM-Terms files may be dropped.

EDIT: This is related to #423.

**Comment by sappelhoff** [comment]
>  NIDM-Terms' BIDS terms (extracted from the specification pdf) into the schema hosted in this repository.

can we be sure that the extraction was (a) complete, and (b) accurate (i.e., not too many things extracted)?


what will be the workflow in the future? Will NIDM-Terms continue to scrape the BIDS spec and update the "scraped terms", which we will then integrate back into the schema? Or will BIDS make the scraping of the BIDS spec unnecessary by directly supplying a schema, that NIDM-Terms can then use? Or did the "scraping" only happen once and in the future BIDS shall be made dependent on NIDM-Terms?

**Comment by tsalo** [comment]
> can we be sure that the extraction was (a) complete, and (b) accurate (i.e., not too many things extracted)?

The terms will definitely need to be reviewed, but they'll ultimately need to defined in the schema anyway, so I think it would be easiest to start from an existing resource.

> what will be the workflow in the future?

That is a little unclear at the moment.

> Will NIDM-Terms continue to scrape the BIDS spec and update the "scraped terms", which we will then integrate back into the schema? Or will BIDS make the scraping of the BIDS spec unnecessary by directly supplying a schema, that NIDM-Terms can then use? Or did the "scraping" only happen once and in the future BIDS shall be made dependent on NIDM-Terms?

The discussion so far has involved deciding between the second and third possibilities. I think we've converged on the second one at this point, though. Essentially, the BIDS specification text (minus "glue" to connect things and make them more readable) should be generated directly from the schema, and NIDM-Terms can import and use the schema separately.

How the terms will be linked to other ontologies and how we can check that we're not redefining or duplicating terms unnecessarily are still open questions, I think.

**Comment by tsalo** [comment]
@dbkeator do you know if the BIDS-Terms files are ready for a PR? I can select relevant fields and convert to YAML for the actual PR, but I want to make sure that the files at [`NIDM-Terms/terms@master`](https://github.com/NIDM-Terms/terms/tree/master/terms/BIDS_Terms) are the ones I should use. I recall a few different versions from the call (e.g., [this ttl file](https://github.com/NIDM-Terms/terms/blob/master/terms/BIDS_Terms.ttl) and [this one](https://github.com/incf-nidash/nidm-specs/blob/master/nidm/nidm-experiment/imports/bids_import.ttl)).

**Comment by dbkeator** [comment]
Hi,
So the one you'd want to use is [this one](https://github.com/NIDM-Terms/terms/blob/master/terms/BIDS_Terms.ttl).  The other one is really an ontology file to be used for other purposes.  I don't think the turtle file linked above is in final form because I'd like to change a few of the prefixes from the non-descript "ns1" - "ns6" but otherwise it is accurate.  Therefore you could use it and convert it to YAML but we'll likely change the prefixes in the next release.  We are working on an HTML view of this file which theoretically could be included in a BIDS terms page but we don't have a draft yet for others to review.  
Cheers!
