### ISSUE TITLE
1.4.1 RELEASE of the BIDS specification

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#607]
The maintainers team has agreed to work towards a BIDS `1.4.1` release within the next weeks. A clear release date has not been set yet, but a GitHub "milestone" tracker has been set up to mark issues and PRs that we want to resolve / merge before the release, see [milestone](https://github.com/bids-standard/bids-specification/milestone/6).

This is a good time for all BIDS contributors to have a look at the [unreleased changes](https://bids-specification.readthedocs.io/en/latest/CHANGES.html#unreleased) that we have been introducing to BIDS since the last release. Make sure there is nothing in there that you'd have pain with --> and if there is, please open an issue so that we can discuss (or reply here). Your help is very much appreciated! 🚀 

Furthermore, all contributors who have been working for BIDS and want their work to be acknowledged, please edit the ["recent contributors" wiki](https://github.com/bids-standard/bids-specification/wiki/Recent-Contributors) with your contributions. For the release, the wiki will be synced with the actual [contributors list](https://bids-specification.readthedocs.io/en/latest/99-appendices/01-contributors.html) in the specification appendix.

@bids-standard/everyone @bids-standard/bep_leads @bids-standard/steering

**Comment by sappelhoff** [comment]
I think the 6th of October may be a good date for a release (1 week from now). We'll discuss this in today's maintainers meeting and post again here.

**Comment by Remi-Gau** [comment]
Do you think that it would make sense to tackle #601 and #608 before then?

**Comment by oesteban** [comment]
The DWI community would really appreciate having #624 and #622 (in this order) merged before then (or having an explicit decision to push them to the next release). WDYT? Is it realistic?

**Comment by sappelhoff** [comment]
> Do you think that it would make sense to tackle #601 and #608 before then?

I don't have the bandwidth to do that myself, but I could probably review those PRs if somebody else made them. :wink: 

> The DWI community would really appreciate having #624 and #622 (in this order) merged before then (or having an explicit decision to push them to the next release). WDYT? Is it realistic?

I am a bit out of my comfort zone with DWI, so I'd appreciate if @tsalo and/or @effigies could offer an opinion on this.

Generally it feels a bit rushed to me to finish the DWI PRs and include them in the release given that both PRs were opened only within the last 24 hours and that they have a larger scope than the #601 and #608 that @Remi-Gau suggested to still include. But I might be wrong and I am happy to reconsider.

**Comment by Remi-Gau** [comment]
> > Do you think that it would make sense to tackle #601 and #608 before then?
> 
> I don't have the bandwidth to do that myself, but I could probably review those PRs if somebody else made them. wink

Ok I will find the bandwidth. Those items have been on my to-do since we opened them and they keep me up at night.

**Comment by effigies** [comment]
> > The DWI community would really appreciate having #624 and #622 (in this order) merged before then (or having an explicit decision to push them to the next release). WDYT? Is it realistic?
> 
> I am a bit out of my comfort zone with DWI, so I'd appreciate if @tsalo and/or @effigies could offer an opinion on this.

These feel like big things to squeeze in before a release, especially a patch release. Once the decisions are made, DWI datasets can be updated and tooling modified to handle them, regardless of a release. In any event, we anticipate a full 1.5.0 release in late November early December (IIRC).

**Comment by sappelhoff** [comment]
The release will be done on October 12th, 2020
