### ISSUE TITLE
MRI page headings are at incorrect levels

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#617]
Currently, the structure of [Magnetic resonance imaging](https://github.com/bids-standard/bids-specification/blob/c27f613c779ba75e35397576998ccf388cfb8943/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md) places the different data type sections (e.g., `anat`, `task`, `fmap`, `dwi`) _under_ the "Common metadata fields" section. 

I think all of the sections in the page starting with **Anatomy imaging data** need to be moved up a level (e.g., `###` --> `##`).

**Comment by effigies** [comment]
I think we need to start at **Sequence Specifics**, which is a level down from **Scanner Hardware**.
