### ISSUE TITLE
Adding CBV support 

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-specification#63]
Hi @chrisfilo , thank you so much for moving development to Git. This has motivated me to finally get to adding CBV contrast support, as we had discussed on the Google docs page.

Would [this](https://github.com/bids-standard/bids-specification/blob/master/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md) be the adequate page to edit for my addition? Is there any model for documenting the CBV field?

**Comment by chrisfilo** [comment]
No worries - thanks for your contributions.

Yes that would be the right place to add CBV.

**Comment by TheChymera** [comment]
@chrisfilo I have trouble understanding the type/modality distinction in BIDS.

Are “CBV” / “BOLD” / “T2w” *modalities*, and “func”, “anat”, “dwi” types? Is there any point in the document where the names of these fields are clearly defined (wasn't able to find it)?

In MR parlance the former are actually known as *contrasts*, and I think using this term would definitively dispel any ambiguity with the “type” field. Is it ok if I refer to this field as the *contrast* field in my update?

**Comment by chrisfilo** [comment]
Those two terms are blurry and I doubt we can untangle them without breaking backward compatible. The definition of type is here: https://github.com/bids-standard/bids-specification/blob/master/src/02-common-principles.md, but suffix takes different meaning from one type to another.

**Comment by TheChymera** [comment]
Yep, that clears one thing up :) 

But **modality**, **suffix**, and **contrast** remain undefined defined there. Ideally, going forward, I would strongly prefer to call the contrasts **contrasts**, if you oppose this I would go for **modalities** second and **suffix** last (suffix isn't really descriptive here, might be confused by casual users with the extension, and will certainly cause even more confusion if the statistic type is added as a suffix to statistic derivatives).

**Comment by TheChymera** [comment]
If you accept the commit, I'd follow it up with a section better documenting the “image contrast” field. Contextualizing it as such would not just help disambiguate the nomenclature, but also clarify for users the distinction between type (high-level categorization), contrast (measure of interest which the voxel intensities provide information on), sequence (the technical instructions which allow the measurement of the contrast), and contrast enhancer (chemical substances which aid the sequence in increasing the contrast).

**Comment by chrisfilo** [comment]
Closing this since https://github.com/bids-standard/bids-specification/pull/82 was merged.
