### ISSUE TITLE
Tracking NeurodataWithoutBorders support for BIDS-iEEG

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/bids-specification#64]
The BIDS-iEEG spec will allow for the [NeurodataWithoutBorders](https://github.com/NeurodataWithoutBorders) format. However, its ability to easily read in/write out in Python and Matlab is still in the works. This issue is for keeping track of its implementation in both languages (and any support added to other packages such as FieldTrip).

Relevant links:

* [FieldTrip issue to discuss adding support for MatNWB](https://github.com/fieldtrip/fieldtrip/issues/721)
* [official matNWB repository](https://github.com/NeurodataWithoutBorders/matnwb)
* [official pyNWB repository](https://github.com/NeurodataWithoutBorders/pynwb)

**Comment by bendichter** [comment]
Thanks for opening this @choldgraf! I'm happy to help anyone who is interested in using the pynwb or matnwb APIs to read and write NWB files within this context

**Comment by sappelhoff** [comment]
Let's reopen this once there is renewed interest and/or concrete steps that are undertaken.
