### ISSUE TITLE
[DISCUSSION] acknowledge contributors in DOIed specs on Zenodo

### ISSUE THREAD

**Issue by tyarkoni** [bids-standard/bids-specification#66]
To facilitate citation, we should auto-generate Zenodo DOIs for each spec, with author list extracted from the contributors list in the docs.

---

edit by @sappelhoff  2020-05-06: PDF versions of the BIDS spec are now stored on zenodo: https://zenodo.org/record/3720628 ... we still have to adjust the metadata on Zenodo to properly acknowledge contributors.

**Comment by chrisfilo** [comment]
What authorship order would you suggest?

**Comment by tyarkoni** [comment]
Good question... we should probably weight each of the different types of contribution some specified amount, sum up each person's contributions, and then order in descending order of total score. (With the option to manually fix some people--e.g., you should always go first in the core BIDS spec, I should go first in the BIDS-Model spec, etc.).

**Comment by tyarkoni** [comment]
I'm not sure assigning a single DOI makes sense. The degree of modularity is already pretty high. I guess I think of BIDS-Derivatives, BIDS-Models, etc., as modular components in a broader ecosystem—much like dependencies of a package. I think maintaining a single DOI is going to make proper credit assignment very difficult in two respects: (a) when people cite the spec, we'll have essentially no idea what part of it they're making use of, and (b) it'll dilute many people's contributions (because you might have played a central role in BIDS-Derivatives, but never touched the other documents).

**Comment by chrisfilo** [comment]
I agree with the credit argument. I guess we could use Zenodo API to issue multiple DOIs upon spec release and associate subsets of the md files with each one. Versioning would have to be the same though if we are to live in the same repo. It's more complex, but not impossible.

Please also mind that Zenodo is not indexed by Google Scholar, so I would still rely on individual papers dedicated to each BEP for credit purposes.

**Comment by tyarkoni** [comment]
Joint versioning sounds reasonable.

I think it's reasonable to assume that in the not-too-distant future, Google Scholar will index Zenodo (see https://github.com/openjournals/brief-ideas/issues/132). If I read the linked thread correctly, they may already be indexing text-heavy repos, which this certainly would be.

**Comment by chrisfilo** [comment]
Ok - could you propose a formula for authorship order? It would be a good start of the discussion.

**Comment by tyarkoni** [comment]
Where are the contributions listed now?

**Comment by tyarkoni** [comment]
As a first pass, maybe just weight everything equally? We can iterate later...

**Comment by tyarkoni** [comment]
The contributions document is definitely out of date though, so maybe it's worth asking people to update it...

**Comment by tyarkoni** [comment]
I guess it's a bit weird to make authorship order a function of the number of icons in the list. It invites pretty easy gaming, and rewards people who interpret their own contributions liberally. But I guess it's fine for now, and we can change it later if it seems problematic.

**Comment by chrisfilo** [comment]
Summoning @bids-standard/everyone for comments. Please let us know if this is ok with you.

**Comment by CPernet** [comment]
+1

**Comment by chrisfilo** [comment]
Yes - through .zenodo.json file. We will need it for affiliations and orcid anyway.

**Comment by effigies** [comment]
Fine with me. A script that reorders the .zenodo.json according to some criteria should be pretty easy to achieve. We use one for nipype releases, so I can adapt that or provide it if someone wants to play with it.

**Comment by adelavega** [comment]
I'm fine with either lead author(s) + random order, or scored order. I suppose tiebreakers are also needed. Fine with alphabetical or random in that case.

**Comment by jbpoline** [comment]
sounds good to me as well

**Comment by jasmainak** [comment]
I'm fine with any scheme of authorship but maybe slight preference for random order. Is there going a different zenodo doi for each version? I can imagine people contributing in ebbs and flows.

**Comment by chrisfilo** [comment]
Yes, each release and each extension will have a separate DOI.

**Comment by nicholst** [comment]
We just have to start by accepting that it is impossible to do in a way
that truly reflects effort in a fine grained way.

The way we've done it on NIDM is to simply have first and last author
chosen and everyone in between is alphabetical.  If there are multiple
people in those first and last roles does Zenodo allow "these authors
jointly played the {first,last} author role"?

**Comment by sappelhoff** [comment]
+1 on having DOIs for the specs (in addition to standalone publications of BEPs like the MEG one did)

> We just have to start by accepting that it is impossible to do in a way that truly reflects effort in a fine grained way.

I agree, but let's summarize our options:

### Options for authorship order
1. first and last author fixed through election (possibly shared with others), the remaining authors order:
    a. randomized
    b. alphabetically
2. all authors in randomized or alphabetical order
3. counting the number of *icons* in each respective spec (equal weighting), tie breaks:
    a. randomized
    b. alphabetically
4. taking into account the Github contribution metrics per spec:
    a. number of issues raised
    b. number of pull requests ... and how many were merged 
    c. number of lines contributed / deleted
    d. number of commits
    e. number of code reviews and comments
5. any combination of 1. to 4.

Regarding point 4., I am not sure which of these contribution metrics we will be able to easily parse from Github.

Personally, I would go with option 1.a because @nicholst comment will hold true, even given a complex combination of options 1. - 4. that I listed above. I also acknowledge @CPernet's comment above, that the order is important (> tracking contributions matters) ... however I would leave that to the standalone publications that come out of every BEP (so far for MRI (main spec) and MEG ... EEG and iEEG to come)

**Comment by teonbrooks** [comment]
- I would go for first author(s) and alphabetically ordered contributors. 
- I don't know/understand what a last author would mean in this case.

Emoji-based ranking isn't a bad idea if we have an agreed-upon weighting but i do understand the concern about potentially gaming (could have some safeguards in CoC). 

Github would be a good idea if we started the BEPs on Github from the beginning. there will be missing attribution for work done in a Google doc first when it is brought over here.

**Comment by nicholst** [comment]
>  I don't know/understand what a last author would mean in this case.

Whatever method we arrive at, we add a note that explains the ordering.
This is essential especially if we use randomised.

I think last author is not impossible to define (and, again, this can all
be defined in a note).  What I have witnessed in this community effort is
that each sub-component typically has 1 or 2 people that are responsible
for the drive and energy to bring a particular BEP to completion, these are
the first authors.  And then there is someone has intellectual
responsibility for BIDS as a whole, who is like a cop on the beat, who
ensures that a particular BEP fits within the ecosystem (e.g. doesn't
conflict with core BIDS, doesn't bloat in scope)... as I understand it this
is @chrisfilo, though I may have missed it if others have played this role;
this seems a natural final author role.

As long as we clearly articulate our decided strategy, I think it's all
good.

**Comment by sappelhoff** [comment]
> Github would be a good idea if we started the BEPs on Github from the beginning. there will be missing attribution for work done in a Google doc first when it is brought over here.

There is a way to get the contributions from the Google Doc version history ... at least @choldgraf somehow managed to extract a list of emails for the iEEG list. Or did you do this manually Chris? 😲

**Comment by dorahermes** [comment]
For the BIDS-iEEG contributions @choldgraf and I have been keeping a manual list because we also got comments from people who send us emails rather than make comments on the google doc.

**Comment by jchoude** [comment]
LGTM.

**Comment by emdupre** [comment]
Is the thought to use defined first and last, and alphabetical within ? That would be my vote, personally :+1:

I wonder if this question is also worth pinging to the mailing list, especially for contributors who have been active in the past but have not yet switched to GitHub.

**Comment by mnarayan** [comment]
> We just have to start by accepting that it is impossible to do in a way that truly reflects effort in a fine grained way. The way we've done it on NIDM is to simply have first and last author chosen and everyone in between is alphabetical. If there are multiple people in those first and last roles does Zenodo allow "these authors jointly played the {first,last} author role"?

I have a slight preference for suggestion from @nicholst to pick alphabetical for middle authors. But okay with other suggestions also.

**Comment by melanieganz** [comment]
I am with @nicholst regarding deciding a first and last authorship and either random or alphabetical in between. I would agree though with @choldgraf that roles and requirements needed to be in first or last author positions should be clearly-defined and agreed-upon by the community.

**Comment by KirstieJane** [comment]
+1 on first & last defined with alphabetical in the middle.

I see the benefit of random, but I think too many readers of the citation (eg on someone's CV) will not realise that the order *is* random and will assume it means something. Alphabetical is a) obvious to the reader and b) much more commonly used.

**Comment by Gilles86** [comment]
> +1 on first & last defined with alphabetical in the middle.
> 
> I see the benefit of random, but I think too many readers of the citation (eg on someone's CV) will not realise that the order _is_ random and will assume it means something. Alphabetical is a) obvious to the reader and b) much more commonly used.

+1

**Comment by vcalhoun** [comment]
This sounds fine to me as well.  Though sometimes the 2nd first and 1st last fields can be useful if folks feel strongly about joint credit for substantial work when more than 2 are involved.

 

VDC

**Comment by effigies** [comment]
https://citation-file-format.github.io/ seems to what Zenodo is moving to over `.zenodo.json` snippets. (Announced [here](https://twitter.com/ZENODO_ORG/status/1420357001490706442).)

**Comment by Remi-Gau** [comment]
@bids-standard/everyone

PR #1115 would in effect start implementing adding contributors to our zenodo releases of the spec.

At the moment the PR would simply list ALL contributors alphabetically (no first or last authors)

**Comment by Remi-Gau** [comment]
Note that BIDS steering group is in favor of listing all contributors in alphabetical for the zenodo release.

https://github.com/bids-standard/bids-specification/pull/1115#issuecomment-1506970406
