### ISSUE TITLE
EEG - confusion between channels.tsv and electrodes.tsv

### ISSUE THREAD

**Issue by arnodelorme** [bids-standard/bids-specification#667]
This dataset for example (https://openneuro.org/datasets/ds002791/versions/1.0.0) has different channel names in its channels.tsv and electrodes.tsv files. 

sub-01/ses-naming/eeg/sub-01_ses-naming_run-1_electrodes.tsv
F10h	6.962	5.382	-2.191
F8	6.484	6.404	-0.14
AFF8h	5.699	7.208	1.791

sub-01/ses-naming/eeg/sub-01_ses-naming_run-1_channels.tsv 
E1	eeg	microV	1000	n/a	n/a	n/a	n/a	n/a	n/a	n/a
E2	eeg	microV	1000	n/a	n/a	n/a	n/a	n/a	n/a	n/a
E3	eeg	microV	1000	n/a	n/a	n/a	n/a	n/a	n/a	n/a
...

The specification suggests that the name should be the same. It also does not enforce that electrodes.tsv should have the same number of rows as channels.tsv.

https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html

Solutions:
1. Clarity in the specification that electrodes.tsv should have the same number of rows as channels.tsv
2. Change the validator to enforce that channel names are the same between electrodes.tsv and channels.tsv

**Comment by sappelhoff** [comment]
electrodes.tsv could have more electrodes than present in channels.tsv for example in the case where an EOG channel (1 channel) is recorded from 2 electrodes with bipolar referencing scheme.

**Comment by sappelhoff** [comment]
> The specification suggests that the name should be the same. It also does not enforce that electrodes.tsv should have the same number of rows as channels.tsv.

actually, could you please cite where you get that idea from? I read the parts of the spec again, and I cannot find that rule.

It also wouldn't make sense in my opinion, apart from the example about bipolar electrodes I listed above. --> Just thinking about a "normal" EEG recording with a reference and a ground electrode --> neither of these two electrodes are "channels" ... but they should be written down in electrodes.tsv.

Unless more information comes up, I would say that we should rather enhance the specification with one or two examles of why the `names` column in channels.tsv  and electrodes.tsv do NOT have to be exactly the same (in fact, they **cannot** be the same sometimes)

We hint at that in the intro:

> Note that for proper documentation of EEG recording metadata it is important to understand the difference between electrode and channel: An EEG electrode is attached to the skin, whereas a channel is the combination of the analog differential amplifier and analog-to-digital converter that result in a potential (voltage) difference that is stored in the EEG dataset. We employ the following short definitions:
>-    Electrode = A single point of contact between the acquisition system and the recording site (for example, scalp, neural tissue, ...). Multiple electrodes can be organized as caps (for EEG), arrays, grids, leads, strips, probes, shafts, and so on.
>-    Channel = A single analog-to-digital converter in the recording system that regularly samples the value of a transducer, which results in the signal being represented as a time series in the digitized data. This can be connected to two electrodes (to measure the potential difference between them), a magnetic field or magnetic gradient sensor, temperature sensor, accelerometer, and so on.

**Comment by CPernet** [comment]
we could suggest to use the the same names for electrodes and channels

**Comment by dorahermes** [comment]
On the topic of adding some examples where it is more difficult to match the positions (in addition to bipolar recordings):

Example 1: a dataset in which an ECG channel is recorded simultaneously with SEEG. The ECG electrode is not present or is n/a in _electrodes.tsv 

Example 2: EEG and SEEG are simultaneously recorded and the EEG positions may not be present or are in a different space than the SEEG positions.

However, if a name in _channels.tsv is not present in _electrodes.tsv that maybe should raise a flag?
