### ISSUE TITLE
MAX_PATH issue on Windows ?

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#674]
Could not find an issue where this was raised in the specs or for the validator and to my knowledge this is not mentioned in the specs so I am opening an issue.

In brief, because Windows imposes limitations on the [fullpath length of filenames](https://www.howtogeek.com/179173/ask-htg-why-is-windows-reporting-this-folder-is-too-long-to-copy/) to 256 characters, would it make sense to cap the length of full path of filenames.

This sounds like an edge case but if people start using several of the entities in some filename and they get very verbose with their labels, this could still be an issue.

Also thinking about the fact that derivatives name might have the tendency to get longer.

**Comment by sappelhoff** [comment]
I didn't look into it too deep, but perhaps this is related: https://github.com/bids-standard/bids-validator/issues/190

**Comment by effigies** [comment]
IMO this is outside the scope of the spec. I would suggest we move this discussion to the validator.

**Comment by Remi-Gau** [comment]
Good catch! Definitely a lead into a potential rabbit-hole. :rabbit: 

OK so it is mentioned in the bids-2-devel: https://github.com/bids-standard/bids-2-devel/issues/8

I think that contrary to what that issue mentions it could be more of an issue for Windows than for AFNI.

Not sure how many datasets in the wild could be affected by that problem. 

Also I think it may be a nice thing to issue a warning for long file names.

**Comment by Remi-Gau** [comment]
> IMO this is outside the scope of the spec. I would suggest we move this discussion to the validator.

OK I will close this here for now, though I suspect that maybe this validator rule should eventually make its way back into the specs.
