### ISSUE TITLE
Extend BIDS format to magnetic resonance spectroscopy

### ISSUE THREAD

**Issue by amirshamaei** [bids-standard/bids-specification#680]
I am working on a general format for MRS and MRSI data. I read the BIDS format article; it has been stated that it will support spectroscopy in the future. To the best of my knowledge, it has not happened yet.  but there are some works, for example, this repo(https://github.com/wexeee/spec2nii) uses a JSON sidecar file for storing parameters. However; It needs some collaborations to reach a consensus about open issues. I would suggest extending BIDS to MRS data.

**Comment by effigies** [comment]
BEP 022 (https://bids.neuroimaging.io/bep022) was working on this. As I understand it, the lead contributors no longer have time to work on it, so it could use some new interested parties to push it forward.

**Comment by amirshamaei** [comment]
> BEP 022 (https://bids.neuroimaging.io/bep022) was working on this. As I understand it, the lead contributors no longer have time to work on it, so it could use some new interested parties to push it forward.

Thank you very much. As I am new in this community; could you please tell me how I can contribute to this extension

**Comment by effigies** [comment]
I think the place to start is [this thread](https://forum.mrshub.org/t/bids-for-spectroscopy/83/40) on MRSHub.

**Comment by sappelhoff** [comment]
@amirshamaei please feel free to reopen this if you need more guidance.

**Comment by gdevenyi** [comment]
I'd like this reopened as it appears there has been movement in the nifti-mrs file standard:
https://github.com/wexeee/mrs_nifti_standard

**Comment by amirshamaei** [comment]
@gdevenyi  Thanks a lot, I have been working with them for a while.
