### ISSUE TITLE
Fix example for iEEGElectrodeGroups field from object to string type

### ISSUE THREAD

**Issue by eceboran** [bids-standard/bids-specification#686]
I would like to use the field name `iEEGElectrodeGroups` in the file `*_ieeg.json` for my BIDS-iEEG dataset. However, I couldn't see any examples of this online.

What does an input to this field look like? 

I tried with

```JSON
"iEEGElectrodeGroups": {
        "depthAmgL": "1x8 depth electrode in the left amygdala",
        "depthAmgR": "1x8 depth electrode in the right amygdala"
    }
```

but it is not accepted for a valid BIDS dataset.

I had to use the following to have a valid BIDS dataset.

```JSON
"iEEGElectrodeGroups": "depthAmgL: 1x8 depth electrode in the left amygdala, depthAmgR: 1x8 depth electrode in the right amygdala"
```

which is less elegant in my opinion, in the sense that it is not the best way of writing it to be read automatically.

Could you describe more in detail how this field is used, and provide examples?

**Comment by tsalo** [comment]
It looks like the specification defines iEEGElectrodeGroups as a `string`, but the example in the table is an `object of strings` (`{'grid1': "10x8 grid on left temporal pole", 'strip2': "1x8 electrode strip on xxx"}`). In the validator, it looks like it only accepts a string (see [here](https://github.com/bids-standard/bids-validator/blob/10b6e62c1fb61157394a0eb187fa506ec4e48f2d/bids-validator/validators/json/schemas/ieeg.json#L37)).

@sappelhoff do you know if the example in the specification is wrong, or if the format is?

**Comment by sappelhoff** [comment]
not sure, let's ask some iEEG people @dorahermes @dvanblooijs

**Comment by dvanblooijs** [comment]
we describe the iEEGElectrodeGroups like this "iEEGElectrodeGroups": "ECoG;C[4x8];IHH[2x8];strip;IHL[1x8];depth;D[1x6];" and this is accepted by the bids validator. The specific location is present in the electrodes.tsv, with coordinates and DKT and Destrieux atlases. The code for describing it is  ieeg_json.iEEGElectrodeGroups           = 'ECoG;C[4x8];IHH[2x8];strip;IHL[1x8];depth;D[1x6];' (which is a string).

**Comment by dorahermes** [comment]
This was added, because there are some software packages for iEEL electrode localization that use the information of grid dimensions (e.g. iElvis, Arjen Stolk's iEEG pipeline), but it seems like neither an object of strings nor one string like @dvanblooijs is using could be easily parsed automatically for this, so my first thought is that a descriptive string would be ok, because imposing more strict object of string rules may give the appearance that is has to be parsable in a specific fashion.

**Comment by sappelhoff** [comment]
Thanks for your comments! I think we should then fix the example in the specification from `{'grid1': "10x8 grid on left temporal pole", 'strip2': "1x8 electrode strip on xxx"}` to a string. Everything else seems to be in order.
