### ISSUE TITLE
make ce-<label> optional for bold/sbref modalities

### ISSUE THREAD

**Issue by dasturge** [bids-standard/bids-specification#69]
Some studies make use of mion/ferumoxytol as a contrast enhancing agent for fmri data, e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4843437/

should also be considered for the epi modality, as it could be present while this field map is acquired.

**Comment by chrisfilo** [comment]
Sounds reasonable to me. Could you open a Pull Request with those changes? Thanks in advance.
