### ISSUE TITLE
'Stimuli' cell inputs are switched in bids_export documentation. 

### ISSUE THREAD

**Issue by MarcRosenkranz** [bids-standard/bids-specification#691]
Hi,

I was trying to load in stimuli files via a script. According to the documentation a cell should follow 'stimuli' with the arrangement:
{ 'stim1', 'Users/xxx/stim1.mp3' }
For me it worked only when I switched the cell entries to:
{ 'Users/xxx/stim1.mp3',  'stim1' }

**Comment by sappelhoff** [comment]
Hi @MarcRosenkranz, your question seems to be related to a "bids_export" tool. Are you talking about EEGLAB's [bids_export](https://github.com/sccn/bids-matlab-tools/blob/master/bids_export.m) If yes, I advise you to pose your question on the mailing list, or on this GitHub repository: https://github.com/sccn/bids-matlab-tools

This is the wrong place to discuss your issue. Here we only discuss the BIDS specification per se, not tools, and not usage questions.

**Comment by MarcRosenkranz** [comment]
Sorry about that. I will post it somewhere else. Thank you.

**Comment by sappelhoff** [comment]
No worries and good luck!
