### ISSUE TITLE
`IntendedFor` fields needs to be harmonized

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#718]
Thanks a lot for your feedback @effigies. I investigated the `IntendedFor` field a bit, see below:

I get the feeling that the different `IntendedFor` fields should be harmonized.

I think this should be its own issue - for the sake of this PR, I will see how much "easy improvement" I can salvage without touching/impacting `IntendedFor`.

in particular, we should clarify that IntendedFor contains a filepath (str) or list of filepaths ... and how these filepaths are to be made up ... if absolute or relative ... to what reference if relative, etc. see #471 

Also I think all of those should accept a str *or* array of str (currently some only accept str).

Lastly, the "descriptions" should be homogenized ... and then the special aspect of using "IntendedFor" with a particular usecase can be added at the end of the description ... or something similar. Just to get rid of this currently confusing diversity in descriptions.

# linking fieldmap data (Recommended, str or array of str)

https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#using-intendedfor-metadata

> Contains one or more filenames with paths relative to the participant subfolder. The path needs to use forward slashes instead of backward slashes. This field is OPTIONAL, and in case the fieldmaps do not correspond to any particular scans, it does not have to be filled.

# link ASL timeseries and m0 scan (Required, str or array or str)

https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#m0scan-metadata-fields

> One or more filenames with paths relative to the subject subfolder, with forward slashes, referring to ASL time series for which the `*_m0scan.nii[.gz]` is intended.

# MEG: link MRI(s) (Optional, str or array of str)

https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#coordinate-system-json-_coordsystemjson

> Path or list of path relative to the subject subfolder pointing to the structural MRI, possibly of different types if a list is specified, to be used with the MEG recording. The path(s) need(s) to use forward slashes instead of backward slashes (for example, ses-/anat/sub-01_T1w.nii.gz).

# EEG: Link MRI/CT (Optional, str)

https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html#coordinate-system-json-_coordsystemjson

> Relative path to associate the electrodes, landmarks and fiducials to an MRI/CT.

# iEEG: Link MRI7CT/Photograph (Recommended, str)

https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/04-intracranial-electroencephalography.html#coordinate-system-json-_coordsystemjson

> This can be an MRI/CT or a file containing the operative photo, x-ray or drawing with path relative to the project folder. If only a surface reconstruction is available, this should point to the surface reconstruction file. Note that this file should have the same coordinate system specified in iEEGCoordinateSystem. For example, T1: sub-<label>/ses-<label>/anat/sub-01_T1w.nii.gz Surface: /derivatives/surfaces/sub-<label>/ses-<label>/anat/sub-01_T1w_pial.R.surf.gii Operative photo: /sub-<label>/ses-<label>/ieeg/sub-0001_ses-01_acq-photo1_photo.jpg Talairach: /derivatives/surfaces/sub-Talairach/ses-01/anat/sub-Talairach_T1w_pial.R.surf.gii

_Originally posted by @sappelhoff in https://github.com/bids-standard/bids-specification/issues/700#issuecomment-768960234_

**Comment by Remi-Gau** [comment]
Related to `intended for` and raised in the last bids-matlab meeting.

`intended for` is defined as: 

>Contains one or more filenames with paths relative to the participant subfolder. The path needs to use forward slashes instead of backward slashes. This field is OPTIONAL, and **in case the fieldmaps do not correspond to any particular scans, it does not have to be filled**.

The part in bold seems to have 2 possible meanings depending on how one understands 'particular':

- Strong assumption: if `intended for` is left empty then this means that the file can be used for any other (and possibly all) file (ex: one fiedmap for all the bold files).

- Weak assumption: if `intended for` is left empty then we don't know to what it should be applied and it is up to the user to take his chances or use information that's not in the dataset to figure out how to use it.

The wording should be changed to lift the ambiguity.

@tiborauer @ChristophePhillips
