### ISSUE TITLE
BEP-001 clarification thread

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-specification#721]
I'm working on getting some [BEP-001 example datasets](https://osf.io/k4bs5/) in shape prior to the spec release. As I have questions I'll post them here. Some of them may require spec clarification, so I'm opening the issue here rather than in the examples repo.

1) Working on ds-mp2rage, the current MP2RAGE files have the `inv` entity, but not `flip`. This makes sense to me in that they co-vary, so either could have equally validly been chosen. That said, the template [here](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data) declares `inv` and `flip` are both required for MP2RAGE. That does not seem to match anything else in the spec, though. Is this a problem with the template?

2) ds-mtsat initially had `acq-T1w`, `acq-MTon` and `acq-MToff`. I changed these to `flip-2`, `flip-1_mt-on` and `flip-1_mt-off`. Was that correct? We'll need to add metadata, but that can go in examples, as long as we get the baseline issues done here.

---

More questions to come as I come up with them.

cc @agahkarakuzu @Gilles86 @ChristophePhillips (please add other BEP-001/qMRI people I've missed) @bids-standard/maintainers

---

Converted datasets for your approval:

* [ ] https://gin.g-node.org/markiewicz/ds-mp2rage
* [ ] https://gin.g-node.org/markiewicz/ds-mp2rageme
* [ ] https://gin.g-node.org/markiewicz/ds-mpm
* [ ] https://gin.g-node.org/markiewicz/ds-mtsat
* [ ] https://gin.g-node.org/markiewicz/ds-qsm
* [ ] https://gin.g-node.org/markiewicz/ds-sa2rage
* [ ] https://gin.g-node.org/markiewicz/ds-vfa

**Comment by Gilles86** [comment]
Hey @effigies 

Great to hear that you are working on this!

The central idea of MP2RAGE is that you acquire the largely same image for two different _inversion times_ that are hence T1 and PD-weighted.

For effiency reasons, these two images _usually_ have different flip angles, but they absolutely don't have to (whereas by definition they have to have different inversion times). I would, thus, like in my example datasets on [osf](https://osf.io/k4bs5/), only use the `inv-` key/value pairs in the file names. I cannot think of any use case where it makes sense to me to use the `flip-` key/value pair in the file name of MP2RAGE files, but maybe one of the other cc'd people can!

-Gilles

**Comment by effigies** [comment]
Okay, it looks like we need to remove `flip` from being a mandatory entity in the MP2RAGE template. This is probably in the schema.

**Comment by effigies** [comment]
I've started datalad versions of all of the datasets at https://gin.g-node.org/markiewicz. All of the NIfTIs have been truncated. For a few I've also gone through the JSON files.

**Comment by agahkarakuzu** [comment]
That's a great catch, thanks @effigies. The `flip` in the `MP2RAGE` scheme should have been a leftover that slipped through the cracks. What you started on https://gin.g-node.org/markiewicz looks great, sorry I've been MIA due to other occupancies, should I contribute on G-Node when I can?

**Comment by effigies** [comment]
You can do that or comment here. If this looks good enough to move to a `bids-examples` PR, I'm happy to move there, which might be a little easier.

**Comment by effigies** [comment]
For `RepetitionTimeExcitation` and `RepetitionTimePreparation`, these are placed under [Anatomy Imaging Data](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data). These apply generally to MRI, correct? For example, this is defined in [ds-mpm/sub-01/fmap/sub-01_acq-bodyMTw_RB1COR.json](https://gin.g-node.org/markiewicz/ds-mpm/src/master/sub-01/fmap/sub-01_acq-bodyMTw_RB1COR.json#L10).

**Comment by agahkarakuzu** [comment]
@effigies in absence of `RepetitionTimePreparation`, `RepetitionTime` and `RepetitionTimeExcitation` correspond to the same thing, and yes, both apply generally to MRI. It is just that the current definition of `RepetitionTimeExcitation` is closer to the general MRI more than the current `RepetitionTime` is. 

Is it feasible to accept both `RepetitionTime` and `RepetitionTimeExcitation` (when there is no `RepetitionTimePrep`) valid until there is a more radical change about this in, let say, `v2.0` ?

**Comment by effigies** [comment]
Moving discussion to bids-standard/bids-examples#245.

I think we can push off expanding RTE/RTP to non-anatomical data in a backwards-compatible way to the next release. Nothing stops people from putting the metadata in unofficially for the moment.
