### ISSUE TITLE
Is complex-valued CBV possible?

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#726]
This stems from https://github.com/bids-standard/bids-validator/pull/1125#discussion_r572958239. @effigies and I are not sure if cerebral blood volume (CBV) data can have magnitude and phase components. I _assume_ that, as an MRI data type, it is inherently a complex signal that, most often, scanners only retain the magnitude component of, but I could be wrong.

Tagging @TheChymera based on the original comment.

**Comment by TheChymera** [comment]
Similarly to BOLD, it is a physiological contrast. It can be obtained either via a contrast agent, or via arterial spin labeling, but the way in which the data is stored is exactly the same as BOLD.

**Comment by tsalo** [comment]
Thanks. We can allow `part` with the CBV suffix then.
