### ISSUE TITLE
MEEG+iEEG --> Make it a requirement that channels in bids sidecar and raw file are in order

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#727]
came up in https://github.com/mne-tools/mne-bids/issues/697#issuecomment-776537456

We currently have the following in the spec:

EEG: 
> To avoid confusion, the channels SHOULD be listed in the order they appear in the EEG data file.

[source](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/03-electroencephalography.html#channels-description-_channelstsv)

iEEG:

> Channels SHOULD appear in the table in the same order they do in the iEEG data file.

[source](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/04-intracranial-electroencephalography.html#channels-description-_channelstsv)

MEG:

> To avoid confusion, the channels SHOULD be listed in the order they appear in the MEG data file.

[source](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#channels-description-_channelstsv)

our proposal (cc @hoechenberger @agramfort ) is to turn this "SHOULD" into a "MUST". This would be in line with the BIDS principle to place most burden on the dataset curation stage, as that's a one-time-burden. All steps that follow after this will have an easier time. For example, tools can rely on the sidecar files, and don't have to double check with the raw files.

Potential issue(s):

- We currently cannot validate a MUST, because we lack JS readers for ephys formats
- Breaking backwards incompatibility for all currently existing datasets that did not follow the RECOMMENDATION ("SHOULD") that we now want to turn into a REQUIREMENT ("MUST")

Somewhat parallel issue(s):

- #667

**Comment by hoechenberger** [comment]
+100 on this one.

**Comment by agramfort** [comment]
+1000 :)

>
