### ISSUE TITLE
*_channels.tsv: "units" column should be "unit"

### ISSUE THREAD

**Issue by hoechenberger** [bids-standard/bids-specification#729]
In `*_channels.tsv` for MEG, EEG, and iEEG data, all column names except for `software_filters` and `units` are in the singular form. `software_filters` being plural does make sense because one may specify multiple filters per channel.

For `units`, however, I think the current specification introduces an inconsistency: to my knowledge, only a single measurement unit can be reasonably assigned to any given channel.

I would therefore propose to deprecate the `units` column in favor of a `unit` column.

Screenshot of the MEG specs:
<img width="748" alt="Screen Shot 2021-02-10 at 16 56 13" src="https://user-images.githubusercontent.com/2046265/107536171-c604de00-6bc1-11eb-8d65-9eaa89d8fd4d.png">

**Comment by sappelhoff** [comment]
I brought up some time in 2018 or 2019, but it was always deemed low impact and annoying, so we skipped it. Tracked here: https://github.com/bids-standard/bids-2-devel/issues/15

**Comment by hoechenberger** [comment]
Whoops, I must've missed this when searching existing issues. Closing as a dupe.
