### ISSUE TITLE
TODO for someone with superpower: invite BEP031 leads/members to the organization

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#732]
NB apparently I am lacking the powers (and not really seeking for them ;)) to invite people (but can create teams, odd)

and add to (freshly created) BEP031 team. (ideally there should be a team per each BEP to be able to easily alert BEP members, ATM there is only BEP009)

From https://bids.neuroimaging.io/bep031

- Marie-Hélène Bourget <marie-helene.bourget@polymtl.ca> - 
- Julien Cohen-Adad <jcohen@polymtl.ca> - @jcohenadad
- Alberto Lazari <alberto.lazari@univ.ox.ac.uk>
- Kurt Schilling <kurt.g.schilling.1@vumc.org> @schillkg
- Timo Dickscheid <t.dickscheid@fz-juelich.de>

**Comment by tsalo** [comment]
Done! I didn't realize you could invite email addresses... Now the leads just need to accept the invites.

**Comment by yarikoptic** [comment]
> Done! I didn't realize you could invite email addresses...

I didn't either! ;) THANKS!

**Comment by sappelhoff** [comment]
closing, because it seems to be done. Thanks for raising it (yarik) and doing it (taylor)
