### ISSUE TITLE
Discuss BEP021 derivatives for electrophys

### ISSUE THREAD

**Issue by robertoostenveld** [bids-standard/bids-specification#733]
Tonight we had a Zoom call to discuss the progress on BEP021 for which the draft is on http://bids.neuroimaging.io/bep021 on google docs. Some of the people that attended were @arnodelorme, @dorahermes, @guiomar, @jasmainak, @agramfort, but do not know the github handle of all. Please help to attend the others with a github presence by mentioning them here.

**Comment by robertoostenveld** [comment]
@jasmainak mentioned 

> The example dataset:
> 
> https://github.com/bids-standard/bids-examples/pull/171
> https://github.com/bids-standard/bids-examples/pull/161
> 
> I haven't looked too closely but I see that it was merged by Robert :) Perhaps a dataset to use for discussion?

**Comment by robertoostenveld** [comment]
The pull requests bids-standard/bids-examples#171 and bids-standard/bids-examples#161 refer to “derivatives”, but looking at the dataset at https://github.com/bids-standard/bids-examples/tree/master/eeg_face13 there is nothing that sets it apart from a regular raw BIDS EEG dataset. 

An example dataset that **is** a proper derivatives is https://github.com/bids-standard/bids-examples/tree/master/ds000001-fmriprep. Note, however, that there are quite some files in that derived dataset that have to be [ignored](https://github.com/bids-standard/bids-examples/blob/master/ds000001-fmriprep/.bidsignore) as they are not standardized (yet). 

Just some general pointers that relate to some topics we discussed:

On https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#derived-dataset-and-pipeline-description it is specified that a derived dataset is also a BIDS dataset. The derived dataset has some required and some recommended extra elements in the dataset_description. When you prepare an example/draft derived ieeg/eeg/meg dataset, please keep these in mind.

Also, on https://bids-specification.readthedocs.io/en/stable/05-derivatives/01-introduction.html it states "Derivatives are outputs of common processing pipelines, capturing data and meta-data sufficient for a researcher to understand and (critically) reuse those outputs in subsequent processing.” That lines up with what Scott and I were saying that a (derived) dataset should be (re)usable in its own right.

**Comment by jasmainak** [comment]
ping @adam2392 @hoechenberger

**Comment by guiomar** [comment]
Hi! I copy here the email too :)

Thanks everyone for the meeting today!

We thought that for the next meeting some of us could present some practical examples so we can have a starting point to discuss.
Preferably we could share the datasets in advance so everyone that has time can go over them and focus the discussion in the more problematic things.

Here's the link to the common derivatives specs merged in 1.4.0: 
https://bids-specification.readthedocs.io/en/stable/05-derivatives/01-introduction.html
There, "derivative" is defined as:

    Derivatives are outputs of common processing pipelines, capturing data and meta-data sufficient for a researcher to understand and (critically) reuse those outputs in subsequent processing. 

In line with what we have discussed.

Also note that there are some metadata fields to point to source data:
https://bids-specification.readthedocs.io/en/stable/05-derivatives/02-common-data-types.html

It's important to distinguish between two types of derivatives:
- pre-processed (in essence they are similar to source data - datatype remains unchanged)
- and processed (they are substantially different to source data - datatype changed)

So I think pre-processed derivatives can be easily accessible at this point (e.g. detrending, filtering, downsampling, re-referencing, etc).

In this logic I don't know where annotations may exactly fall. But they are also an important step (and I think that can be also interesting for other modalities and extensions).

Talk very soon!

**Comment by sappelhoff** [comment]
As far as I heard,  @smakeig (Scott Makeig) @nucleuscub (Ramon Martinez-Cancino) also attended

**Comment by robertoostenveld** [comment]
The discussion on this issue has been moved over to https://github.com/bids-standard/bep021/issues/5, where it can be discussed more specifically in the BEP021 "electrophys derivatives" repository.
