### ISSUE TITLE
Search box missing on bids-specification.readthedocs.io stable page

### ISSUE THREAD

**Issue by htwangtw** [bids-standard/bids-specification#744]
I rely on the search function to find BIDS sepc a lot. This morning I found that missing on the web page. Normally it's on the top right corner.

**Comment by sappelhoff** [comment]
what browser are you on? did you try:

- https://bids-specification.readthedocs.io/en/latest/ and
- https://bids-specification.readthedocs.io/en/stable/

For me it works (Ubuntu 18.04, latest firefox, and latest chrome)

**Comment by Remi-Gau** [comment]
Same here.

![Screenshot 2021-02-24 11:30:09](https://user-images.githubusercontent.com/6961185/108987542-b393a580-7693-11eb-8254-1c49c50a7417.png)

**Comment by Remi-Gau** [comment]
On a side note

@htwangtw : if you sometimes realize things that are in the specs are not findable via the search function of the doc (it has happened to me), do not hesitate to open an issue about it because I would not mind reducing the amount of random scrolling users have to do.

**Comment by htwangtw** [comment]
System spec:
Debian 10, Firefox 78.7.0esr (latest for Debian)
This is what I see:
![image](https://user-images.githubusercontent.com/13743617/108989887-036f6e00-768e-11eb-8fe7-9c2d52c24dd9.png)
When I switch to 1.4.1 or below the box appear again.

**Comment by effigies** [comment]
We should check whether there's been an mkdocs release.

**Comment by sappelhoff** [comment]
good point, it seems like our mkdocs theme (mkdocs material) *did* release though (2 days ago):

![image](https://user-images.githubusercontent.com/9084751/109008951-36c1f500-76ae-11eb-8679-8d33e23c7585.png)


perhaps that could have something to do with it

**Comment by effigies** [comment]
The mkdocs-material renders its own docs: https://squidfunk.github.io/mkdocs-material/

@htwangtw Are you able to see search there?

**Comment by htwangtw** [comment]
Nope. The search bar is not there.

**Comment by effigies** [comment]
That's good news, because it should be easier for them to fix upstream when you can confirm on their site. Could you report to https://github.com/squidfunk/mkdocs-material/issues?

**Comment by htwangtw** [comment]
I have submitted an issue there but I don't understand the requests - perhaps @effigies and @sappelhoff can help?

**Comment by sappelhoff** [comment]
He asked:

> Could you please check the developer console? I suspect that Firefox 78 is too old and is missing an ES6/7 feature we're using. Also please check if this issue is present with Material 6.2.8.

I don't know what you are supposed to check in the [developer console](https://developer.mozilla.org/en-US/docs/Tools/Web_Console) , but the issue does not exist for Material 6.2.8 as you mention in https://github.com/bids-standard/bids-specification/issues/744#issuecomment-784989264:

>  When I switch to 1.4.1 or below the box appear again.

anyhow, I recommend that you follow up in the issue on mkdocs-material, the maintainer of that repo can most likely be more helpful.

**Comment by htwangtw** [comment]
You are right I should just ask it there instead of falling back to people here. Still thanks for pointing out ver 1.4.1 is in Material 6.2.8

**Comment by sappelhoff** [comment]
>  Still thanks for pointing out ver 1.4.1 is in Material 6.2.8

actually, 1.4.1 was released 2020-10-13, so it most likely uses material `6.0.2` https://github.com/squidfunk/mkdocs-material/releases/tag/6.0.2

**Comment by effigies** [comment]
Checking the source https://bids-specification.readthedocs.io/en/bep-009/ is currently rendered with 6.2.8.

**Comment by htwangtw** [comment]
Some other people has reported the same issue. There is an avilible fix on their master branch now.

**Comment by effigies** [comment]
@htwangtw Can you verify that the issue is resolved:

* https://bids-specification.readthedocs.io/en/v1.5.0/
* https://bids-specification.readthedocs.io/en/stable/
* https://bids-specification.readthedocs.io/en/latest/

**Comment by htwangtw** [comment]
Yes they are all good now

**Comment by effigies** [comment]
Awesome. Thanks for noticing this and reporting it here and upstream!
