### ISSUE TITLE
Remaining formatting issues in tables

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#746]
2 other issues I have noticed that make my inner OCD unhappy:

-  ~~inconsistency in the format of the table headers in the spec: most of the time it is in bold but not always~~
- numeric examples in the tables concerning the content of json files are not "highlighted" and might not be as obvious to the reader.

For example

```markdown
Number of EEG channels included in the recording (for example, 128).
```

Should probably be:

```markdown
Number of EEG channels included in the recording (for example, `128`).
```

- inconsistencies in the rendering of string and numeric values for tables (mostly for stings)

Sometimes examples are written:

```
like this
```

and other times

```
`like that`
```

| **Column name** | **Requirement level** | **Description**                                                                                                                                                               |
|-----------------|-----------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| name            | REQUIRED              | Channel name (for example, FC1, Cz)                                                                                                                                           |
| units           | REQUIRED              | Physical unit of the value represented in this channel, for example, `V` for Volt, or `fT/cm` for femto Tesla per centimeter (see [Units](../02-common-principles.md#units)). |

_Originally posted by @Remi-Gau in https://github.com/bids-standard/bids-specification/issues/739#issuecomment-782854311_

**Comment by sappelhoff** [comment]
just noticed a similar "formatting" related PR: https://github.com/bids-standard/bids-specification/pull/786

I think if we don't put CIs into place to catch these soft, style related things, it'll be hard to maintain.

**Comment by Remi-Gau** [comment]
> just noticed a similar "formatting" related PR: #786
> 
> I think if we don't put CIs into place to catch these soft, style related things, it'll be hard to maintain.

Agreed. Though regarding the CI part we have to keep in mind that possibly a lot of this will be "encoded" in the metadata part of the awesome schema that @tsalo is working on.

So the style check will probably have to be done on some intermediate files after the macros are applied, no? I think you did some similar magic recently, am I right?

**Comment by sappelhoff** [comment]
> Agreed. Though regarding the CI part we have to keep in mind that possibly a lot of this will be "encoded" in the metadata part of the awesome schema that @tsalo is working on.

Indeed, and I think between Taylor and me we managed to purge a few more styling "bugs".

> So the style check will probably have to be done on some intermediate files after the macros are applied, no? 

Yes, since #774 these kinds of styling "bugs" would have to be fixed in the schema files ... OR on the spec **after** the schema is applied. --> But I think running a CI on the YAML file "descriptions" would be nicer:

https://github.com/bids-standard/bids-specification/blob/87ca2c1ee40eede9f41d92c30847cf2ef758b3b3/src/schema/metadata/Acknowledgements.yaml#L3-L5

We just need someone to spend a couple of "minutes to hours"™ to write a script and a GitHub Action to run it :sunglasses:
