### ISSUE TITLE
aslcontext.tsv and inheritance

### ISSUE THREAD

**Issue by noah10** [bids-standard/bids-specification#749]
The BIDS spec (v.1.5.0) has sections describing an [aslcontext.tsv ](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#_aslcontexttsv) file for use with ASL scans, and also the [inheritance principle](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#the-inheritance-principle), which says that instead of providing multiple identical metadata files you can provide a single one at a higher level whose contents will apply to lower levels.

Unfortunately, if you attempt to place a single aslcontext.tsv file at the top level of the dataset directory, the bids validator (v1.6.2) will tell you "Files with such naming scheme are not part of BIDS specification." (The same file, renamed `sub-<label>_ses-<label>_aslcontext.tsv` and placed in the sub/ses/perf directory with its corresponding nifti file, passes validation.)

Either this is a bug in the validator that should be fixed or the spec should be updated to explicitly say that the inheritance principle does not apply to the aslcontext.tsv file. (To me it looks like the former, but I'm no ASL expert.)

**Comment by effigies** [comment]
This seems like a good argument that ASL context files should be considered inheritable metadata, but I want to check in with @patsycle @HenkMutsaerts about whether this was already considered and rejected for some reason.

**Comment by sappelhoff** [comment]
Sounds like a good case for inheritance to me as well, but more ASL expert opinions would be appreciated.

Technical comment: This is the spot in bids-validator where `aslcontext.tsv` would need to be added: https://github.com/bids-standard/bids-validator/blob/5ee85764957b8b07681ac33c92b7d3052c01ce45/bids-validator/bids_validator/rules/top_level_rules.json#L1-L21

**Comment by ericearl** [comment]
I'm preparing some ASL data now and would like this inheritance feature for `aslcontext.tsv`. Is there any reason not to allow this, or at least add it as a feature in the schema-based validator?

**Comment by effigies** [comment]
They are inheritable in the schema-based validator.

**Comment by ericearl** [comment]
I'll try it there and let this issue here know what I find out.
