### ISSUE TITLE
Sourcedata structure constrained or not?

### ISSUE THREAD

**Issue by erdalkaraca** [bids-standard/bids-specification#758]
The chapter about sourcedata vs rawdata is a bit confusing from my point of view: on the one hand the sourcedata folder MUST be BIDS compliant, but ALTERNATIVELY it may not, see:

https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#source-vs-raw-vs-derived-data

It reads like "if the creatue is a dog it must bark but if it is an animal it may do anything" :-)

**Comment by tsalo** [comment]
It must be BIDS-ish if the folder is located in the BIDS dataset, but if it's not then you can organize it however you want.

`sourcedata` in BIDS dataset:
```Text
my-dataset/  # BIDS, aka raw data
    sourcedata/  # must be BIDS-ish
        sub-X/
    sub-X/
    [etc]
```

`sourcedata` _not_ in BIDS dataset:
```Text
my-dataset/  
    rawdata/  # BIDS, aka raw data
        sub-X/
        [etc]
    sourcedata/  # no need for BIDS-ish structure
```

**Comment by erdalkaraca** [comment]
Thanks,  @tsalo, that makes it much clearer.
