### ISSUE TITLE
BIDS support for .bmat file

### ISSUE THREAD

**Issue by ycAbout** [bids-standard/bids-specification#770]
Searched through the BIDS specification and this repository, cannot find any information for .bmat file. 
If would be nice for BIDS to support .bmat file.

cc
@gdevenyi

**Comment by tsalo** [comment]
Could you clarify what you mean by ".bmat" file? Is this a file format for MRI data? Physio data? Task data?

**Comment by ycAbout** [comment]
I am working on a project involves animal mri data, the .bmat file generated under dwi. 
I searched online, seems got more info under B-Matrices at http://brainsuite.org/processing/diffusion/file-formats/

**Comment by effigies** [comment]
cc @bids-standard/raw-mri-dwi for input

**Comment by marcelzwiers** [comment]
BIDS already supports bval & bvec files, it seems unnecessary to also support bmat files (which contains the same info)? Having two file formats for the same thing is what the standard tries to get rid of...

**Comment by sappelhoff** [comment]
@ycAbout I am closing this issue now based on @marcelzwiers answer. I am happy to re-open if you want to make a new point or continue the discussion :-)
