### ISSUE TITLE
TODO for someone with superpower: invite BEP032 leads/members to the organization

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#778]
ATM just
- [x] @SylvainTakerkart
- [x] and invite julia.sprenger of univ-amu.fr

if could right away add to https://github.com/orgs/bids-standard/teams/bep032/members - would be appreciated

**Comment by effigies** [comment]
@sylvaintakerkart added to BEP-032 and invited. @yarikoptic bumped to org owner.

**Comment by yarikoptic** [comment]
thank you @effigies !

**Comment by SylvainTakerkart** [comment]
yep, thanks @effigies !
