### ISSUE TITLE
Render diffs in macros-generated specification content in pull requests

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#788]
One concern about the increasing automation of the specification contents based on the schema is that pull requests no longer show diffs in the markdown files. Instead, the only diffs will generally be in the YAML files (or worse, the Python code), where it may not be clear what effect the changes will have on the rendered specification.

It would be great to have a bot or even just a CI step that shows how the PR's changes impact the macros-generated elements of the specification.

This stems from https://github.com/bids-standard/bids-specification/pull/774#pullrequestreview-645964932 and the 2021/04/27 BIDS maintainers call.

**Comment by Remi-Gau** [comment]
Do we still want to do this or are we happy with point to the rendered HTML for visualisation?

Personally the latter is fine with me.

**Comment by sappelhoff** [comment]
Latter is fine with me, too.

**Comment by Remi-Gau** [comment]
ok will close this for now.
@tsalo reopen if you feel otherwise
