### ISSUE TITLE
Specification of AssociatedEmptyRoom

### ISSUE THREAD

**Issue by hoechenberger** [bids-standard/bids-specification#790]
Hello,

MEG experimental data often comes with an associated "empty-room" recording, which is supposed to capture the signal recorded with no participant present.

BIDS allows to indicate **which** empty-room recording belongs to an experimental recording via the `AssociatedEmptyRoom` key in [`*_meg.json`](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#sidecar-json-_megjson). Specifically, the specs state the following:

> Relative path in BIDS folder structure to empty-room file associated with the subject’s MEG recording. The path needs to use forward slashes instead of backward slashes (for example, "sub-emptyroom/ses-/meg/sub-emptyroom_ses-_task-noise_run-_meg.ds").

Two questions came to my mind:

- The path is supposed to be "relative", but it's unclear to me what the reference point is supposed to be. Intuitively, I assumed it's either the location of `*_meg.json`, or of the experimental recording. However, the path in the example seems to be relative to the **BIDS root**. What is the correct way to specify `AssociatedEmptyRoom`?
- The path in the example has empty `ses` and `run` entities. I didn't know this was even valid. Is that a mistake?

For reference, this is the schema currently used for validation of `AssociatedEmptyRoom`. It's … under-complex and therefore didn't provide me with any additional clues:
https://github.com/bids-standard/bids-validator/blob/2f0ca2458cff47e1fd1f898c3a81aef370558085/bids-validator/validators/json/schemas/meg.json#L48-L59

Thanks for you help,

Richard

**Comment by sappelhoff** [comment]
Thanks for opening this Richard, ... it definitely needs some clarification ... and a bugfix for the example that you point out:

https://github.com/bids-standard/bids-specification/blame/master/src/04-modality-specific-files/02-magnetoencephalography.md#L136

> `"sub-emptyroom/ses-/meg/sub-emptyroom_ses-_task-noise_run-_meg.ds"`

This whole issue is very much related to the issues we have with `IntendedFor`:

- https://github.com/bids-standard/bids-specification/issues/471
- https://github.com/bids-standard/bids-specification/issues/718

cc @robertoostenveld @effigies
