### ISSUE TITLE
Add in internal links

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#8]
For example, linking from the table of contents to the particular section.

**Comment by PeerHerholz** [comment]
Anyone already working on this? Otherwise, I would give it a try. 
As it's "just" about adding links, I assume the discussion in #18 and the possible
outcomes won't influence this, eh?

**Comment by franklin-feingold** [comment]
I apologize for the delayed response! If you would like to give this a try no problem! We have landed on using mkdocs for the rendering of the specification (the choice of rendering would have affected the internal links). Thank you for offering to try this!

**Comment by franklin-feingold** [comment]
update - I am going to start going through and adding internal links. Please ping me if you would like to help!
