### ISSUE TITLE
inconsistent style for the folder structure in the examples

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#807]
Most examples folder structure in the specs are of the form:

```
sub-01/
    ses-test/
        sub-01_ses-test_task-overtverbgeneration_bold.json
        sub-01_ses-test_task-overtverbgeneration_run-2_bold.json
        anat/
            sub-01_ses-test_T1w.nii.gz
        func/
            sub-01_ses-test_task-overtverbgeneration_run-1_bold.nii.gz
            sub-01_ses-test_task-overtverbgeneration_run-2_bold.nii.gz
```

But I realized that those in the qMRI page are more of the "tree" type:

```
└── sub-01/
     └── anat/
         ├── sub-01_inv-1_part-mag_MP2RAGE.nii.gz
         ├── sub-01_inv-1_part-phase_MP2RAGE.nii.gz
         ├── sub-01_inv-1_MP2RAGE.json
         ├── sub-01_inv-2_part-mag_MP2RAGE.nii.gz
         ├── sub-01_inv-2_part-phase_MP2RAGE.nii.gz
         └── sub-01_inv-2_MP2RAGE.json
```

This is a minor difference that it would be nice to standardize.

Even though it represents more work, I am tempted to make the "tree" version the default for the example.

The main reason is that it makes them even more visually distinct than the filename templates.

Any thoughts?

**Comment by effigies** [comment]
As long as they look okay in HTML and PDF, I have no problem with the tree style. I think they're mostly going to be auto generated from schema, so the additional work should be minimal.

**Comment by Remi-Gau** [comment]
wait... the examples are going to be auto-generated or the filename templates ? It is the latter, right?

then in this case we would just need to make sure that all the examples have a non-tree style.

**Comment by sappelhoff** [comment]
I like the tree style pipes, but they break in the PDF, see https://github.com/bids-standard/bids-specification/issues/766

Although that issue does not seem to reduce legibility, so it may be fine to change all examples to use the tree style pipes.

In any case, +1 for consistency.

And I was not aware that we'd turn examples into schemas?

**Comment by effigies** [comment]
I misread and thought we were talking templates...

**Comment by tsalo** [comment]
This might be useful for making tree-like templates: https://realpython.com/directory-tree-generator-python/

**Comment by Remi-Gau** [comment]
Thanks @tsalo 
Will have a look at that

**Comment by Remi-Gau** [comment]
> This might be useful for making tree-like templates: https://realpython.com/directory-tree-generator-python/

@tsalo 
I see that you have started creating some code to generate those examples.

Let me know if you want me to generate the macro calls in the markdown files so that I am not completely useless on that front.

**Comment by tsalo** [comment]
I didn't get very far with the code, unfortunately. I haven't circled back to it yet, so if you are willing to take a crack at it, that would be awesome. Or anyone else who is interested too.
