### ISSUE TITLE
Specify allowed values for entities that requires specific values in bids schema

### ISSUE THREAD

**Issue by soichih** [bids-standard/bids-specification#809]
Ref > 
https://github.com/bids-standard/bids-specification/blob/c0434124f4b07fd53af925aecae124c2a9102a0b/src/schema/entities.yaml#L169

Would it make sense to enumerate all allowed values for certain entities like this?

```
    options:
      - phase
      - mag
      - real
      - imag 
```

Downstream apps (ezBIDS, bids-validator, etc) can then use this information to let user pick / validate from one of the allowed values?

**Comment by tsalo** [comment]
Ah, I actually have a PR for this: #792. It's a bit more expansive than this issue, but could be scaled back if necessary.
