### ISSUE TITLE
inconsistencies between text and table for channels.tsv for iEEG

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#817]
The text mentions:

> The two required columns are channel name and type.

Whereas the table lists 5 required columns.

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html#channels-description-_channelstsv

Suggestion: removing the mention of required columns in the text and only rely on the table

Do the same for the EEG datatype (no inconsistency there but this is another duplication of the same information).

**Comment by dorahermes** [comment]
+1 on consistency with EEG and MEG: keep name, type and units as required
