### ISSUE TITLE
CT scans as a reference for iEEG electrode coordinates

### ISSUE THREAD

**Issue by Aaronearlerichardson** [bids-standard/bids-specification#826]
Under the current release of BIDS, iEEG files need a coordinate system to identify electrode locations. These coordinate system files need a reference scan, which the [specification claims may be MRI or CT scans](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html#recommended-3d-coordinate-systems). However CT scans are [not yet covered under the specification](https://docs.google.com/document/d/1fqnJZ18x5LJC8jiJ8yvPHUGFzNBZ6gW2kywYrUKWtuo/edit#heading=h.bs4ewiqm3qrq), and so cannot be included or referenced normally. 

How difficult would it be to add CT scans to the specification? If that isn't easily doable, is there a BIDS compliant way of referencing these CT scans while still being BIDS compliant?

**Comment by sappelhoff** [comment]
Hi @Aaronearlerichardson, there is a BIDS extension proposal (BEP) under way for CT data, where input is wanted: https://bids.neuroimaging.io/bep024

In the meantime I think that @dorahermes or @alexrockhill  or @adam2392 may have dealt with this problem to offer good advice.

**Comment by alexrockhill** [comment]
In my ieeg analysis pipeline, the CT is registered to the MR before determining the locations of the electrode contacts. Even if the contacts are found first, they could just be transformed to MRI space using the MRI affine. I don't know of a use-case where you have an intracranial recording without an MR so this seems like a good enough solution for the present, but maybe it would be nice to add a CT to the coordinate references at some point.

**Comment by Aaronearlerichardson** [comment]
Our data also includes MR for co-registration, so @alexrockhill's solution looks to be sufficient for our purposes. Thank you!

**Comment by sappelhoff** [comment]
Closing this as resolved for now. When https://bids.neuroimaging.io/bep024 picks up speed, the best-practice solution may change.
