### ISSUE TITLE
Just FYI: the schema is being used by the tools already!!!

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#829]
It is exciting!!!

look at this

https://github.com/brainlife/ezbids/search?q=bids-specification&type=code

Burn upon reading!

**Comment by soichih** [comment]
![image](https://user-images.githubusercontent.com/923896/125000351-2e93a200-e01e-11eb-9d6b-4122497413bd.png)

**Comment by tsalo** [comment]
That's awesome! I'm glad it's proving useful.
