### ISSUE TITLE
Add links to specific bids-example in the specification

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#842]
I just realized that the EEG page links to some specific examples from the BIDS example repo:
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html

I wonder if it would not be a good thing to generalize to other modalities too.

Any thoughts on this?

**Comment by sappelhoff** [comment]
I think that's a good idea. For some modalities it'll be easier to find a good place (e.g., separate pages like ieeg) for these links than for others (MRI modalities are all on a big page), but should all be doable. Some modalities have huge amounts of examples (MRI) so it'll be a good opportunity to identify the most helpful 3 and link to them.

**Comment by Remi-Gau** [comment]
OK will start with the easier ones...
And will most likely getting started on this when tackling the MRI page... :stuck_out_tongue_closed_eyes:
