### ISSUE TITLE
Recap table for "volume timing"?

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#85]
As it is now there are different ways to describe when each functional volume was acquired using the 5 following fields (AFAICT): 
- `DelayTime`
- `AcquisitionDuration`
- `SliceTiming`                       
- `RepetitionTime`
- `VolumeTiming`   
  
Some are of those fields are mutually exclusive and some options are only available for sparse sequences.

I had started working on a table to add to the specs that would recapitulate all those possibilities and might be a bit quicker than parsing sentences like:
> If the field is not present it is assumed to be set to zero. This field is REQUIRED for sparse sequences using the RepetitionTime field that do not have the SliceTiming field set to allowed for accurate calculation of "acquisition time". This field is mutually exclusive with `VolumeTiming`.

Should I give it a go and see if it helps?

**Comment by chrisfilo** [comment]
I think this would be a useful clarification to add - thank you!

**Comment by Remi-Gau** [comment]
Below is a first attempt at what such table would look like before I send it as a PR. 
I have also quoted the parts from the specs that I used to build the table.

What do you think?

**Legend**
[X] --> has to be filled
[ ] --> has to be left empty
empty cell --> can be specified but not required


|                   | RepetitionTime | SliceTiming | AcquisitionDuration | DelayTime | VolumeTiming |
|-------------------|:--------------:|:-------------:|:---------------------:|:-----------:|:--------------:|
| option 1          |       [X]      |             |         [ ]         |           |      [ ]     |
| option 2          |       [ ]      |     [X]     |                     |    [ ]    |      [X]     |
| option 3          |       [ ]      |             |         [X]         |    [ ]    |      [X]     |
| sparse sequence 1 |       [X]      |     [X]     |         [ ]         |           |      [ ]     |
| sparse sequence 1 |       [X]      |     [X]     |         [ ]         |    [X]    |      [ ]     |
| sparse sequence 1 |       [X]      |             |         [ ]         |    [X]    |      [ ]     |

> SliceTiming is REQUIRED for sparse sequences that do not have the DelayTime field set.
> 
> RepetitionTime  is mutually exclusive with VolumeTiming
> 
> VolumeTiming is mutually exclusive with RepetitionTime and DelayTime. If defined, this requires acquisition time (TA) be defined via either SliceTiming or AcquisitionDuration be defined.
> 
> DelayTime is REQUIRED for sparse sequences using the RepetitionTime field that do not have the SliceTiming field set to allowed for accurate calculation of "acquisition time". This field is mutually exclusive with VolumeTiming.
> 
> AcquisitionDuration field is REQUIRED for sequences that are described with the VolumeTiming field and that not have the SliceTiming field set to allowed for accurate calculation of "acquisition time". This field is mutually exclusive with RepetitionTime.

**Comment by chrisfilo** [comment]
LGTM - I would open a PR at this stage.

Best,
Chris

**Comment by Remi-Gau** [comment]
Dealt with by pull request #87.
