### ISSUE TITLE
"LGTM" tool warns about regexp for "remove_internal_links" function (for PDF build)

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [bids-standard/bids-specification#852]
Here are the two LGTM warnings:
* https://lgtm.com/projects/g/bids-standard/bids-specification/snapshot/225bf2292f8dc5754a4829c837074b91ad9d9980/files/pdf_build_src/process_markdowns.py?sort=name&dir=ASC&mode=heatmap#x48aac9687c9e224f:1
* https://lgtm.com/projects/g/bids-standard/bids-specification/snapshot/225bf2292f8dc5754a4829c837074b91ad9d9980/files/pdf_build_src/process_markdowns.py?sort=name&dir=ASC&mode=heatmap#x6ea466000e63cf12:1

The relevant lines of code:
* [line 114 of `pdf_build_src/process_markdowns.py`](https://github.com/bids-standard/bids-specification/blob/28ad463/pdf_build_src/process_markdowns.py#L114)
```python
        primary_pattern = re.compile(r'\[((?!http).[\w\s.\(\)`*/–]+)\]\(((?!http).+(\.md|\.yml|\.md#[\w\-\w]+))\)')  # noqa: E501
```
* [line 117 of `pdf_build_src/process_markdowns.py`](https://github.com/bids-standard/bids-specification/blob/28ad463/pdf_build_src/process_markdowns.py#L117)
```python
        primary_pattern = re.compile(r'\[([\w\s.\(\)`*/–]+)\]\(([#\w\-._\w]+)\)')
```

Indeed, there are two **`\w`** within **classes** of characters delimited by [] and not groups of characters delimited by ():
* **`[\w\-\w]`**
* **`[#\w\-._\w]`**

See [Duplication in regular expression character class](https://lgtm.com/rules/7880099/):
> Character classes in regular expressions represent sets of characters, so there is no need to specify the same character twice in one character class. Duplicate characters in character classes are at best useless, and may even indicate a latent bug.
> 
> ### Recommendation
> 
> Determine whether a character is simply duplicated or whether the character class was in fact meant as a group. If it is just a duplicate, then remove the duplicate character. If was supposed to be a group, then replace the square brackets with parentheses.

**Comment by sappelhoff** [comment]
as mentioned in https://github.com/bids-standard/bids-specification/pull/855#pullrequestreview-736032140, this should probably be fixed as part of #596
