### ISSUE TITLE
Should spell out prevention for case-insensitive collisions

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#857]
## problem in detail.

the encounter life cycle: 
- git on Mac and Windows would complain that file system is case insensitive while cloning a repository where there are files which would collide if case is dropped : https://github.com/datalad/datalad/issues/5925
- while proposing a solution https://github.com/PennLINC/HBN_BIDS/pull/1 , a [valid question was asked](https://github.com/PennLINC/HBN_BIDS/pull/1#issuecomment-902817095) by @mattcieslak - "how did this pass the validator?"

and well -- upon my search in bids-specification or bids-validator I found no relevant hits.  It seems that BIDS nohow instructs to avoid such collisions --  in https://bids-specification.readthedocs.io/en/stable/02-common-principles.html we just say "<label> - an alphanumeric value, possibly prefixed with arbitrary number of 0s for consistent indentation, for example, it is rest in task-rest following task-<label> specification."

I think we should 
- extend `label` description that the value MUST be unique and present in a single casing (e.g. there should also be no `sub-S1` and `sub-s1` in the same dataset ).
- bids-validator should verify that there is no such collisions (e.g. crude test is `len(set(paths)) == len(set([p.lower() for p in paths]))`) and issue ERROR

**Comment by sappelhoff** [comment]
Thanks for bringing this up, I wonder why we didn't run into problems with this much sooner. My gut feeling tells me that your proposed (breaking) change is good and should go into BIDS 1.x as a "bugfix".
