### ISSUE TITLE
[INFRA] Add a .gitattributes file to enforce line endings

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [bids-standard/bids-specification#860]
As seen in #859.

Suggested solution documented in this comment: https://github.com/bids-standard/bids-specification/pull/859#issuecomment-903549146

**Comment by Remi-Gau** [comment]
I think we discussed this a while back (can't remember where) and said that we'd cross that bridge when we get to it.

Personally ok with crossing it now.

**Comment by sappelhoff** [comment]
> I think we discussed this a while back (can't remember where) and said that we'd cross that bridge when we get to it.

Thanks, that reminded me as well ... but I cannot find that issue/PR/conversation again :( if you know where it is, Remi - could you please crosslink to here?

**Comment by Remi-Gau** [comment]
Sweet baby jesus on a pogo stick: that took quite a bit of github archeology to dig that convo, but here it is (in the validator repo)

https://github.com/bids-standard/bids-validator/pull/1134#discussion_r559558156
