### ISSUE TITLE
Branch for BEP031

### ISSUE THREAD

**Issue by mariehbourget** [bids-standard/bids-specification#871]
Hi @bids-standard/maintainers,

We will be ready to submit the bids-examples and bids-specification PRs for the Microscopy BEP031 next week.

(The bids-validator part is not ready yet but should follow in about 2 weeks).

As discussed, we will do the bids-examples PR from our fork, but for the bids-specification, we would need to have a branch with push access on the main repository. Please, let me know if that still works for you and how to proceed.

Also, as discussed, we will minimize the number of files to review and create “manual” metadata tables and filename templates instead of using the macros with yaml files. Regarding the new macro “make_filetree_example” for examples of folder content, would you prefer we use the macro or write the examples in `Text` for the community review?

Thanks!
Marie-Hélène

(also tagging @jcohenadad)

**Comment by sappelhoff** [comment]
Hi @mariehbourget I created https://github.com/bids-standard/bids-specification/tree/bep031 for you and invited you to access this repository with "write" access. Let me know if all of that worked.

> Also, as discussed, we will minimize the number of files to review and create “manual” metadata tables and filename templates instead of using the macros with yaml files. Regarding the new macro “make_filetree_example” for examples of folder content, would you prefer we use the macro or write the examples in Text for the community review?

As far as I remember from our meeting, we will "macrofy" everything after the review. So for the initial PR, please format everything without any automated rendering/schema. :-)

**Comment by mariehbourget** [comment]
> Hi @mariehbourget I created https://github.com/bids-standard/bids-specification/tree/bep031 for you and invited you to access this repository with "write" access. Let me know if all of that worked.

Yes, everything seems to work, thank you!

> As far as I remember from our meeting, we will "macrofy" everything after the review. So for the initial PR, please format everything without any automated rendering/schema. :-)

Sounds good :)
