### ISSUE TITLE
BIDS Steering Group election - nomination period 

### ISSUE THREAD

**Issue by franklin-feingold** [bids-standard/bids-specification#878]
Dear BIDS community, 

We are excited to announce the opening of the nomination period for electing a new Steering Group member! The nomination period opens today and will close on Friday, October 1st at 11:59pm (Pacific time).

This new member will be taking the place of our outgoing member, Kirstie Whitaker. While submitting your nomination, we please ask to prepare a brief description of what you would add to the Steering Group if elected and include it within [this form](https://forms.gle/JDryfJRLP2AiHVPg9). We are looking to maintain and enhance our range of diverse perspectives and experiences currently present on the Steering Group. 

If you are interested in nominating yourself - please submit your name to our [nomination google form](https://forms.gle/JDryfJRLP2AiHVPg9) (also linked below).

Nomination form: https://forms.gle/JDryfJRLP2AiHVPg9

If you have any questions, please feel free to reach out to Franklin (ffein@stanford.edu)

Thank you,
The BIDS team

**Comment by sappelhoff** [comment]
Thanks to everyone who participated in the nomination period. All BIDS contributors should have received an invitation to vote by now, see also: https://groups.google.com/g/bids-discussion/c/1yFd0I8A_to
