### ISSUE TITLE
animated bids logo

### ISSUE THREAD

**Issue by adswa** [bids-standard/bids-specification#882]
Hey! I had teaching myself how to animate SVGs on my bucket list, and got around to do it today. I practiced with the BIDS logo. Since this repo here contains the logos, I thought to leave a note - if you want to have an animated version of the logo, feel free to take it. Its not spectacular, but it exists :smile: 
https://github.com/adswa/animated-bids-logo/blob/master/bids-animated.webm

**Comment by guiomar** [comment]
Thanks @adswa!! It looks beautiful!!

**Comment by Remi-Gau** [comment]
Love it!!

Should we add a link to this in logo README: https://github.com/bids-standard/bids-specification/tree/master/BIDS_logo ?

**Comment by sappelhoff** [comment]
Nice! Thanks a lot :)

**Comment by sappelhoff** [comment]
@adswa do you want to make a PR to add the animated version to https://github.com/bids-standard/bids-specification/tree/master/BIDS_logo, including an update to the README? :-)

**Comment by adswa** [comment]
Sure, I would be happy to!
