### ISSUE TITLE
Misunderstanding in iEEG electrodes.tsv description of "name" column?

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#893]
For the `name` column in an `electrodes.tsv` file, [the spec says](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/04-intracranial-electroencephalography.html#channels-description-_channelstsv):

> The label must correspond to `_electrodes.tsv` name and all ieeg type channels are
    required to have a position.

This doesn't make sense technically. An electrode is an electrical contact, a channel is a potential measurement between two electrodes. When applying an average reference, or a dedicated (common to all) reference electrode, it is *kind of* sensible to name a channel like an electrode, and this is arguably the most common practice, and where a lot of confusion between electrode vs channel comes from.

The concept breaks apart for bipolar recordings: Imaging an EOG recording with an electrode named `VEOG+` above the left eye, and its counterpart named `VEOG-` below the left eye. Both these electrodes together form the channel named `VEOG` ... however, in electrodes.tsv, this bipolar recording would need two rows, not a single one. Then again in channels.tsv, there would only be `VEOG`, a single row.

_Originally posted by @sappelhoff in https://github.com/bids-standard/bids-specification/pull/827#discussion_r723262582_

--> We don't have such a description in [MEG](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/02-magnetoencephalography.html#channels-description-_channelstsv) or [EEG](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#channels-description-_channelstsv). Is this a small bug that needs to be corrected @dorahermes? Or am I not seeing the full picture here?

I would cut out the requirement "The label must correspond to `_electrodes.tsv` name and all ieeg type channels are
    required to have a position.", because I think it doesn't make sense in all situations.

**Comment by robertoostenveld** [comment]
I think there are two aspects to consider in the current text. Let me highlight them in bold:

_Label of the channel. The **label must correspond to** _electrodes.tsv name and all ieeg type **channels are required to have a position**. The reference channel name MAY be provided in the reference column._

The second one is easy: channels don't have a position (but electrodes have).

The first one probably was initially inspired to have an unambiguous link between channels and electrodes. Having two columns, each with one electrode label in it, allows mapping the channel to the electrodes. If a channel were named "ch1", then you would not know to which electrodes (the one of interest and the reference) it pertains. If a channel were named "Cz-M1" (using EEG here, as more people are probably familiar with the electrode naming), then a  single name disambiguates the link between channel and electrodes. If name=Cz and referenmce=M1, then it is also unambiguous.

**Comment by dorahermes** [comment]
I agree that the 'channels are required to have a position' is not correct. The first version was indeed inspired to have an unambiguous link between electrodes and channels, to ensure good practices, but this already creates an issue if you have a trigger channel.
