### ISSUE TITLE
Create index page based on the schema

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#900]
I think it might be useful to create an index page based on the schema. Basically, the page would include all of the object definitions in the schema, broken down by object type (e.g., datatype, metadata field, suffix), and _hopefully_ linking to any uses of that object in the specification.

**Comment by sappelhoff** [comment]
> A glossary would be a great start, although optimally we'd also be able to generate links back to the specification text where the terms are used.

great idea, +1
