### ISSUE TITLE
Adding sourcedata filename to a column in the scans.tsv file

### ISSUE THREAD

**Issue by adam2392** [bids-standard/bids-specification#905]
### Problem
I've been working with conversion of `sourcedata` files over to BIDS for the sake of i) speeding up my analysis work streams and ii) speeding up sharing of datasets. However, many times you'll have new datasets coming in, or maybe you want to determine if the file you uploaded with some filename (e.g. `subject001_eeg_001.edf`) was converted or not.

Moreover, many of my collaborators (i.e. clinicians) only remember their original file naming scheme, not the organized BIDS files. Unfortunately, then there's a lot of back and forth about which file is which unless there is a backwards trace of which BIDS file corresponds to which source file. There is no easy way to check this right now. 

### Suggestion
My proposal is to add a SHOULD requirement in the `scans.tsv` that suggests that users add a column to the file for `original_filename`, which adds the filename of the source file. This way, one can backtrack what was converted easily. To be honest, I think it should be a MUST, unless there is some sort of PHI embedded in the source filename?

**Comment by adam2392** [comment]
You mean https://bids-specification.readthedocs.io/en/stable/05-derivatives/02-common-data-types.html here?

I suppose that serves the same purpose as adding `original_filename` in scans.tsv. However, where would these go? Would they go in the sidecar JSON? 

I'm okay w/ either option as long as it's specified in BIDS, then we can support it in `mne-bids`.

**Comment by effigies** [comment]
> You mean https://bids-specification.readthedocs.io/en/stable/05-derivatives/02-common-data-types.html here?

Yes.

> I suppose that serves the same purpose as adding `original_filename` in scans.tsv. However, where would these go? Would they go in the sidecar JSON?

Yes.

---

Another approach to this could just be a table in `sourcedata/` or `code/` with `source`/`destination` columns. It could serve as a log or an input to a tool that performs the conversions.

**Comment by adam2392** [comment]
Should this just go in the sidecar json part for each MEG, EEG and iEEG?

**Comment by sappelhoff** [comment]
closed, because we discussed in #906 that implementing this on the tooling side of things would suffice ... see https://github.com/mne-tools/mne-bids/pull/890
