### ISSUE TITLE
How do I visualize data made up of BIDS

### ISSUE THREAD

**Issue by iDestro** [bids-standard/bids-specification#922]

**Comment by PeerHerholz** [comment]
Ahoi hoi @iDestro,

could you potentially provide more information regarding the desired outcome and the data you have? In the current state, things are a bit too sparse to actually address your question. Furthermore, your inquiry might be better suited as a question on [www.neurostars.org](www.neurostars.org), as it's really more of a question than an issue with the specification (at least so far). It's a great open and searchable forum through which others might be quicker in replying, more people see the questions and might be able to provide help/support/ideas, as well as the chance to find a solution for folks with similar questions/problems in the future is increased. 

HTH, cheers, Peer
