### ISSUE TITLE
Summary of unique participants for each modality?

### ISSUE THREAD

**Issue by dorianps** [bids-standard/bids-specification#924]
Hi all,

Not sure I am posting to the correct repository. Is there any BIDS app or script that summarizes a dataset by parsing all the modalities and counting how many unique participants are available for each modality (e.g., anat: t1w/t2w, func: task-restingstate/task-motor, dwi: acq-singleshelldir42, etc.)? Basically, we need a head count for every type of scan in the dataset.

Thank you.
Dorian

**Comment by Remi-Gau** [comment]
hey @dorianps 

Thanks for posting this. I think we might better responses and also better visibility (for now  but also for answers to you question) if you post it on Neurostars.

Remember to use the BIDS tags to help people find you question: https://neurostars.org/search?q=tags%3Abids

Would you be OK posting there?

**Comment by Remi-Gau** [comment]
That being said your question is very similar to a recent request from @rotemb9 and also other people around having such feature as part of BIDS matlab.

I was literally working on this (see draft [here)](https://github.com/bids-standard/bids-matlab/issues/279#issuecomment-963062303) this morning but I would be more than keen on working on a python equivalent of this.

**Comment by dorianps** [comment]
Thank you @Remi-Gau . I will post it in Neurostars, no problem.

I know how to possibly do this in R, and I am not very practical in python, but I was wondering if there was a universal tool the BIDS community is using for this purpose.
I am also experimenting with datalad's metadata aggregation which may list all findings by modality or subject. Again, the easiest for me is to create a data.frame (or list of data.frames) in R and parse BIDS filename.
