### ISSUE TITLE
Disallowing upper-case EDF extension?

### ISSUE THREAD

**Issue by adam2392** [bids-standard/bids-specification#926]
Right now, we don't specify what sort of EDF extension to use (upper or lower case). However, it is validated for only lower case extension. In the EDF spec though, both are allowed.

Should we constrain BIDS to only allow lower-case? We need to make it explicit. This makes validation and downstream tool-building easier.

Came up in: https://github.com/bids-standard/bids-validator/pull/1381

**Comment by sappelhoff** [comment]
closed in #927
