### ISSUE TITLE
dwi description seems wrong: T2w instead of T2*w

### ISSUE THREAD

**Issue by jcohenadad** [bids-standard/bids-specification#930]
[here](https://github.com/bids-standard/bids-specification/blob/cceb6dc354db907df6868422e88334db69e71e9e/src/04-modality-specific-files/01-magnetic-resonance-imaging-data.md#diffusion-imaging-data) it says that "Diffusion-weighted imaging contrast (specialized T2* weighting)."

but given that DWI is based on a spin echo (vs. gradient echo) EPI, I would call it a "specialized T2 weighting" instead.

**Comment by tsalo** [comment]
Pinging @oesteban, who might be able to weigh in on this.

If it is something that needs to be changed, we can do that in the suffixes schema file:

https://github.com/bids-standard/bids-specification/blob/30c61b7eb473cccd2414d3947d38487995720f67/src/schema/objects/suffixes.yaml#L426-L429
