### ISSUE TITLE
Instructions for how to update the specification with a BEP

### ISSUE THREAD

**Issue by choldgraf** [bids-standard/bids-specification#96]
Is there a place with instructions for how to update the BIDS specification with a new BEP? I think we're ready to go soon with BIDS-iEEG, and wonder if we can use this as an opportunity to improve the docs around contributing to the markdown etc.

**Comment by emdupre** [comment]
I know there's the [BIDS Contributor Guide](https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/edit) -- I think we decided against putting this in the starter kit, though I can't quite remember why -- maybe @KirstieJane would know ?

Regardless, there's still a lot here that references google docs, and I'm not sure if the whole thing should be converted to Markdown !

**Comment by chrisfilo** [comment]
Indeed the Contributor Guide explains the procedure and has been updated a while ago to mention the need for sending a Pull Request with the BEP in Markdown form.

I think it is a great idea to improve the docs - starting from porting Contributor Guide to Markdown and incorporating it into this repo.

**Comment by choldgraf** [comment]
As a first start, how about we add a section to the bids-specification website for this, and just link to the google doc?

**Comment by chrisfilo** [comment]
Sounds good to me!

**Comment by emdupre** [comment]
Right now it's linked in the text under the table for current BEPs -- would
you think that part should all be moved to its own section ? Or just this
guide ?

**Comment by choldgraf** [comment]
Ahh I see it - IMO those could live in their own separate section so that they show up in the navbar on the left and are more discoverable that way. What if we:

1. Made a section for "Extending the BIDS specification" at the end and move the current text there.
2. Replace that text with a short description of the extension process and link out to the new page for more information.

**Comment by emdupre** [comment]
I'd +1 having all of the BEPs (and the guide) as their own section from the navbar ! So that sounds good to me :+1:

**Comment by emdupre** [comment]
It looks like the links added here aren't rendering correctly :(

https://bids-specification.readthedocs.io/en/latest/06-extensions.html

**Comment by choldgraf** [comment]
ahhh I bet it's because of the line break that I added to try and not violate line length limits...

**Comment by emdupre** [comment]
Should we re-open this issue, @chrisfilo ?
