### ISSUE TITLE
Add HTML comments linking to documentation before macro calls in specification

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#960]
Recently, a number of users have mentioned that the schema-related macros in the specification are difficult to work with for folks who are not already familiar with them. The maintainers are working on improving documentation of the schema-related code, and one idea was to add an HTML comment before each macro call in the specification linking to documentation and clarifying what the code snippet means.

Something like this (proposed by @effigies):

```
<!-- This block generates a metadata table. The definitions of these fields can be found in src/schema/objects/metadata.yaml and a guide for editing at <link>. -->
```

The comment would vary based on the type of macro call, so suffix tables would link to the suffixes YAML file, etc.

**Comment by VisLab** [comment]
I think this would be very helpful.
