### ISSUE TITLE
Number of acquisitions required by BIDS for certain quantitative MRI field maps

### ISSUE THREAD

**Issue by dlevitas** [bids-standard/bids-specification#964]
I'm trying to get a handle on the [quantitative MRI](https://bids-specification.readthedocs.io/en/stable/99-appendices/11-qmri.html#appendix-xi-quantitative-mri) BIDS documentation, specifically, how many acquisitions BIDS expects for the different field maps.  Some field maps (e.g. `TB1TFL`, `TB1RFM`) seem to require 2 acquisitions to be BIDS compliant; however, the documentation is more sparse for others. I was wondering how many acquisitions BIDS expects for `TB1SRGE` and `TB1DAM` field maps, or are they variable?

**Comment by neurolabusc** [comment]
@dlevitas I think this is related to a lot of my [queries regarding BEP001](https://github.com/bids-standard/bep001/issues). Recent BEPS have introduced a lot of desirable fields without consideration regarding how this meta information will be detected. Without concrete examples, I think that dcm2niix will tend to err on the side of caution and not populate these tags.

**Comment by effigies** [comment]
@dlevitas I think Neurostars might get more response from the qMRI community. With BEP001 complete, I'm not sure how many participants will be actively monitoring issues for BIDS as a whole.

**Comment by dlevitas** [comment]
Solved [here](https://neurostars.org/t/number-of-images-required-by-bids-for-certain-qmri-field-map-sequences/21094/3?u=dlevitas).
