### ISSUE TITLE
`sessions.tsv` representation in YAML

### ISSUE THREAD

**Issue by TheChymera** [bids-standard/bids-specification#978]
Is [the `*_sessions.tsv`](https://bids-specification.readthedocs.io/en/stable/06-longitudinal-and-multi-site-studies.html#sessions-file) represented anywhere in the YAML schema data? I couldn't find it mentioned other than in a comment, and it would be pretty cool to have it there for automatic specification loading, as seen [here](https://github.com/bids-standard/bids-specification/pull/969).

**Comment by tsalo** [comment]
It looks like neither `sessions.tsv` nor `scans.tsv` is defined in the suffixes file. That's the only place I can think to include either, at the moment, since we don't currently have a way to define files that should appear anywhere except the top or bottom levels of the dataset.

**Comment by TheChymera** [comment]
@tsalo Who should I get in touch with if I want to work on this? Seems like a good idea to make the schema complete, esp now that it has been somewhat split off into its own package.

**Comment by tsalo** [comment]
We just started having regular schema meetings with a small group. The first meeting was last week. You can bring it up at this week's meeting. However, I want to note that "mak[ing] the schema complete" is not a simple task, and there are many elements we need to deal with before we can consider it complete.

**Comment by TheChymera** [comment]
@tsalo Is this the meeting 2022-01-19 at 11:00-13:00?

**Comment by tsalo** [comment]
That one's a one-off for designing a roadmap for the schema. The regular schema meeting is on Thursday (2022-01-20) at 15:00.

**Comment by TheChymera** [comment]
@tsalo could I get an invite link? If so you can send it to horea ÄT mit DÖT edu.

**Comment by tsalo** [comment]
@TheChymera I believe you were already invited (a gmail address with your name is listed under the invitees on the GCal event), but @effigies, can you resend the invite to his MIT email?

**Comment by TheChymera** [comment]
@tsalo oh, I just checked my calendar, so if the invite was recent it worked.
