### ISSUE TITLE
Chimap naming doesn't seem to be BIDS-valid?

### ISSUE THREAD

**Issue by andrew-yian-sun** [bids-standard/bids-specification#979]
Hi all,

I was using the online BIDS validator on my dataset and was told that my Chimap naming was incorrect somehow, but I can't figure out why.

![image](https://user-images.githubusercontent.com/49765705/150046784-ec48cefa-7507-4c6b-8972-dc01905d9e26.png)

Here's the full error log file. Please let me know what the issue is!
https://drive.google.com/file/d/1h_DCRyk25FKbz1ZhKDdojpB2thqRZwaF/view?usp=sharing 

Thanks,
Andrew

**Comment by tsalo** [comment]
Based on [the MRI Entity Table](https://bids-specification.readthedocs.io/en/stable/99-appendices/04-entity-table.html#magnetic-resonance-imaging), `Chimap` files may have `sub`, `ses`, `acq`, `ce`, `rec`, and `run` entities, but no `echo`. My understanding is that `Chimap` is a quantitative map, so there shouldn't be any entities that would be used to estimate quantitative values in a map like that, such as `echo`, `part`, `flip`, `inv`, or `mt`.

Can I ask why you have `echo` in the filename?

**Comment by andrew-yian-sun** [comment]
@tsalo Thanks for the quick reply and the catch! 

I used HeuDiConv but didn't specify `echo` in the heuristic.py file:
`chimap = create_key('sub-{subject}/{session}/fmap/sub-{subject}_{session}_run-{item:03d}_Chimap')`

It looks to be an automatic insertion based on the fact that the QSM files were split into several folders? 
![image](https://user-images.githubusercontent.com/49765705/150070301-60a4a5e8-102f-4b59-852e-e05485c80b0f.png)

This may be a question for the HeuDiConv people then, as I'm not sure how to not get that `echo` in there.

**Comment by effigies** [comment]
It sounds like you have the files for calculating the Chimap, not the Chimap itself. Perhaps there's a more appropriate suffix?

**Comment by andrew-yian-sun** [comment]
Thanks everyone! We don't have data from the individual coils reconstructed, but the files in GRE_QSM correspond to magnitude images (GRE_QSM_23s) and phase maps (GRE_QSM_24s), and that sub-numbers indeed correspond to the echos.

So my understanding is that we would do something like `sub-0061_part-mag_echo-1_GRE.nii.gz` for consistency, but that it would still have to be added to `.bidsignore`?

**Comment by effigies** [comment]
The templates (defined [here](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#anatomy-imaging-data)) are going to be:

```
            sub-<label>[_ses-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>]_echo-<index>[_part-<label>]_MEGRE.json
            sub-<label>[_ses-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>]_echo-<index>[_part-<label>]_MEGRE.nii[.gz]
```

So: sub-0061_echo-1_part-mag_MEGRE.nii.gz

Note that the order of entities is mandatory; echo comes before part.

**Comment by andrew-yian-sun** [comment]
It seems like HeuDiConv is automatically placing `echo` right before `_MEGRE`, such that I cannot get the order to be correct:

Here is the relevant line in my heuristic file: `megre_mag = create_key('sub-{subject}/{session}/anat/sub-{subject}_{session}_part-mag_MEGRE')` (If I add `echo`, it results in 2 instances of it)

And it results in something like: 'sub-0061/ses-1/anat/sub-0061_ses-1_part-mag_echo-1_MEGRE.json', making it BIDS-invalid. I will forward this issue to nipy/heudiconv.

**Comment by effigies** [comment]
Do you also have phase images? If not, you can just drop part-mag.

**Comment by andrew-yian-sun** [comment]
Yes I do :(

**Comment by tsalo** [comment]
It looks like you followed up in heudiconv in https://github.com/nipy/heudiconv/issues/541. Given that you're going to use the MEGRE suffix, which allows the `part` and `echo` entities, can I close this?

**Comment by andrew-yian-sun** [comment]
Yes, thank you!
