### ISSUE TITLE
BIDS and schema version

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#988]
Opening a discussion regarding the prospect of having different versions of the schema for different BIDS version.

Or on how to deal with different BIDS version untill we have version specific BIDS schema.

Mentioned in this [bids-matlab PR](https://github.com/bids-standard/bids-matlab/pull/300#issuecomment-1019951022)

> having a maintained set of rules for all versions (possibly in separate repository) will help
developers (eg. me) of bidsifiers/validators to avoid a lot of if/else when dealing with older bids datasets.

This also relates to a regular question we get on the BIDS validator regarding validating a given BIDS version.

**Comment by yarikoptic** [comment]
well, we will have "version specific BIDS schema" as soon as any next release comes (I haven't realized there were none since 1.6.0 and now at v1.6.0-430-gf8882915 ! -- 430 commits after that!) since it does get adjusted along with PRs and thus will be released along with BIDS specification releases.

Some related ideas on how we organize/release releases of DANDI schema -- see https://github.com/bids-standard/bids-specification/issues/543#issuecomment-895365211

**Comment by Remi-Gau** [comment]
>     * Schema could be a separate repository, so if someone need it for bidsifier/validator, he can just clone a set of config files
>       instead of full bids-specifications.
> 
>     * in json, as more portable compared to yaml
> 
>     * 3 separate file per version (entities, metadata, additional rules and exceptions), and oriented by easy search given data-type and suffix

Tempted to say we can close this one, now that we have a single file JSON version of the schema.

https://bids-specification.readthedocs.io/en/latest/schema.json

**Comment by yarikoptic** [comment]
as for separate repo, we also have https://github.com/bids-standard/bids-schema intended to collect releases (and possibly "snapshots" of master) of the schema.  Currently just a copy of yamls but I filed https://github.com/bids-standard/bids-schema/issues/8 so we could also have json serialization. Then schema could, at least for now, being developed directly in this repo, and that repo have various versions of the bids standard and in possibly different serializations.

**Comment by Remi-Gau** [comment]
OK
So will close this for now.
