### ISSUE TITLE
licence of BIDS logo

### ISSUE THREAD

**Issue by guiomar** [bids-standard/bids-specification#995]
Hi!

Whats the licence of BIDS logo?
Shall we include it in its corresponding readme?

**Comment by sappelhoff** [comment]
I think it's CC By 4.0, but @franklin-feingold should know ... also whether the copyright holder is "BIDS contributors", or the designer who was paid for their work.

**Comment by effigies** [comment]
I'm 99% certain we bought the copyright as part of the process. I don't know who "we" are, though. Might say something like "Shared under CC-BY by the BIDS Steering Group."

**Comment by franklin-feingold** [comment]
as @effigies mentioned when I was running the logo design competition that is what I understood too - we are the rights holder. 

+1 to Chris's recommendation
